"""OpenGL.GL.EXT.convolution -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, AnyArrayResult, FloatArray, FloatArrayResult, IntArray, IntArrayResult

from OpenGL.raw.GL._types import *

GL_CONVOLUTION_1D_EXT: int
GL_CONVOLUTION_2D_EXT: int
GL_CONVOLUTION_BORDER_MODE_EXT: int
GL_CONVOLUTION_FILTER_BIAS_EXT: int
GL_CONVOLUTION_FILTER_SCALE_EXT: int
GL_CONVOLUTION_FORMAT_EXT: int
GL_CONVOLUTION_HEIGHT_EXT: int
GL_CONVOLUTION_WIDTH_EXT: int
GL_MAX_CONVOLUTION_HEIGHT_EXT: int
GL_MAX_CONVOLUTION_WIDTH_EXT: int
GL_POST_CONVOLUTION_ALPHA_BIAS_EXT: int
GL_POST_CONVOLUTION_ALPHA_SCALE_EXT: int
GL_POST_CONVOLUTION_BLUE_BIAS_EXT: int
GL_POST_CONVOLUTION_BLUE_SCALE_EXT: int
GL_POST_CONVOLUTION_GREEN_BIAS_EXT: int
GL_POST_CONVOLUTION_GREEN_SCALE_EXT: int
GL_POST_CONVOLUTION_RED_BIAS_EXT: int
GL_POST_CONVOLUTION_RED_SCALE_EXT: int
GL_REDUCE_EXT: int
GL_SEPARABLE_2D_EXT: int

def glConvolutionFilter1DEXT(target: int, internalformat: int, width: int, format: int, type: int, image: AnyArray) -> None: ...
def glConvolutionFilter2DEXT(target: int, internalformat: int, width: int, height: int, format: int, type: int, image: AnyArray) -> None: ...
def glConvolutionParameterfEXT(target: int, pname: int, params: float) -> None: ...
def glConvolutionParameterfvEXT(target: int, pname: int, params: FloatArray) -> None: ...
def glConvolutionParameteriEXT(target: int, pname: int, params: int) -> None: ...
def glConvolutionParameterivEXT(target: int, pname: int, params: IntArray) -> None: ...
def glCopyConvolutionFilter1DEXT(target: int, internalformat: int, x: int, y: int, width: int) -> None: ...
def glCopyConvolutionFilter2DEXT(target: int, internalformat: int, x: int, y: int, width: int, height: int) -> None: ...
def glGetConvolutionFilterEXT(target: int, format: int, type: int, image: AnyArray | None = None) -> AnyArrayResult: ...
def glGetConvolutionParameterfvEXT(target: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetConvolutionParameterivEXT(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetSeparableFilterEXT(target: int, format: int, type: int, row: AnyArray | None = None, column: AnyArray | None = None, span: AnyArray | None = None) -> tuple[AnyArrayResult, AnyArrayResult, AnyArrayResult]: ...
def glSeparableFilter2DEXT(target: int, internalformat: int, width: int, height: int, format: int, type: int, row: AnyArray, column: AnyArray) -> None: ...

def glInitConvolutionEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
