"""OpenGL.GL.EXT.coordinate_frame -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, ByteArray, DoubleArray, FloatArray, IntArray, ShortArray

from OpenGL.raw.GL._types import *

GL_BINORMAL_ARRAY_EXT: int
GL_BINORMAL_ARRAY_POINTER_EXT: int
GL_BINORMAL_ARRAY_STRIDE_EXT: int
GL_BINORMAL_ARRAY_TYPE_EXT: int
GL_CURRENT_BINORMAL_EXT: int
GL_CURRENT_TANGENT_EXT: int
GL_MAP1_BINORMAL_EXT: int
GL_MAP1_TANGENT_EXT: int
GL_MAP2_BINORMAL_EXT: int
GL_MAP2_TANGENT_EXT: int
GL_TANGENT_ARRAY_EXT: int
GL_TANGENT_ARRAY_POINTER_EXT: int
GL_TANGENT_ARRAY_STRIDE_EXT: int
GL_TANGENT_ARRAY_TYPE_EXT: int

def glBinormal3bEXT(bx: int, by: int, bz: int) -> None: ...
def glBinormal3bvEXT(v: ByteArray) -> None: ...
def glBinormal3dEXT(bx: float, by: float, bz: float) -> None: ...
def glBinormal3dvEXT(v: DoubleArray) -> None: ...
def glBinormal3fEXT(bx: float, by: float, bz: float) -> None: ...
def glBinormal3fvEXT(v: FloatArray) -> None: ...
def glBinormal3iEXT(bx: int, by: int, bz: int) -> None: ...
def glBinormal3ivEXT(v: IntArray) -> None: ...
def glBinormal3sEXT(bx: int, by: int, bz: int) -> None: ...
def glBinormal3svEXT(v: ShortArray) -> None: ...
def glBinormalPointerEXT(type: int, stride: int, pointer: AnyArray) -> None: ...
def glTangent3bEXT(tx: int, ty: int, tz: int) -> None: ...
def glTangent3bvEXT(v: ByteArray) -> None: ...
def glTangent3dEXT(tx: float, ty: float, tz: float) -> None: ...
def glTangent3dvEXT(v: DoubleArray) -> None: ...
def glTangent3fEXT(tx: float, ty: float, tz: float) -> None: ...
def glTangent3fvEXT(v: FloatArray) -> None: ...
def glTangent3iEXT(tx: int, ty: int, tz: int) -> None: ...
def glTangent3ivEXT(v: IntArray) -> None: ...
def glTangent3sEXT(tx: int, ty: int, tz: int) -> None: ...
def glTangent3svEXT(v: ShortArray) -> None: ...
def glTangentPointerEXT(type: int, stride: int, pointer: AnyArray) -> None: ...

def glInitCoordinateFrameEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
