"""OpenGL.GL.EXT.copy_texture -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

def glCopyTexImage1DEXT(target: int, level: int, internalformat: int, x: int, y: int, width: int, border: int) -> None: ...
def glCopyTexImage2DEXT(target: int, level: int, internalformat: int, x: int, y: int, width: int, height: int, border: int) -> None: ...
def glCopyTexSubImage1DEXT(target: int, level: int, xoffset: int, x: int, y: int, width: int) -> None: ...
def glCopyTexSubImage2DEXT(target: int, level: int, xoffset: int, yoffset: int, x: int, y: int, width: int, height: int) -> None: ...
def glCopyTexSubImage3DEXT(target: int, level: int, xoffset: int, yoffset: int, zoffset: int, x: int, y: int, width: int, height: int) -> None: ...

def glInitCopyTextureEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
