"""OpenGL.GL.EXT.direct_state_access -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, AnyArrayResult, DoubleArray, DoubleArrayResult, FloatArray, FloatArrayResult, IntArray, IntArrayResult, UByteArray, UByteArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_PROGRAM_MATRIX_EXT: int
GL_PROGRAM_MATRIX_STACK_DEPTH_EXT: int
GL_TRANSPOSE_PROGRAM_MATRIX_EXT: int

def glBindMultiTextureEXT(texunit: int, target: int, texture: int) -> None: ...
def glCheckNamedFramebufferStatusEXT(framebuffer: int, target: int) -> int: ...
def glClearNamedBufferDataEXT(buffer: int, internalformat: int, format: int, type: int, data: AnyArray) -> None: ...
def glClearNamedBufferSubDataEXT(buffer: int, internalformat: int, offset: int, size: int, format: int, type: int, data: AnyArray) -> None: ...
def glClientAttribDefaultEXT(mask: int) -> None: ...
def glCompressedMultiTexImage1DEXT(texunit: int, target: int, level: int, internalformat: int, width: int, border: int, imageSize: int, bits: AnyArray) -> None: ...
def glCompressedMultiTexImage2DEXT(texunit: int, target: int, level: int, internalformat: int, width: int, height: int, border: int, imageSize: int, bits: AnyArray) -> None: ...
def glCompressedMultiTexImage3DEXT(texunit: int, target: int, level: int, internalformat: int, width: int, height: int, depth: int, border: int, imageSize: int, bits: AnyArray) -> None: ...
def glCompressedMultiTexSubImage1DEXT(texunit: int, target: int, level: int, xoffset: int, width: int, format: int, imageSize: int, bits: AnyArray) -> None: ...
def glCompressedMultiTexSubImage2DEXT(texunit: int, target: int, level: int, xoffset: int, yoffset: int, width: int, height: int, format: int, imageSize: int, bits: AnyArray) -> None: ...
def glCompressedMultiTexSubImage3DEXT(texunit: int, target: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, imageSize: int, bits: AnyArray) -> None: ...
def glCompressedTextureImage1DEXT(texture: int, target: int, level: int, internalformat: int, width: int, border: int, imageSize: int, bits: AnyArray) -> None: ...
def glCompressedTextureImage2DEXT(texture: int, target: int, level: int, internalformat: int, width: int, height: int, border: int, imageSize: int, bits: AnyArray) -> None: ...
def glCompressedTextureImage3DEXT(texture: int, target: int, level: int, internalformat: int, width: int, height: int, depth: int, border: int, imageSize: int, bits: AnyArray) -> None: ...
def glCompressedTextureSubImage1DEXT(texture: int, target: int, level: int, xoffset: int, width: int, format: int, imageSize: int, bits: AnyArray) -> None: ...
def glCompressedTextureSubImage2DEXT(texture: int, target: int, level: int, xoffset: int, yoffset: int, width: int, height: int, format: int, imageSize: int, bits: AnyArray) -> None: ...
def glCompressedTextureSubImage3DEXT(texture: int, target: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, imageSize: int, bits: AnyArray) -> None: ...
def glCopyMultiTexImage1DEXT(texunit: int, target: int, level: int, internalformat: int, x: int, y: int, width: int, border: int) -> None: ...
def glCopyMultiTexImage2DEXT(texunit: int, target: int, level: int, internalformat: int, x: int, y: int, width: int, height: int, border: int) -> None: ...
def glCopyMultiTexSubImage1DEXT(texunit: int, target: int, level: int, xoffset: int, x: int, y: int, width: int) -> None: ...
def glCopyMultiTexSubImage2DEXT(texunit: int, target: int, level: int, xoffset: int, yoffset: int, x: int, y: int, width: int, height: int) -> None: ...
def glCopyMultiTexSubImage3DEXT(texunit: int, target: int, level: int, xoffset: int, yoffset: int, zoffset: int, x: int, y: int, width: int, height: int) -> None: ...
def glCopyTextureImage1DEXT(texture: int, target: int, level: int, internalformat: int, x: int, y: int, width: int, border: int) -> None: ...
def glCopyTextureImage2DEXT(texture: int, target: int, level: int, internalformat: int, x: int, y: int, width: int, height: int, border: int) -> None: ...
def glCopyTextureSubImage1DEXT(texture: int, target: int, level: int, xoffset: int, x: int, y: int, width: int) -> None: ...
def glCopyTextureSubImage2DEXT(texture: int, target: int, level: int, xoffset: int, yoffset: int, x: int, y: int, width: int, height: int) -> None: ...
def glCopyTextureSubImage3DEXT(texture: int, target: int, level: int, xoffset: int, yoffset: int, zoffset: int, x: int, y: int, width: int, height: int) -> None: ...
def glDisableClientStateIndexedEXT(array: int, index: int) -> None: ...
def glDisableClientStateiEXT(array: int, index: int) -> None: ...
def glDisableIndexedEXT(target: int, index: int) -> None: ...
def glDisableVertexArrayAttribEXT(vaobj: int, index: int) -> None: ...
def glDisableVertexArrayEXT(vaobj: int, array: int) -> None: ...
def glEnableClientStateIndexedEXT(array: int, index: int) -> None: ...
def glEnableClientStateiEXT(array: int, index: int) -> None: ...
def glEnableIndexedEXT(target: int, index: int) -> None: ...
def glEnableVertexArrayAttribEXT(vaobj: int, index: int) -> None: ...
def glEnableVertexArrayEXT(vaobj: int, array: int) -> None: ...
def glFlushMappedNamedBufferRangeEXT(buffer: int, offset: int, length: int) -> None: ...
def glFramebufferDrawBufferEXT(framebuffer: int, mode: int) -> None: ...
def glFramebufferDrawBuffersEXT(framebuffer: int, n: int, bufs: UIntArray) -> None: ...
def glFramebufferReadBufferEXT(framebuffer: int, mode: int) -> None: ...
def glGenerateMultiTexMipmapEXT(texunit: int, target: int) -> None: ...
def glGenerateTextureMipmapEXT(texture: int, target: int) -> None: ...
def glGetBooleanIndexedvEXT(target: int, index: int, data: UByteArray | None = None) -> UByteArrayResult: ...
def glGetCompressedMultiTexImageEXT(texunit: int, target: int, lod: int, img: AnyArray) -> None: ...
def glGetCompressedTextureImageEXT(texture: int, target: int, lod: int, img: AnyArray) -> None: ...
def glGetDoubleIndexedvEXT(target: int, index: int, data: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetDoublei_vEXT(pname: int, index: int, params: DoubleArray) -> None: ...
def glGetFloatIndexedvEXT(target: int, index: int, data: FloatArray | None = None) -> FloatArrayResult: ...
def glGetFloati_vEXT(pname: int, index: int, params: FloatArray) -> None: ...
def glGetFramebufferParameterivEXT(framebuffer: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetIntegerIndexedvEXT(target: int, index: int, data: IntArray | None = None) -> IntArrayResult: ...
def glGetMultiTexEnvfvEXT(texunit: int, target: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetMultiTexEnvivEXT(texunit: int, target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetMultiTexGendvEXT(texunit: int, coord: int, pname: int, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetMultiTexGenfvEXT(texunit: int, coord: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetMultiTexGenivEXT(texunit: int, coord: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetMultiTexImageEXT(texunit: int, target: int, level: int, format: int, type: int, pixels: AnyArray | None = None) -> AnyArrayResult: ...
def glGetMultiTexLevelParameterfvEXT(texunit: int, target: int, level: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetMultiTexLevelParameterivEXT(texunit: int, target: int, level: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetMultiTexParameterIivEXT(texunit: int, target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetMultiTexParameterIuivEXT(texunit: int, target: int, pname: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glGetMultiTexParameterfvEXT(texunit: int, target: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetMultiTexParameterivEXT(texunit: int, target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetNamedBufferParameterivEXT(buffer: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetNamedBufferPointervEXT(buffer: int, pname: int, params: AnyArray | None = None) -> AnyArrayResult: ...
def glGetNamedBufferSubDataEXT(buffer: int, offset: int, size: int, data: AnyArray | None = None) -> AnyArrayResult: ...
def glGetNamedFramebufferAttachmentParameterivEXT(framebuffer: int, attachment: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetNamedFramebufferParameterivEXT(framebuffer: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetNamedProgramLocalParameterIivEXT(program: int, target: int, index: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetNamedProgramLocalParameterIuivEXT(program: int, target: int, index: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glGetNamedProgramLocalParameterdvEXT(program: int, target: int, index: int, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetNamedProgramLocalParameterfvEXT(program: int, target: int, index: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetNamedProgramStringEXT(program: int, target: int, pname: int, string: AnyArray) -> None: ...
def glGetNamedProgramivEXT(program: int, target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetNamedRenderbufferParameterivEXT(renderbuffer: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetPointerIndexedvEXT(target: int, index: int, data: AnyArray | None = None) -> AnyArrayResult: ...
def glGetPointeri_vEXT(pname: int, index: int, params: AnyArray) -> None: ...
def glGetTextureImageEXT(texture: int, target: int, level: int, format: int, type: int, pixels: AnyArray | None = None) -> AnyArrayResult: ...
def glGetTextureLevelParameterfvEXT(texture: int, target: int, level: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetTextureLevelParameterivEXT(texture: int, target: int, level: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetTextureParameterIivEXT(texture: int, target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetTextureParameterIuivEXT(texture: int, target: int, pname: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glGetTextureParameterfvEXT(texture: int, target: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetTextureParameterivEXT(texture: int, target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetVertexArrayIntegeri_vEXT(vaobj: int, index: int, pname: int, param: IntArray) -> None: ...
def glGetVertexArrayIntegervEXT(vaobj: int, pname: int, param: IntArray) -> None: ...
def glGetVertexArrayPointeri_vEXT(vaobj: int, index: int, pname: int, param: AnyArray) -> None: ...
def glGetVertexArrayPointervEXT(vaobj: int, pname: int, param: AnyArray) -> None: ...
def glIsEnabledIndexedEXT(target: int, index: int) -> int: ...
def glMapNamedBufferEXT(buffer: int, access: int) -> int | None: ...
def glMapNamedBufferRangeEXT(buffer: int, offset: int, length: int, access: int) -> int | None: ...
def glMatrixFrustumEXT(mode: int, left: float, right: float, bottom: float, top: float, zNear: float, zFar: float) -> None: ...
def glMatrixLoadIdentityEXT(mode: int) -> None: ...
def glMatrixLoadTransposedEXT(mode: int, m: DoubleArray) -> None: ...
def glMatrixLoadTransposefEXT(mode: int, m: FloatArray) -> None: ...
def glMatrixLoaddEXT(mode: int, m: DoubleArray) -> None: ...
def glMatrixLoadfEXT(mode: int, m: FloatArray) -> None: ...
def glMatrixMultTransposedEXT(mode: int, m: DoubleArray) -> None: ...
def glMatrixMultTransposefEXT(mode: int, m: FloatArray) -> None: ...
def glMatrixMultdEXT(mode: int, m: DoubleArray) -> None: ...
def glMatrixMultfEXT(mode: int, m: FloatArray) -> None: ...
def glMatrixOrthoEXT(mode: int, left: float, right: float, bottom: float, top: float, zNear: float, zFar: float) -> None: ...
def glMatrixPopEXT(mode: int) -> None: ...
def glMatrixPushEXT(mode: int) -> None: ...
def glMatrixRotatedEXT(mode: int, angle: float, x: float, y: float, z: float) -> None: ...
def glMatrixRotatefEXT(mode: int, angle: float, x: float, y: float, z: float) -> None: ...
def glMatrixScaledEXT(mode: int, x: float, y: float, z: float) -> None: ...
def glMatrixScalefEXT(mode: int, x: float, y: float, z: float) -> None: ...
def glMatrixTranslatedEXT(mode: int, x: float, y: float, z: float) -> None: ...
def glMatrixTranslatefEXT(mode: int, x: float, y: float, z: float) -> None: ...
def glMultiTexBufferEXT(texunit: int, target: int, internalformat: int, buffer: int) -> None: ...
def glMultiTexCoordPointerEXT(texunit: int, size: int, type: int, stride: int, pointer: AnyArray) -> None: ...
def glMultiTexEnvfEXT(texunit: int, target: int, pname: int, param: float) -> None: ...
def glMultiTexEnvfvEXT(texunit: int, target: int, pname: int, params: FloatArray) -> None: ...
def glMultiTexEnviEXT(texunit: int, target: int, pname: int, param: int) -> None: ...
def glMultiTexEnvivEXT(texunit: int, target: int, pname: int, params: IntArray) -> None: ...
def glMultiTexGendEXT(texunit: int, coord: int, pname: int, param: float) -> None: ...
def glMultiTexGendvEXT(texunit: int, coord: int, pname: int, params: DoubleArray) -> None: ...
def glMultiTexGenfEXT(texunit: int, coord: int, pname: int, param: float) -> None: ...
def glMultiTexGenfvEXT(texunit: int, coord: int, pname: int, params: FloatArray) -> None: ...
def glMultiTexGeniEXT(texunit: int, coord: int, pname: int, param: int) -> None: ...
def glMultiTexGenivEXT(texunit: int, coord: int, pname: int, params: IntArray) -> None: ...
def glMultiTexImage1DEXT(texunit: int, target: int, level: int, internalformat: int, width: int, border: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glMultiTexImage2DEXT(texunit: int, target: int, level: int, internalformat: int, width: int, height: int, border: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glMultiTexImage3DEXT(texunit: int, target: int, level: int, internalformat: int, width: int, height: int, depth: int, border: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glMultiTexParameterIivEXT(texunit: int, target: int, pname: int, params: IntArray) -> None: ...
def glMultiTexParameterIuivEXT(texunit: int, target: int, pname: int, params: UIntArray) -> None: ...
def glMultiTexParameterfEXT(texunit: int, target: int, pname: int, param: float) -> None: ...
def glMultiTexParameterfvEXT(texunit: int, target: int, pname: int, params: FloatArray) -> None: ...
def glMultiTexParameteriEXT(texunit: int, target: int, pname: int, param: int) -> None: ...
def glMultiTexParameterivEXT(texunit: int, target: int, pname: int, params: IntArray) -> None: ...
def glMultiTexRenderbufferEXT(texunit: int, target: int, renderbuffer: int) -> None: ...
def glMultiTexSubImage1DEXT(texunit: int, target: int, level: int, xoffset: int, width: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glMultiTexSubImage2DEXT(texunit: int, target: int, level: int, xoffset: int, yoffset: int, width: int, height: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glMultiTexSubImage3DEXT(texunit: int, target: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glNamedBufferDataEXT(buffer: int, size: int, data: AnyArray, usage: int) -> None: ...
def glNamedBufferStorageEXT(buffer: int, size: int, data: AnyArray, flags: int) -> None: ...
def glNamedBufferSubDataEXT(buffer: int, offset: int, size: int, data: AnyArray) -> None: ...
def glNamedCopyBufferSubDataEXT(readBuffer: int, writeBuffer: int, readOffset: int, writeOffset: int, size: int) -> None: ...
def glNamedFramebufferParameteriEXT(framebuffer: int, pname: int, param: int) -> None: ...
def glNamedFramebufferRenderbufferEXT(framebuffer: int, attachment: int, renderbuffertarget: int, renderbuffer: int) -> None: ...
def glNamedFramebufferTexture1DEXT(framebuffer: int, attachment: int, textarget: int, texture: int, level: int) -> None: ...
def glNamedFramebufferTexture2DEXT(framebuffer: int, attachment: int, textarget: int, texture: int, level: int) -> None: ...
def glNamedFramebufferTexture3DEXT(framebuffer: int, attachment: int, textarget: int, texture: int, level: int, zoffset: int) -> None: ...
def glNamedFramebufferTextureEXT(framebuffer: int, attachment: int, texture: int, level: int) -> None: ...
def glNamedFramebufferTextureFaceEXT(framebuffer: int, attachment: int, texture: int, level: int, face: int) -> None: ...
def glNamedFramebufferTextureLayerEXT(framebuffer: int, attachment: int, texture: int, level: int, layer: int) -> None: ...
def glNamedProgramLocalParameter4dEXT(program: int, target: int, index: int, x: float, y: float, z: float, w: float) -> None: ...
def glNamedProgramLocalParameter4dvEXT(program: int, target: int, index: int, params: DoubleArray) -> None: ...
def glNamedProgramLocalParameter4fEXT(program: int, target: int, index: int, x: float, y: float, z: float, w: float) -> None: ...
def glNamedProgramLocalParameter4fvEXT(program: int, target: int, index: int, params: FloatArray) -> None: ...
def glNamedProgramLocalParameterI4iEXT(program: int, target: int, index: int, x: int, y: int, z: int, w: int) -> None: ...
def glNamedProgramLocalParameterI4ivEXT(program: int, target: int, index: int, params: IntArray) -> None: ...
def glNamedProgramLocalParameterI4uiEXT(program: int, target: int, index: int, x: int, y: int, z: int, w: int) -> None: ...
def glNamedProgramLocalParameterI4uivEXT(program: int, target: int, index: int, params: UIntArray) -> None: ...
def glNamedProgramLocalParameters4fvEXT(program: int, target: int, index: int, count: int, params: FloatArray) -> None: ...
def glNamedProgramLocalParametersI4ivEXT(program: int, target: int, index: int, count: int, params: IntArray) -> None: ...
def glNamedProgramLocalParametersI4uivEXT(program: int, target: int, index: int, count: int, params: UIntArray) -> None: ...
def glNamedProgramStringEXT(program: int, target: int, format: int, len: int, string: AnyArray) -> None: ...
def glNamedRenderbufferStorageEXT(renderbuffer: int, internalformat: int, width: int, height: int) -> None: ...
def glNamedRenderbufferStorageMultisampleCoverageEXT(renderbuffer: int, coverageSamples: int, colorSamples: int, internalformat: int, width: int, height: int) -> None: ...
def glNamedRenderbufferStorageMultisampleEXT(renderbuffer: int, samples: int, internalformat: int, width: int, height: int) -> None: ...
def glProgramUniform1dEXT(program: int, location: int, x: float) -> None: ...
def glProgramUniform1dvEXT(program: int, location: int, count: int, value: DoubleArray) -> None: ...
def glProgramUniform1fEXT(program: int, location: int, v0: float) -> None: ...
def glProgramUniform1fvEXT(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform1iEXT(program: int, location: int, v0: int) -> None: ...
def glProgramUniform1ivEXT(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform1uiEXT(program: int, location: int, v0: int) -> None: ...
def glProgramUniform1uivEXT(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniform2dEXT(program: int, location: int, x: float, y: float) -> None: ...
def glProgramUniform2dvEXT(program: int, location: int, count: int, value: DoubleArray) -> None: ...
def glProgramUniform2fEXT(program: int, location: int, v0: float, v1: float) -> None: ...
def glProgramUniform2fvEXT(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform2iEXT(program: int, location: int, v0: int, v1: int) -> None: ...
def glProgramUniform2ivEXT(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform2uiEXT(program: int, location: int, v0: int, v1: int) -> None: ...
def glProgramUniform2uivEXT(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniform3dEXT(program: int, location: int, x: float, y: float, z: float) -> None: ...
def glProgramUniform3dvEXT(program: int, location: int, count: int, value: DoubleArray) -> None: ...
def glProgramUniform3fEXT(program: int, location: int, v0: float, v1: float, v2: float) -> None: ...
def glProgramUniform3fvEXT(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform3iEXT(program: int, location: int, v0: int, v1: int, v2: int) -> None: ...
def glProgramUniform3ivEXT(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform3uiEXT(program: int, location: int, v0: int, v1: int, v2: int) -> None: ...
def glProgramUniform3uivEXT(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniform4dEXT(program: int, location: int, x: float, y: float, z: float, w: float) -> None: ...
def glProgramUniform4dvEXT(program: int, location: int, count: int, value: DoubleArray) -> None: ...
def glProgramUniform4fEXT(program: int, location: int, v0: float, v1: float, v2: float, v3: float) -> None: ...
def glProgramUniform4fvEXT(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform4iEXT(program: int, location: int, v0: int, v1: int, v2: int, v3: int) -> None: ...
def glProgramUniform4ivEXT(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform4uiEXT(program: int, location: int, v0: int, v1: int, v2: int, v3: int) -> None: ...
def glProgramUniform4uivEXT(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniformMatrix2dvEXT(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix2fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix2x3dvEXT(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix2x3fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix2x4dvEXT(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix2x4fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix3dvEXT(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix3fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix3x2dvEXT(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix3x2fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix3x4dvEXT(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix3x4fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix4dvEXT(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix4fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix4x2dvEXT(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix4x2fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix4x3dvEXT(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix4x3fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glPushClientAttribDefaultEXT(mask: int) -> None: ...
def glTextureBufferEXT(texture: int, target: int, internalformat: int, buffer: int) -> None: ...
def glTextureBufferRangeEXT(texture: int, target: int, internalformat: int, buffer: int, offset: int, size: int) -> None: ...
def glTextureImage1DEXT(texture: int, target: int, level: int, internalformat: int, width: int, border: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glTextureImage2DEXT(texture: int, target: int, level: int, internalformat: int, width: int, height: int, border: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glTextureImage3DEXT(texture: int, target: int, level: int, internalformat: int, width: int, height: int, depth: int, border: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glTexturePageCommitmentEXT(texture: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, commit: bool) -> None: ...
def glTextureParameterIivEXT(texture: int, target: int, pname: int, params: IntArray) -> None: ...
def glTextureParameterIuivEXT(texture: int, target: int, pname: int, params: UIntArray) -> None: ...
def glTextureParameterfEXT(texture: int, target: int, pname: int, param: float) -> None: ...
def glTextureParameterfvEXT(texture: int, target: int, pname: int, params: FloatArray) -> None: ...
def glTextureParameteriEXT(texture: int, target: int, pname: int, param: int) -> None: ...
def glTextureParameterivEXT(texture: int, target: int, pname: int, params: IntArray) -> None: ...
def glTextureRenderbufferEXT(texture: int, target: int, renderbuffer: int) -> None: ...
def glTextureStorage1DEXT(texture: int, target: int, levels: int, internalformat: int, width: int) -> None: ...
def glTextureStorage2DEXT(texture: int, target: int, levels: int, internalformat: int, width: int, height: int) -> None: ...
def glTextureStorage2DMultisampleEXT(texture: int, target: int, samples: int, internalformat: int, width: int, height: int, fixedsamplelocations: bool) -> None: ...
def glTextureStorage3DEXT(texture: int, target: int, levels: int, internalformat: int, width: int, height: int, depth: int) -> None: ...
def glTextureStorage3DMultisampleEXT(texture: int, target: int, samples: int, internalformat: int, width: int, height: int, depth: int, fixedsamplelocations: bool) -> None: ...
def glTextureSubImage1DEXT(texture: int, target: int, level: int, xoffset: int, width: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glTextureSubImage2DEXT(texture: int, target: int, level: int, xoffset: int, yoffset: int, width: int, height: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glTextureSubImage3DEXT(texture: int, target: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glUnmapNamedBufferEXT(buffer: int) -> int: ...
def glVertexArrayBindVertexBufferEXT(vaobj: int, bindingindex: int, buffer: int, offset: int, stride: int) -> None: ...
def glVertexArrayColorOffsetEXT(vaobj: int, buffer: int, size: int, type: int, stride: int, offset: int) -> None: ...
def glVertexArrayEdgeFlagOffsetEXT(vaobj: int, buffer: int, stride: int, offset: int) -> None: ...
def glVertexArrayFogCoordOffsetEXT(vaobj: int, buffer: int, type: int, stride: int, offset: int) -> None: ...
def glVertexArrayIndexOffsetEXT(vaobj: int, buffer: int, type: int, stride: int, offset: int) -> None: ...
def glVertexArrayMultiTexCoordOffsetEXT(vaobj: int, buffer: int, texunit: int, size: int, type: int, stride: int, offset: int) -> None: ...
def glVertexArrayNormalOffsetEXT(vaobj: int, buffer: int, type: int, stride: int, offset: int) -> None: ...
def glVertexArraySecondaryColorOffsetEXT(vaobj: int, buffer: int, size: int, type: int, stride: int, offset: int) -> None: ...
def glVertexArrayTexCoordOffsetEXT(vaobj: int, buffer: int, size: int, type: int, stride: int, offset: int) -> None: ...
def glVertexArrayVertexAttribBindingEXT(vaobj: int, attribindex: int, bindingindex: int) -> None: ...
def glVertexArrayVertexAttribDivisorEXT(vaobj: int, index: int, divisor: int) -> None: ...
def glVertexArrayVertexAttribFormatEXT(vaobj: int, attribindex: int, size: int, type: int, normalized: bool, relativeoffset: int) -> None: ...
def glVertexArrayVertexAttribIFormatEXT(vaobj: int, attribindex: int, size: int, type: int, relativeoffset: int) -> None: ...
def glVertexArrayVertexAttribIOffsetEXT(vaobj: int, buffer: int, index: int, size: int, type: int, stride: int, offset: int) -> None: ...
def glVertexArrayVertexAttribLFormatEXT(vaobj: int, attribindex: int, size: int, type: int, relativeoffset: int) -> None: ...
def glVertexArrayVertexAttribLOffsetEXT(vaobj: int, buffer: int, index: int, size: int, type: int, stride: int, offset: int) -> None: ...
def glVertexArrayVertexAttribOffsetEXT(vaobj: int, buffer: int, index: int, size: int, type: int, normalized: bool, stride: int, offset: int) -> None: ...
def glVertexArrayVertexBindingDivisorEXT(vaobj: int, bindingindex: int, divisor: int) -> None: ...
def glVertexArrayVertexOffsetEXT(vaobj: int, buffer: int, size: int, type: int, stride: int, offset: int) -> None: ...

def glInitDirectStateAccessEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
