"""OpenGL.GL.EXT.draw_buffers2 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray, IntArrayResult, UByteArray, UByteArrayResult

from OpenGL.raw.GL._types import *

def glColorMaskIndexedEXT(index: int, r: int, g: int, b: int, a: int) -> None: ...
def glDisableIndexedEXT(target: int, index: int) -> None: ...
def glEnableIndexedEXT(target: int, index: int) -> None: ...
def glGetBooleanIndexedvEXT(target: int, index: int, data: UByteArray | None = None) -> UByteArrayResult: ...
def glGetIntegerIndexedvEXT(target: int, index: int, data: IntArray | None = None) -> IntArrayResult: ...
def glIsEnabledIndexedEXT(target: int, index: int) -> int: ...

def glInitDrawBuffers2EXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
