"""OpenGL.GL.EXT.external_buffer -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

def glBufferStorageExternalEXT(target: int, offset: int, size: int, clientBuffer: Any, flags: int) -> None: ...
def glNamedBufferStorageExternalEXT(buffer: int, offset: int, size: int, clientBuffer: Any, flags: int) -> None: ...

def glInitExternalBufferEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
