"""OpenGL.GL.EXT.framebuffer_blit_layers -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

def glBlitFramebufferLayerEXT(srcX0: int, srcY0: int, srcX1: int, srcY1: int, srcLayer: int, dstX0: int, dstY0: int, dstX1: int, dstY1: int, dstLayer: int, mask: int, filter: int) -> None: ...
def glBlitFramebufferLayersEXT(srcX0: int, srcY0: int, srcX1: int, srcY1: int, dstX0: int, dstY0: int, dstX1: int, dstY1: int, mask: int, filter: int) -> None: ...

def glInitFramebufferBlitLayersEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
