"""OpenGL.GL.EXT.geometry_shader4 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

GL_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT: int
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT: int
GL_FRAMEBUFFER_INCOMPLETE_LAYER_COUNT_EXT: int
GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT: int
GL_GEOMETRY_INPUT_TYPE_EXT: int
GL_GEOMETRY_OUTPUT_TYPE_EXT: int
GL_GEOMETRY_SHADER_EXT: int
GL_GEOMETRY_VERTICES_OUT_EXT: int
GL_LINES_ADJACENCY_EXT: int
GL_LINE_STRIP_ADJACENCY_EXT: int
GL_MAX_GEOMETRY_OUTPUT_VERTICES_EXT: int
GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT: int
GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT: int
GL_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT: int
GL_MAX_GEOMETRY_VARYING_COMPONENTS_EXT: int
GL_MAX_VARYING_COMPONENTS_EXT: int
GL_MAX_VERTEX_VARYING_COMPONENTS_EXT: int
GL_PROGRAM_POINT_SIZE_EXT: int
GL_TRIANGLES_ADJACENCY_EXT: int
GL_TRIANGLE_STRIP_ADJACENCY_EXT: int

def glProgramParameteriEXT(program: int, pname: int, value: int) -> None: ...

def glInitGeometryShader4EXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
