"""OpenGL.GL.EXT.gpu_shader4 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, ByteArray, IntArray, IntArrayResult, ShortArray, UByteArray, UIntArray, UIntArrayResult, UShortArray

from OpenGL.raw.GL._types import *

GL_INT_SAMPLER_1D_ARRAY_EXT: int
GL_INT_SAMPLER_1D_EXT: int
GL_INT_SAMPLER_2D_ARRAY_EXT: int
GL_INT_SAMPLER_2D_EXT: int
GL_INT_SAMPLER_2D_RECT_EXT: int
GL_INT_SAMPLER_3D_EXT: int
GL_INT_SAMPLER_BUFFER_EXT: int
GL_INT_SAMPLER_CUBE_EXT: int
GL_MAX_PROGRAM_TEXEL_OFFSET_EXT: int
GL_MIN_PROGRAM_TEXEL_OFFSET_EXT: int
GL_SAMPLER_1D_ARRAY_EXT: int
GL_SAMPLER_1D_ARRAY_SHADOW_EXT: int
GL_SAMPLER_2D_ARRAY_EXT: int
GL_SAMPLER_2D_ARRAY_SHADOW_EXT: int
GL_SAMPLER_BUFFER_EXT: int
GL_SAMPLER_CUBE_SHADOW_EXT: int
GL_UNSIGNED_INT_SAMPLER_1D_ARRAY_EXT: int
GL_UNSIGNED_INT_SAMPLER_1D_EXT: int
GL_UNSIGNED_INT_SAMPLER_2D_ARRAY_EXT: int
GL_UNSIGNED_INT_SAMPLER_2D_EXT: int
GL_UNSIGNED_INT_SAMPLER_2D_RECT_EXT: int
GL_UNSIGNED_INT_SAMPLER_3D_EXT: int
GL_UNSIGNED_INT_SAMPLER_BUFFER_EXT: int
GL_UNSIGNED_INT_SAMPLER_CUBE_EXT: int
GL_UNSIGNED_INT_VEC2_EXT: int
GL_UNSIGNED_INT_VEC3_EXT: int
GL_UNSIGNED_INT_VEC4_EXT: int
GL_VERTEX_ATTRIB_ARRAY_INTEGER_EXT: int

def glBindFragDataLocationEXT(program: int, color: int, name: ByteArray) -> None: ...
def glGetFragDataLocationEXT(program: int, name: ByteArray) -> int: ...
def glGetUniformuivEXT(program: int, location: int, params: UIntArray) -> None: ...
def glGetVertexAttribIivEXT(index: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetVertexAttribIuivEXT(index: int, pname: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glUniform1uiEXT(location: int, v0: int) -> None: ...
def glUniform1uivEXT(location: int, count: int, value: UIntArray) -> None: ...
def glUniform2uiEXT(location: int, v0: int, v1: int) -> None: ...
def glUniform2uivEXT(location: int, count: int, value: UIntArray) -> None: ...
def glUniform3uiEXT(location: int, v0: int, v1: int, v2: int) -> None: ...
def glUniform3uivEXT(location: int, count: int, value: UIntArray) -> None: ...
def glUniform4uiEXT(location: int, v0: int, v1: int, v2: int, v3: int) -> None: ...
def glUniform4uivEXT(location: int, count: int, value: UIntArray) -> None: ...
def glVertexAttribI1iEXT(index: int, x: int) -> None: ...
def glVertexAttribI1ivEXT(index: int, v: IntArray) -> None: ...
def glVertexAttribI1uiEXT(index: int, x: int) -> None: ...
def glVertexAttribI1uivEXT(index: int, v: UIntArray) -> None: ...
def glVertexAttribI2iEXT(index: int, x: int, y: int) -> None: ...
def glVertexAttribI2ivEXT(index: int, v: IntArray) -> None: ...
def glVertexAttribI2uiEXT(index: int, x: int, y: int) -> None: ...
def glVertexAttribI2uivEXT(index: int, v: UIntArray) -> None: ...
def glVertexAttribI3iEXT(index: int, x: int, y: int, z: int) -> None: ...
def glVertexAttribI3ivEXT(index: int, v: IntArray) -> None: ...
def glVertexAttribI3uiEXT(index: int, x: int, y: int, z: int) -> None: ...
def glVertexAttribI3uivEXT(index: int, v: UIntArray) -> None: ...
def glVertexAttribI4bvEXT(index: int, v: ByteArray) -> None: ...
def glVertexAttribI4iEXT(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttribI4ivEXT(index: int, v: IntArray) -> None: ...
def glVertexAttribI4svEXT(index: int, v: ShortArray) -> None: ...
def glVertexAttribI4ubvEXT(index: int, v: UByteArray) -> None: ...
def glVertexAttribI4uiEXT(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttribI4uivEXT(index: int, v: UIntArray) -> None: ...
def glVertexAttribI4usvEXT(index: int, v: UShortArray) -> None: ...
def glVertexAttribIPointerEXT(index: int, size: int, type: int, stride: int, pointer: AnyArray) -> None: ...

def glInitGpuShader4EXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
