"""OpenGL.GL.EXT.histogram -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, AnyArrayResult, FloatArray, FloatArrayResult, IntArray, IntArrayResult

from OpenGL.raw.GL._types import *

GL_HISTOGRAM_ALPHA_SIZE_EXT: int
GL_HISTOGRAM_BLUE_SIZE_EXT: int
GL_HISTOGRAM_EXT: int
GL_HISTOGRAM_FORMAT_EXT: int
GL_HISTOGRAM_GREEN_SIZE_EXT: int
GL_HISTOGRAM_LUMINANCE_SIZE_EXT: int
GL_HISTOGRAM_RED_SIZE_EXT: int
GL_HISTOGRAM_SINK_EXT: int
GL_HISTOGRAM_WIDTH_EXT: int
GL_MINMAX_EXT: int
GL_MINMAX_FORMAT_EXT: int
GL_MINMAX_SINK_EXT: int
GL_PROXY_HISTOGRAM_EXT: int
GL_TABLE_TOO_LARGE_EXT: int

def glGetHistogramEXT(target: int, reset: int, format: int, type: int, values: AnyArray | None = None) -> AnyArrayResult: ...
def glGetHistogramParameterfvEXT(target: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetHistogramParameterivEXT(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetMinmaxEXT(target: int, reset: int, format: int, type: int, values: AnyArray | None = None) -> AnyArrayResult: ...
def glGetMinmaxParameterfvEXT(target: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetMinmaxParameterivEXT(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glHistogramEXT(target: int, width: int, internalformat: int, sink: int) -> None: ...
def glMinmaxEXT(target: int, internalformat: int, sink: int) -> None: ...
def glResetHistogramEXT(target: int) -> None: ...
def glResetMinmaxEXT(target: int) -> None: ...

def glInitHistogramEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
