"""OpenGL.GL.EXT.memory_object -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray, UByteArray, UIntArray

from OpenGL.raw.GL._types import *

GL_DEDICATED_MEMORY_OBJECT_EXT: int
GL_DEVICE_UUID_EXT: int
GL_DRIVER_UUID_EXT: int
GL_LINEAR_TILING_EXT: int
GL_NUM_DEVICE_UUIDS_EXT: int
GL_NUM_TILING_TYPES_EXT: int
GL_OPTIMAL_TILING_EXT: int
GL_PROTECTED_MEMORY_OBJECT_EXT: int
GL_TEXTURE_TILING_EXT: int
GL_TILING_TYPES_EXT: int
GL_UUID_SIZE_EXT: int

def glBufferStorageMemEXT(target: int, size: int, memory: int, offset: int) -> None: ...
def glCreateMemoryObjectsEXT(n: int, memoryObjects: UIntArray) -> None: ...
def glDeleteMemoryObjectsEXT(n: int, memoryObjects: UIntArray) -> None: ...
def glGetMemoryObjectParameterivEXT(memoryObject: int, pname: int, params: IntArray) -> None: ...
def glGetUnsignedBytei_vEXT(target: int, index: int, data: UByteArray) -> None: ...
def glGetUnsignedBytevEXT(pname: int, data: UByteArray) -> None: ...
def glIsMemoryObjectEXT(memoryObject: int) -> int: ...
def glMemoryObjectParameterivEXT(memoryObject: int, pname: int, params: IntArray) -> None: ...
def glNamedBufferStorageMemEXT(buffer: int, size: int, memory: int, offset: int) -> None: ...
def glTexStorageMem1DEXT(target: int, levels: int, internalFormat: int, width: int, memory: int, offset: int) -> None: ...
def glTexStorageMem2DEXT(target: int, levels: int, internalFormat: int, width: int, height: int, memory: int, offset: int) -> None: ...
def glTexStorageMem2DMultisampleEXT(target: int, samples: int, internalFormat: int, width: int, height: int, fixedSampleLocations: bool, memory: int, offset: int) -> None: ...
def glTexStorageMem3DEXT(target: int, levels: int, internalFormat: int, width: int, height: int, depth: int, memory: int, offset: int) -> None: ...
def glTexStorageMem3DMultisampleEXT(target: int, samples: int, internalFormat: int, width: int, height: int, depth: int, fixedSampleLocations: bool, memory: int, offset: int) -> None: ...
def glTextureStorageMem1DEXT(texture: int, levels: int, internalFormat: int, width: int, memory: int, offset: int) -> None: ...
def glTextureStorageMem2DEXT(texture: int, levels: int, internalFormat: int, width: int, height: int, memory: int, offset: int) -> None: ...
def glTextureStorageMem2DMultisampleEXT(texture: int, samples: int, internalFormat: int, width: int, height: int, fixedSampleLocations: bool, memory: int, offset: int) -> None: ...
def glTextureStorageMem3DEXT(texture: int, levels: int, internalFormat: int, width: int, height: int, depth: int, memory: int, offset: int) -> None: ...
def glTextureStorageMem3DMultisampleEXT(texture: int, samples: int, internalFormat: int, width: int, height: int, depth: int, fixedSampleLocations: bool, memory: int, offset: int) -> None: ...

def glInitMemoryObjectEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
