'''OpenGL extension EXT.polygon_offset

This module customises the behaviour of the 
OpenGL.raw.GL.EXT.polygon_offset to provide a more 
Python-friendly API
'''
from OpenGL import platform, constants, constant, arrays
from OpenGL import extensions, wrapper
from OpenGL.GL import glget
import ctypes
from OpenGL.raw.GL.EXT.polygon_offset import *
### END AUTOGENERATED SECTION