"""OpenGL.GL.EXT.secondary_color -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, ByteArray, DoubleArray, FloatArray, IntArray, ShortArray, UByteArray, UIntArray, UShortArray

from OpenGL.raw.GL._types import *

GL_COLOR_SUM_EXT: int
GL_CURRENT_SECONDARY_COLOR_EXT: int
GL_SECONDARY_COLOR_ARRAY_EXT: int
GL_SECONDARY_COLOR_ARRAY_POINTER_EXT: int
GL_SECONDARY_COLOR_ARRAY_SIZE_EXT: int
GL_SECONDARY_COLOR_ARRAY_STRIDE_EXT: int
GL_SECONDARY_COLOR_ARRAY_TYPE_EXT: int

def glSecondaryColor3bEXT(red: int, green: int, blue: int) -> None: ...
def glSecondaryColor3bvEXT(v: ByteArray) -> None: ...
def glSecondaryColor3dEXT(red: float, green: float, blue: float) -> None: ...
def glSecondaryColor3dvEXT(v: DoubleArray) -> None: ...
def glSecondaryColor3fEXT(red: float, green: float, blue: float) -> None: ...
def glSecondaryColor3fvEXT(v: FloatArray) -> None: ...
def glSecondaryColor3iEXT(red: int, green: int, blue: int) -> None: ...
def glSecondaryColor3ivEXT(v: IntArray) -> None: ...
def glSecondaryColor3sEXT(red: int, green: int, blue: int) -> None: ...
def glSecondaryColor3svEXT(v: ShortArray) -> None: ...
def glSecondaryColor3ubEXT(red: int, green: int, blue: int) -> None: ...
def glSecondaryColor3ubvEXT(v: UByteArray) -> None: ...
def glSecondaryColor3uiEXT(red: int, green: int, blue: int) -> None: ...
def glSecondaryColor3uivEXT(v: UIntArray) -> None: ...
def glSecondaryColor3usEXT(red: int, green: int, blue: int) -> None: ...
def glSecondaryColor3usvEXT(v: UShortArray) -> None: ...
def glSecondaryColorPointerEXT(size: int, type: int, stride: int, pointer: AnyArray) -> None: ...

def glInitSecondaryColorEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
