"""OpenGL.GL.EXT.semaphore -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UByteArray, UInt64Array, UIntArray

from OpenGL.raw.GL._types import *

GL_DEVICE_UUID_EXT: int
GL_DRIVER_UUID_EXT: int
GL_LAYOUT_COLOR_ATTACHMENT_EXT: int
GL_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_EXT: int
GL_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_EXT: int
GL_LAYOUT_DEPTH_STENCIL_ATTACHMENT_EXT: int
GL_LAYOUT_DEPTH_STENCIL_READ_ONLY_EXT: int
GL_LAYOUT_GENERAL_EXT: int
GL_LAYOUT_SHADER_READ_ONLY_EXT: int
GL_LAYOUT_TRANSFER_DST_EXT: int
GL_LAYOUT_TRANSFER_SRC_EXT: int
GL_NUM_DEVICE_UUIDS_EXT: int
GL_UUID_SIZE_EXT: int

def glDeleteSemaphoresEXT(n: int, semaphores: UIntArray) -> None: ...
def glGenSemaphoresEXT(n: int, semaphores: UIntArray) -> None: ...
def glGetSemaphoreParameterui64vEXT(semaphore: int, pname: int, params: UInt64Array) -> None: ...
def glGetUnsignedBytei_vEXT(target: int, index: int, data: UByteArray) -> None: ...
def glGetUnsignedBytevEXT(pname: int, data: UByteArray) -> None: ...
def glIsSemaphoreEXT(semaphore: int) -> int: ...
def glSemaphoreParameterui64vEXT(semaphore: int, pname: int, params: UInt64Array) -> None: ...
def glSignalSemaphoreEXT(semaphore: int, numBufferBarriers: int, buffers: UIntArray, numTextureBarriers: int, textures: UIntArray, dstLayouts: UIntArray) -> None: ...
def glWaitSemaphoreEXT(semaphore: int, numBufferBarriers: int, buffers: UIntArray, numTextureBarriers: int, textures: UIntArray, srcLayouts: UIntArray) -> None: ...

def glInitSemaphoreEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
