"""OpenGL.GL.EXT.shader_image_load_store -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

GL_ALL_BARRIER_BITS_EXT: int
GL_ATOMIC_COUNTER_BARRIER_BIT_EXT: int
GL_BUFFER_UPDATE_BARRIER_BIT_EXT: int
GL_COMMAND_BARRIER_BIT_EXT: int
GL_ELEMENT_ARRAY_BARRIER_BIT_EXT: int
GL_FRAMEBUFFER_BARRIER_BIT_EXT: int
GL_IMAGE_1D_ARRAY_EXT: int
GL_IMAGE_1D_EXT: int
GL_IMAGE_2D_ARRAY_EXT: int
GL_IMAGE_2D_EXT: int
GL_IMAGE_2D_MULTISAMPLE_ARRAY_EXT: int
GL_IMAGE_2D_MULTISAMPLE_EXT: int
GL_IMAGE_2D_RECT_EXT: int
GL_IMAGE_3D_EXT: int
GL_IMAGE_BINDING_ACCESS_EXT: int
GL_IMAGE_BINDING_FORMAT_EXT: int
GL_IMAGE_BINDING_LAYERED_EXT: int
GL_IMAGE_BINDING_LAYER_EXT: int
GL_IMAGE_BINDING_LEVEL_EXT: int
GL_IMAGE_BINDING_NAME_EXT: int
GL_IMAGE_BUFFER_EXT: int
GL_IMAGE_CUBE_EXT: int
GL_IMAGE_CUBE_MAP_ARRAY_EXT: int
GL_INT_IMAGE_1D_ARRAY_EXT: int
GL_INT_IMAGE_1D_EXT: int
GL_INT_IMAGE_2D_ARRAY_EXT: int
GL_INT_IMAGE_2D_EXT: int
GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT: int
GL_INT_IMAGE_2D_MULTISAMPLE_EXT: int
GL_INT_IMAGE_2D_RECT_EXT: int
GL_INT_IMAGE_3D_EXT: int
GL_INT_IMAGE_BUFFER_EXT: int
GL_INT_IMAGE_CUBE_EXT: int
GL_INT_IMAGE_CUBE_MAP_ARRAY_EXT: int
GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS_EXT: int
GL_MAX_IMAGE_SAMPLES_EXT: int
GL_MAX_IMAGE_UNITS_EXT: int
GL_PIXEL_BUFFER_BARRIER_BIT_EXT: int
GL_SHADER_IMAGE_ACCESS_BARRIER_BIT_EXT: int
GL_TEXTURE_FETCH_BARRIER_BIT_EXT: int
GL_TEXTURE_UPDATE_BARRIER_BIT_EXT: int
GL_TRANSFORM_FEEDBACK_BARRIER_BIT_EXT: int
GL_UNIFORM_BARRIER_BIT_EXT: int
GL_UNSIGNED_INT_IMAGE_1D_ARRAY_EXT: int
GL_UNSIGNED_INT_IMAGE_1D_EXT: int
GL_UNSIGNED_INT_IMAGE_2D_ARRAY_EXT: int
GL_UNSIGNED_INT_IMAGE_2D_EXT: int
GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT: int
GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_EXT: int
GL_UNSIGNED_INT_IMAGE_2D_RECT_EXT: int
GL_UNSIGNED_INT_IMAGE_3D_EXT: int
GL_UNSIGNED_INT_IMAGE_BUFFER_EXT: int
GL_UNSIGNED_INT_IMAGE_CUBE_EXT: int
GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY_EXT: int
GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT_EXT: int

def glBindImageTextureEXT(index: int, texture: int, level: int, layered: bool, layer: int, access: int, format: int) -> None: ...
def glMemoryBarrierEXT(barriers: int) -> None: ...

def glInitShaderImageLoadStoreEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
