"""OpenGL.GL.EXT.texture -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

GL_ALPHA12_EXT: int
GL_ALPHA16_EXT: int
GL_ALPHA4_EXT: int
GL_ALPHA8_EXT: int
GL_INTENSITY12_EXT: int
GL_INTENSITY16_EXT: int
GL_INTENSITY4_EXT: int
GL_INTENSITY8_EXT: int
GL_INTENSITY_EXT: int
GL_LUMINANCE12_ALPHA12_EXT: int
GL_LUMINANCE12_ALPHA4_EXT: int
GL_LUMINANCE12_EXT: int
GL_LUMINANCE16_ALPHA16_EXT: int
GL_LUMINANCE16_EXT: int
GL_LUMINANCE4_ALPHA4_EXT: int
GL_LUMINANCE4_EXT: int
GL_LUMINANCE6_ALPHA2_EXT: int
GL_LUMINANCE8_ALPHA8_EXT: int
GL_LUMINANCE8_EXT: int
GL_PROXY_TEXTURE_1D_EXT: int
GL_PROXY_TEXTURE_2D_EXT: int
GL_REPLACE_EXT: int
GL_RGB10_A2_EXT: int
GL_RGB10_EXT: int
GL_RGB12_EXT: int
GL_RGB16_EXT: int
GL_RGB2_EXT: int
GL_RGB4_EXT: int
GL_RGB5_A1_EXT: int
GL_RGB5_EXT: int
GL_RGB8_EXT: int
GL_RGBA12_EXT: int
GL_RGBA16_EXT: int
GL_RGBA2_EXT: int
GL_RGBA4_EXT: int
GL_RGBA8_EXT: int
GL_TEXTURE_ALPHA_SIZE_EXT: int
GL_TEXTURE_BLUE_SIZE_EXT: int
GL_TEXTURE_GREEN_SIZE_EXT: int
GL_TEXTURE_INTENSITY_SIZE_EXT: int
GL_TEXTURE_LUMINANCE_SIZE_EXT: int
GL_TEXTURE_RED_SIZE_EXT: int
GL_TEXTURE_TOO_LARGE_EXT: int

def glInitTextureEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
