"""OpenGL.GL.EXT.texture_object -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray, UByteArray, UByteArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_TEXTURE_1D_BINDING_EXT: int
GL_TEXTURE_2D_BINDING_EXT: int
GL_TEXTURE_3D_BINDING_EXT: int
GL_TEXTURE_PRIORITY_EXT: int
GL_TEXTURE_RESIDENT_EXT: int

def glAreTexturesResidentEXT(n: int, textures: UIntArray, residences: UByteArray | None = None) -> UByteArrayResult: ...
def glBindTextureEXT(target: int, texture: int) -> None: ...
def glDeleteTexturesEXT(n: int, textures: UIntArray) -> None: ...
def glGenTexturesEXT(n: int, textures: UIntArray | None = None) -> UIntArrayResult: ...
def glIsTextureEXT(texture: int) -> int: ...
def glPrioritizeTexturesEXT(n: int, textures: UIntArray, priorities: FloatArray) -> None: ...

def glInitTextureObjectEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
