"""OpenGL.GL.EXT.vertex_attrib_64bit -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, DoubleArray, DoubleArrayResult

from OpenGL.raw.GL._types import *

GL_DOUBLE_MAT2_EXT: int
GL_DOUBLE_MAT2x3_EXT: int
GL_DOUBLE_MAT2x4_EXT: int
GL_DOUBLE_MAT3_EXT: int
GL_DOUBLE_MAT3x2_EXT: int
GL_DOUBLE_MAT3x4_EXT: int
GL_DOUBLE_MAT4_EXT: int
GL_DOUBLE_MAT4x2_EXT: int
GL_DOUBLE_MAT4x3_EXT: int
GL_DOUBLE_VEC2_EXT: int
GL_DOUBLE_VEC3_EXT: int
GL_DOUBLE_VEC4_EXT: int

def glGetVertexAttribLdvEXT(index: int, pname: int, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glVertexAttribL1dEXT(index: int, x: float) -> None: ...
def glVertexAttribL1dvEXT(index: int, v: DoubleArray) -> None: ...
def glVertexAttribL2dEXT(index: int, x: float, y: float) -> None: ...
def glVertexAttribL2dvEXT(index: int, v: DoubleArray) -> None: ...
def glVertexAttribL3dEXT(index: int, x: float, y: float, z: float) -> None: ...
def glVertexAttribL3dvEXT(index: int, v: DoubleArray) -> None: ...
def glVertexAttribL4dEXT(index: int, x: float, y: float, z: float, w: float) -> None: ...
def glVertexAttribL4dvEXT(index: int, v: DoubleArray) -> None: ...
def glVertexAttribLPointerEXT(index: int, size: int, type: int, stride: int, pointer: AnyArray) -> None: ...

def glInitVertexAttrib64BitEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
