"""OpenGL.GL.EXT.win32_keyed_mutex -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

def glAcquireKeyedMutexWin32EXT(memory: int, key: int, timeout: int) -> int: ...
def glReleaseKeyedMutexWin32EXT(memory: int, key: int) -> int: ...

def glInitWin32KeyedMutexEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
