'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p
from OpenGL.GL import glget
EXTENSION_NAME = 'GL_INGR_color_clamp'
_p.unpack_constants( """GL_RED_MIN_CLAMP_INGR 0x8560
GL_GREEN_MIN_CLAMP_INGR 0x8561
GL_BLUE_MIN_CLAMP_INGR 0x8562
GL_ALPHA_MIN_CLAMP_INGR 0x8563
GL_RED_MAX_CLAMP_INGR 0x8564
GL_GREEN_MAX_CLAMP_INGR 0x8565
GL_BLUE_MAX_CLAMP_INGR 0x8566
GL_ALPHA_MAX_CLAMP_INGR 0x8567""", globals())
glget.addGLGetConstant( GL_RED_MIN_CLAMP_INGR, (1,) )
glget.addGLGetConstant( GL_GREEN_MIN_CLAMP_INGR, (1,) )
glget.addGLGetConstant( GL_BLUE_MIN_CLAMP_INGR, (1,) )
glget.addGLGetConstant( GL_ALPHA_MIN_CLAMP_INGR, (1,) )
glget.addGLGetConstant( GL_RED_MAX_CLAMP_INGR, (1,) )
glget.addGLGetConstant( GL_GREEN_MAX_CLAMP_INGR, (1,) )
glget.addGLGetConstant( GL_BLUE_MAX_CLAMP_INGR, (1,) )
glget.addGLGetConstant( GL_ALPHA_MAX_CLAMP_INGR, (1,) )


def glInitColorClampINGR():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
