"""OpenGL.GL.MESA.window_pos -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import DoubleArray, FloatArray, IntArray, ShortArray

from OpenGL.raw.GL._types import *

def glWindowPos2dMESA(x: float, y: float) -> None: ...
def glWindowPos2dvMESA(v: DoubleArray) -> None: ...
def glWindowPos2fMESA(x: float, y: float) -> None: ...
def glWindowPos2fvMESA(v: FloatArray) -> None: ...
def glWindowPos2iMESA(x: int, y: int) -> None: ...
def glWindowPos2ivMESA(v: IntArray) -> None: ...
def glWindowPos2sMESA(x: int, y: int) -> None: ...
def glWindowPos2svMESA(v: ShortArray) -> None: ...
def glWindowPos3dMESA(x: float, y: float, z: float) -> None: ...
def glWindowPos3dvMESA(v: DoubleArray) -> None: ...
def glWindowPos3fMESA(x: float, y: float, z: float) -> None: ...
def glWindowPos3fvMESA(v: FloatArray) -> None: ...
def glWindowPos3iMESA(x: int, y: int, z: int) -> None: ...
def glWindowPos3ivMESA(v: IntArray) -> None: ...
def glWindowPos3sMESA(x: int, y: int, z: int) -> None: ...
def glWindowPos3svMESA(v: ShortArray) -> None: ...
def glWindowPos4dMESA(x: float, y: float, z: float, w: float) -> None: ...
def glWindowPos4dvMESA(v: DoubleArray) -> None: ...
def glWindowPos4fMESA(x: float, y: float, z: float, w: float) -> None: ...
def glWindowPos4fvMESA(v: FloatArray) -> None: ...
def glWindowPos4iMESA(x: int, y: int, z: int, w: int) -> None: ...
def glWindowPos4ivMESA(v: IntArray) -> None: ...
def glWindowPos4sMESA(x: int, y: int, z: int, w: int) -> None: ...
def glWindowPos4svMESA(v: ShortArray) -> None: ...

def glInitWindowPosMESA() -> bool: ...

def __getattr__(name: str) -> Any: ...
