"""OpenGL.GLX.SGIX.hyperpipe -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray

from OpenGL.raw.GLX._types import *

GLX_BAD_HYPERPIPE_CONFIG_SGIX: int
GLX_BAD_HYPERPIPE_SGIX: int
GLX_HYPERPIPE_DISPLAY_PIPE_SGIX: int
GLX_HYPERPIPE_ID_SGIX: int
GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX: int
GLX_HYPERPIPE_PIXEL_AVERAGE_SGIX: int
GLX_HYPERPIPE_RENDER_PIPE_SGIX: int
GLX_HYPERPIPE_STEREO_SGIX: int
GLX_PIPE_RECT_LIMITS_SGIX: int
GLX_PIPE_RECT_SGIX: int

def glXBindHyperpipeSGIX(dpy: AnyArray, hpId: int) -> int: ...
def glXDestroyHyperpipeConfigSGIX(dpy: AnyArray, hpId: int) -> int: ...
def glXHyperpipeAttribSGIX(dpy: AnyArray, timeSlice: int, attrib: int, size: int, attribList: AnyArray) -> int: ...
def glXHyperpipeConfigSGIX(dpy: AnyArray, networkId: int, npipes: int, cfg: AnyArray, hpId: IntArray) -> int: ...
def glXQueryHyperpipeAttribSGIX(dpy: AnyArray, timeSlice: int, attrib: int, size: int, returnAttribList: AnyArray) -> int: ...
def glXQueryHyperpipeBestAttribSGIX(dpy: AnyArray, timeSlice: int, attrib: int, size: int, attribList: AnyArray, returnAttribList: AnyArray) -> int: ...
def glXQueryHyperpipeConfigSGIX(dpy: AnyArray, hpId: int, npipes: IntArray) -> bytes: ...
def glXQueryHyperpipeNetworkSGIX(dpy: AnyArray, npipes: IntArray) -> bytes: ...

def glInitHyperpipeSGIX() -> bool: ...

def __getattr__(name: str) -> Any: ...
