"""OpenGL.GLX.SGIX.video_resize -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray

from OpenGL.raw.GLX._types import *

GLX_SYNC_FRAME_SGIX: int
GLX_SYNC_SWAP_SGIX: int

def glXBindChannelToWindowSGIX(display: AnyArray, screen: int, channel: int, window: Any) -> int: ...
def glXChannelRectSGIX(display: AnyArray, screen: int, channel: int, x: int, y: int, w: int, h: int) -> int: ...
def glXChannelRectSyncSGIX(display: AnyArray, screen: int, channel: int, synctype: int) -> int: ...
def glXQueryChannelDeltasSGIX(display: AnyArray, screen: int, channel: int, x: IntArray, y: IntArray, w: IntArray, h: IntArray) -> int: ...
def glXQueryChannelRectSGIX(display: AnyArray, screen: int, channel: int, dx: IntArray, dy: IntArray, dw: IntArray, dh: IntArray) -> int: ...

def glInitVideoResizeSGIX() -> bool: ...

def __getattr__(name: str) -> Any: ...
