"""OpenGL.GLX.NV.swap_group -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, UIntArray

from OpenGL.raw.GLX._types import *

def glXBindSwapBarrierNV(dpy: AnyArray, group: int, barrier: int) -> int: ...
def glXJoinSwapGroupNV(dpy: AnyArray, drawable: Any, group: int) -> int: ...
def glXQueryFrameCountNV(dpy: AnyArray, screen: int, count: UIntArray) -> int: ...
def glXQueryMaxSwapGroupsNV(dpy: AnyArray, screen: int, maxGroups: UIntArray, maxBarriers: UIntArray) -> int: ...
def glXQuerySwapGroupNV(dpy: AnyArray, drawable: Any, group: UIntArray, barrier: UIntArray) -> int: ...
def glXResetFrameCountNV(dpy: AnyArray, screen: int) -> int: ...

def glInitSwapGroupNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
