"""OpenGL.GLX.NV.video_capture -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray

from OpenGL.raw.GLX._types import *

GLX_DEVICE_ID_NV: int
GLX_NUM_VIDEO_CAPTURE_SLOTS_NV: int
GLX_UNIQUE_ID_NV: int

def glXBindVideoCaptureDeviceNV(dpy: AnyArray, video_capture_slot: int, device: Any) -> int: ...
def glXEnumerateVideoCaptureDevicesNV(dpy: AnyArray, screen: int, nelements: IntArray) -> bytes: ...
def glXLockVideoCaptureDeviceNV(dpy: AnyArray, device: Any) -> None: ...
def glXQueryVideoCaptureDeviceNV(dpy: AnyArray, device: Any, attribute: int, value: IntArray) -> int: ...
def glXReleaseVideoCaptureDeviceNV(dpy: AnyArray, device: Any) -> None: ...

def glInitVideoCaptureNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
