'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p, constants as _cs, arrays
from OpenGL.GL import glget
import ctypes
EXTENSION_NAME = 'GL_ATI_envmap_bumpmap'
def _f( function ):
    return _p.createFunction( function,_p.GL,'GL_ATI_envmap_bumpmap',False)
_p.unpack_constants( """GL_BUMP_ROT_MATRIX_ATI 0x8775
GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
GL_BUMP_TEX_UNITS_ATI 0x8778
GL_DUDV_ATI 0x8779
GL_DU8DV8_ATI 0x877A
GL_BUMP_ENVMAP_ATI 0x877B
GL_BUMP_TARGET_ATI 0x877C""", globals())
@_f
@_p.types(None,_cs.GLenum,arrays.GLintArray)
def glTexBumpParameterivATI( pname,param ):pass
@_f
@_p.types(None,_cs.GLenum,arrays.GLfloatArray)
def glTexBumpParameterfvATI( pname,param ):pass
@_f
@_p.types(None,_cs.GLenum,arrays.GLintArray)
def glGetTexBumpParameterivATI( pname,param ):pass
@_f
@_p.types(None,_cs.GLenum,arrays.GLfloatArray)
def glGetTexBumpParameterfvATI( pname,param ):pass


def glInitEnvmapBumpmapATI():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
