"""OpenGL.WGL.I3D.gamma -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray

from OpenGL.raw.WGL._types import *

WGL_GAMMA_EXCLUDE_DESKTOP_I3D: int
WGL_GAMMA_TABLE_SIZE_I3D: int

def wglGetGammaTableI3D(hDC: Any, iEntries: int, puRed: AnyArray, puGreen: AnyArray, puBlue: AnyArray) -> int: ...
def wglGetGammaTableParametersI3D(hDC: Any, iAttribute: int, piValue: IntArray) -> int: ...
def wglSetGammaTableI3D(hDC: Any, iEntries: int, puRed: AnyArray, puGreen: AnyArray, puBlue: AnyArray) -> int: ...
def wglSetGammaTableParametersI3D(hDC: Any, iAttribute: int, piValue: IntArray) -> int: ...

def glInitGammaI3D() -> bool: ...

def __getattr__(name: str) -> Any: ...
