"""OpenGL.WGL.I3D.genlock -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.WGL._types import *

WGL_GENLOCK_SOURCE_DIGITAL_FIELD_I3D: int
WGL_GENLOCK_SOURCE_DIGITAL_SYNC_I3D: int
WGL_GENLOCK_SOURCE_EDGE_BOTH_I3D: int
WGL_GENLOCK_SOURCE_EDGE_FALLING_I3D: int
WGL_GENLOCK_SOURCE_EDGE_RISING_I3D: int
WGL_GENLOCK_SOURCE_EXTERNAL_FIELD_I3D: int
WGL_GENLOCK_SOURCE_EXTERNAL_SYNC_I3D: int
WGL_GENLOCK_SOURCE_EXTERNAL_TTL_I3D: int
WGL_GENLOCK_SOURCE_MULTIVIEW_I3D: int

def wglDisableGenlockI3D(hDC: Any) -> int: ...
def wglEnableGenlockI3D(hDC: Any) -> int: ...
def wglGenlockSampleRateI3D(hDC: Any, uRate: int) -> int: ...
def wglGenlockSourceDelayI3D(hDC: Any, uDelay: int) -> int: ...
def wglGenlockSourceEdgeI3D(hDC: Any, uEdge: int) -> int: ...
def wglGenlockSourceI3D(hDC: Any, uSource: int) -> int: ...
def wglGetGenlockSampleRateI3D(hDC: Any, uRate: AnyArray) -> int: ...
def wglGetGenlockSourceDelayI3D(hDC: Any, uDelay: AnyArray) -> int: ...
def wglGetGenlockSourceEdgeI3D(hDC: Any, uEdge: AnyArray) -> int: ...
def wglGetGenlockSourceI3D(hDC: Any, uSource: AnyArray) -> int: ...
def wglIsEnabledGenlockI3D(hDC: Any, pFlag: AnyArray) -> int: ...
def wglQueryGenlockMaxSourceDelayI3D(hDC: Any, uMaxLineDelay: AnyArray, uMaxPixelDelay: AnyArray) -> int: ...

def glInitGenlockI3D() -> bool: ...

def __getattr__(name: str) -> Any: ...
