"""OpenGL.WGL.I3D.image_buffer -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.WGL._types import *

WGL_IMAGE_BUFFER_LOCK_I3D: int
WGL_IMAGE_BUFFER_MIN_ACCESS_I3D: int

def wglAssociateImageBufferEventsI3D(hDC: Any, pEvent: AnyArray, pAddress: AnyArray, pSize: AnyArray, count: int) -> int: ...
def wglCreateImageBufferI3D(hDC: Any, dwSize: int, uFlags: int) -> Any: ...
def wglDestroyImageBufferI3D(hDC: Any, pAddress: Any) -> int: ...
def wglReleaseImageBufferEventsI3D(hDC: Any, pAddress: AnyArray, count: int) -> int: ...

def glInitImageBufferI3D() -> bool: ...

def __getattr__(name: str) -> Any: ...
