"""OpenGL.WGL.I3D.swap_frame_usage -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, FloatArray

from OpenGL.raw.WGL._types import *

def wglBeginFrameTrackingI3D() -> int: ...
def wglEndFrameTrackingI3D() -> int: ...
def wglGetFrameUsageI3D(pUsage: FloatArray) -> int: ...
def wglQueryFrameTrackingI3D(pFrameCount: AnyArray, pMissedFrames: AnyArray, pLastMissedUsage: FloatArray) -> int: ...

def glInitSwapFrameUsageI3D() -> bool: ...

def __getattr__(name: str) -> Any: ...
