"""OpenGL.WGL.I3D.swap_frame_lock -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.WGL._types import *

def wglDisableFrameLockI3D() -> int: ...
def wglEnableFrameLockI3D() -> int: ...
def wglIsEnabledFrameLockI3D(pFlag: AnyArray) -> int: ...
def wglQueryFrameLockMasterI3D(pFlag: AnyArray) -> int: ...

def glInitSwapFrameLockI3D() -> bool: ...

def __getattr__(name: str) -> Any: ...
