"""OpenGL.EGL.NV.native_query -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.EGL._types import *

def eglQueryNativeDisplayNV(dpy: Any, display_id: AnyArray) -> int: ...
def eglQueryNativePixmapNV(dpy: Any, surf: Any, pixmap: AnyArray) -> int: ...
def eglQueryNativeWindowNV(dpy: Any, surf: Any, window: AnyArray) -> int: ...

def glInitNativeQueryNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
