"""OpenGL.EGL.NV.system_time -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.EGL._types import *

def eglGetSystemTimeFrequencyNV() -> int: ...
def eglGetSystemTimeNV() -> int: ...

def glInitSystemTimeNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
