"""OpenGL.GLX.MESA.swap_control -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GLX._types import *

def glXGetSwapIntervalMESA() -> int: ...
def glXSwapIntervalMESA(interval: int) -> int: ...

def glInitSwapControlMESA() -> bool: ...

def __getattr__(name: str) -> Any: ...
