'''Autogenerated by xml_generate script, do not edit!'''
from OpenGL import platform as _p, arrays
from OpenGL.raw.GL import _types as _cs
from OpenGL.constant import Constant as _C

import ctypes
EXTENSION_NAME = 'GL_NV_register_combiners2'
def _f( function ):
    return _p.createFunction( function,_p.GL,'GL_NV_register_combiners2')
GL_PER_STAGE_CONSTANTS_NV=_C('GL_PER_STAGE_CONSTANTS_NV',0x8535)
@_f
@_p.types(None,_cs.GLenum,_cs.GLenum,arrays.GLfloatArray)
def glCombinerStageParameterfvNV(stage,pname,params):pass
# Calculate length of params from pname:CombinerParameterNV
@_f
@_p.types(None,_cs.GLenum,_cs.GLenum,arrays.GLfloatArray)
def glGetCombinerStageParameterfvNV(stage,pname,params):pass
# Calculate length of params from pname:CombinerParameterNV
