'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p, constants as _cs, arrays
from OpenGL.GL import glget
import ctypes
EXTENSION_NAME = 'GL_NV_register_combiners2'
def _f( function ):
    return _p.createFunction( function,_p.GL,'GL_NV_register_combiners2',False)
_p.unpack_constants( """GL_PER_STAGE_CONSTANTS_NV 0x8535""", globals())
glget.addGLGetConstant( GL_PER_STAGE_CONSTANTS_NV, (1,) )
@_f
@_p.types(None,_cs.GLenum,_cs.GLenum,arrays.GLfloatArray)
def glCombinerStageParameterfvNV( stage,pname,params ):pass
@_f
@_p.types(None,_cs.GLenum,_cs.GLenum,arrays.GLfloatArray)
def glGetCombinerStageParameterfvNV( stage,pname,params ):pass


def glInitRegisterCombiners2NV():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
