'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p, constants as _cs, arrays
from OpenGL.GL import glget
import ctypes
EXTENSION_NAME = 'GL_NV_texture_barrier'
def _f( function ):
    return _p.createFunction( function,_p.GL,'GL_NV_texture_barrier',False)

@_f
@_p.types(None,)
def glTextureBarrierNV(  ):pass


def glInitTextureBarrierNV():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
