'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p
from OpenGL.GL import glget
EXTENSION_NAME = 'GL_NV_texture_expand_normal'
_p.unpack_constants( """GL_TEXTURE_UNSIGNED_REMAP_MODE_NV 0x888F""", globals())


def glInitTextureExpandNormalNV():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
