'''OpenGL extension NV.vdpau_interop

Automatically generated by the get_gl_extensions script, do not edit!
'''
from OpenGL import platform, constants, constant, arrays
from OpenGL import extensions
from OpenGL.GL import glget
import ctypes
EXTENSION_NAME = 'GL_NV_vdpau_interop'
_DEPRECATED = False
GL_SURFACE_STATE_NV = constant.Constant( 'GL_SURFACE_STATE_NV', 0x86EB )
GL_SURFACE_REGISTERED_NV = constant.Constant( 'GL_SURFACE_REGISTERED_NV', 0x86FD )
GL_SURFACE_MAPPED_NV = constant.Constant( 'GL_SURFACE_MAPPED_NV', 0x8700 )
GL_WRITE_DISCARD_NV = constant.Constant( 'GL_WRITE_DISCARD_NV', 0x88BE )


def glInitVdpauInteropNV():
    '''Return boolean indicating whether this extension is available'''
    return extensions.hasGLExtension( EXTENSION_NAME )
