"""OpenGL.GL.APPLE.element_array -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray

from OpenGL.raw.GL._types import *

GL_ELEMENT_ARRAY_APPLE: int
GL_ELEMENT_ARRAY_POINTER_APPLE: int
GL_ELEMENT_ARRAY_TYPE_APPLE: int

def glDrawElementArrayAPPLE(mode: int, first: int, count: int) -> None: ...
def glDrawRangeElementArrayAPPLE(mode: int, start: int, end: int, first: int, count: int) -> None: ...
def glElementPointerAPPLE(type: int, pointer: AnyArray) -> None: ...
def glMultiDrawElementArrayAPPLE(mode: int, first: IntArray, count: IntArray, primcount: int) -> None: ...
def glMultiDrawRangeElementArrayAPPLE(mode: int, start: int, end: int, first: IntArray, count: IntArray, primcount: int) -> None: ...

def glInitElementArrayAPPLE() -> bool: ...

def __getattr__(name: str) -> Any: ...
