"""OpenGL.GL.APPLE.fence -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_DRAW_PIXELS_APPLE: int
GL_FENCE_APPLE: int

def glDeleteFencesAPPLE(n: int, fences: UIntArray) -> None: ...
def glFinishFenceAPPLE(fence: int) -> None: ...
def glFinishObjectAPPLE(object: int, name: int) -> None: ...
def glGenFencesAPPLE(n: int, fences: UIntArray | None = None) -> UIntArrayResult: ...
def glIsFenceAPPLE(fence: int) -> int: ...
def glSetFenceAPPLE(fence: int) -> None: ...
def glTestFenceAPPLE(fence: int) -> int: ...
def glTestObjectAPPLE(object: int, name: int) -> int: ...

def glInitFenceAPPLE() -> bool: ...

def __getattr__(name: str) -> Any: ...
