"""OpenGL.GL.APPLE.vertex_array_object -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_VERTEX_ARRAY_BINDING_APPLE: int

def glBindVertexArrayAPPLE(array: int) -> None: ...
def glDeleteVertexArraysAPPLE(n: int, arrays: UIntArray) -> None: ...
def glGenVertexArraysAPPLE(n: int, arrays: UIntArray | None = None) -> UIntArrayResult: ...
def glIsVertexArrayAPPLE(array: int) -> int: ...

def glInitVertexArrayObjectAPPLE() -> bool: ...

def __getattr__(name: str) -> Any: ...
