'''Autogenerated by xml_generate script, do not edit!'''
from OpenGL import platform as _p, arrays
from OpenGL.raw.GL import _types as _cs
from OpenGL.constant import Constant as _C

import ctypes
EXTENSION_NAME = 'GL_DMP_shader_binary'
def _f( function ):
    return _p.createFunction( function,_p.GL,'GL_DMP_shader_binary')
GL_SHADER_BINARY_DMP=_C('GL_SHADER_BINARY_DMP',0x9250)

