"""OpenGL.WGL.NV.DX_interop -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.WGL._types import *

WGL_ACCESS_READ_ONLY_NV: int
WGL_ACCESS_READ_WRITE_NV: int
WGL_ACCESS_WRITE_DISCARD_NV: int

def wglDXCloseDeviceNV(hDevice: Any) -> int: ...
def wglDXLockObjectsNV(hDevice: Any, count: int, hObjects: AnyArray) -> int: ...
def wglDXObjectAccessNV(hObject: Any, access: int) -> int: ...
def wglDXOpenDeviceNV(dxDevice: AnyArray) -> Any: ...
def wglDXRegisterObjectNV(hDevice: Any, dxObject: AnyArray, name: int, type: int, access: int) -> Any: ...
def wglDXSetResourceShareHandleNV(dxObject: AnyArray, shareHandle: Any) -> int: ...
def wglDXUnlockObjectsNV(hDevice: Any, count: int, hObjects: AnyArray) -> int: ...
def wglDXUnregisterObjectNV(hDevice: Any, hObject: Any) -> int: ...

def glInitDxInteropNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
