"""OpenGL.WGL.NV.gpu_affinity -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.WGL._types import *

ERROR_INCOMPATIBLE_AFFINITY_MASKS_NV: int
ERROR_MISSING_AFFINITY_MASK_NV: int

def wglCreateAffinityDCNV(phGpuList: AnyArray) -> Any: ...
def wglDeleteDCNV(hdc: Any) -> int: ...
def wglEnumGpuDevicesNV(hGpu: Any, iDeviceIndex: int, lpGpuDevice: Any) -> int: ...
def wglEnumGpusFromAffinityDCNV(hAffinityDC: Any, iGpuIndex: int, hGpu: AnyArray) -> int: ...
def wglEnumGpusNV(iGpuIndex: int, phGpu: AnyArray) -> int: ...

def glInitGpuAffinityNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
