"""OpenGL.WGL.NV.swap_group -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UIntArray

from OpenGL.raw.WGL._types import *

def wglBindSwapBarrierNV(group: int, barrier: int) -> int: ...
def wglJoinSwapGroupNV(hDC: Any, group: int) -> int: ...
def wglQueryFrameCountNV(hDC: Any, count: UIntArray) -> int: ...
def wglQueryMaxSwapGroupsNV(hDC: Any, maxGroups: UIntArray, maxBarriers: UIntArray) -> int: ...
def wglQuerySwapGroupNV(hDC: Any, group: UIntArray, barrier: UIntArray) -> int: ...
def wglResetFrameCountNV(hDC: Any) -> int: ...

def glInitSwapGroupNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
