"""OpenGL.WGL.NV.video_capture -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray

from OpenGL.raw.WGL._types import *

WGL_NUM_VIDEO_CAPTURE_SLOTS_NV: int
WGL_UNIQUE_ID_NV: int

def wglBindVideoCaptureDeviceNV(uVideoSlot: int, hDevice: Any) -> int: ...
def wglEnumerateVideoCaptureDevicesNV(hDc: Any, phDeviceList: AnyArray) -> int: ...
def wglLockVideoCaptureDeviceNV(hDc: Any, hDevice: Any) -> int: ...
def wglQueryVideoCaptureDeviceNV(hDc: Any, hDevice: Any, iAttribute: int, piValue: IntArray) -> int: ...
def wglReleaseVideoCaptureDeviceNV(hDc: Any, hDevice: Any) -> int: ...

def glInitVideoCaptureNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
