"""OpenGL.EGL.KHR.create_context -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.EGL._types import *

EGL_CONTEXT_FLAGS_KHR: int
EGL_CONTEXT_MAJOR_VERSION_KHR: int
EGL_CONTEXT_MINOR_VERSION_KHR: int
EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT_KHR: int
EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT_KHR: int
EGL_CONTEXT_OPENGL_DEBUG_BIT_KHR: int
EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE_BIT_KHR: int
EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR: int
EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR: int
EGL_CONTEXT_OPENGL_ROBUST_ACCESS_BIT_KHR: int
EGL_LOSE_CONTEXT_ON_RESET_KHR: int
EGL_NO_RESET_NOTIFICATION_KHR: int
EGL_OPENGL_ES3_BIT: int
EGL_OPENGL_ES3_BIT_KHR: int

def glInitCreateContextKHR() -> bool: ...

def __getattr__(name: str) -> Any: ...
