"""OpenGL.EGL.KHR.stream_consumer_gltexture -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.EGL._types import *

EGL_CONSUMER_ACQUIRE_TIMEOUT_USEC_KHR: int

def eglStreamConsumerAcquireKHR(dpy: Any, stream: Any) -> int: ...
def eglStreamConsumerGLTextureExternalKHR(dpy: Any, stream: Any) -> int: ...
def eglStreamConsumerReleaseKHR(dpy: Any, stream: Any) -> int: ...

def glInitStreamConsumerGltextureKHR() -> bool: ...

def __getattr__(name: str) -> Any: ...
