"""OpenGL.EGL.KHR.stream_cross_process_fd -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.EGL._types import *

def eglCreateStreamFromFileDescriptorKHR(dpy: Any, file_descriptor: int) -> Any: ...
def eglGetStreamFileDescriptorKHR(dpy: Any, stream: Any) -> int: ...

def glInitStreamCrossProcessFdKHR() -> bool: ...

def __getattr__(name: str) -> Any: ...
