"""OpenGL.EGL.KHR.stream_attrib -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import Int64Array

from OpenGL.raw.EGL._types import *

EGL_CONSUMER_LATENCY_USEC_KHR: int
EGL_STREAM_STATE_CONNECTING_KHR: int
EGL_STREAM_STATE_CREATED_KHR: int
EGL_STREAM_STATE_KHR: int

def eglCreateStreamAttribKHR(dpy: Any, attrib_list: Int64Array) -> Any: ...
def eglQueryStreamAttribKHR(dpy: Any, stream: Any, attribute: int, value: Int64Array) -> int: ...
def eglSetStreamAttribKHR(dpy: Any, stream: Any, attribute: int, value: int) -> int: ...
def eglStreamConsumerAcquireAttribKHR(dpy: Any, stream: Any, attrib_list: Int64Array) -> int: ...
def eglStreamConsumerReleaseAttribKHR(dpy: Any, stream: Any, attrib_list: Int64Array) -> int: ...

def eglInitStreamAttribKHR(*args: Any, **named: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
