"""OpenGL.GLES2.AMD.performance_monitor -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, AnyArrayResult, ByteArray, ByteArrayResult, IntArray, IntArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GLES2._types import *

GL_COUNTER_RANGE_AMD: int
GL_COUNTER_TYPE_AMD: int
GL_PERCENTAGE_AMD: int
GL_PERFMON_RESULT_AMD: int
GL_PERFMON_RESULT_AVAILABLE_AMD: int
GL_PERFMON_RESULT_SIZE_AMD: int
GL_UNSIGNED_INT64_AMD: int

def glBeginPerfMonitorAMD(monitor: int) -> None: ...
def glDeletePerfMonitorsAMD(n: int, monitors: UIntArray | None = None) -> UIntArrayResult: ...
def glEndPerfMonitorAMD(monitor: int) -> None: ...
def glGenPerfMonitorsAMD(n: int, monitors: UIntArray | None = None) -> UIntArrayResult: ...
def glGetPerfMonitorCounterDataAMD(monitor: int, pname: int, dataSize: int, data: UIntArray | None = None, bytesWritten: IntArray | None = None) -> tuple[IntArrayResult, UIntArrayResult]: ...
def glGetPerfMonitorCounterInfoAMD(group: int, counter: int, pname: int, data: AnyArray | None = None) -> AnyArrayResult: ...
def glGetPerfMonitorCounterStringAMD(group: int, counter: int, bufSize: int, length: IntArray | None = None, counterString: ByteArray | None = None) -> tuple[ByteArrayResult, IntArrayResult]: ...
def glGetPerfMonitorCountersAMD(group: int, numCounters: IntArray, maxActiveCounters: IntArray, counterSize: int, counters: UIntArray | None = None) -> tuple[UIntArrayResult, IntArrayResult, IntArrayResult]: ...
def glGetPerfMonitorGroupStringAMD(group: int, bufSize: int, length: IntArray | None = None, groupString: ByteArray | None = None) -> tuple[ByteArrayResult, IntArrayResult]: ...
def glGetPerfMonitorGroupsAMD(numGroups: IntArray, groupsSize: int, groups: UIntArray | None = None) -> tuple[UIntArrayResult, IntArrayResult]: ...
def glSelectPerfMonitorCountersAMD(monitor: int, enable: int, group: int, numCounters: int, counterList: UIntArray | None = None) -> UIntArrayResult: ...

def glInitPerformanceMonitorAMD() -> bool: ...

def __getattr__(name: str) -> Any: ...
