'''Autogenerated by xml_generate script, do not edit!'''
from OpenGL import platform as _p, arrays
from OpenGL.raw.GL import _types as _cs
from OpenGL.constant import Constant as _C

import ctypes
EXTENSION_NAME = 'GL_SUN_convolution_border_modes'
def _f( function ):
    return _p.createFunction( function,_p.GL,'GL_SUN_convolution_border_modes')
GL_WRAP_BORDER_SUN=_C('GL_WRAP_BORDER_SUN',0x81D4)

