'''OpenGL extension SUN.convolution_border_modes

Automatically generated by the get_gl_extensions script, do not edit!
'''
from OpenGL import platform as _p
EXTENSION_NAME = 'GL_SUN_convolution_border_modes'
_p.unpack_constants( """GL_WRAP_BORDER_SUN 0x81D4""", globals())


def glInitConvolutionBorderModesSUN():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
