'''OpenGL extension SUN.slice_accum

Automatically generated by the get_gl_extensions script, do not edit!
'''
from OpenGL import platform as _p
EXTENSION_NAME = 'GL_SUN_slice_accum'
_p.unpack_constants( """GL_SLICE_ACCUM_SUN 0x85CC""", globals())


def glInitSliceAccumSUN():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
