"""OpenGL.GL.NVX.conditional_render -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

def glBeginConditionalRenderNVX(id: int) -> None: ...
def glEndConditionalRenderNVX() -> None: ...

def glInitConditionalRenderNVX() -> bool: ...

def __getattr__(name: str) -> Any: ...
