"""OpenGL.GL.NVX.gpu_multicast2 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray, IntArray, UInt64Array, UIntArray

from OpenGL.raw.GL._types import *

GL_UPLOAD_GPU_MASK_NVX: int

def glAsyncCopyBufferSubDataNVX(waitSemaphoreCount: int, waitSemaphoreArray: UIntArray, fenceValueArray: UInt64Array, readGpu: int, writeGpuMask: int, readBuffer: int, writeBuffer: int, readOffset: int, writeOffset: int, size: int, signalSemaphoreCount: int, signalSemaphoreArray: UIntArray, signalValueArray: UInt64Array) -> int: ...
def glAsyncCopyImageSubDataNVX(waitSemaphoreCount: int, waitSemaphoreArray: UIntArray, waitValueArray: UInt64Array, srcGpu: int, dstGpuMask: int, srcName: int, srcTarget: int, srcLevel: int, srcX: int, srcY: int, srcZ: int, dstName: int, dstTarget: int, dstLevel: int, dstX: int, dstY: int, dstZ: int, srcWidth: int, srcHeight: int, srcDepth: int, signalSemaphoreCount: int, signalSemaphoreArray: UIntArray, signalValueArray: UInt64Array) -> int: ...
def glMulticastScissorArrayvNVX(gpu: int, first: int, count: int, v: IntArray) -> None: ...
def glMulticastViewportArrayvNVX(gpu: int, first: int, count: int, v: FloatArray) -> None: ...
def glMulticastViewportPositionWScaleNVX(gpu: int, index: int, xcoeff: float, ycoeff: float) -> None: ...
def glUploadGpuMaskNVX(mask: int) -> None: ...

def glInitGpuMulticast2NVX() -> bool: ...

def __getattr__(name: str) -> Any: ...
