"""OpenGL.GL.NVX.progress_fence -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UInt64Array, UIntArray

from OpenGL.raw.GL._types import *

def glClientWaitSemaphoreui64NVX(fenceObjectCount: int, semaphoreArray: UIntArray, fenceValueArray: UInt64Array) -> None: ...
def glCreateProgressFenceNVX() -> int: ...
def glSignalSemaphoreui64NVX(signalGpu: int, fenceObjectCount: int, semaphoreArray: UIntArray, fenceValueArray: UInt64Array) -> None: ...
def glWaitSemaphoreui64NVX(waitGpu: int, fenceObjectCount: int, semaphoreArray: UIntArray, fenceValueArray: UInt64Array) -> None: ...

def glInitProgressFenceNVX() -> bool: ...

def __getattr__(name: str) -> Any: ...
