"""OpenGL.GLES1.QCOM.driver_control -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import ByteArray, IntArray, UIntArray

from OpenGL.raw.GLES1._types import *

def glDisableDriverControlQCOM(driverControl: int) -> None: ...
def glEnableDriverControlQCOM(driverControl: int) -> None: ...
def glGetDriverControlStringQCOM(driverControl: int, bufSize: int, length: IntArray, driverControlString: ByteArray) -> None: ...
def glGetDriverControlsQCOM(num: IntArray, size: int, driverControls: UIntArray) -> None: ...

def glInitDriverControlQCOM() -> bool: ...

def __getattr__(name: str) -> Any: ...
