"""OpenGL.GLES1.QCOM.extended_get -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray, UIntArray

from OpenGL.raw.GLES1._types import *

GL_STATE_RESTORE: int
GL_TEXTURE_DEPTH_QCOM: int
GL_TEXTURE_FORMAT_QCOM: int
GL_TEXTURE_HEIGHT_QCOM: int
GL_TEXTURE_IMAGE_VALID_QCOM: int
GL_TEXTURE_INTERNAL_FORMAT_QCOM: int
GL_TEXTURE_NUM_LEVELS_QCOM: int
GL_TEXTURE_OBJECT_VALID_QCOM: int
GL_TEXTURE_TARGET_QCOM: int
GL_TEXTURE_TYPE_QCOM: int
GL_TEXTURE_WIDTH_QCOM: int

def glExtGetBufferPointervQCOM(target: int, params: AnyArray) -> None: ...
def glExtGetBuffersQCOM(buffers: UIntArray, maxBuffers: int, numBuffers: IntArray) -> None: ...
def glExtGetFramebuffersQCOM(framebuffers: UIntArray, maxFramebuffers: int, numFramebuffers: IntArray) -> None: ...
def glExtGetRenderbuffersQCOM(renderbuffers: UIntArray, maxRenderbuffers: int, numRenderbuffers: IntArray) -> None: ...
def glExtGetTexLevelParameterivQCOM(texture: int, face: int, level: int, pname: int, params: IntArray) -> None: ...
def glExtGetTexSubImageQCOM(target: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, type: int, texels: AnyArray) -> None: ...
def glExtGetTexturesQCOM(textures: UIntArray, maxTextures: int, numTextures: IntArray) -> None: ...
def glExtTexObjectStateOverrideiQCOM(target: int, pname: int, param: int) -> None: ...

def glInitExtendedGetQCOM() -> bool: ...

def __getattr__(name: str) -> Any: ...
