"""OpenGL.GL.OES.single_precision -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray, FloatArrayResult

from OpenGL.raw.GL._types import *

def glClearDepthfOES(depth: float) -> None: ...
def glClipPlanefOES(plane: int, equation: FloatArray) -> None: ...
def glDepthRangefOES(n: float, f: float) -> None: ...
def glFrustumfOES(l: float, r: float, b: float, t: float, n: float, f: float) -> None: ...
def glGetClipPlanefOES(plane: int, equation: FloatArray | None = None) -> FloatArrayResult: ...
def glOrthofOES(l: float, r: float, b: float, t: float, n: float, f: float) -> None: ...

def glInitSinglePrecisionOES() -> bool: ...

def __getattr__(name: str) -> Any: ...
