"""OpenGL.GL.NV.bindless_texture -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UInt64Array

from OpenGL.raw.GL._types import *

def glGetImageHandleNV(texture: int, level: int, layered: bool, layer: int, format: int) -> int: ...
def glGetTextureHandleNV(texture: int) -> int: ...
def glGetTextureSamplerHandleNV(texture: int, sampler: int) -> int: ...
def glIsImageHandleResidentNV(handle: int) -> int: ...
def glIsTextureHandleResidentNV(handle: int) -> int: ...
def glMakeImageHandleNonResidentNV(handle: int) -> None: ...
def glMakeImageHandleResidentNV(handle: int, access: int) -> None: ...
def glMakeTextureHandleNonResidentNV(handle: int) -> None: ...
def glMakeTextureHandleResidentNV(handle: int) -> None: ...
def glProgramUniformHandleui64NV(program: int, location: int, value: int) -> None: ...
def glProgramUniformHandleui64vNV(program: int, location: int, count: int, values: UInt64Array) -> None: ...
def glUniformHandleui64NV(location: int, value: int) -> None: ...
def glUniformHandleui64vNV(location: int, count: int, value: UInt64Array) -> None: ...

def glInitBindlessTextureNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
