"""OpenGL.GL.NV.command_list -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, Int64Array, IntArray, UInt64Array, UIntArray

from OpenGL.raw.GL._types import *

GL_ALPHA_REF_COMMAND_NV: int
GL_ATTRIBUTE_ADDRESS_COMMAND_NV: int
GL_BLEND_COLOR_COMMAND_NV: int
GL_DRAW_ARRAYS_COMMAND_NV: int
GL_DRAW_ARRAYS_INSTANCED_COMMAND_NV: int
GL_DRAW_ARRAYS_STRIP_COMMAND_NV: int
GL_DRAW_ELEMENTS_COMMAND_NV: int
GL_DRAW_ELEMENTS_INSTANCED_COMMAND_NV: int
GL_DRAW_ELEMENTS_STRIP_COMMAND_NV: int
GL_ELEMENT_ADDRESS_COMMAND_NV: int
GL_FRONT_FACE_COMMAND_NV: int
GL_LINE_WIDTH_COMMAND_NV: int
GL_NOP_COMMAND_NV: int
GL_POLYGON_OFFSET_COMMAND_NV: int
GL_SCISSOR_COMMAND_NV: int
GL_STENCIL_REF_COMMAND_NV: int
GL_TERMINATE_SEQUENCE_COMMAND_NV: int
GL_UNIFORM_ADDRESS_COMMAND_NV: int
GL_VIEWPORT_COMMAND_NV: int

def glCallCommandListNV(list: int) -> None: ...
def glCommandListSegmentsNV(list: int, segments: int) -> None: ...
def glCompileCommandListNV(list: int) -> None: ...
def glCreateCommandListsNV(n: int, lists: UIntArray) -> None: ...
def glCreateStatesNV(n: int, states: UIntArray) -> None: ...
def glDeleteCommandListsNV(n: int, lists: UIntArray) -> None: ...
def glDeleteStatesNV(n: int, states: UIntArray) -> None: ...
def glDrawCommandsAddressNV(primitiveMode: int, indirects: UInt64Array, sizes: IntArray, count: int) -> None: ...
def glDrawCommandsNV(primitiveMode: int, buffer: int, indirects: Int64Array, sizes: IntArray, count: int) -> None: ...
def glDrawCommandsStatesAddressNV(indirects: UInt64Array, sizes: IntArray, states: UIntArray, fbos: UIntArray, count: int) -> None: ...
def glDrawCommandsStatesNV(buffer: int, indirects: Int64Array, sizes: IntArray, states: UIntArray, fbos: UIntArray, count: int) -> None: ...
def glGetCommandHeaderNV(tokenID: int, size: int) -> int: ...
def glGetStageIndexNV(shadertype: int) -> int: ...
def glIsCommandListNV(list: int) -> int: ...
def glIsStateNV(state: int) -> int: ...
def glListDrawCommandsStatesClientNV(list: int, segment: int, indirects: AnyArray, sizes: IntArray, states: UIntArray, fbos: UIntArray, count: int) -> None: ...
def glStateCaptureNV(state: int, mode: int) -> None: ...

def glInitCommandListNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
