"""OpenGL.GL.NV.draw_vulkan_image -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import ByteArray

from OpenGL.raw.GL._types import *

def glDrawVkImageNV(vkImage: int, sampler: int, x0: float, y0: float, x1: float, y1: float, z: float, s0: float, t0: float, s1: float, t1: float) -> None: ...
def glGetVkProcAddrNV(name: ByteArray) -> Any: ...
def glSignalVkFenceNV(vkFence: int) -> None: ...
def glSignalVkSemaphoreNV(vkSemaphore: int) -> None: ...
def glWaitVkSemaphoreNV(vkSemaphore: int) -> None: ...

def glInitDrawVulkanImageNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
