"""OpenGL.GL.NV.fragment_program -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import DoubleArray, DoubleArrayResult, FloatArray, FloatArrayResult, UByteArray

from OpenGL.raw.GL._types import *

GL_FRAGMENT_PROGRAM_BINDING_NV: int
GL_FRAGMENT_PROGRAM_NV: int
GL_MAX_FRAGMENT_PROGRAM_LOCAL_PARAMETERS_NV: int
GL_MAX_TEXTURE_COORDS_NV: int
GL_MAX_TEXTURE_IMAGE_UNITS_NV: int
GL_PROGRAM_ERROR_STRING_NV: int

def glGetProgramNamedParameterdvNV(id: int, len: int, name: UByteArray, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetProgramNamedParameterfvNV(id: int, len: int, name: UByteArray, params: FloatArray | None = None) -> FloatArrayResult: ...
def glProgramNamedParameter4dNV(id: int, len: int, name: UByteArray, x: float, y: float, z: float, w: float) -> None: ...
def glProgramNamedParameter4dvNV(id: int, len: int, name: UByteArray, v: DoubleArray) -> None: ...
def glProgramNamedParameter4fNV(id: int, len: int, name: UByteArray, x: float, y: float, z: float, w: float) -> None: ...
def glProgramNamedParameter4fvNV(id: int, len: int, name: UByteArray, v: FloatArray) -> None: ...

def glInitFragmentProgramNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
