"""OpenGL.GL.NV.gpu_program4 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray, IntArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_MAX_PROGRAM_ATTRIB_COMPONENTS_NV: int
GL_MAX_PROGRAM_GENERIC_ATTRIBS_NV: int
GL_MAX_PROGRAM_GENERIC_RESULTS_NV: int
GL_MAX_PROGRAM_RESULT_COMPONENTS_NV: int
GL_MAX_PROGRAM_TEXEL_OFFSET_NV: int
GL_MIN_PROGRAM_TEXEL_OFFSET_NV: int
GL_PROGRAM_ATTRIB_COMPONENTS_NV: int
GL_PROGRAM_RESULT_COMPONENTS_NV: int

def glGetProgramEnvParameterIivNV(target: int, index: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetProgramEnvParameterIuivNV(target: int, index: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glGetProgramLocalParameterIivNV(target: int, index: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetProgramLocalParameterIuivNV(target: int, index: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glProgramEnvParameterI4iNV(target: int, index: int, x: int, y: int, z: int, w: int) -> None: ...
def glProgramEnvParameterI4ivNV(target: int, index: int, params: IntArray) -> None: ...
def glProgramEnvParameterI4uiNV(target: int, index: int, x: int, y: int, z: int, w: int) -> None: ...
def glProgramEnvParameterI4uivNV(target: int, index: int, params: UIntArray) -> None: ...
def glProgramEnvParametersI4ivNV(target: int, index: int, count: int, params: IntArray) -> None: ...
def glProgramEnvParametersI4uivNV(target: int, index: int, count: int, params: UIntArray) -> None: ...
def glProgramLocalParameterI4iNV(target: int, index: int, x: int, y: int, z: int, w: int) -> None: ...
def glProgramLocalParameterI4ivNV(target: int, index: int, params: IntArray) -> None: ...
def glProgramLocalParameterI4uiNV(target: int, index: int, x: int, y: int, z: int, w: int) -> None: ...
def glProgramLocalParameterI4uivNV(target: int, index: int, params: UIntArray) -> None: ...
def glProgramLocalParametersI4ivNV(target: int, index: int, count: int, params: IntArray) -> None: ...
def glProgramLocalParametersI4uivNV(target: int, index: int, count: int, params: UIntArray) -> None: ...

def glInitGpuProgram4NV() -> bool: ...

def __getattr__(name: str) -> Any: ...
