"""OpenGL.GL.NV.gpu_multicast -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, FloatArray, Int64Array, IntArray, UInt64Array, UIntArray

from OpenGL.raw.GL._types import *

GL_MULTICAST_GPUS_NV: int
GL_MULTICAST_PROGRAMMABLE_SAMPLE_LOCATION_NV: int
GL_PER_GPU_STORAGE_BIT_NV: int
GL_PER_GPU_STORAGE_NV: int
GL_RENDER_GPU_MASK_NV: int

def glMulticastBarrierNV() -> None: ...
def glMulticastBlitFramebufferNV(srcGpu: int, dstGpu: int, srcX0: int, srcY0: int, srcX1: int, srcY1: int, dstX0: int, dstY0: int, dstX1: int, dstY1: int, mask: int, filter: int) -> None: ...
def glMulticastBufferSubDataNV(gpuMask: int, buffer: int, offset: int, size: int, data: AnyArray) -> None: ...
def glMulticastCopyBufferSubDataNV(readGpu: int, writeGpuMask: int, readBuffer: int, writeBuffer: int, readOffset: int, writeOffset: int, size: int) -> None: ...
def glMulticastCopyImageSubDataNV(srcGpu: int, dstGpuMask: int, srcName: int, srcTarget: int, srcLevel: int, srcX: int, srcY: int, srcZ: int, dstName: int, dstTarget: int, dstLevel: int, dstX: int, dstY: int, dstZ: int, srcWidth: int, srcHeight: int, srcDepth: int) -> None: ...
def glMulticastFramebufferSampleLocationsfvNV(gpu: int, framebuffer: int, start: int, count: int, v: FloatArray) -> None: ...
def glMulticastGetQueryObjecti64vNV(gpu: int, id: int, pname: int, params: Int64Array) -> None: ...
def glMulticastGetQueryObjectivNV(gpu: int, id: int, pname: int, params: IntArray) -> None: ...
def glMulticastGetQueryObjectui64vNV(gpu: int, id: int, pname: int, params: UInt64Array) -> None: ...
def glMulticastGetQueryObjectuivNV(gpu: int, id: int, pname: int, params: UIntArray) -> None: ...
def glMulticastWaitSyncNV(signalGpu: int, waitGpuMask: int) -> None: ...
def glRenderGpuMaskNV(mask: int) -> None: ...

def glInitGpuMulticastNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
