"""OpenGL.GL.NV.half_float -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UShortArray

from OpenGL.raw.GL._types import *

GL_HALF_FLOAT_NV: int

def glColor3hNV(red: int, green: int, blue: int) -> None: ...
def glColor3hvNV(v: UShortArray) -> None: ...
def glColor4hNV(red: int, green: int, blue: int, alpha: int) -> None: ...
def glColor4hvNV(v: UShortArray) -> None: ...
def glFogCoordhNV(fog: int) -> None: ...
def glFogCoordhvNV(fog: UShortArray) -> None: ...
def glMultiTexCoord1hNV(target: int, s: int) -> None: ...
def glMultiTexCoord1hvNV(target: int, v: UShortArray) -> None: ...
def glMultiTexCoord2hNV(target: int, s: int, t: int) -> None: ...
def glMultiTexCoord2hvNV(target: int, v: UShortArray) -> None: ...
def glMultiTexCoord3hNV(target: int, s: int, t: int, r: int) -> None: ...
def glMultiTexCoord3hvNV(target: int, v: UShortArray) -> None: ...
def glMultiTexCoord4hNV(target: int, s: int, t: int, r: int, q: int) -> None: ...
def glMultiTexCoord4hvNV(target: int, v: UShortArray) -> None: ...
def glNormal3hNV(nx: int, ny: int, nz: int) -> None: ...
def glNormal3hvNV(v: UShortArray) -> None: ...
def glSecondaryColor3hNV(red: int, green: int, blue: int) -> None: ...
def glSecondaryColor3hvNV(v: UShortArray) -> None: ...
def glTexCoord1hNV(s: int) -> None: ...
def glTexCoord1hvNV(v: UShortArray) -> None: ...
def glTexCoord2hNV(s: int, t: int) -> None: ...
def glTexCoord2hvNV(v: UShortArray) -> None: ...
def glTexCoord3hNV(s: int, t: int, r: int) -> None: ...
def glTexCoord3hvNV(v: UShortArray) -> None: ...
def glTexCoord4hNV(s: int, t: int, r: int, q: int) -> None: ...
def glTexCoord4hvNV(v: UShortArray) -> None: ...
def glVertex2hNV(x: int, y: int) -> None: ...
def glVertex2hvNV(v: UShortArray) -> None: ...
def glVertex3hNV(x: int, y: int, z: int) -> None: ...
def glVertex3hvNV(v: UShortArray) -> None: ...
def glVertex4hNV(x: int, y: int, z: int, w: int) -> None: ...
def glVertex4hvNV(v: UShortArray) -> None: ...
def glVertexAttrib1hNV(index: int, x: int) -> None: ...
def glVertexAttrib1hvNV(index: int, v: UShortArray) -> None: ...
def glVertexAttrib2hNV(index: int, x: int, y: int) -> None: ...
def glVertexAttrib2hvNV(index: int, v: UShortArray) -> None: ...
def glVertexAttrib3hNV(index: int, x: int, y: int, z: int) -> None: ...
def glVertexAttrib3hvNV(index: int, v: UShortArray) -> None: ...
def glVertexAttrib4hNV(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttrib4hvNV(index: int, v: UShortArray) -> None: ...
def glVertexAttribs1hvNV(index: int, n: int, v: UShortArray) -> None: ...
def glVertexAttribs2hvNV(index: int, n: int, v: UShortArray) -> None: ...
def glVertexAttribs3hvNV(index: int, n: int, v: UShortArray) -> None: ...
def glVertexAttribs4hvNV(index: int, n: int, v: UShortArray) -> None: ...
def glVertexWeighthNV(weight: int) -> None: ...
def glVertexWeighthvNV(weight: UShortArray) -> None: ...

def glInitHalfFloatNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
