"""OpenGL.GL.NV.memory_object_sparse -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

def glBufferPageCommitmentMemNV(target: int, offset: int, size: int, memory: int, memOffset: int, commit: bool) -> None: ...
def glNamedBufferPageCommitmentMemNV(buffer: int, offset: int, size: int, memory: int, memOffset: int, commit: bool) -> None: ...
def glTexPageCommitmentMemNV(target: int, layer: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, memory: int, offset: int, commit: bool) -> None: ...
def glTexturePageCommitmentMemNV(texture: int, layer: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, memory: int, offset: int, commit: bool) -> None: ...

def glInitMemoryObjectSparseNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
