"""OpenGL.GL.NV.occlusion_query -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray, IntArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_CURRENT_OCCLUSION_QUERY_ID_NV: int
GL_PIXEL_COUNTER_BITS_NV: int
GL_PIXEL_COUNT_AVAILABLE_NV: int
GL_PIXEL_COUNT_NV: int

def glBeginOcclusionQueryNV(id: int) -> None: ...
def glDeleteOcclusionQueriesNV(n: int, ids: UIntArray) -> None: ...
def glEndOcclusionQueryNV() -> None: ...
def glGenOcclusionQueriesNV(n: int, ids: UIntArray | None = None) -> UIntArrayResult: ...
def glGetOcclusionQueryivNV(id: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetOcclusionQueryuivNV(id: int, pname: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glIsOcclusionQueryNV(id: int) -> int: ...

def glInitOcclusionQueryNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
