"""OpenGL.GL.NV.present_video -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import Int64Array, Int64ArrayResult, IntArray, IntArrayResult, UInt64Array, UInt64ArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_CURRENT_TIME_NV: int
GL_FIELDS_NV: int
GL_FRAME_NV: int
GL_NUM_FILL_STREAMS_NV: int
GL_PRESENT_DURATION_NV: int
GL_PRESENT_TIME_NV: int

def glGetVideoi64vNV(video_slot: int, pname: int, params: Int64Array | None = None) -> Int64ArrayResult: ...
def glGetVideoivNV(video_slot: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetVideoui64vNV(video_slot: int, pname: int, params: UInt64Array | None = None) -> UInt64ArrayResult: ...
def glGetVideouivNV(video_slot: int, pname: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glPresentFrameDualFillNV(video_slot: int, minPresentTime: int, beginPresentTimeId: int, presentDurationId: int, type: int, target0: int, fill0: int, target1: int, fill1: int, target2: int, fill2: int, target3: int, fill3: int) -> None: ...
def glPresentFrameKeyedNV(video_slot: int, minPresentTime: int, beginPresentTimeId: int, presentDurationId: int, type: int, target0: int, fill0: int, key0: int, target1: int, fill1: int, key1: int) -> None: ...

def glInitPresentVideoNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
