"""OpenGL.GL.NV.query_resource_tag -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import ByteArray, IntArray

from OpenGL.raw.GL._types import *

def glDeleteQueryResourceTagNV(n: int, tagIds: IntArray) -> None: ...
def glGenQueryResourceTagNV(n: int, tagIds: IntArray) -> None: ...
def glQueryResourceTagNV(tagId: int, tagString: ByteArray) -> None: ...

def glInitQueryResourceTagNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
