"""OpenGL.GL.NV.shader_buffer_load -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UInt64Array, UInt64ArrayResult

from OpenGL.raw.GL._types import *

GL_BUFFER_GPU_ADDRESS_NV: int
GL_GPU_ADDRESS_NV: int
GL_MAX_SHADER_BUFFER_ADDRESS_NV: int

def glGetBufferParameterui64vNV(target: int, pname: int, params: UInt64Array | None = None) -> UInt64ArrayResult: ...
def glGetIntegerui64vNV(value: int, result: UInt64Array | None = None) -> UInt64ArrayResult: ...
def glGetNamedBufferParameterui64vNV(buffer: int, pname: int, params: UInt64Array | None = None) -> UInt64ArrayResult: ...
def glGetUniformui64vNV(program: int, location: int, params: UInt64Array) -> None: ...
def glIsBufferResidentNV(target: int) -> int: ...
def glIsNamedBufferResidentNV(buffer: int) -> int: ...
def glMakeBufferNonResidentNV(target: int) -> None: ...
def glMakeBufferResidentNV(target: int, access: int) -> None: ...
def glMakeNamedBufferNonResidentNV(buffer: int) -> None: ...
def glMakeNamedBufferResidentNV(buffer: int, access: int) -> None: ...
def glProgramUniformui64NV(program: int, location: int, value: int) -> None: ...
def glProgramUniformui64vNV(program: int, location: int, count: int, value: UInt64Array) -> None: ...
def glUniformui64NV(location: int, value: int) -> None: ...
def glUniformui64vNV(location: int, count: int, value: UInt64Array) -> None: ...

def glInitShaderBufferLoadNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
