"""OpenGL.GL.NV.texture_multisample -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

GL_TEXTURE_COLOR_SAMPLES_NV: int
GL_TEXTURE_COVERAGE_SAMPLES_NV: int

def glTexImage2DMultisampleCoverageNV(target: int, coverageSamples: int, colorSamples: int, internalFormat: int, width: int, height: int, fixedSampleLocations: int) -> None: ...
def glTexImage3DMultisampleCoverageNV(target: int, coverageSamples: int, colorSamples: int, internalFormat: int, width: int, height: int, depth: int, fixedSampleLocations: int) -> None: ...
def glTextureImage2DMultisampleCoverageNV(texture: int, target: int, coverageSamples: int, colorSamples: int, internalFormat: int, width: int, height: int, fixedSampleLocations: int) -> None: ...
def glTextureImage2DMultisampleNV(texture: int, target: int, samples: int, internalFormat: int, width: int, height: int, fixedSampleLocations: int) -> None: ...
def glTextureImage3DMultisampleCoverageNV(texture: int, target: int, coverageSamples: int, colorSamples: int, internalFormat: int, width: int, height: int, depth: int, fixedSampleLocations: int) -> None: ...
def glTextureImage3DMultisampleNV(texture: int, target: int, samples: int, internalFormat: int, width: int, height: int, depth: int, fixedSampleLocations: int) -> None: ...

def glInitTextureMultisampleNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
