"""OpenGL.GL.NV.texture_shader3 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

GL_DEPENDENT_HILO_TEXTURE_2D_NV: int
GL_DEPENDENT_RGB_TEXTURE_3D_NV: int
GL_DEPENDENT_RGB_TEXTURE_CUBE_MAP_NV: int
GL_DOT_PRODUCT_AFFINE_DEPTH_REPLACE_NV: int
GL_DOT_PRODUCT_PASS_THROUGH_NV: int
GL_DOT_PRODUCT_TEXTURE_1D_NV: int
GL_FORCE_BLUE_TO_ONE_NV: int
GL_HILO8_NV: int
GL_OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV: int
GL_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV: int
GL_OFFSET_HILO_TEXTURE_2D_NV: int
GL_OFFSET_HILO_TEXTURE_RECTANGLE_NV: int
GL_OFFSET_PROJECTIVE_TEXTURE_2D_NV: int
GL_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV: int
GL_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV: int
GL_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV: int
GL_SIGNED_HILO8_NV: int

def glInitTextureShader3NV() -> bool: ...

def __getattr__(name: str) -> Any: ...
