"""OpenGL.GL.NV.texture_shader -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

GL_CONST_EYE_NV: int
GL_CULL_FRAGMENT_NV: int
GL_CULL_MODES_NV: int
GL_DEPENDENT_AR_TEXTURE_2D_NV: int
GL_DEPENDENT_GB_TEXTURE_2D_NV: int
GL_DOT_PRODUCT_CONST_EYE_REFLECT_CUBE_MAP_NV: int
GL_DOT_PRODUCT_DEPTH_REPLACE_NV: int
GL_DOT_PRODUCT_DIFFUSE_CUBE_MAP_NV: int
GL_DOT_PRODUCT_NV: int
GL_DOT_PRODUCT_REFLECT_CUBE_MAP_NV: int
GL_DOT_PRODUCT_TEXTURE_2D_NV: int
GL_DOT_PRODUCT_TEXTURE_CUBE_MAP_NV: int
GL_DOT_PRODUCT_TEXTURE_RECTANGLE_NV: int
GL_DSDT8_MAG8_INTENSITY8_NV: int
GL_DSDT8_MAG8_NV: int
GL_DSDT8_NV: int
GL_DSDT_MAG_INTENSITY_NV: int
GL_DSDT_MAG_NV: int
GL_DSDT_MAG_VIB_NV: int
GL_DSDT_NV: int
GL_DS_BIAS_NV: int
GL_DS_SCALE_NV: int
GL_DT_BIAS_NV: int
GL_DT_SCALE_NV: int
GL_HILO16_NV: int
GL_HILO_NV: int
GL_HI_BIAS_NV: int
GL_HI_SCALE_NV: int
GL_LO_BIAS_NV: int
GL_LO_SCALE_NV: int
GL_MAGNITUDE_BIAS_NV: int
GL_MAGNITUDE_SCALE_NV: int
GL_OFFSET_TEXTURE_2D_BIAS_NV: int
GL_OFFSET_TEXTURE_2D_MATRIX_NV: int
GL_OFFSET_TEXTURE_2D_NV: int
GL_OFFSET_TEXTURE_2D_SCALE_NV: int
GL_OFFSET_TEXTURE_BIAS_NV: int
GL_OFFSET_TEXTURE_MATRIX_NV: int
GL_OFFSET_TEXTURE_RECTANGLE_NV: int
GL_OFFSET_TEXTURE_RECTANGLE_SCALE_NV: int
GL_OFFSET_TEXTURE_SCALE_NV: int
GL_PASS_THROUGH_NV: int
GL_PREVIOUS_TEXTURE_INPUT_NV: int
GL_RGBA_UNSIGNED_DOT_PRODUCT_MAPPING_NV: int
GL_SHADER_CONSISTENT_NV: int
GL_SHADER_OPERATION_NV: int
GL_SIGNED_ALPHA8_NV: int
GL_SIGNED_ALPHA_NV: int
GL_SIGNED_HILO16_NV: int
GL_SIGNED_HILO_NV: int
GL_SIGNED_INTENSITY8_NV: int
GL_SIGNED_INTENSITY_NV: int
GL_SIGNED_LUMINANCE8_ALPHA8_NV: int
GL_SIGNED_LUMINANCE8_NV: int
GL_SIGNED_LUMINANCE_ALPHA_NV: int
GL_SIGNED_LUMINANCE_NV: int
GL_SIGNED_RGB8_NV: int
GL_SIGNED_RGB8_UNSIGNED_ALPHA8_NV: int
GL_SIGNED_RGBA8_NV: int
GL_SIGNED_RGBA_NV: int
GL_SIGNED_RGB_NV: int
GL_SIGNED_RGB_UNSIGNED_ALPHA_NV: int
GL_TEXTURE_BORDER_VALUES_NV: int
GL_TEXTURE_DS_SIZE_NV: int
GL_TEXTURE_DT_SIZE_NV: int
GL_TEXTURE_HI_SIZE_NV: int
GL_TEXTURE_LO_SIZE_NV: int
GL_TEXTURE_MAG_SIZE_NV: int
GL_TEXTURE_SHADER_NV: int
GL_UNSIGNED_INT_8_8_S8_S8_REV_NV: int
GL_UNSIGNED_INT_S8_S8_8_8_NV: int
GL_VIBRANCE_BIAS_NV: int
GL_VIBRANCE_SCALE_NV: int

def glInitTextureShaderNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
