"""OpenGL.GL.NV.transform_feedback2 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_TRANSFORM_FEEDBACK_BINDING_NV: int
GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE_NV: int
GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED_NV: int
GL_TRANSFORM_FEEDBACK_NV: int

def glBindTransformFeedbackNV(target: int, id: int) -> None: ...
def glDeleteTransformFeedbacksNV(n: int, ids: UIntArray) -> None: ...
def glDrawTransformFeedbackNV(mode: int, id: int) -> None: ...
def glGenTransformFeedbacksNV(n: int, ids: UIntArray | None = None) -> UIntArrayResult: ...
def glIsTransformFeedbackNV(id: int) -> int: ...
def glPauseTransformFeedbackNV() -> None: ...
def glResumeTransformFeedbackNV() -> None: ...

def glInitTransformFeedback2NV() -> bool: ...

def __getattr__(name: str) -> Any: ...
