"""OpenGL.GL.NV.vdpau_interop -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, Int64Array, IntArray, IntArrayResult, UIntArray

from OpenGL.raw.GL._types import *

GL_SURFACE_MAPPED_NV: int
GL_SURFACE_REGISTERED_NV: int
GL_SURFACE_STATE_NV: int
GL_WRITE_DISCARD_NV: int

def glVDPAUFiniNV() -> None: ...
def glVDPAUGetSurfaceivNV(surface: int, pname: int, count: int, length: IntArray, values: IntArray | None = None) -> IntArrayResult: ...
def glVDPAUInitNV(vdpDevice: AnyArray, getProcAddress: AnyArray) -> None: ...
def glVDPAUIsSurfaceNV(surface: int) -> int: ...
def glVDPAUMapSurfacesNV(numSurfaces: int, surfaces: Int64Array) -> None: ...
def glVDPAURegisterOutputSurfaceNV(vdpSurface: AnyArray, target: int, numTextureNames: int, textureNames: UIntArray) -> int: ...
def glVDPAURegisterVideoSurfaceNV(vdpSurface: AnyArray, target: int, numTextureNames: int, textureNames: UIntArray) -> int: ...
def glVDPAUSurfaceAccessNV(surface: int, access: int) -> None: ...
def glVDPAUUnmapSurfacesNV(numSurface: int, surfaces: Int64Array) -> None: ...
def glVDPAUUnregisterSurfaceNV(surface: int) -> None: ...

def glInitVdpauInteropNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
