"""OpenGL.GL.NV.vertex_attrib_integer_64bit -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import Int64Array, Int64ArrayResult, UInt64Array, UInt64ArrayResult

from OpenGL.raw.GL._types import *

GL_INT64_NV: int
GL_UNSIGNED_INT64_NV: int

def glGetVertexAttribLi64vNV(index: int, pname: int, params: Int64Array | None = None) -> Int64ArrayResult: ...
def glGetVertexAttribLui64vNV(index: int, pname: int, params: UInt64Array | None = None) -> UInt64ArrayResult: ...
def glVertexAttribL1i64NV(index: int, x: int) -> None: ...
def glVertexAttribL1i64vNV(index: int, v: Int64Array) -> None: ...
def glVertexAttribL1ui64NV(index: int, x: int) -> None: ...
def glVertexAttribL1ui64vNV(index: int, v: UInt64Array) -> None: ...
def glVertexAttribL2i64NV(index: int, x: int, y: int) -> None: ...
def glVertexAttribL2i64vNV(index: int, v: Int64Array) -> None: ...
def glVertexAttribL2ui64NV(index: int, x: int, y: int) -> None: ...
def glVertexAttribL2ui64vNV(index: int, v: UInt64Array) -> None: ...
def glVertexAttribL3i64NV(index: int, x: int, y: int, z: int) -> None: ...
def glVertexAttribL3i64vNV(index: int, v: Int64Array) -> None: ...
def glVertexAttribL3ui64NV(index: int, x: int, y: int, z: int) -> None: ...
def glVertexAttribL3ui64vNV(index: int, v: UInt64Array) -> None: ...
def glVertexAttribL4i64NV(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttribL4i64vNV(index: int, v: Int64Array) -> None: ...
def glVertexAttribL4ui64NV(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttribL4ui64vNV(index: int, v: UInt64Array) -> None: ...
def glVertexAttribLFormatNV(index: int, size: int, type: int, stride: int) -> None: ...

def glInitVertexAttribInteger64BitNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
