"""OpenGL.GL.NV.vertex_program -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, AnyArrayResult, DoubleArray, DoubleArrayResult, FloatArray, FloatArrayResult, IntArray, IntArrayResult, ShortArray, UByteArray, UByteArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_ATTRIB_ARRAY_POINTER_NV: int
GL_ATTRIB_ARRAY_SIZE_NV: int
GL_ATTRIB_ARRAY_STRIDE_NV: int
GL_ATTRIB_ARRAY_TYPE_NV: int
GL_CURRENT_ATTRIB_NV: int
GL_CURRENT_MATRIX_NV: int
GL_CURRENT_MATRIX_STACK_DEPTH_NV: int
GL_IDENTITY_NV: int
GL_INVERSE_NV: int
GL_INVERSE_TRANSPOSE_NV: int
GL_MAP1_VERTEX_ATTRIB0_4_NV: int
GL_MAP1_VERTEX_ATTRIB10_4_NV: int
GL_MAP1_VERTEX_ATTRIB11_4_NV: int
GL_MAP1_VERTEX_ATTRIB12_4_NV: int
GL_MAP1_VERTEX_ATTRIB13_4_NV: int
GL_MAP1_VERTEX_ATTRIB14_4_NV: int
GL_MAP1_VERTEX_ATTRIB15_4_NV: int
GL_MAP1_VERTEX_ATTRIB1_4_NV: int
GL_MAP1_VERTEX_ATTRIB2_4_NV: int
GL_MAP1_VERTEX_ATTRIB3_4_NV: int
GL_MAP1_VERTEX_ATTRIB4_4_NV: int
GL_MAP1_VERTEX_ATTRIB5_4_NV: int
GL_MAP1_VERTEX_ATTRIB6_4_NV: int
GL_MAP1_VERTEX_ATTRIB7_4_NV: int
GL_MAP1_VERTEX_ATTRIB8_4_NV: int
GL_MAP1_VERTEX_ATTRIB9_4_NV: int
GL_MAP2_VERTEX_ATTRIB0_4_NV: int
GL_MAP2_VERTEX_ATTRIB10_4_NV: int
GL_MAP2_VERTEX_ATTRIB11_4_NV: int
GL_MAP2_VERTEX_ATTRIB12_4_NV: int
GL_MAP2_VERTEX_ATTRIB13_4_NV: int
GL_MAP2_VERTEX_ATTRIB14_4_NV: int
GL_MAP2_VERTEX_ATTRIB15_4_NV: int
GL_MAP2_VERTEX_ATTRIB1_4_NV: int
GL_MAP2_VERTEX_ATTRIB2_4_NV: int
GL_MAP2_VERTEX_ATTRIB3_4_NV: int
GL_MAP2_VERTEX_ATTRIB4_4_NV: int
GL_MAP2_VERTEX_ATTRIB5_4_NV: int
GL_MAP2_VERTEX_ATTRIB6_4_NV: int
GL_MAP2_VERTEX_ATTRIB7_4_NV: int
GL_MAP2_VERTEX_ATTRIB8_4_NV: int
GL_MAP2_VERTEX_ATTRIB9_4_NV: int
GL_MATRIX0_NV: int
GL_MATRIX1_NV: int
GL_MATRIX2_NV: int
GL_MATRIX3_NV: int
GL_MATRIX4_NV: int
GL_MATRIX5_NV: int
GL_MATRIX6_NV: int
GL_MATRIX7_NV: int
GL_MAX_TRACK_MATRICES_NV: int
GL_MAX_TRACK_MATRIX_STACK_DEPTH_NV: int
GL_MODELVIEW_PROJECTION_NV: int
GL_PROGRAM_ERROR_POSITION_NV: int
GL_PROGRAM_LENGTH_NV: int
GL_PROGRAM_PARAMETER_NV: int
GL_PROGRAM_RESIDENT_NV: int
GL_PROGRAM_STRING_NV: int
GL_PROGRAM_TARGET_NV: int
GL_TRACK_MATRIX_NV: int
GL_TRACK_MATRIX_TRANSFORM_NV: int
GL_TRANSPOSE_NV: int
GL_VERTEX_ATTRIB_ARRAY0_NV: int
GL_VERTEX_ATTRIB_ARRAY10_NV: int
GL_VERTEX_ATTRIB_ARRAY11_NV: int
GL_VERTEX_ATTRIB_ARRAY12_NV: int
GL_VERTEX_ATTRIB_ARRAY13_NV: int
GL_VERTEX_ATTRIB_ARRAY14_NV: int
GL_VERTEX_ATTRIB_ARRAY15_NV: int
GL_VERTEX_ATTRIB_ARRAY1_NV: int
GL_VERTEX_ATTRIB_ARRAY2_NV: int
GL_VERTEX_ATTRIB_ARRAY3_NV: int
GL_VERTEX_ATTRIB_ARRAY4_NV: int
GL_VERTEX_ATTRIB_ARRAY5_NV: int
GL_VERTEX_ATTRIB_ARRAY6_NV: int
GL_VERTEX_ATTRIB_ARRAY7_NV: int
GL_VERTEX_ATTRIB_ARRAY8_NV: int
GL_VERTEX_ATTRIB_ARRAY9_NV: int
GL_VERTEX_PROGRAM_BINDING_NV: int
GL_VERTEX_PROGRAM_NV: int
GL_VERTEX_PROGRAM_POINT_SIZE_NV: int
GL_VERTEX_PROGRAM_TWO_SIDE_NV: int
GL_VERTEX_STATE_PROGRAM_NV: int

def glAreProgramsResidentNV(n: int, programs: UIntArray, residences: UByteArray | None = None) -> UByteArrayResult: ...
def glBindProgramNV(target: int, id: int) -> None: ...
def glDeleteProgramsNV(n: int, programs: UIntArray) -> None: ...
def glExecuteProgramNV(target: int, id: int, params: FloatArray) -> None: ...
def glGenProgramsNV(n: int, programs: UIntArray | None = None) -> UIntArrayResult: ...
def glGetProgramParameterdvNV(target: int, index: int, pname: int, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetProgramParameterfvNV(target: int, index: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetProgramStringNV(id: int, pname: int, program: UByteArray) -> None: ...
def glGetProgramivNV(id: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetTrackMatrixivNV(target: int, address: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetVertexAttribPointervNV(index: int, pname: int, pointer: AnyArray | None = None) -> AnyArrayResult: ...
def glGetVertexAttribdvNV(index: int, pname: int, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetVertexAttribfvNV(index: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetVertexAttribivNV(index: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glIsProgramNV(id: int) -> int: ...
def glLoadProgramNV(target: int, id: int, len: int, program: UByteArray) -> None: ...
def glProgramParameter4dNV(target: int, index: int, x: float, y: float, z: float, w: float) -> None: ...
def glProgramParameter4dvNV(target: int, index: int, v: DoubleArray) -> None: ...
def glProgramParameter4fNV(target: int, index: int, x: float, y: float, z: float, w: float) -> None: ...
def glProgramParameter4fvNV(target: int, index: int, v: FloatArray) -> None: ...
def glProgramParameters4dvNV(target: int, index: int, count: int, v: DoubleArray) -> None: ...
def glProgramParameters4fvNV(target: int, index: int, count: int, v: FloatArray) -> None: ...
def glRequestResidentProgramsNV(n: int, programs: UIntArray) -> None: ...
def glTrackMatrixNV(target: int, address: int, matrix: int, transform: int) -> None: ...
def glVertexAttrib1dNV(index: int, x: float) -> None: ...
def glVertexAttrib1dvNV(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib1fNV(index: int, x: float) -> None: ...
def glVertexAttrib1fvNV(index: int, v: FloatArray) -> None: ...
def glVertexAttrib1sNV(index: int, x: int) -> None: ...
def glVertexAttrib1svNV(index: int, v: ShortArray) -> None: ...
def glVertexAttrib2dNV(index: int, x: float, y: float) -> None: ...
def glVertexAttrib2dvNV(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib2fNV(index: int, x: float, y: float) -> None: ...
def glVertexAttrib2fvNV(index: int, v: FloatArray) -> None: ...
def glVertexAttrib2sNV(index: int, x: int, y: int) -> None: ...
def glVertexAttrib2svNV(index: int, v: ShortArray) -> None: ...
def glVertexAttrib3dNV(index: int, x: float, y: float, z: float) -> None: ...
def glVertexAttrib3dvNV(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib3fNV(index: int, x: float, y: float, z: float) -> None: ...
def glVertexAttrib3fvNV(index: int, v: FloatArray) -> None: ...
def glVertexAttrib3sNV(index: int, x: int, y: int, z: int) -> None: ...
def glVertexAttrib3svNV(index: int, v: ShortArray) -> None: ...
def glVertexAttrib4dNV(index: int, x: float, y: float, z: float, w: float) -> None: ...
def glVertexAttrib4dvNV(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib4fNV(index: int, x: float, y: float, z: float, w: float) -> None: ...
def glVertexAttrib4fvNV(index: int, v: FloatArray) -> None: ...
def glVertexAttrib4sNV(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttrib4svNV(index: int, v: ShortArray) -> None: ...
def glVertexAttrib4ubNV(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttrib4ubvNV(index: int, v: UByteArray) -> None: ...
def glVertexAttribPointerNV(index: int, fsize: int, type: int, stride: int, pointer: AnyArray) -> None: ...
def glVertexAttribs1dvNV(index: int, count: int, v: DoubleArray) -> None: ...
def glVertexAttribs1fvNV(index: int, count: int, v: FloatArray) -> None: ...
def glVertexAttribs1svNV(index: int, count: int, v: ShortArray) -> None: ...
def glVertexAttribs2dvNV(index: int, count: int, v: DoubleArray) -> None: ...
def glVertexAttribs2fvNV(index: int, count: int, v: FloatArray) -> None: ...
def glVertexAttribs2svNV(index: int, count: int, v: ShortArray) -> None: ...
def glVertexAttribs3dvNV(index: int, count: int, v: DoubleArray) -> None: ...
def glVertexAttribs3fvNV(index: int, count: int, v: FloatArray) -> None: ...
def glVertexAttribs3svNV(index: int, count: int, v: ShortArray) -> None: ...
def glVertexAttribs4dvNV(index: int, count: int, v: DoubleArray) -> None: ...
def glVertexAttribs4fvNV(index: int, count: int, v: FloatArray) -> None: ...
def glVertexAttribs4svNV(index: int, count: int, v: ShortArray) -> None: ...
def glVertexAttribs4ubvNV(index: int, count: int, v: UByteArray) -> None: ...

def glInitVertexProgramNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
