"""OpenGL.GL.NV.vertex_program4 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, ByteArray, IntArray, IntArrayResult, ShortArray, UByteArray, UIntArray, UIntArrayResult, UShortArray

from OpenGL.raw.GL._types import *

GL_VERTEX_ATTRIB_ARRAY_INTEGER_NV: int

def glGetVertexAttribIivEXT(index: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetVertexAttribIuivEXT(index: int, pname: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glVertexAttribI1iEXT(index: int, x: int) -> None: ...
def glVertexAttribI1ivEXT(index: int, v: IntArray) -> None: ...
def glVertexAttribI1uiEXT(index: int, x: int) -> None: ...
def glVertexAttribI1uivEXT(index: int, v: UIntArray) -> None: ...
def glVertexAttribI2iEXT(index: int, x: int, y: int) -> None: ...
def glVertexAttribI2ivEXT(index: int, v: IntArray) -> None: ...
def glVertexAttribI2uiEXT(index: int, x: int, y: int) -> None: ...
def glVertexAttribI2uivEXT(index: int, v: UIntArray) -> None: ...
def glVertexAttribI3iEXT(index: int, x: int, y: int, z: int) -> None: ...
def glVertexAttribI3ivEXT(index: int, v: IntArray) -> None: ...
def glVertexAttribI3uiEXT(index: int, x: int, y: int, z: int) -> None: ...
def glVertexAttribI3uivEXT(index: int, v: UIntArray) -> None: ...
def glVertexAttribI4bvEXT(index: int, v: ByteArray) -> None: ...
def glVertexAttribI4iEXT(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttribI4ivEXT(index: int, v: IntArray) -> None: ...
def glVertexAttribI4svEXT(index: int, v: ShortArray) -> None: ...
def glVertexAttribI4ubvEXT(index: int, v: UByteArray) -> None: ...
def glVertexAttribI4uiEXT(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttribI4uivEXT(index: int, v: UIntArray) -> None: ...
def glVertexAttribI4usvEXT(index: int, v: UShortArray) -> None: ...
def glVertexAttribIPointerEXT(index: int, size: int, type: int, stride: int, pointer: AnyArray) -> None: ...

def glInitVertexProgram4NV() -> bool: ...

def __getattr__(name: str) -> Any: ...
