'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p
from OpenGL.GL import glget
EXTENSION_NAME = 'GL_ARB_explicit_uniform_location'
_p.unpack_constants( """GL_MAX_UNIFORM_LOCATIONS 0x826E""", globals())


def glInitExplicitUniformLocationARB():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
