'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p
from OpenGL.GL import glget
EXTENSION_NAME = 'GL_ARB_framebuffer_object'
_p.unpack_constants( """GL_INDEX 0x8222
GL_TEXTURE_LUMINANCE_TYPE 0x8C14
GL_TEXTURE_INTENSITY_TYPE 0x8C15""", globals())


def glInitFramebufferObjectDeprecatedARB():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
