'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p
from OpenGL.GL import glget
EXTENSION_NAME = 'GL_ARB_texture_cube_map'
_p.unpack_constants( """GL_NORMAL_MAP_ARB 0x8511
GL_REFLECTION_MAP_ARB 0x8512
GL_TEXTURE_CUBE_MAP_ARB 0x8513
GL_TEXTURE_BINDING_CUBE_MAP_ARB 0x8514
GL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB 0x8515
GL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB 0x8516
GL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB 0x8517
GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB 0x8518
GL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB 0x8519
GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB 0x851A
GL_PROXY_TEXTURE_CUBE_MAP_ARB 0x851B
GL_MAX_CUBE_MAP_TEXTURE_SIZE_ARB 0x851C""", globals())
glget.addGLGetConstant( GL_TEXTURE_CUBE_MAP_ARB, (1,) )
glget.addGLGetConstant( GL_TEXTURE_BINDING_CUBE_MAP_ARB, (1,) )
glget.addGLGetConstant( GL_MAX_CUBE_MAP_TEXTURE_SIZE_ARB, (1,) )


def glInitTextureCubeMapARB():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
