"""OpenGL.GLES2.IMG.bindless_texture -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UInt64Array

from OpenGL.raw.GLES2._types import *

def glGetTextureHandleIMG(texture: int) -> int: ...
def glGetTextureSamplerHandleIMG(texture: int, sampler: int) -> int: ...
def glProgramUniformHandleui64IMG(program: int, location: int, value: int) -> None: ...
def glProgramUniformHandleui64vIMG(program: int, location: int, count: int, values: UInt64Array) -> None: ...
def glUniformHandleui64IMG(location: int, value: int) -> None: ...
def glUniformHandleui64vIMG(location: int, count: int, value: UInt64Array) -> None: ...

def glInitBindlessTextureIMG() -> bool: ...

def __getattr__(name: str) -> Any: ...
