'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p, constants as _cs, arrays
from OpenGL.GL import glget
import ctypes
EXTENSION_NAME = 'GL_EXT_blend_minmax'
def _f( function ):
    return _p.createFunction( function,_p.GL,'GL_EXT_blend_minmax',False)
_p.unpack_constants( """GL_FUNC_ADD_EXT 0x8006
GL_MIN_EXT 0x8007
GL_MAX_EXT 0x8008
GL_BLEND_EQUATION_EXT 0x8009""", globals())
glget.addGLGetConstant( GL_BLEND_EQUATION_EXT, (1,) )
@_f
@_p.types(None,_cs.GLenum)
def glBlendEquationEXT( mode ):pass


def glInitBlendMinmaxEXT():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
