'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p, constants as _cs, arrays
from OpenGL.GL import glget
import ctypes
EXTENSION_NAME = 'GL_EXT_blend_func_separate'
def _f( function ):
    return _p.createFunction( function,_p.GL,'GL_EXT_blend_func_separate',False)
_p.unpack_constants( """GL_BLEND_DST_RGB_EXT 0x80C8
GL_BLEND_SRC_RGB_EXT 0x80C9
GL_BLEND_DST_ALPHA_EXT 0x80CA
GL_BLEND_SRC_ALPHA_EXT 0x80CB""", globals())
glget.addGLGetConstant( GL_BLEND_DST_RGB_EXT, (1,) )
glget.addGLGetConstant( GL_BLEND_SRC_RGB_EXT, (1,) )
glget.addGLGetConstant( GL_BLEND_DST_ALPHA_EXT, (1,) )
glget.addGLGetConstant( GL_BLEND_SRC_ALPHA_EXT, (1,) )
@_f
@_p.types(None,_cs.GLenum,_cs.GLenum,_cs.GLenum,_cs.GLenum)
def glBlendFuncSeparateEXT( sfactorRGB,dfactorRGB,sfactorAlpha,dfactorAlpha ):pass


def glInitBlendFuncSeparateEXT():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
