'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p, constants as _cs, arrays
from OpenGL.GL import glget
import ctypes
EXTENSION_NAME = 'GL_EXT_compiled_vertex_array'
def _f( function ):
    return _p.createFunction( function,_p.GL,'GL_EXT_compiled_vertex_array',False)
_p.unpack_constants( """GL_ARRAY_ELEMENT_LOCK_FIRST_EXT 0x81A8
GL_ARRAY_ELEMENT_LOCK_COUNT_EXT 0x81A9""", globals())
glget.addGLGetConstant( GL_ARRAY_ELEMENT_LOCK_FIRST_EXT, (1,) )
glget.addGLGetConstant( GL_ARRAY_ELEMENT_LOCK_COUNT_EXT, (1,) )
@_f
@_p.types(None,_cs.GLint,_cs.GLsizei)
def glLockArraysEXT( first,count ):pass
@_f
@_p.types(None,)
def glUnlockArraysEXT(  ):pass


def glInitCompiledVertexArrayEXT():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
