'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p
from OpenGL.GL import glget
EXTENSION_NAME = 'GL_EXT_stencil_wrap'
_p.unpack_constants( """GL_INCR_WRAP_EXT 0x8507
GL_DECR_WRAP_EXT 0x8508""", globals())


def glInitStencilWrapEXT():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
