'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p, constants as _cs, arrays
from OpenGL.GL import glget
import ctypes
EXTENSION_NAME = 'GL_EXT_stencil_clear_tag'
def _f( function ):
    return _p.createFunction( function,_p.GL,'GL_EXT_stencil_clear_tag',False)
_p.unpack_constants( """GL_STENCIL_TAG_BITS_EXT 0x88F2
GL_STENCIL_CLEAR_TAG_VALUE_EXT 0x88F3""", globals())
@_f
@_p.types(None,_cs.GLsizei,_cs.GLuint)
def glStencilClearTagEXT( stencilTagBits,stencilClearTag ):pass


def glInitStencilClearTagEXT():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
