'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p
from OpenGL.GL import glget
EXTENSION_NAME = 'GL_EXT_texture_compression_s3tc'
_p.unpack_constants( """GL_COMPRESSED_RGB_S3TC_DXT1_EXT 0x83F0
GL_COMPRESSED_RGBA_S3TC_DXT1_EXT 0x83F1
GL_COMPRESSED_RGBA_S3TC_DXT3_EXT 0x83F2
GL_COMPRESSED_RGBA_S3TC_DXT5_EXT 0x83F3""", globals())


def glInitTextureCompressionS3TcEXT():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
