'''OpenGL extension ANGLE.surface_d3d_texture_2d_share_handle

This module customises the behaviour of the 
OpenGL.raw.EGL.ANGLE.surface_d3d_texture_2d_share_handle to provide a more 
Python-friendly API

The official definition of this extension is available here:
http://www.opengl.org/registry/specs/ANGLE/surface_d3d_texture_2d_share_handle.txt
'''
from OpenGL import platform, constant, arrays
from OpenGL import extensions, wrapper
import ctypes
from OpenGL.raw.EGL import _types, _glgets
from OpenGL._declarations import define as _define
_EXTENSION_NAME = _define(globals(), 'OpenGL.raw.EGL.ANGLE.surface_d3d_texture_2d_share_handle')

def glInitSurfaceD3DTexture2DShareHandleANGLE():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( _EXTENSION_NAME )


### END AUTOGENERATED SECTION