"""OpenGL.GLES2.MESA.sampler_objects -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray, FloatArrayResult, IntArray, IntArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GLES2._types import *

GL_SAMPLER_BINDING: int

def glBindSampler(unit: int, sampler: int) -> None: ...
def glDeleteSamplers(count: int, samplers: UIntArray) -> None: ...
def glGenSamplers(count: int, samplers: UIntArray | None = None) -> UIntArrayResult: ...
def glGetSamplerParameterfv(sampler: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetSamplerParameteriv(sampler: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glIsSampler(sampler: int) -> int: ...
def glSamplerParameterf(sampler: int, pname: int, param: float) -> None: ...
def glSamplerParameterfv(sampler: int, pname: int, param: FloatArray) -> None: ...
def glSamplerParameteri(sampler: int, pname: int, param: int) -> None: ...
def glSamplerParameteriv(sampler: int, pname: int, param: IntArray) -> None: ...

def glInitSamplerObjectsMESA() -> bool: ...

def __getattr__(name: str) -> Any: ...
