"""OpenGL.GLES1.OES.byte_coordinates -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import ByteArray

from OpenGL.raw.GLES1._types import *

GL_BYTE: int

def glMultiTexCoord1bOES(texture: int, s: int) -> None: ...
def glMultiTexCoord1bvOES(texture: int, coords: ByteArray) -> None: ...
def glMultiTexCoord2bOES(texture: int, s: int, t: int) -> None: ...
def glMultiTexCoord2bvOES(texture: int, coords: ByteArray) -> None: ...
def glMultiTexCoord3bOES(texture: int, s: int, t: int, r: int) -> None: ...
def glMultiTexCoord3bvOES(texture: int, coords: ByteArray) -> None: ...
def glMultiTexCoord4bOES(texture: int, s: int, t: int, r: int, q: int) -> None: ...
def glMultiTexCoord4bvOES(texture: int, coords: ByteArray) -> None: ...
def glTexCoord1bOES(s: int) -> None: ...
def glTexCoord1bvOES(coords: ByteArray) -> None: ...
def glTexCoord2bOES(s: int, t: int) -> None: ...
def glTexCoord2bvOES(coords: ByteArray) -> None: ...
def glTexCoord3bOES(s: int, t: int, r: int) -> None: ...
def glTexCoord3bvOES(coords: ByteArray) -> None: ...
def glTexCoord4bOES(s: int, t: int, r: int, q: int) -> None: ...
def glTexCoord4bvOES(coords: ByteArray) -> None: ...
def glVertex2bOES(x: int, y: int) -> None: ...
def glVertex2bvOES(coords: ByteArray) -> None: ...
def glVertex3bOES(x: int, y: int, z: int) -> None: ...
def glVertex3bvOES(coords: ByteArray) -> None: ...
def glVertex4bOES(x: int, y: int, z: int, w: int) -> None: ...
def glVertex4bvOES(coords: ByteArray) -> None: ...

def glInitByteCoordinatesOES() -> bool: ...

def __getattr__(name: str) -> Any: ...
