"""OpenGL.GLES1.OES.draw_texture -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray, IntArray, ShortArray

from OpenGL.raw.GLES1._types import *

GL_TEXTURE_CROP_RECT_OES: int

def glDrawTexfOES(x: float, y: float, z: float, width: float, height: float) -> None: ...
def glDrawTexfvOES(coords: FloatArray) -> None: ...
def glDrawTexiOES(x: int, y: int, z: int, width: int, height: int) -> None: ...
def glDrawTexivOES(coords: IntArray) -> None: ...
def glDrawTexsOES(x: int, y: int, z: int, width: int, height: int) -> None: ...
def glDrawTexsvOES(coords: ShortArray) -> None: ...
def glDrawTexxOES(x: int, y: int, z: int, width: int, height: int) -> None: ...
def glDrawTexxvOES(coords: IntArray) -> None: ...

def glInitDrawTextureOES() -> bool: ...

def __getattr__(name: str) -> Any: ...
