"""OpenGL.GLES1.OES.fixed_point -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray, IntArrayResult, UByteArray, UIntArray

from OpenGL.raw.GLES1._types import *

GL_FIXED_OES: int

def glAccumxOES(op: int, value: int) -> None: ...
def glAlphaFuncxOES(func: int, ref: int) -> None: ...
def glBitmapxOES(width: int, height: int, xorig: int, yorig: int, xmove: int, ymove: int, bitmap: UByteArray) -> None: ...
def glBlendColorxOES(red: int, green: int, blue: int, alpha: int) -> None: ...
def glClearAccumxOES(red: int, green: int, blue: int, alpha: int) -> None: ...
def glClearColorxOES(red: int, green: int, blue: int, alpha: int) -> None: ...
def glClearDepthxOES(depth: int) -> None: ...
def glClipPlanexOES(plane: int, equation: IntArray) -> None: ...
def glColor3xOES(red: int, green: int, blue: int) -> None: ...
def glColor3xvOES(components: IntArray) -> None: ...
def glColor4xOES(red: int, green: int, blue: int, alpha: int) -> None: ...
def glColor4xvOES(components: IntArray) -> None: ...
def glConvolutionParameterxOES(target: int, pname: int, param: int) -> None: ...
def glConvolutionParameterxvOES(target: int, pname: int, params: IntArray) -> None: ...
def glDepthRangexOES(n: int, f: int) -> None: ...
def glEvalCoord1xOES(u: int) -> None: ...
def glEvalCoord1xvOES(coords: IntArray) -> None: ...
def glEvalCoord2xOES(u: int, v: int) -> None: ...
def glEvalCoord2xvOES(coords: IntArray) -> None: ...
def glFeedbackBufferxOES(n: int, type: int, buffer: IntArray) -> None: ...
def glFogxOES(pname: int, param: int) -> None: ...
def glFogxvOES(pname: int, param: IntArray) -> None: ...
def glFrustumxOES(l: int, r: int, b: int, t: int, n: int, f: int) -> None: ...
def glGetClipPlanexOES(plane: int, equation: IntArray | None = None) -> IntArrayResult: ...
def glGetConvolutionParameterxvOES(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetFixedvOES(pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetHistogramParameterxvOES(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetLightxOES(light: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetLightxvOES(light: int, pname: int, params: IntArray) -> None: ...
def glGetMapxvOES(target: int, query: int, v: IntArray | None = None) -> IntArrayResult: ...
def glGetMaterialxOES(face: int, pname: int, param: int) -> None: ...
def glGetMaterialxvOES(face: int, pname: int, params: IntArray) -> None: ...
def glGetPixelMapxv(map: int, size: int, values: IntArray | None = None) -> IntArrayResult: ...
def glGetTexEnvxvOES(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetTexGenxvOES(coord: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetTexLevelParameterxvOES(target: int, level: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetTexParameterxvOES(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glIndexxOES(component: int) -> None: ...
def glIndexxvOES(component: IntArray) -> None: ...
def glLightModelxOES(pname: int, param: int) -> None: ...
def glLightModelxvOES(pname: int, param: IntArray) -> None: ...
def glLightxOES(light: int, pname: int, param: int) -> None: ...
def glLightxvOES(light: int, pname: int, params: IntArray) -> None: ...
def glLineWidthxOES(width: int) -> None: ...
def glLoadMatrixxOES(m: IntArray) -> None: ...
def glLoadTransposeMatrixxOES(m: IntArray) -> None: ...
def glMap1xOES(target: int, u1: int, u2: int, stride: int, order: int, points: int) -> None: ...
def glMap2xOES(target: int, u1: int, u2: int, ustride: int, uorder: int, v1: int, v2: int, vstride: int, vorder: int, points: int) -> None: ...
def glMapGrid1xOES(n: int, u1: int, u2: int) -> None: ...
def glMapGrid2xOES(n: int, u1: int, u2: int, v1: int, v2: int) -> None: ...
def glMaterialxOES(face: int, pname: int, param: int) -> None: ...
def glMaterialxvOES(face: int, pname: int, param: IntArray) -> None: ...
def glMultMatrixxOES(m: IntArray) -> None: ...
def glMultTransposeMatrixxOES(m: IntArray) -> None: ...
def glMultiTexCoord1xOES(texture: int, s: int) -> None: ...
def glMultiTexCoord1xvOES(texture: int, coords: IntArray) -> None: ...
def glMultiTexCoord2xOES(texture: int, s: int, t: int) -> None: ...
def glMultiTexCoord2xvOES(texture: int, coords: IntArray) -> None: ...
def glMultiTexCoord3xOES(texture: int, s: int, t: int, r: int) -> None: ...
def glMultiTexCoord3xvOES(texture: int, coords: IntArray) -> None: ...
def glMultiTexCoord4xOES(texture: int, s: int, t: int, r: int, q: int) -> None: ...
def glMultiTexCoord4xvOES(texture: int, coords: IntArray) -> None: ...
def glNormal3xOES(nx: int, ny: int, nz: int) -> None: ...
def glNormal3xvOES(coords: IntArray) -> None: ...
def glOrthoxOES(l: int, r: int, b: int, t: int, n: int, f: int) -> None: ...
def glPassThroughxOES(token: int) -> None: ...
def glPixelMapx(map: int, size: int, values: IntArray) -> None: ...
def glPixelStorex(pname: int, param: int) -> None: ...
def glPixelTransferxOES(pname: int, param: int) -> None: ...
def glPixelZoomxOES(xfactor: int, yfactor: int) -> None: ...
def glPointParameterxOES(pname: int, param: int) -> None: ...
def glPointParameterxvOES(pname: int, params: IntArray) -> None: ...
def glPointSizexOES(size: int) -> None: ...
def glPolygonOffsetxOES(factor: int, units: int) -> None: ...
def glPrioritizeTexturesxOES(n: int, textures: UIntArray, priorities: IntArray) -> None: ...
def glRasterPos2xOES(x: int, y: int) -> None: ...
def glRasterPos2xvOES(coords: IntArray) -> None: ...
def glRasterPos3xOES(x: int, y: int, z: int) -> None: ...
def glRasterPos3xvOES(coords: IntArray) -> None: ...
def glRasterPos4xOES(x: int, y: int, z: int, w: int) -> None: ...
def glRasterPos4xvOES(coords: IntArray) -> None: ...
def glRectxOES(x1: int, y1: int, x2: int, y2: int) -> None: ...
def glRectxvOES(v1: IntArray, v2: IntArray) -> None: ...
def glRotatexOES(angle: int, x: int, y: int, z: int) -> None: ...
def glSampleCoveragexOES(value: int, invert: bool) -> None: ...
def glScalexOES(x: int, y: int, z: int) -> None: ...
def glTexCoord1xOES(s: int) -> None: ...
def glTexCoord1xvOES(coords: IntArray) -> None: ...
def glTexCoord2xOES(s: int, t: int) -> None: ...
def glTexCoord2xvOES(coords: IntArray) -> None: ...
def glTexCoord3xOES(s: int, t: int, r: int) -> None: ...
def glTexCoord3xvOES(coords: IntArray) -> None: ...
def glTexCoord4xOES(s: int, t: int, r: int, q: int) -> None: ...
def glTexCoord4xvOES(coords: IntArray) -> None: ...
def glTexEnvxOES(target: int, pname: int, param: int) -> None: ...
def glTexEnvxvOES(target: int, pname: int, params: IntArray) -> None: ...
def glTexGenxOES(coord: int, pname: int, param: int) -> None: ...
def glTexGenxvOES(coord: int, pname: int, params: IntArray) -> None: ...
def glTexParameterxOES(target: int, pname: int, param: int) -> None: ...
def glTexParameterxvOES(target: int, pname: int, params: IntArray) -> None: ...
def glTranslatexOES(x: int, y: int, z: int) -> None: ...
def glVertex2xOES(x: int) -> None: ...
def glVertex2xvOES(coords: IntArray) -> None: ...
def glVertex3xOES(x: int, y: int) -> None: ...
def glVertex3xvOES(coords: IntArray) -> None: ...
def glVertex4xOES(x: int, y: int, z: int) -> None: ...
def glVertex4xvOES(coords: IntArray) -> None: ...

def glInitFixedPointOES() -> bool: ...

def __getattr__(name: str) -> Any: ...
