"""OpenGL.GLES1.OES.texture_cube_map -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray, IntArray, IntArrayResult

from OpenGL.raw.GLES1._types import *

GL_MAX_CUBE_MAP_TEXTURE_SIZE_OES: int
GL_NORMAL_MAP_OES: int
GL_REFLECTION_MAP_OES: int
GL_TEXTURE_BINDING_CUBE_MAP_OES: int
GL_TEXTURE_CUBE_MAP_NEGATIVE_X_OES: int
GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_OES: int
GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_OES: int
GL_TEXTURE_CUBE_MAP_OES: int
GL_TEXTURE_CUBE_MAP_POSITIVE_X_OES: int
GL_TEXTURE_CUBE_MAP_POSITIVE_Y_OES: int
GL_TEXTURE_CUBE_MAP_POSITIVE_Z_OES: int
GL_TEXTURE_GEN_MODE_OES: int
GL_TEXTURE_GEN_STR_OES: int

def glGetTexGenfvOES(coord: int, pname: int, params: FloatArray) -> None: ...
def glGetTexGenivOES(coord: int, pname: int, params: IntArray) -> None: ...
def glGetTexGenxvOES(coord: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glTexGenfOES(coord: int, pname: int, param: float) -> None: ...
def glTexGenfvOES(coord: int, pname: int, params: FloatArray) -> None: ...
def glTexGeniOES(coord: int, pname: int, param: int) -> None: ...
def glTexGenivOES(coord: int, pname: int, params: IntArray) -> None: ...
def glTexGenxOES(coord: int, pname: int, param: int) -> None: ...
def glTexGenxvOES(coord: int, pname: int, params: IntArray) -> None: ...

def glInitTextureCubeMapOES() -> bool: ...

def __getattr__(name: str) -> Any: ...
