"""OpenGL.WGL.VERSION.WGL_1_0 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.WGL._types import *

WGL_FONT_LINES: int
WGL_FONT_POLYGONS: int
WGL_SWAP_MAIN_PLANE: int
WGL_SWAP_OVERLAY1: int
WGL_SWAP_OVERLAY10: int
WGL_SWAP_OVERLAY11: int
WGL_SWAP_OVERLAY12: int
WGL_SWAP_OVERLAY13: int
WGL_SWAP_OVERLAY14: int
WGL_SWAP_OVERLAY15: int
WGL_SWAP_OVERLAY2: int
WGL_SWAP_OVERLAY3: int
WGL_SWAP_OVERLAY4: int
WGL_SWAP_OVERLAY5: int
WGL_SWAP_OVERLAY6: int
WGL_SWAP_OVERLAY7: int
WGL_SWAP_OVERLAY8: int
WGL_SWAP_OVERLAY9: int
WGL_SWAP_UNDERLAY1: int
WGL_SWAP_UNDERLAY10: int
WGL_SWAP_UNDERLAY11: int
WGL_SWAP_UNDERLAY12: int
WGL_SWAP_UNDERLAY13: int
WGL_SWAP_UNDERLAY14: int
WGL_SWAP_UNDERLAY15: int
WGL_SWAP_UNDERLAY2: int
WGL_SWAP_UNDERLAY3: int
WGL_SWAP_UNDERLAY4: int
WGL_SWAP_UNDERLAY5: int
WGL_SWAP_UNDERLAY6: int
WGL_SWAP_UNDERLAY7: int
WGL_SWAP_UNDERLAY8: int
WGL_SWAP_UNDERLAY9: int

def ChoosePixelFormat(hDc: Any, pPfd: AnyArray) -> int: ...
def DescribePixelFormat(hdc: Any, ipfd: int, cjpfd: int, ppfd: AnyArray) -> int: ...
def GetEnhMetaFilePixelFormat(hemf: Any, cbBuffer: int, ppfd: AnyArray) -> int: ...
def GetPixelFormat(hdc: Any) -> int: ...
def SetPixelFormat(hdc: Any, ipfd: int, ppfd: AnyArray) -> int: ...
def SwapBuffers(hdc: Any) -> int: ...
def wglCopyContext(hglrcSrc: Any, hglrcDst: Any, mask: int) -> int: ...
def wglCreateContext(hDc: Any) -> Any: ...
def wglCreateLayerContext(hDc: Any, level: int) -> Any: ...
def wglDeleteContext(oldContext: Any) -> int: ...
def wglDescribeLayerPlane(hDc: Any, pixelFormat: int, layerPlane: int, nBytes: int, plpd: AnyArray) -> int: ...
def wglGetCurrentContext() -> Any: ...
def wglGetCurrentDC() -> Any: ...
def wglGetLayerPaletteEntries(hdc: Any, iLayerPlane: int, iStart: int, cEntries: int, pcr: AnyArray) -> int: ...
def wglGetProcAddress(lpszProc: Any) -> Any: ...
def wglMakeCurrent(hDc: Any, newContext: Any) -> int: ...
def wglRealizeLayerPalette(hdc: Any, iLayerPlane: int, bRealize: int) -> int: ...
def wglSetLayerPaletteEntries(hdc: Any, iLayerPlane: int, iStart: int, cEntries: int, pcr: AnyArray) -> int: ...
def wglShareLists(hrcSrvShare: Any, hrcSrvSource: Any) -> int: ...
def wglSwapLayerBuffers(hdc: Any, fuFlags: int) -> int: ...
def wglUseFontBitmaps(hDC: Any, first: int, count: int, listBase: int) -> int: ...
def wglUseFontBitmapsA(hDC: Any, first: int, count: int, listBase: int) -> int: ...
def wglUseFontBitmapsW(hDC: Any, first: int, count: int, listBase: int) -> int: ...
def wglUseFontOutlines(hDC: Any, first: int, count: int, listBase: int, deviation: float, extrusion: float, format: int, lpgmf: Any) -> int: ...
def wglUseFontOutlinesA(hDC: Any, first: int, count: int, listBase: int, deviation: float, extrusion: float, format: int, lpgmf: Any) -> int: ...
def wglUseFontOutlinesW(hDC: Any, first: int, count: int, listBase: int, deviation: float, extrusion: float, format: int, lpgmf: Any) -> int: ...

def glInitWgl10VERSION() -> bool: ...

def __getattr__(name: str) -> Any: ...
