"""OpenGL.GL.ARB.base_instance -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.GL._types import *

def glDrawArraysInstancedBaseInstance(mode: int, first: int, count: int, instancecount: int, baseinstance: int) -> None: ...
def glDrawElementsInstancedBaseInstance(mode: int, count: int, type: int, indices: AnyArray, instancecount: int, baseinstance: int) -> None: ...
def glDrawElementsInstancedBaseVertexBaseInstance(mode: int, count: int, type: int, indices: AnyArray, instancecount: int, basevertex: int, baseinstance: int) -> None: ...

def glInitBaseInstanceARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
