"""OpenGL.GL.ARB.bindless_texture -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UInt64Array

from OpenGL.raw.GL._types import *

GL_UNSIGNED_INT64_ARB: int

def glGetImageHandleARB(texture: int, level: int, layered: bool, layer: int, format: int) -> int: ...
def glGetTextureHandleARB(texture: int) -> int: ...
def glGetTextureSamplerHandleARB(texture: int, sampler: int) -> int: ...
def glGetVertexAttribLui64vARB(index: int, pname: int, params: UInt64Array) -> None: ...
def glIsImageHandleResidentARB(handle: int) -> int: ...
def glIsTextureHandleResidentARB(handle: int) -> int: ...
def glMakeImageHandleNonResidentARB(handle: int) -> None: ...
def glMakeImageHandleResidentARB(handle: int, access: int) -> None: ...
def glMakeTextureHandleNonResidentARB(handle: int) -> None: ...
def glMakeTextureHandleResidentARB(handle: int) -> None: ...
def glProgramUniformHandleui64ARB(program: int, location: int, value: int) -> None: ...
def glProgramUniformHandleui64vARB(program: int, location: int, count: int, values: UInt64Array) -> None: ...
def glUniformHandleui64ARB(location: int, value: int) -> None: ...
def glUniformHandleui64vARB(location: int, count: int, value: UInt64Array) -> None: ...
def glVertexAttribL1ui64ARB(index: int, x: int) -> None: ...
def glVertexAttribL1ui64vARB(index: int, v: UInt64Array) -> None: ...

def glInitBindlessTextureARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
