"""OpenGL.GL.ARB.draw_buffers_blend -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

def glBlendEquationSeparateiARB(buf: int, modeRGB: int, modeAlpha: int) -> None: ...
def glBlendEquationiARB(buf: int, mode: int) -> None: ...
def glBlendFuncSeparateiARB(buf: int, srcRGB: int, dstRGB: int, srcAlpha: int, dstAlpha: int) -> None: ...
def glBlendFunciARB(buf: int, src: int, dst: int) -> None: ...

def glInitDrawBuffersBlendARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
