"""OpenGL.GL.ARB.draw_elements_base_vertex -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray

from OpenGL.raw.GL._types import *

def glDrawElementsBaseVertex(mode: int, count: int, type: int, indices: AnyArray, basevertex: int) -> None: ...
def glDrawElementsInstancedBaseVertex(mode: int, count: int, type: int, indices: AnyArray, instancecount: int, basevertex: int) -> None: ...
def glDrawRangeElementsBaseVertex(mode: int, start: int, end: int, count: int, type: int, indices: AnyArray, basevertex: int) -> None: ...
def glMultiDrawElementsBaseVertex(mode: int, count: IntArray, type: int, indices: AnyArray, drawcount: int, basevertex: IntArray) -> None: ...

def glInitDrawElementsBaseVertexARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
