"""OpenGL.GL.ARB.gpu_shader_int64 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import Int64Array, UInt64Array

from OpenGL.raw.GL._types import *

GL_INT64_ARB: int
GL_INT64_VEC2_ARB: int
GL_INT64_VEC3_ARB: int
GL_INT64_VEC4_ARB: int
GL_UNSIGNED_INT64_ARB: int
GL_UNSIGNED_INT64_VEC2_ARB: int
GL_UNSIGNED_INT64_VEC3_ARB: int
GL_UNSIGNED_INT64_VEC4_ARB: int

def glGetUniformi64vARB(program: int, location: int, params: Int64Array) -> None: ...
def glGetUniformui64vARB(program: int, location: int, params: UInt64Array) -> None: ...
def glGetnUniformi64vARB(program: int, location: int, bufSize: int, params: Int64Array) -> None: ...
def glGetnUniformui64vARB(program: int, location: int, bufSize: int, params: UInt64Array) -> None: ...
def glProgramUniform1i64ARB(program: int, location: int, x: int) -> None: ...
def glProgramUniform1i64vARB(program: int, location: int, count: int, value: Int64Array) -> None: ...
def glProgramUniform1ui64ARB(program: int, location: int, x: int) -> None: ...
def glProgramUniform1ui64vARB(program: int, location: int, count: int, value: UInt64Array) -> None: ...
def glProgramUniform2i64ARB(program: int, location: int, x: int, y: int) -> None: ...
def glProgramUniform2i64vARB(program: int, location: int, count: int, value: Int64Array) -> None: ...
def glProgramUniform2ui64ARB(program: int, location: int, x: int, y: int) -> None: ...
def glProgramUniform2ui64vARB(program: int, location: int, count: int, value: UInt64Array) -> None: ...
def glProgramUniform3i64ARB(program: int, location: int, x: int, y: int, z: int) -> None: ...
def glProgramUniform3i64vARB(program: int, location: int, count: int, value: Int64Array) -> None: ...
def glProgramUniform3ui64ARB(program: int, location: int, x: int, y: int, z: int) -> None: ...
def glProgramUniform3ui64vARB(program: int, location: int, count: int, value: UInt64Array) -> None: ...
def glProgramUniform4i64ARB(program: int, location: int, x: int, y: int, z: int, w: int) -> None: ...
def glProgramUniform4i64vARB(program: int, location: int, count: int, value: Int64Array) -> None: ...
def glProgramUniform4ui64ARB(program: int, location: int, x: int, y: int, z: int, w: int) -> None: ...
def glProgramUniform4ui64vARB(program: int, location: int, count: int, value: UInt64Array) -> None: ...
def glUniform1i64ARB(location: int, x: int) -> None: ...
def glUniform1i64vARB(location: int, count: int, value: Int64Array) -> None: ...
def glUniform1ui64ARB(location: int, x: int) -> None: ...
def glUniform1ui64vARB(location: int, count: int, value: UInt64Array) -> None: ...
def glUniform2i64ARB(location: int, x: int, y: int) -> None: ...
def glUniform2i64vARB(location: int, count: int, value: Int64Array) -> None: ...
def glUniform2ui64ARB(location: int, x: int, y: int) -> None: ...
def glUniform2ui64vARB(location: int, count: int, value: UInt64Array) -> None: ...
def glUniform3i64ARB(location: int, x: int, y: int, z: int) -> None: ...
def glUniform3i64vARB(location: int, count: int, value: Int64Array) -> None: ...
def glUniform3ui64ARB(location: int, x: int, y: int, z: int) -> None: ...
def glUniform3ui64vARB(location: int, count: int, value: UInt64Array) -> None: ...
def glUniform4i64ARB(location: int, x: int, y: int, z: int, w: int) -> None: ...
def glUniform4i64vARB(location: int, count: int, value: Int64Array) -> None: ...
def glUniform4ui64ARB(location: int, x: int, y: int, z: int, w: int) -> None: ...
def glUniform4ui64vARB(location: int, count: int, value: UInt64Array) -> None: ...

def glInitGpuShaderInt64ARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
