"""OpenGL.GL.ARB.gpu_shader_fp64 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import DoubleArray

from OpenGL.raw.GL._types import *

GL_DOUBLE: int
GL_DOUBLE_MAT2: int
GL_DOUBLE_MAT2x3: int
GL_DOUBLE_MAT2x4: int
GL_DOUBLE_MAT3: int
GL_DOUBLE_MAT3x2: int
GL_DOUBLE_MAT3x4: int
GL_DOUBLE_MAT4: int
GL_DOUBLE_MAT4x2: int
GL_DOUBLE_MAT4x3: int
GL_DOUBLE_VEC2: int
GL_DOUBLE_VEC3: int
GL_DOUBLE_VEC4: int

def glGetUniformdv(program: int, location: int, params: DoubleArray) -> None: ...
def glUniform1d(location: int, x: float) -> None: ...
def glUniform1dv(location: int, count: int, value: DoubleArray) -> None: ...
def glUniform2d(location: int, x: float, y: float) -> None: ...
def glUniform2dv(location: int, count: int, value: DoubleArray) -> None: ...
def glUniform3d(location: int, x: float, y: float, z: float) -> None: ...
def glUniform3dv(location: int, count: int, value: DoubleArray) -> None: ...
def glUniform4d(location: int, x: float, y: float, z: float, w: float) -> None: ...
def glUniform4dv(location: int, count: int, value: DoubleArray) -> None: ...
def glUniformMatrix2dv(location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glUniformMatrix2x3dv(location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glUniformMatrix2x4dv(location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glUniformMatrix3dv(location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glUniformMatrix3x2dv(location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glUniformMatrix3x4dv(location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glUniformMatrix4dv(location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glUniformMatrix4x2dv(location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glUniformMatrix4x3dv(location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...

def glInitGpuShaderFp64ARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
