# mypy: ignore-errors
# The names in this module arrive from the declaration tables at import
# time, so a checker reading this file sees calls to things it cannot
# find.  The typed surface is the .pyi stub beside the package.
'''OpenGL extension ARB.gpu_shader_int64

This module customises the behaviour of the 
OpenGL.raw.GL.ARB.gpu_shader_int64 to provide a more 
Python-friendly API

Overview (from the spec)
	
	The extension introduces the following features for all shader types:
	
	  * support for 64-bit scalar and vector integer data types, including
	    uniform API, uniform buffer object, transform feedback, and shader
	    input and output support;
	
	  * new built-in functions to pack and unpack 64-bit integer types into a
	    two-component 32-bit integer vector;
	
	  * new built-in functions to convert double-precision floating-point
	    values to or from their 64-bit integer bit encodings;
	
	  * vector relational functions supporting comparisons of vectors of
	    64-bit integer types; and
	
	  * common functions abs, sign, min, max, clamp, and mix supporting
	    arguments of 64-bit integer types.
	

The official definition of this extension is available here:
http://www.opengl.org/registry/specs/ARB/gpu_shader_int64.txt
'''
from OpenGL import platform, constant, arrays
from OpenGL import extensions, wrapper
import ctypes
from OpenGL.raw.GL import _types, _glgets
from OpenGL._declarations import define as _define
_EXTENSION_NAME = _define(globals(), 'OpenGL.raw.GL.ARB.gpu_shader_int64', customise=True)

def glInitGpuShaderInt64ARB():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( _EXTENSION_NAME )

# INPUT glUniform1i64vARB.value size not checked against count
# INPUT glUniform2i64vARB.value size not checked against count*2
# INPUT glUniform3i64vARB.value size not checked against count*3
# INPUT glUniform4i64vARB.value size not checked against count*4
# INPUT glUniform1ui64vARB.value size not checked against count
# INPUT glUniform2ui64vARB.value size not checked against count*2
# INPUT glUniform3ui64vARB.value size not checked against count*3
# INPUT glUniform4ui64vARB.value size not checked against count*4
# INPUT glGetUniformi64vARB.params size not checked against 'program,location'
# INPUT glGetUniformui64vARB.params size not checked against 'program,location'
# INPUT glProgramUniform1i64vARB.value size not checked against count
# INPUT glProgramUniform2i64vARB.value size not checked against count*2
# INPUT glProgramUniform3i64vARB.value size not checked against count*3
# INPUT glProgramUniform4i64vARB.value size not checked against count*4
# INPUT glProgramUniform1ui64vARB.value size not checked against count
# INPUT glProgramUniform2ui64vARB.value size not checked against count*2
# INPUT glProgramUniform3ui64vARB.value size not checked against count*3
# INPUT glProgramUniform4ui64vARB.value size not checked against count*4
### END AUTOGENERATED SECTION