"""OpenGL.GL.ARB.invalidate_subdata -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UIntArray

from OpenGL.raw.GL._types import *

def glInvalidateBufferData(buffer: int) -> None: ...
def glInvalidateBufferSubData(buffer: int, offset: int, length: int) -> None: ...
def glInvalidateFramebuffer(target: int, numAttachments: int, attachments: UIntArray) -> None: ...
def glInvalidateSubFramebuffer(target: int, numAttachments: int, attachments: UIntArray, x: int, y: int, width: int, height: int) -> None: ...
def glInvalidateTexImage(texture: int, level: int) -> None: ...
def glInvalidateTexSubImage(texture: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int) -> None: ...

def glInitInvalidateSubdataARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
