"""OpenGL.GL.ARB.multi_bind -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import Int64Array, IntArray, UInt64Array, UIntArray

from OpenGL.raw.GL._types import *

def glBindBuffersBase(target: int, first: int, count: int, buffers: UIntArray) -> None: ...
def glBindBuffersRange(target: int, first: int, count: int, buffers: UIntArray, offsets: Int64Array, sizes: UInt64Array) -> None: ...
def glBindImageTextures(first: int, count: int, textures: UIntArray) -> None: ...
def glBindSamplers(first: int, count: int, samplers: UIntArray) -> None: ...
def glBindTextures(first: int, count: int, textures: UIntArray) -> None: ...
def glBindVertexBuffers(first: int, count: int, buffers: UIntArray, offsets: Int64Array, strides: IntArray) -> None: ...

def glInitMultiBindARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
