"""OpenGL.GL.ARB.multitexture -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import DoubleArray, FloatArray, IntArray, ShortArray

from OpenGL.raw.GL._types import *

GL_ACTIVE_TEXTURE_ARB: int
GL_CLIENT_ACTIVE_TEXTURE_ARB: int
GL_MAX_TEXTURE_UNITS_ARB: int
GL_TEXTURE0_ARB: int
GL_TEXTURE10_ARB: int
GL_TEXTURE11_ARB: int
GL_TEXTURE12_ARB: int
GL_TEXTURE13_ARB: int
GL_TEXTURE14_ARB: int
GL_TEXTURE15_ARB: int
GL_TEXTURE16_ARB: int
GL_TEXTURE17_ARB: int
GL_TEXTURE18_ARB: int
GL_TEXTURE19_ARB: int
GL_TEXTURE1_ARB: int
GL_TEXTURE20_ARB: int
GL_TEXTURE21_ARB: int
GL_TEXTURE22_ARB: int
GL_TEXTURE23_ARB: int
GL_TEXTURE24_ARB: int
GL_TEXTURE25_ARB: int
GL_TEXTURE26_ARB: int
GL_TEXTURE27_ARB: int
GL_TEXTURE28_ARB: int
GL_TEXTURE29_ARB: int
GL_TEXTURE2_ARB: int
GL_TEXTURE30_ARB: int
GL_TEXTURE31_ARB: int
GL_TEXTURE3_ARB: int
GL_TEXTURE4_ARB: int
GL_TEXTURE5_ARB: int
GL_TEXTURE6_ARB: int
GL_TEXTURE7_ARB: int
GL_TEXTURE8_ARB: int
GL_TEXTURE9_ARB: int

def glActiveTextureARB(texture: int) -> None: ...
def glClientActiveTextureARB(texture: int) -> None: ...
def glMultiTexCoord1dARB(target: int, s: float) -> None: ...
def glMultiTexCoord1dvARB(target: int, v: DoubleArray) -> None: ...
def glMultiTexCoord1fARB(target: int, s: float) -> None: ...
def glMultiTexCoord1fvARB(target: int, v: FloatArray) -> None: ...
def glMultiTexCoord1iARB(target: int, s: int) -> None: ...
def glMultiTexCoord1ivARB(target: int, v: IntArray) -> None: ...
def glMultiTexCoord1sARB(target: int, s: int) -> None: ...
def glMultiTexCoord1svARB(target: int, v: ShortArray) -> None: ...
def glMultiTexCoord2dARB(target: int, s: float, t: float) -> None: ...
def glMultiTexCoord2dvARB(target: int, v: DoubleArray) -> None: ...
def glMultiTexCoord2fARB(target: int, s: float, t: float) -> None: ...
def glMultiTexCoord2fvARB(target: int, v: FloatArray) -> None: ...
def glMultiTexCoord2iARB(target: int, s: int, t: int) -> None: ...
def glMultiTexCoord2ivARB(target: int, v: IntArray) -> None: ...
def glMultiTexCoord2sARB(target: int, s: int, t: int) -> None: ...
def glMultiTexCoord2svARB(target: int, v: ShortArray) -> None: ...
def glMultiTexCoord3dARB(target: int, s: float, t: float, r: float) -> None: ...
def glMultiTexCoord3dvARB(target: int, v: DoubleArray) -> None: ...
def glMultiTexCoord3fARB(target: int, s: float, t: float, r: float) -> None: ...
def glMultiTexCoord3fvARB(target: int, v: FloatArray) -> None: ...
def glMultiTexCoord3iARB(target: int, s: int, t: int, r: int) -> None: ...
def glMultiTexCoord3ivARB(target: int, v: IntArray) -> None: ...
def glMultiTexCoord3sARB(target: int, s: int, t: int, r: int) -> None: ...
def glMultiTexCoord3svARB(target: int, v: ShortArray) -> None: ...
def glMultiTexCoord4dARB(target: int, s: float, t: float, r: float, q: float) -> None: ...
def glMultiTexCoord4dvARB(target: int, v: DoubleArray) -> None: ...
def glMultiTexCoord4fARB(target: int, s: float, t: float, r: float, q: float) -> None: ...
def glMultiTexCoord4fvARB(target: int, v: FloatArray) -> None: ...
def glMultiTexCoord4iARB(target: int, s: int, t: int, r: int, q: int) -> None: ...
def glMultiTexCoord4ivARB(target: int, v: IntArray) -> None: ...
def glMultiTexCoord4sARB(target: int, s: int, t: int, r: int, q: int) -> None: ...
def glMultiTexCoord4svARB(target: int, v: ShortArray) -> None: ...

def glInitMultitextureARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
