"""OpenGL.GL.ARB.multi_draw_indirect -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.GL._types import *

def glMultiDrawArraysIndirect(mode: int, indirect: AnyArray, drawcount: int, stride: int) -> None: ...
def glMultiDrawElementsIndirect(mode: int, type: int, indirect: AnyArray, drawcount: int, stride: int) -> None: ...

def glInitMultiDrawIndirectARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
