"""OpenGL.GL.ARB.occlusion_query -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray, IntArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_CURRENT_QUERY_ARB: int
GL_QUERY_COUNTER_BITS_ARB: int
GL_QUERY_RESULT_ARB: int
GL_QUERY_RESULT_AVAILABLE_ARB: int
GL_SAMPLES_PASSED_ARB: int

def glBeginQueryARB(target: int, id: int) -> None: ...
def glDeleteQueriesARB(n: int, ids: UIntArray) -> None: ...
def glEndQueryARB(target: int) -> None: ...
def glGenQueriesARB(n: int, ids: UIntArray | None = None) -> UIntArrayResult: ...
def glGetQueryObjectivARB(id: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetQueryObjectuivARB(id: int, pname: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glGetQueryivARB(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glIsQueryARB(id: int) -> int: ...

def glInitOcclusionQueryARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
