# mypy: ignore-errors
# The names in this module arrive from the declaration tables at import
# time, so a checker reading this file sees calls to things it cannot
# find.  The typed surface is the .pyi stub beside the package.
'''OpenGL extension ARB.post_depth_coverage

This module customises the behaviour of the 
OpenGL.raw.GL.ARB.post_depth_coverage to provide a more 
Python-friendly API

Overview (from the spec)
	
	This extension allows the fragment shader to control whether values in
	gl_SampleMaskIn[] reflect the coverage after application of the early
	depth and stencil tests.  This feature can be enabled with the following
	layout qualifier in the fragment shader:
	
	    layout(post_depth_coverage) in;
	
	Use of this feature implicitly enables early fragment tests.

The official definition of this extension is available here:
http://www.opengl.org/registry/specs/ARB/post_depth_coverage.txt
'''
from OpenGL import platform, constant, arrays
from OpenGL import extensions, wrapper
import ctypes
from OpenGL.raw.GL import _types, _glgets
from OpenGL._declarations import define as _define
_EXTENSION_NAME = _define(globals(), 'OpenGL.raw.GL.ARB.post_depth_coverage')

def glInitPostDepthCoverageARB():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( _EXTENSION_NAME )


### END AUTOGENERATED SECTION