"""OpenGL.GL.ARB.robustness -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, AnyArrayResult, DoubleArray, DoubleArrayResult, FloatArray, FloatArrayResult, IntArray, IntArrayResult, UByteArray, UByteArrayResult, UIntArray, UIntArrayResult, UShortArray, UShortArrayResult

from OpenGL.raw.GL._types import *

GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT_ARB: int
GL_GUILTY_CONTEXT_RESET_ARB: int
GL_INNOCENT_CONTEXT_RESET_ARB: int
GL_LOSE_CONTEXT_ON_RESET_ARB: int
GL_NO_ERROR: int
GL_NO_RESET_NOTIFICATION_ARB: int
GL_RESET_NOTIFICATION_STRATEGY_ARB: int
GL_UNKNOWN_CONTEXT_RESET_ARB: int

def glGetGraphicsResetStatusARB() -> int: ...
def glGetnColorTableARB(target: int, format: int, type: int, bufSize: int, table: AnyArray | None = None) -> AnyArrayResult: ...
def glGetnCompressedTexImageARB(target: int, lod: int, bufSize: int, img: AnyArray | None = None) -> AnyArrayResult: ...
def glGetnConvolutionFilterARB(target: int, format: int, type: int, bufSize: int, image: AnyArray | None = None) -> AnyArrayResult: ...
def glGetnHistogramARB(target: int, reset: bool, format: int, type: int, bufSize: int, values: AnyArray | None = None) -> AnyArrayResult: ...
def glGetnMapdvARB(target: int, query: int, bufSize: int, v: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetnMapfvARB(target: int, query: int, bufSize: int, v: FloatArray | None = None) -> FloatArrayResult: ...
def glGetnMapivARB(target: int, query: int, bufSize: int, v: IntArray | None = None) -> IntArrayResult: ...
def glGetnMinmaxARB(target: int, reset: bool, format: int, type: int, bufSize: int, values: AnyArray | None = None) -> AnyArrayResult: ...
def glGetnPixelMapfvARB(map: int, bufSize: int, values: FloatArray | None = None) -> FloatArrayResult: ...
def glGetnPixelMapuivARB(map: int, bufSize: int, values: UIntArray | None = None) -> UIntArrayResult: ...
def glGetnPixelMapusvARB(map: int, bufSize: int, values: UShortArray | None = None) -> UShortArrayResult: ...
def glGetnPolygonStippleARB(bufSize: int, pattern: UByteArray | None = None) -> UByteArrayResult: ...
def glGetnSeparableFilterARB(target: int, format: int, type: int, rowBufSize: int, row: AnyArray, columnBufSize: int, column: AnyArray | None = None, span: AnyArray | None = None) -> tuple[AnyArrayResult, AnyArrayResult, AnyArrayResult]: ...
def glGetnTexImageARB(target: int, level: int, format: int, type: int, bufSize: int, img: AnyArray | None = None) -> AnyArrayResult: ...
def glGetnUniformdvARB(program: int, location: int, bufSize: int, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetnUniformfvARB(program: int, location: int, bufSize: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetnUniformivARB(program: int, location: int, bufSize: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetnUniformuivARB(program: int, location: int, bufSize: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glReadnPixelsARB(x: int, y: int, width: int, height: int, format: int, type: int, bufSize: int, data: AnyArray | None = None) -> AnyArrayResult: ...

def glInitRobustnessARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
