"""OpenGL.GL.ARB.separate_shader_objects -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, ByteArray, ByteArrayResult, DoubleArray, FloatArray, IntArray, IntArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_ACTIVE_PROGRAM: int
GL_ALL_SHADER_BITS: int
GL_FRAGMENT_SHADER_BIT: int
GL_GEOMETRY_SHADER_BIT: int
GL_PROGRAM_PIPELINE_BINDING: int
GL_PROGRAM_SEPARABLE: int
GL_TESS_CONTROL_SHADER_BIT: int
GL_TESS_EVALUATION_SHADER_BIT: int
GL_VERTEX_SHADER_BIT: int

def glActiveShaderProgram(pipeline: int, program: int) -> None: ...
def glBindProgramPipeline(pipeline: int) -> None: ...
def glCreateShaderProgramv(type: int, count: int, strings: AnyArray) -> int: ...
def glDeleteProgramPipelines(n: int, pipelines: UIntArray) -> None: ...
def glGenProgramPipelines(n: int, pipelines: UIntArray | None = None) -> UIntArrayResult: ...
def glGetProgramPipelineInfoLog(pipeline: int, bufSize: int, length: IntArray | None = None, infoLog: ByteArray | None = None) -> tuple[ByteArrayResult, IntArrayResult]: ...
def glGetProgramPipelineiv(pipeline: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glIsProgramPipeline(pipeline: int) -> int: ...
def glProgramParameteri(program: int, pname: int, value: int) -> None: ...
def glProgramUniform1d(program: int, location: int, v0: float) -> None: ...
def glProgramUniform1dv(program: int, location: int, count: int, value: DoubleArray) -> None: ...
def glProgramUniform1f(program: int, location: int, v0: float) -> None: ...
def glProgramUniform1fv(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform1i(program: int, location: int, v0: int) -> None: ...
def glProgramUniform1iv(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform1ui(program: int, location: int, v0: int) -> None: ...
def glProgramUniform1uiv(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniform2d(program: int, location: int, v0: float, v1: float) -> None: ...
def glProgramUniform2dv(program: int, location: int, count: int, value: DoubleArray) -> None: ...
def glProgramUniform2f(program: int, location: int, v0: float, v1: float) -> None: ...
def glProgramUniform2fv(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform2i(program: int, location: int, v0: int, v1: int) -> None: ...
def glProgramUniform2iv(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform2ui(program: int, location: int, v0: int, v1: int) -> None: ...
def glProgramUniform2uiv(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniform3d(program: int, location: int, v0: float, v1: float, v2: float) -> None: ...
def glProgramUniform3dv(program: int, location: int, count: int, value: DoubleArray) -> None: ...
def glProgramUniform3f(program: int, location: int, v0: float, v1: float, v2: float) -> None: ...
def glProgramUniform3fv(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform3i(program: int, location: int, v0: int, v1: int, v2: int) -> None: ...
def glProgramUniform3iv(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform3ui(program: int, location: int, v0: int, v1: int, v2: int) -> None: ...
def glProgramUniform3uiv(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniform4d(program: int, location: int, v0: float, v1: float, v2: float, v3: float) -> None: ...
def glProgramUniform4dv(program: int, location: int, count: int, value: DoubleArray) -> None: ...
def glProgramUniform4f(program: int, location: int, v0: float, v1: float, v2: float, v3: float) -> None: ...
def glProgramUniform4fv(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform4i(program: int, location: int, v0: int, v1: int, v2: int, v3: int) -> None: ...
def glProgramUniform4iv(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform4ui(program: int, location: int, v0: int, v1: int, v2: int, v3: int) -> None: ...
def glProgramUniform4uiv(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniformMatrix2dv(program: int, location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glProgramUniformMatrix2fv(program: int, location: int, count: int, transpose: int, value: FloatArray) -> None: ...
def glProgramUniformMatrix2x3dv(program: int, location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glProgramUniformMatrix2x3fv(program: int, location: int, count: int, transpose: int, value: FloatArray) -> None: ...
def glProgramUniformMatrix2x4dv(program: int, location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glProgramUniformMatrix2x4fv(program: int, location: int, count: int, transpose: int, value: FloatArray) -> None: ...
def glProgramUniformMatrix3dv(program: int, location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glProgramUniformMatrix3fv(program: int, location: int, count: int, transpose: int, value: FloatArray) -> None: ...
def glProgramUniformMatrix3x2dv(program: int, location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glProgramUniformMatrix3x2fv(program: int, location: int, count: int, transpose: int, value: FloatArray) -> None: ...
def glProgramUniformMatrix3x4dv(program: int, location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glProgramUniformMatrix3x4fv(program: int, location: int, count: int, transpose: int, value: FloatArray) -> None: ...
def glProgramUniformMatrix4dv(program: int, location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glProgramUniformMatrix4fv(program: int, location: int, count: int, transpose: int, value: FloatArray) -> None: ...
def glProgramUniformMatrix4x2dv(program: int, location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glProgramUniformMatrix4x2fv(program: int, location: int, count: int, transpose: int, value: FloatArray) -> None: ...
def glProgramUniformMatrix4x3dv(program: int, location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glProgramUniformMatrix4x3fv(program: int, location: int, count: int, transpose: int, value: FloatArray) -> None: ...
def glUseProgramStages(pipeline: int, stages: int, program: int) -> None: ...
def glValidateProgramPipeline(pipeline: int) -> None: ...

def glInitSeparateShaderObjectsARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
