"""OpenGL.GL.ARB.shader_atomic_counters -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray, IntArrayResult

from OpenGL.raw.GL._types import *

GL_ACTIVE_ATOMIC_COUNTER_BUFFERS: int
GL_ATOMIC_COUNTER_BUFFER: int
GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS: int
GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTER_INDICES: int
GL_ATOMIC_COUNTER_BUFFER_BINDING: int
GL_ATOMIC_COUNTER_BUFFER_DATA_SIZE: int
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_FRAGMENT_SHADER: int
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_GEOMETRY_SHADER: int
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_CONTROL_SHADER: int
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_EVALUATION_SHADER: int
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_VERTEX_SHADER: int
GL_ATOMIC_COUNTER_BUFFER_SIZE: int
GL_ATOMIC_COUNTER_BUFFER_START: int
GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS: int
GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE: int
GL_MAX_COMBINED_ATOMIC_COUNTERS: int
GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS: int
GL_MAX_FRAGMENT_ATOMIC_COUNTERS: int
GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS: int
GL_MAX_GEOMETRY_ATOMIC_COUNTERS: int
GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS: int
GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS: int
GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS: int
GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS: int
GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS: int
GL_MAX_VERTEX_ATOMIC_COUNTERS: int
GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS: int
GL_UNIFORM_ATOMIC_COUNTER_BUFFER_INDEX: int
GL_UNSIGNED_INT_ATOMIC_COUNTER: int

def glGetActiveAtomicCounterBufferiv(program: int, bufferIndex: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...

def glInitShaderAtomicCountersARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
