"""OpenGL.GL.ARB.shader_image_load_store -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

GL_ALL_BARRIER_BITS: int
GL_ATOMIC_COUNTER_BARRIER_BIT: int
GL_BUFFER_UPDATE_BARRIER_BIT: int
GL_COMMAND_BARRIER_BIT: int
GL_ELEMENT_ARRAY_BARRIER_BIT: int
GL_FRAMEBUFFER_BARRIER_BIT: int
GL_IMAGE_1D: int
GL_IMAGE_1D_ARRAY: int
GL_IMAGE_2D: int
GL_IMAGE_2D_ARRAY: int
GL_IMAGE_2D_MULTISAMPLE: int
GL_IMAGE_2D_MULTISAMPLE_ARRAY: int
GL_IMAGE_2D_RECT: int
GL_IMAGE_3D: int
GL_IMAGE_BINDING_ACCESS: int
GL_IMAGE_BINDING_FORMAT: int
GL_IMAGE_BINDING_LAYER: int
GL_IMAGE_BINDING_LAYERED: int
GL_IMAGE_BINDING_LEVEL: int
GL_IMAGE_BINDING_NAME: int
GL_IMAGE_BUFFER: int
GL_IMAGE_CUBE: int
GL_IMAGE_CUBE_MAP_ARRAY: int
GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS: int
GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE: int
GL_IMAGE_FORMAT_COMPATIBILITY_TYPE: int
GL_INT_IMAGE_1D: int
GL_INT_IMAGE_1D_ARRAY: int
GL_INT_IMAGE_2D: int
GL_INT_IMAGE_2D_ARRAY: int
GL_INT_IMAGE_2D_MULTISAMPLE: int
GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY: int
GL_INT_IMAGE_2D_RECT: int
GL_INT_IMAGE_3D: int
GL_INT_IMAGE_BUFFER: int
GL_INT_IMAGE_CUBE: int
GL_INT_IMAGE_CUBE_MAP_ARRAY: int
GL_MAX_COMBINED_IMAGE_UNIFORMS: int
GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS: int
GL_MAX_FRAGMENT_IMAGE_UNIFORMS: int
GL_MAX_GEOMETRY_IMAGE_UNIFORMS: int
GL_MAX_IMAGE_SAMPLES: int
GL_MAX_IMAGE_UNITS: int
GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS: int
GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS: int
GL_MAX_VERTEX_IMAGE_UNIFORMS: int
GL_PIXEL_BUFFER_BARRIER_BIT: int
GL_SHADER_IMAGE_ACCESS_BARRIER_BIT: int
GL_TEXTURE_FETCH_BARRIER_BIT: int
GL_TEXTURE_UPDATE_BARRIER_BIT: int
GL_TRANSFORM_FEEDBACK_BARRIER_BIT: int
GL_UNIFORM_BARRIER_BIT: int
GL_UNSIGNED_INT_IMAGE_1D: int
GL_UNSIGNED_INT_IMAGE_1D_ARRAY: int
GL_UNSIGNED_INT_IMAGE_2D: int
GL_UNSIGNED_INT_IMAGE_2D_ARRAY: int
GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE: int
GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY: int
GL_UNSIGNED_INT_IMAGE_2D_RECT: int
GL_UNSIGNED_INT_IMAGE_3D: int
GL_UNSIGNED_INT_IMAGE_BUFFER: int
GL_UNSIGNED_INT_IMAGE_CUBE: int
GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY: int
GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT: int

def glBindImageTexture(unit: int, texture: int, level: int, layered: bool, layer: int, access: int, format: int) -> None: ...
def glMemoryBarrier(barriers: int) -> None: ...

def glInitShaderImageLoadStoreARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
