"""OpenGL.GL.ARB.shading_language_include -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, ByteArray, ByteArrayResult, IntArray, IntArrayResult

from OpenGL.raw.GL._types import *

GL_NAMED_STRING_LENGTH_ARB: int
GL_NAMED_STRING_TYPE_ARB: int
GL_SHADER_INCLUDE_ARB: int

def glCompileShaderIncludeARB(shader: int, count: int, path: AnyArray, length: IntArray) -> None: ...
def glDeleteNamedStringARB(namelen: int, name: ByteArray) -> None: ...
def glGetNamedStringARB(namelen: int, name: ByteArray, bufSize: int, stringlen: IntArray | None = None, string: ByteArray | None = None) -> tuple[ByteArrayResult, IntArrayResult]: ...
def glGetNamedStringivARB(namelen: int, name: ByteArray, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glIsNamedStringARB(namelen: int, name: ByteArray) -> int: ...
def glNamedStringARB(type: int, namelen: int, name: ByteArray, stringlen: int, string: ByteArray) -> None: ...

def glInitShadingLanguageIncludeARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
