'''OpenGL extension ARB.shader_texture_lod

This module customises the behaviour of the 
OpenGL.raw.GL.ARB.shader_texture_lod to provide a more 
Python-friendly API
'''
from OpenGL import platform, constants, constant, arrays
from OpenGL import extensions, wrapper
from OpenGL.GL import glget
import ctypes
from OpenGL.raw.GL.ARB.shader_texture_lod import *
### END AUTOGENERATED SECTION