"""OpenGL.GL.ARB.shader_subroutine -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import ByteArray, ByteArrayResult, IntArray, IntArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_ACTIVE_SUBROUTINES: int
GL_ACTIVE_SUBROUTINE_MAX_LENGTH: int
GL_ACTIVE_SUBROUTINE_UNIFORMS: int
GL_ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS: int
GL_ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH: int
GL_COMPATIBLE_SUBROUTINES: int
GL_MAX_SUBROUTINES: int
GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS: int
GL_NUM_COMPATIBLE_SUBROUTINES: int
GL_UNIFORM_NAME_LENGTH: int
GL_UNIFORM_SIZE: int

def glGetActiveSubroutineName(program: int, shadertype: int, index: int, bufSize: int, length: IntArray | None = None, name: ByteArray | None = None) -> tuple[IntArrayResult, ByteArrayResult]: ...
def glGetActiveSubroutineUniformName(program: int, shadertype: int, index: int, bufSize: int, length: IntArray | None = None, name: ByteArray | None = None) -> tuple[IntArrayResult, ByteArrayResult]: ...
def glGetActiveSubroutineUniformiv(program: int, shadertype: int, index: int, pname: int, values: IntArray | None = None) -> IntArrayResult: ...
def glGetProgramStageiv(program: int, shadertype: int, pname: int, values: IntArray | None = None) -> IntArrayResult: ...
def glGetSubroutineIndex(program: int, shadertype: int, name: ByteArray) -> int: ...
def glGetSubroutineUniformLocation(program: int, shadertype: int, name: ByteArray) -> int: ...
def glGetUniformSubroutineuiv(shadertype: int, location: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glUniformSubroutinesuiv(shadertype: int, count: int, indices: UIntArray) -> None: ...

def glInitShaderSubroutineARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
