"""OpenGL.GL.ARB.shader_storage_buffer_object -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS: int
GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES: int
GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS: int
GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS: int
GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS: int
GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS: int
GL_MAX_SHADER_STORAGE_BLOCK_SIZE: int
GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS: int
GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS: int
GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS: int
GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS: int
GL_SHADER_STORAGE_BARRIER_BIT: int
GL_SHADER_STORAGE_BUFFER: int
GL_SHADER_STORAGE_BUFFER_BINDING: int
GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT: int
GL_SHADER_STORAGE_BUFFER_SIZE: int
GL_SHADER_STORAGE_BUFFER_START: int

def glShaderStorageBlockBinding(program: int, storageBlockIndex: int, storageBlockBinding: int) -> None: ...

def glInitShaderStorageBufferObjectARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
