"""OpenGL.GL.ARB.shader_objects -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, ByteArray, ByteArrayResult, FloatArray, FloatArrayResult, IntArray, IntArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_BOOL_ARB: int
GL_BOOL_VEC2_ARB: int
GL_BOOL_VEC3_ARB: int
GL_BOOL_VEC4_ARB: int
GL_FLOAT_MAT2_ARB: int
GL_FLOAT_MAT3_ARB: int
GL_FLOAT_MAT4_ARB: int
GL_FLOAT_VEC2_ARB: int
GL_FLOAT_VEC3_ARB: int
GL_FLOAT_VEC4_ARB: int
GL_INT_VEC2_ARB: int
GL_INT_VEC3_ARB: int
GL_INT_VEC4_ARB: int
GL_OBJECT_ACTIVE_UNIFORMS_ARB: int
GL_OBJECT_ACTIVE_UNIFORM_MAX_LENGTH_ARB: int
GL_OBJECT_ATTACHED_OBJECTS_ARB: int
GL_OBJECT_COMPILE_STATUS_ARB: int
GL_OBJECT_DELETE_STATUS_ARB: int
GL_OBJECT_INFO_LOG_LENGTH_ARB: int
GL_OBJECT_LINK_STATUS_ARB: int
GL_OBJECT_SHADER_SOURCE_LENGTH_ARB: int
GL_OBJECT_SUBTYPE_ARB: int
GL_OBJECT_TYPE_ARB: int
GL_OBJECT_VALIDATE_STATUS_ARB: int
GL_PROGRAM_OBJECT_ARB: int
GL_SAMPLER_1D_ARB: int
GL_SAMPLER_1D_SHADOW_ARB: int
GL_SAMPLER_2D_ARB: int
GL_SAMPLER_2D_RECT_ARB: int
GL_SAMPLER_2D_RECT_SHADOW_ARB: int
GL_SAMPLER_2D_SHADOW_ARB: int
GL_SAMPLER_3D_ARB: int
GL_SAMPLER_CUBE_ARB: int
GL_SHADER_OBJECT_ARB: int

def glAttachObjectARB(containerObj: int, obj: int) -> None: ...
def glCompileShaderARB(shaderObj: int) -> None: ...
def glCreateProgramObjectARB() -> int: ...
def glCreateShaderObjectARB(shaderType: int) -> int: ...
def glDeleteObjectARB(obj: int) -> None: ...
def glDetachObjectARB(containerObj: int, attachedObj: int) -> None: ...
def glGetActiveUniformARB(programObj: int, index: int, maxLength: int, length: IntArray | None = None, size: IntArray | None = None, type: UIntArray | None = None, name: ByteArray | None = None) -> tuple[IntArrayResult, ByteArrayResult, IntArrayResult, UIntArrayResult]: ...
def glGetAttachedObjectsARB(containerObj: int, maxCount: int, count: IntArray | None = None, obj: UIntArray | None = None) -> tuple[IntArrayResult, UIntArrayResult]: ...
def glGetHandleARB(pname: int) -> int: ...
def glGetInfoLogARB(obj: int, maxLength: int, length: IntArray | None = None, infoLog: ByteArray | None = None) -> tuple[ByteArrayResult, IntArrayResult]: ...
def glGetObjectParameterfvARB(obj: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetObjectParameterivARB(obj: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetShaderSourceARB(obj: int, maxLength: int, length: IntArray | None = None, source: ByteArray | None = None) -> tuple[IntArrayResult, ByteArrayResult]: ...
def glGetUniformLocationARB(programObj: int, name: ByteArray) -> int: ...
def glGetUniformfvARB(programObj: int, location: int, params: FloatArray) -> None: ...
def glGetUniformivARB(programObj: int, location: int, params: IntArray) -> None: ...
def glLinkProgramARB(programObj: int) -> None: ...
def glShaderSourceARB(shaderObj: Any, string: Any) -> None: ...
def glUniform1fARB(location: int, v0: float) -> None: ...
def glUniform1fvARB(location: int, count: int, value: FloatArray) -> None: ...
def glUniform1iARB(location: int, v0: int) -> None: ...
def glUniform1ivARB(location: int, count: int, value: IntArray) -> None: ...
def glUniform2fARB(location: int, v0: float, v1: float) -> None: ...
def glUniform2fvARB(location: int, count: int, value: FloatArray) -> None: ...
def glUniform2iARB(location: int, v0: int, v1: int) -> None: ...
def glUniform2ivARB(location: int, count: int, value: IntArray) -> None: ...
def glUniform3fARB(location: int, v0: float, v1: float, v2: float) -> None: ...
def glUniform3fvARB(location: int, count: int, value: FloatArray) -> None: ...
def glUniform3iARB(location: int, v0: int, v1: int, v2: int) -> None: ...
def glUniform3ivARB(location: int, count: int, value: IntArray) -> None: ...
def glUniform4fARB(location: int, v0: float, v1: float, v2: float, v3: float) -> None: ...
def glUniform4fvARB(location: int, count: int, value: FloatArray) -> None: ...
def glUniform4iARB(location: int, v0: int, v1: int, v2: int, v3: int) -> None: ...
def glUniform4ivARB(location: int, count: int, value: IntArray) -> None: ...
def glUniformMatrix2fvARB(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUniformMatrix3fvARB(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUniformMatrix4fvARB(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUseProgramObjectARB(programObj: int) -> None: ...
def glValidateProgramARB(programObj: int) -> None: ...

def glInitShaderObjectsARB() -> bool: ...
GL_INFO_LOG_LENGTH_ARB: int
conv: Any

def __getattr__(name: str) -> Any: ...
