"""OpenGL.GL.ARB.tessellation_shader -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray

from OpenGL.raw.GL._types import *

GL_CCW: int
GL_CW: int
GL_EQUAL: int
GL_FRACTIONAL_EVEN: int
GL_FRACTIONAL_ODD: int
GL_ISOLINES: int
GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS: int
GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS: int
GL_MAX_PATCH_VERTICES: int
GL_MAX_TESS_CONTROL_INPUT_COMPONENTS: int
GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS: int
GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS: int
GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS: int
GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS: int
GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS: int
GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS: int
GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS: int
GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS: int
GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS: int
GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS: int
GL_MAX_TESS_GEN_LEVEL: int
GL_MAX_TESS_PATCH_COMPONENTS: int
GL_PATCHES: int
GL_PATCH_DEFAULT_INNER_LEVEL: int
GL_PATCH_DEFAULT_OUTER_LEVEL: int
GL_PATCH_VERTICES: int
GL_QUADS: int
GL_TESS_CONTROL_OUTPUT_VERTICES: int
GL_TESS_CONTROL_SHADER: int
GL_TESS_EVALUATION_SHADER: int
GL_TESS_GEN_MODE: int
GL_TESS_GEN_POINT_MODE: int
GL_TESS_GEN_SPACING: int
GL_TESS_GEN_VERTEX_ORDER: int
GL_TRIANGLES: int
GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER: int
GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER: int

def glPatchParameterfv(pname: int, values: FloatArray) -> None: ...
def glPatchParameteri(pname: int, value: int) -> None: ...

def glInitTessellationShaderARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
