"""OpenGL.GL.ARB.texture_storage_multisample -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

def glTexStorage2DMultisample(target: int, samples: int, internalformat: int, width: int, height: int, fixedsamplelocations: bool) -> None: ...
def glTexStorage3DMultisample(target: int, samples: int, internalformat: int, width: int, height: int, depth: int, fixedsamplelocations: bool) -> None: ...

def glInitTextureStorageMultisampleARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
