"""OpenGL.GL.ARB.texture_storage -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

GL_TEXTURE_IMMUTABLE_FORMAT: int

def glTexStorage1D(target: int, levels: int, internalformat: int, width: int) -> None: ...
def glTexStorage2D(target: int, levels: int, internalformat: int, width: int, height: int) -> None: ...
def glTexStorage3D(target: int, levels: int, internalformat: int, width: int, height: int, depth: int) -> None: ...

def glInitTextureStorageARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
