"""OpenGL.GL.ARB.transform_feedback_instanced -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

def glDrawTransformFeedbackInstanced(mode: int, id: int, instancecount: int) -> None: ...
def glDrawTransformFeedbackStreamInstanced(mode: int, id: int, stream: int, instancecount: int) -> None: ...

def glInitTransformFeedbackInstancedARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
