"""OpenGL.GL.ARB.transform_feedback3 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray, IntArrayResult

from OpenGL.raw.GL._types import *

GL_MAX_TRANSFORM_FEEDBACK_BUFFERS: int
GL_MAX_VERTEX_STREAMS: int

def glBeginQueryIndexed(target: int, index: int, id: int) -> None: ...
def glDrawTransformFeedbackStream(mode: int, id: int, stream: int) -> None: ...
def glEndQueryIndexed(target: int, index: int) -> None: ...
def glGetQueryIndexediv(target: int, index: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...

def glInitTransformFeedback3ARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
