"""OpenGL.GL.ARB.transform_feedback2 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_TRANSFORM_FEEDBACK: int
GL_TRANSFORM_FEEDBACK_BINDING: int
GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE: int
GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED: int

def glBindTransformFeedback(target: int, id: int) -> None: ...
def glDeleteTransformFeedbacks(n: int, ids: UIntArray) -> None: ...
def glDrawTransformFeedback(mode: int, id: int) -> None: ...
def glGenTransformFeedbacks(n: int, ids: UIntArray | None = None) -> UIntArrayResult: ...
def glIsTransformFeedback(id: int) -> int: ...
def glPauseTransformFeedback() -> None: ...
def glResumeTransformFeedback() -> None: ...

def glInitTransformFeedback2ARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
