"""OpenGL.GL.ARB.vertex_array_object -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_VERTEX_ARRAY_BINDING: int

def glBindVertexArray(array: int) -> None: ...
def glDeleteVertexArrays(n: int, arrays: UIntArray) -> None: ...
def glGenVertexArrays(n: int, arrays: UIntArray | None = None) -> UIntArrayResult: ...
def glIsVertexArray(array: int) -> int: ...

def glInitVertexArrayObjectARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
