"""OpenGL.GL.ARB.vertex_program -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, AnyArrayResult, ByteArray, DoubleArray, DoubleArrayResult, FloatArray, FloatArrayResult, IntArray, IntArrayResult, ShortArray, UByteArray, UIntArray, UIntArrayResult, UShortArray

from OpenGL.raw.GL._types import *

GL_COLOR_SUM_ARB: int
GL_CURRENT_MATRIX_ARB: int
GL_CURRENT_MATRIX_STACK_DEPTH_ARB: int
GL_CURRENT_VERTEX_ATTRIB_ARB: int
GL_MATRIX0_ARB: int
GL_MATRIX10_ARB: int
GL_MATRIX11_ARB: int
GL_MATRIX12_ARB: int
GL_MATRIX13_ARB: int
GL_MATRIX14_ARB: int
GL_MATRIX15_ARB: int
GL_MATRIX16_ARB: int
GL_MATRIX17_ARB: int
GL_MATRIX18_ARB: int
GL_MATRIX19_ARB: int
GL_MATRIX1_ARB: int
GL_MATRIX20_ARB: int
GL_MATRIX21_ARB: int
GL_MATRIX22_ARB: int
GL_MATRIX23_ARB: int
GL_MATRIX24_ARB: int
GL_MATRIX25_ARB: int
GL_MATRIX26_ARB: int
GL_MATRIX27_ARB: int
GL_MATRIX28_ARB: int
GL_MATRIX29_ARB: int
GL_MATRIX2_ARB: int
GL_MATRIX30_ARB: int
GL_MATRIX31_ARB: int
GL_MATRIX3_ARB: int
GL_MATRIX4_ARB: int
GL_MATRIX5_ARB: int
GL_MATRIX6_ARB: int
GL_MATRIX7_ARB: int
GL_MATRIX8_ARB: int
GL_MATRIX9_ARB: int
GL_MAX_PROGRAM_ADDRESS_REGISTERS_ARB: int
GL_MAX_PROGRAM_ATTRIBS_ARB: int
GL_MAX_PROGRAM_ENV_PARAMETERS_ARB: int
GL_MAX_PROGRAM_INSTRUCTIONS_ARB: int
GL_MAX_PROGRAM_LOCAL_PARAMETERS_ARB: int
GL_MAX_PROGRAM_MATRICES_ARB: int
GL_MAX_PROGRAM_MATRIX_STACK_DEPTH_ARB: int
GL_MAX_PROGRAM_NATIVE_ADDRESS_REGISTERS_ARB: int
GL_MAX_PROGRAM_NATIVE_ATTRIBS_ARB: int
GL_MAX_PROGRAM_NATIVE_INSTRUCTIONS_ARB: int
GL_MAX_PROGRAM_NATIVE_PARAMETERS_ARB: int
GL_MAX_PROGRAM_NATIVE_TEMPORARIES_ARB: int
GL_MAX_PROGRAM_PARAMETERS_ARB: int
GL_MAX_PROGRAM_TEMPORARIES_ARB: int
GL_MAX_VERTEX_ATTRIBS_ARB: int
GL_PROGRAM_ADDRESS_REGISTERS_ARB: int
GL_PROGRAM_ATTRIBS_ARB: int
GL_PROGRAM_BINDING_ARB: int
GL_PROGRAM_ERROR_POSITION_ARB: int
GL_PROGRAM_ERROR_STRING_ARB: int
GL_PROGRAM_FORMAT_ARB: int
GL_PROGRAM_FORMAT_ASCII_ARB: int
GL_PROGRAM_INSTRUCTIONS_ARB: int
GL_PROGRAM_LENGTH_ARB: int
GL_PROGRAM_NATIVE_ADDRESS_REGISTERS_ARB: int
GL_PROGRAM_NATIVE_ATTRIBS_ARB: int
GL_PROGRAM_NATIVE_INSTRUCTIONS_ARB: int
GL_PROGRAM_NATIVE_PARAMETERS_ARB: int
GL_PROGRAM_NATIVE_TEMPORARIES_ARB: int
GL_PROGRAM_PARAMETERS_ARB: int
GL_PROGRAM_STRING_ARB: int
GL_PROGRAM_TEMPORARIES_ARB: int
GL_PROGRAM_UNDER_NATIVE_LIMITS_ARB: int
GL_TRANSPOSE_CURRENT_MATRIX_ARB: int
GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB: int
GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB: int
GL_VERTEX_ATTRIB_ARRAY_POINTER_ARB: int
GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB: int
GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB: int
GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB: int
GL_VERTEX_PROGRAM_ARB: int
GL_VERTEX_PROGRAM_POINT_SIZE_ARB: int
GL_VERTEX_PROGRAM_TWO_SIDE_ARB: int

def glBindProgramARB(target: int, program: int) -> None: ...
def glDeleteProgramsARB(n: int, programs: UIntArray) -> None: ...
def glDisableVertexAttribArrayARB(index: int) -> None: ...
def glEnableVertexAttribArrayARB(index: int) -> None: ...
def glGenProgramsARB(n: int, programs: UIntArray | None = None) -> UIntArrayResult: ...
def glGetProgramEnvParameterdvARB(target: int, index: int, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetProgramEnvParameterfvARB(target: int, index: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetProgramLocalParameterdvARB(target: int, index: int, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetProgramLocalParameterfvARB(target: int, index: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetProgramStringARB(target: int, pname: int, string: AnyArray) -> None: ...
def glGetProgramivARB(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetVertexAttribPointervARB(index: int, pname: int, pointer: AnyArray | None = None) -> AnyArrayResult: ...
def glGetVertexAttribdvARB(index: int, pname: int, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetVertexAttribfvARB(index: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetVertexAttribivARB(index: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glIsProgramARB(program: int) -> int: ...
def glProgramEnvParameter4dARB(target: int, index: int, x: float, y: float, z: float, w: float) -> None: ...
def glProgramEnvParameter4dvARB(target: int, index: int, params: DoubleArray) -> None: ...
def glProgramEnvParameter4fARB(target: int, index: int, x: float, y: float, z: float, w: float) -> None: ...
def glProgramEnvParameter4fvARB(target: int, index: int, params: FloatArray) -> None: ...
def glProgramLocalParameter4dARB(target: int, index: int, x: float, y: float, z: float, w: float) -> None: ...
def glProgramLocalParameter4dvARB(target: int, index: int, params: DoubleArray) -> None: ...
def glProgramLocalParameter4fARB(target: int, index: int, x: float, y: float, z: float, w: float) -> None: ...
def glProgramLocalParameter4fvARB(target: int, index: int, params: FloatArray) -> None: ...
def glProgramStringARB(target: int, format: int, len: int, string: AnyArray) -> None: ...
def glVertexAttrib1dARB(index: int, x: float) -> None: ...
def glVertexAttrib1dvARB(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib1fARB(index: int, x: float) -> None: ...
def glVertexAttrib1fvARB(index: int, v: FloatArray) -> None: ...
def glVertexAttrib1sARB(index: int, x: int) -> None: ...
def glVertexAttrib1svARB(index: int, v: ShortArray) -> None: ...
def glVertexAttrib2dARB(index: int, x: float, y: float) -> None: ...
def glVertexAttrib2dvARB(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib2fARB(index: int, x: float, y: float) -> None: ...
def glVertexAttrib2fvARB(index: int, v: FloatArray) -> None: ...
def glVertexAttrib2sARB(index: int, x: int, y: int) -> None: ...
def glVertexAttrib2svARB(index: int, v: ShortArray) -> None: ...
def glVertexAttrib3dARB(index: int, x: float, y: float, z: float) -> None: ...
def glVertexAttrib3dvARB(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib3fARB(index: int, x: float, y: float, z: float) -> None: ...
def glVertexAttrib3fvARB(index: int, v: FloatArray) -> None: ...
def glVertexAttrib3sARB(index: int, x: int, y: int, z: int) -> None: ...
def glVertexAttrib3svARB(index: int, v: ShortArray) -> None: ...
def glVertexAttrib4NbvARB(index: int, v: ByteArray) -> None: ...
def glVertexAttrib4NivARB(index: int, v: IntArray) -> None: ...
def glVertexAttrib4NsvARB(index: int, v: ShortArray) -> None: ...
def glVertexAttrib4NubARB(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttrib4NubvARB(index: int, v: UByteArray) -> None: ...
def glVertexAttrib4NuivARB(index: int, v: UIntArray) -> None: ...
def glVertexAttrib4NusvARB(index: int, v: UShortArray) -> None: ...
def glVertexAttrib4bvARB(index: int, v: ByteArray) -> None: ...
def glVertexAttrib4dARB(index: int, x: float, y: float, z: float, w: float) -> None: ...
def glVertexAttrib4dvARB(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib4fARB(index: int, x: float, y: float, z: float, w: float) -> None: ...
def glVertexAttrib4fvARB(index: int, v: FloatArray) -> None: ...
def glVertexAttrib4ivARB(index: int, v: IntArray) -> None: ...
def glVertexAttrib4sARB(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttrib4svARB(index: int, v: ShortArray) -> None: ...
def glVertexAttrib4ubvARB(index: int, v: UByteArray) -> None: ...
def glVertexAttrib4uivARB(index: int, v: UIntArray) -> None: ...
def glVertexAttrib4usvARB(index: int, v: UShortArray) -> None: ...
def glVertexAttribPointerARB(index: int, size: int, type: int, normalized: int, stride: int, pointer: AnyArray) -> None: ...

def glInitVertexProgramARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
