"""OpenGL.GL.ARB.vertex_type_2_10_10_10_rev -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UIntArray

from OpenGL.raw.GL._types import *

GL_INT_2_10_10_10_REV: int
GL_UNSIGNED_INT_2_10_10_10_REV: int

def glColorP3ui(type: int, color: int) -> None: ...
def glColorP3uiv(type: int, color: UIntArray) -> None: ...
def glColorP4ui(type: int, color: int) -> None: ...
def glColorP4uiv(type: int, color: UIntArray) -> None: ...
def glMultiTexCoordP1ui(texture: int, type: int, coords: int) -> None: ...
def glMultiTexCoordP1uiv(texture: int, type: int, coords: UIntArray) -> None: ...
def glMultiTexCoordP2ui(texture: int, type: int, coords: int) -> None: ...
def glMultiTexCoordP2uiv(texture: int, type: int, coords: UIntArray) -> None: ...
def glMultiTexCoordP3ui(texture: int, type: int, coords: int) -> None: ...
def glMultiTexCoordP3uiv(texture: int, type: int, coords: UIntArray) -> None: ...
def glMultiTexCoordP4ui(texture: int, type: int, coords: int) -> None: ...
def glMultiTexCoordP4uiv(texture: int, type: int, coords: UIntArray) -> None: ...
def glNormalP3ui(type: int, coords: int) -> None: ...
def glNormalP3uiv(type: int, coords: UIntArray) -> None: ...
def glSecondaryColorP3ui(type: int, color: int) -> None: ...
def glSecondaryColorP3uiv(type: int, color: UIntArray) -> None: ...
def glTexCoordP1ui(type: int, coords: int) -> None: ...
def glTexCoordP1uiv(type: int, coords: UIntArray) -> None: ...
def glTexCoordP2ui(type: int, coords: int) -> None: ...
def glTexCoordP2uiv(type: int, coords: UIntArray) -> None: ...
def glTexCoordP3ui(type: int, coords: int) -> None: ...
def glTexCoordP3uiv(type: int, coords: UIntArray) -> None: ...
def glTexCoordP4ui(type: int, coords: int) -> None: ...
def glTexCoordP4uiv(type: int, coords: UIntArray) -> None: ...
def glVertexAttribP1ui(index: int, type: int, normalized: int, value: int) -> None: ...
def glVertexAttribP1uiv(index: int, type: int, normalized: int, value: UIntArray) -> None: ...
def glVertexAttribP2ui(index: int, type: int, normalized: int, value: int) -> None: ...
def glVertexAttribP2uiv(index: int, type: int, normalized: int, value: UIntArray) -> None: ...
def glVertexAttribP3ui(index: int, type: int, normalized: int, value: int) -> None: ...
def glVertexAttribP3uiv(index: int, type: int, normalized: int, value: UIntArray) -> None: ...
def glVertexAttribP4ui(index: int, type: int, normalized: int, value: int) -> None: ...
def glVertexAttribP4uiv(index: int, type: int, normalized: int, value: UIntArray) -> None: ...
def glVertexP2ui(type: int, value: int) -> None: ...
def glVertexP2uiv(type: int, value: UIntArray) -> None: ...
def glVertexP3ui(type: int, value: int) -> None: ...
def glVertexP3uiv(type: int, value: UIntArray) -> None: ...
def glVertexP4ui(type: int, value: int) -> None: ...
def glVertexP4uiv(type: int, value: UIntArray) -> None: ...

def glInitVertexType2101010RevARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
