"""OpenGL.GL.ARB.vertex_attrib_binding -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

GL_MAX_VERTEX_ATTRIB_BINDINGS: int
GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET: int
GL_VERTEX_ATTRIB_BINDING: int
GL_VERTEX_ATTRIB_RELATIVE_OFFSET: int
GL_VERTEX_BINDING_DIVISOR: int
GL_VERTEX_BINDING_OFFSET: int
GL_VERTEX_BINDING_STRIDE: int

def glBindVertexBuffer(bindingindex: int, buffer: int, offset: int, stride: int) -> None: ...
def glVertexAttribBinding(attribindex: int, bindingindex: int) -> None: ...
def glVertexAttribFormat(attribindex: int, size: int, type: int, normalized: int, relativeoffset: int) -> None: ...
def glVertexAttribIFormat(attribindex: int, size: int, type: int, relativeoffset: int) -> None: ...
def glVertexAttribLFormat(attribindex: int, size: int, type: int, relativeoffset: int) -> None: ...
def glVertexBindingDivisor(bindingindex: int, divisor: int) -> None: ...

def glInitVertexAttribBindingARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
