"""OpenGL.GL.ARB.vertex_shader -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, AnyArrayResult, ByteArray, ByteArrayResult, DoubleArray, DoubleArrayResult, FloatArray, FloatArrayResult, IntArray, IntArrayResult, ShortArray, UByteArray, UIntArray, UIntArrayResult, UShortArray

from OpenGL.raw.GL._types import *

GL_CURRENT_VERTEX_ATTRIB_ARB: int
GL_FLOAT: int
GL_FLOAT_MAT2_ARB: int
GL_FLOAT_MAT3_ARB: int
GL_FLOAT_MAT4_ARB: int
GL_FLOAT_VEC2_ARB: int
GL_FLOAT_VEC3_ARB: int
GL_FLOAT_VEC4_ARB: int
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS_ARB: int
GL_MAX_TEXTURE_COORDS_ARB: int
GL_MAX_TEXTURE_IMAGE_UNITS_ARB: int
GL_MAX_VARYING_FLOATS_ARB: int
GL_MAX_VERTEX_ATTRIBS_ARB: int
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS_ARB: int
GL_MAX_VERTEX_UNIFORM_COMPONENTS_ARB: int
GL_OBJECT_ACTIVE_ATTRIBUTES_ARB: int
GL_OBJECT_ACTIVE_ATTRIBUTE_MAX_LENGTH_ARB: int
GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB: int
GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB: int
GL_VERTEX_ATTRIB_ARRAY_POINTER_ARB: int
GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB: int
GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB: int
GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB: int
GL_VERTEX_PROGRAM_POINT_SIZE_ARB: int
GL_VERTEX_PROGRAM_TWO_SIDE_ARB: int
GL_VERTEX_SHADER_ARB: int

def glBindAttribLocationARB(programObj: int, index: int, name: ByteArray) -> None: ...
def glDisableVertexAttribArrayARB(index: int) -> None: ...
def glEnableVertexAttribArrayARB(index: int) -> None: ...
def glGetActiveAttribARB(programObj: int, index: int, maxLength: int, length: IntArray | None = None, size: IntArray | None = None, type: UIntArray | None = None, name: ByteArray | None = None) -> tuple[IntArrayResult, ByteArrayResult, IntArrayResult, UIntArrayResult]: ...
def glGetAttribLocationARB(programObj: int, name: ByteArray) -> int: ...
def glGetVertexAttribPointervARB(index: int, pname: int, pointer: AnyArray | None = None) -> AnyArrayResult: ...
def glGetVertexAttribdvARB(index: int, pname: int, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetVertexAttribfvARB(index: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetVertexAttribivARB(index: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glVertexAttrib1dARB(index: int, x: float) -> None: ...
def glVertexAttrib1dvARB(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib1fARB(index: int, x: float) -> None: ...
def glVertexAttrib1fvARB(index: int, v: FloatArray) -> None: ...
def glVertexAttrib1sARB(index: int, x: int) -> None: ...
def glVertexAttrib1svARB(index: int, v: ShortArray) -> None: ...
def glVertexAttrib2dARB(index: int, x: float, y: float) -> None: ...
def glVertexAttrib2dvARB(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib2fARB(index: int, x: float, y: float) -> None: ...
def glVertexAttrib2fvARB(index: int, v: FloatArray) -> None: ...
def glVertexAttrib2sARB(index: int, x: int, y: int) -> None: ...
def glVertexAttrib2svARB(index: int, v: ShortArray) -> None: ...
def glVertexAttrib3dARB(index: int, x: float, y: float, z: float) -> None: ...
def glVertexAttrib3dvARB(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib3fARB(index: int, x: float, y: float, z: float) -> None: ...
def glVertexAttrib3fvARB(index: int, v: FloatArray) -> None: ...
def glVertexAttrib3sARB(index: int, x: int, y: int, z: int) -> None: ...
def glVertexAttrib3svARB(index: int, v: ShortArray) -> None: ...
def glVertexAttrib4NbvARB(index: int, v: ByteArray) -> None: ...
def glVertexAttrib4NivARB(index: int, v: IntArray) -> None: ...
def glVertexAttrib4NsvARB(index: int, v: ShortArray) -> None: ...
def glVertexAttrib4NubARB(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttrib4NubvARB(index: int, v: UByteArray) -> None: ...
def glVertexAttrib4NuivARB(index: int, v: UIntArray) -> None: ...
def glVertexAttrib4NusvARB(index: int, v: UShortArray) -> None: ...
def glVertexAttrib4bvARB(index: int, v: ByteArray) -> None: ...
def glVertexAttrib4dARB(index: int, x: float, y: float, z: float, w: float) -> None: ...
def glVertexAttrib4dvARB(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib4fARB(index: int, x: float, y: float, z: float, w: float) -> None: ...
def glVertexAttrib4fvARB(index: int, v: FloatArray) -> None: ...
def glVertexAttrib4ivARB(index: int, v: IntArray) -> None: ...
def glVertexAttrib4sARB(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttrib4svARB(index: int, v: ShortArray) -> None: ...
def glVertexAttrib4ubvARB(index: int, v: UByteArray) -> None: ...
def glVertexAttrib4uivARB(index: int, v: UIntArray) -> None: ...
def glVertexAttrib4usvARB(index: int, v: UShortArray) -> None: ...
def glVertexAttribPointerARB(index: int, size: int, type: int, normalized: bool, stride: int, pointer: AnyArray) -> None: ...

def glInitVertexShaderARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
