"""OpenGL.GL.ARB.vertex_attrib_64bit -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, DoubleArray, DoubleArrayResult

from OpenGL.raw.GL._types import *

GL_DOUBLE_MAT2: int
GL_DOUBLE_MAT2x3: int
GL_DOUBLE_MAT2x4: int
GL_DOUBLE_MAT3: int
GL_DOUBLE_MAT3x2: int
GL_DOUBLE_MAT3x4: int
GL_DOUBLE_MAT4: int
GL_DOUBLE_MAT4x2: int
GL_DOUBLE_MAT4x3: int
GL_DOUBLE_VEC2: int
GL_DOUBLE_VEC3: int
GL_DOUBLE_VEC4: int
GL_RGB32I: int

def glGetVertexAttribLdv(index: int, pname: int, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glVertexAttribL1d(index: int, x: float) -> None: ...
def glVertexAttribL1dv(index: int, v: DoubleArray) -> None: ...
def glVertexAttribL2d(index: int, x: float, y: float) -> None: ...
def glVertexAttribL2dv(index: int, v: DoubleArray) -> None: ...
def glVertexAttribL3d(index: int, x: float, y: float, z: float) -> None: ...
def glVertexAttribL3dv(index: int, v: DoubleArray) -> None: ...
def glVertexAttribL4d(index: int, x: float, y: float, z: float, w: float) -> None: ...
def glVertexAttribL4dv(index: int, v: DoubleArray) -> None: ...
def glVertexAttribLPointer(index: int, size: int, type: int, stride: int, pointer: AnyArray) -> None: ...

def glInitVertexAttrib64BitARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
