"""OpenGL.GL.ARB.viewport_array -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import DoubleArray, DoubleArrayResult, FloatArray, FloatArrayResult, IntArray

from OpenGL.raw.GL._types import *

GL_DEPTH_RANGE: int
GL_FIRST_VERTEX_CONVENTION: int
GL_LAST_VERTEX_CONVENTION: int
GL_LAYER_PROVOKING_VERTEX: int
GL_MAX_VIEWPORTS: int
GL_PROVOKING_VERTEX: int
GL_SCISSOR_BOX: int
GL_SCISSOR_TEST: int
GL_UNDEFINED_VERTEX: int
GL_VIEWPORT: int
GL_VIEWPORT_BOUNDS_RANGE: int
GL_VIEWPORT_INDEX_PROVOKING_VERTEX: int
GL_VIEWPORT_SUBPIXEL_BITS: int

def glDepthRangeArraydvNV(first: int, count: int, v: DoubleArray) -> None: ...
def glDepthRangeArrayv(first: int, count: int, v: DoubleArray) -> None: ...
def glDepthRangeIndexed(index: int, n: float, f: float) -> None: ...
def glDepthRangeIndexeddNV(index: int, n: float, f: float) -> None: ...
def glGetDoublei_v(target: int, index: int, data: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetFloati_v(target: int, index: int, data: FloatArray | None = None) -> FloatArrayResult: ...
def glScissorArrayv(first: int, count: int, v: IntArray) -> None: ...
def glScissorIndexed(index: int, left: int, bottom: int, width: int, height: int) -> None: ...
def glScissorIndexedv(index: int, v: IntArray) -> None: ...
def glViewportArrayv(first: int, count: int, v: FloatArray) -> None: ...
def glViewportIndexedf(index: int, x: float, y: float, w: float, h: float) -> None: ...
def glViewportIndexedfv(index: int, v: FloatArray) -> None: ...

def glInitViewportArrayARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
