"""OpenGL.GL.ARB.window_pos -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import DoubleArray, FloatArray, IntArray, ShortArray

from OpenGL.raw.GL._types import *

def glWindowPos2dARB(x: float, y: float) -> None: ...
def glWindowPos2dvARB(v: DoubleArray) -> None: ...
def glWindowPos2fARB(x: float, y: float) -> None: ...
def glWindowPos2fvARB(v: FloatArray) -> None: ...
def glWindowPos2iARB(x: int, y: int) -> None: ...
def glWindowPos2ivARB(v: IntArray) -> None: ...
def glWindowPos2sARB(x: int, y: int) -> None: ...
def glWindowPos2svARB(v: ShortArray) -> None: ...
def glWindowPos3dARB(x: float, y: float, z: float) -> None: ...
def glWindowPos3dvARB(v: DoubleArray) -> None: ...
def glWindowPos3fARB(x: float, y: float, z: float) -> None: ...
def glWindowPos3fvARB(v: FloatArray) -> None: ...
def glWindowPos3iARB(x: int, y: int, z: int) -> None: ...
def glWindowPos3ivARB(v: IntArray) -> None: ...
def glWindowPos3sARB(x: int, y: int, z: int) -> None: ...
def glWindowPos3svARB(v: ShortArray) -> None: ...

def glInitWindowPosARB() -> bool: ...

def __getattr__(name: str) -> Any: ...
