"""OpenGL.GLX.OML.sync_control -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, Int64Array

from OpenGL.raw.GLX._types import *

def glXGetMscRateOML(dpy: AnyArray, drawable: Any, numerator: AnyArray, denominator: AnyArray) -> int: ...
def glXGetSyncValuesOML(dpy: AnyArray, drawable: Any, ust: Int64Array, msc: Int64Array, sbc: Int64Array) -> int: ...
def glXSwapBuffersMscOML(dpy: AnyArray, drawable: Any, target_msc: int, divisor: int, remainder: int) -> int: ...
def glXWaitForMscOML(dpy: AnyArray, drawable: Any, target_msc: int, divisor: int, remainder: int, ust: Int64Array, msc: Int64Array, sbc: Int64Array) -> int: ...
def glXWaitForSbcOML(dpy: AnyArray, drawable: Any, target_sbc: int, ust: Int64Array, msc: Int64Array, sbc: Int64Array) -> int: ...

def glInitSyncControlOML() -> bool: ...

def __getattr__(name: str) -> Any: ...
