"""OpenGL.GLES2.QCOM.extended_get2 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import ByteArray, IntArray, UIntArray

from OpenGL.raw.GLES2._types import *

def glExtGetProgramBinarySourceQCOM(program: int, shadertype: int, source: ByteArray, length: IntArray) -> None: ...
def glExtGetProgramsQCOM(programs: UIntArray, maxPrograms: int, numPrograms: IntArray) -> None: ...
def glExtGetShadersQCOM(shaders: UIntArray, maxShaders: int, numShaders: IntArray) -> None: ...
def glExtIsProgramBinaryQCOM(program: int) -> int: ...

def glInitExtendedGet2QCOM() -> bool: ...

def __getattr__(name: str) -> Any: ...
