"""OpenGL.GLES2.QCOM.tiled_rendering -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GLES2._types import *

GL_COLOR_BUFFER_BIT0_QCOM: int
GL_COLOR_BUFFER_BIT1_QCOM: int
GL_COLOR_BUFFER_BIT2_QCOM: int
GL_COLOR_BUFFER_BIT3_QCOM: int
GL_COLOR_BUFFER_BIT4_QCOM: int
GL_COLOR_BUFFER_BIT5_QCOM: int
GL_COLOR_BUFFER_BIT6_QCOM: int
GL_COLOR_BUFFER_BIT7_QCOM: int
GL_DEPTH_BUFFER_BIT0_QCOM: int
GL_DEPTH_BUFFER_BIT1_QCOM: int
GL_DEPTH_BUFFER_BIT2_QCOM: int
GL_DEPTH_BUFFER_BIT3_QCOM: int
GL_DEPTH_BUFFER_BIT4_QCOM: int
GL_DEPTH_BUFFER_BIT5_QCOM: int
GL_DEPTH_BUFFER_BIT6_QCOM: int
GL_DEPTH_BUFFER_BIT7_QCOM: int
GL_MULTISAMPLE_BUFFER_BIT0_QCOM: int
GL_MULTISAMPLE_BUFFER_BIT1_QCOM: int
GL_MULTISAMPLE_BUFFER_BIT2_QCOM: int
GL_MULTISAMPLE_BUFFER_BIT3_QCOM: int
GL_MULTISAMPLE_BUFFER_BIT4_QCOM: int
GL_MULTISAMPLE_BUFFER_BIT5_QCOM: int
GL_MULTISAMPLE_BUFFER_BIT6_QCOM: int
GL_MULTISAMPLE_BUFFER_BIT7_QCOM: int
GL_STENCIL_BUFFER_BIT0_QCOM: int
GL_STENCIL_BUFFER_BIT1_QCOM: int
GL_STENCIL_BUFFER_BIT2_QCOM: int
GL_STENCIL_BUFFER_BIT3_QCOM: int
GL_STENCIL_BUFFER_BIT4_QCOM: int
GL_STENCIL_BUFFER_BIT5_QCOM: int
GL_STENCIL_BUFFER_BIT6_QCOM: int
GL_STENCIL_BUFFER_BIT7_QCOM: int

def glEndTilingQCOM(preserveMask: int) -> None: ...
def glStartTilingQCOM(x: int, y: int, width: int, height: int, preserveMask: int) -> None: ...

def glInitTiledRenderingQCOM() -> bool: ...

def __getattr__(name: str) -> Any: ...
