"""OpenGL.GLES2.ANGLE.instanced_arrays -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.GLES2._types import *

GL_VERTEX_ATTRIB_ARRAY_DIVISOR_ANGLE: int

def glDrawArraysInstancedANGLE(mode: int, first: int, count: int, primcount: int) -> None: ...
def glDrawElementsInstancedANGLE(mode: int, count: int, type: int, indices: AnyArray, primcount: int) -> None: ...
def glVertexAttribDivisorANGLE(index: int, divisor: int) -> None: ...

def glInitInstancedArraysANGLE() -> bool: ...

def __getattr__(name: str) -> Any: ...
