'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p, constants as _cs, arrays
from OpenGL.GL import glget
import ctypes
EXTENSION_NAME = 'GL_SUNX_constant_data'
def _f( function ):
    return _p.createFunction( function,_p.GL,'GL_SUNX_constant_data',False)
_p.unpack_constants( """GL_UNPACK_CONSTANT_DATA_SUNX 0x81D5
GL_TEXTURE_CONSTANT_DATA_SUNX 0x81D6""", globals())
@_f
@_p.types(None,)
def glFinishTextureSUNX(  ):pass


def glInitConstantDataSUNX():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
