"""OpenGL.GL.SGIS.pixel_texture -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray, FloatArrayResult, IntArray, IntArrayResult

from OpenGL.raw.GL._types import *

GL_PIXEL_FRAGMENT_ALPHA_SOURCE_SGIS: int
GL_PIXEL_FRAGMENT_RGB_SOURCE_SGIS: int
GL_PIXEL_GROUP_COLOR_SGIS: int
GL_PIXEL_TEXTURE_SGIS: int

def glGetPixelTexGenParameterfvSGIS(pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetPixelTexGenParameterivSGIS(pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glPixelTexGenParameterfSGIS(pname: int, param: float) -> None: ...
def glPixelTexGenParameterfvSGIS(pname: int, params: FloatArray) -> None: ...
def glPixelTexGenParameteriSGIS(pname: int, param: int) -> None: ...
def glPixelTexGenParameterivSGIS(pname: int, params: IntArray) -> None: ...

def glInitPixelTextureSGIS() -> bool: ...

def __getattr__(name: str) -> Any: ...
