"""OpenGL.GL.SGIS.texture_select -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

GL_DUAL_ALPHA12_SGIS: int
GL_DUAL_ALPHA16_SGIS: int
GL_DUAL_ALPHA4_SGIS: int
GL_DUAL_ALPHA8_SGIS: int
GL_DUAL_INTENSITY12_SGIS: int
GL_DUAL_INTENSITY16_SGIS: int
GL_DUAL_INTENSITY4_SGIS: int
GL_DUAL_INTENSITY8_SGIS: int
GL_DUAL_LUMINANCE12_SGIS: int
GL_DUAL_LUMINANCE16_SGIS: int
GL_DUAL_LUMINANCE4_SGIS: int
GL_DUAL_LUMINANCE8_SGIS: int
GL_DUAL_LUMINANCE_ALPHA4_SGIS: int
GL_DUAL_LUMINANCE_ALPHA8_SGIS: int
GL_DUAL_TEXTURE_SELECT_SGIS: int
GL_QUAD_ALPHA4_SGIS: int
GL_QUAD_ALPHA8_SGIS: int
GL_QUAD_INTENSITY4_SGIS: int
GL_QUAD_INTENSITY8_SGIS: int
GL_QUAD_LUMINANCE4_SGIS: int
GL_QUAD_LUMINANCE8_SGIS: int
GL_QUAD_TEXTURE_SELECT_SGIS: int

def glInitTextureSelectSGIS() -> bool: ...

def __getattr__(name: str) -> Any: ...
