"""OpenGL.GL.ATI.map_object_buffer -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

def glMapObjectBufferATI(buffer: int) -> int | None: ...
def glUnmapObjectBufferATI(buffer: int) -> None: ...

def glInitMapObjectBufferATI() -> bool: ...

def __getattr__(name: str) -> Any: ...
