"""OpenGL.GL.ATI.vertex_streams -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import ByteArray, DoubleArray, FloatArray, IntArray, ShortArray

from OpenGL.raw.GL._types import *

GL_MAX_VERTEX_STREAMS_ATI: int
GL_VERTEX_SOURCE_ATI: int
GL_VERTEX_STREAM0_ATI: int
GL_VERTEX_STREAM1_ATI: int
GL_VERTEX_STREAM2_ATI: int
GL_VERTEX_STREAM3_ATI: int
GL_VERTEX_STREAM4_ATI: int
GL_VERTEX_STREAM5_ATI: int
GL_VERTEX_STREAM6_ATI: int
GL_VERTEX_STREAM7_ATI: int

def glClientActiveVertexStreamATI(stream: int) -> None: ...
def glNormalStream3bATI(stream: int, nx: int, ny: int, nz: int) -> None: ...
def glNormalStream3bvATI(stream: int, coords: ByteArray) -> None: ...
def glNormalStream3dATI(stream: int, nx: float, ny: float, nz: float) -> None: ...
def glNormalStream3dvATI(stream: int, coords: DoubleArray) -> None: ...
def glNormalStream3fATI(stream: int, nx: float, ny: float, nz: float) -> None: ...
def glNormalStream3fvATI(stream: int, coords: FloatArray) -> None: ...
def glNormalStream3iATI(stream: int, nx: int, ny: int, nz: int) -> None: ...
def glNormalStream3ivATI(stream: int, coords: IntArray) -> None: ...
def glNormalStream3sATI(stream: int, nx: int, ny: int, nz: int) -> None: ...
def glNormalStream3svATI(stream: int, coords: ShortArray) -> None: ...
def glVertexBlendEnvfATI(pname: int, param: float) -> None: ...
def glVertexBlendEnviATI(pname: int, param: int) -> None: ...
def glVertexStream1dATI(stream: int, x: float) -> None: ...
def glVertexStream1dvATI(stream: int, coords: DoubleArray) -> None: ...
def glVertexStream1fATI(stream: int, x: float) -> None: ...
def glVertexStream1fvATI(stream: int, coords: FloatArray) -> None: ...
def glVertexStream1iATI(stream: int, x: int) -> None: ...
def glVertexStream1ivATI(stream: int, coords: IntArray) -> None: ...
def glVertexStream1sATI(stream: int, x: int) -> None: ...
def glVertexStream1svATI(stream: int, coords: ShortArray) -> None: ...
def glVertexStream2dATI(stream: int, x: float, y: float) -> None: ...
def glVertexStream2dvATI(stream: int, coords: DoubleArray) -> None: ...
def glVertexStream2fATI(stream: int, x: float, y: float) -> None: ...
def glVertexStream2fvATI(stream: int, coords: FloatArray) -> None: ...
def glVertexStream2iATI(stream: int, x: int, y: int) -> None: ...
def glVertexStream2ivATI(stream: int, coords: IntArray) -> None: ...
def glVertexStream2sATI(stream: int, x: int, y: int) -> None: ...
def glVertexStream2svATI(stream: int, coords: ShortArray) -> None: ...
def glVertexStream3dATI(stream: int, x: float, y: float, z: float) -> None: ...
def glVertexStream3dvATI(stream: int, coords: DoubleArray) -> None: ...
def glVertexStream3fATI(stream: int, x: float, y: float, z: float) -> None: ...
def glVertexStream3fvATI(stream: int, coords: FloatArray) -> None: ...
def glVertexStream3iATI(stream: int, x: int, y: int, z: int) -> None: ...
def glVertexStream3ivATI(stream: int, coords: IntArray) -> None: ...
def glVertexStream3sATI(stream: int, x: int, y: int, z: int) -> None: ...
def glVertexStream3svATI(stream: int, coords: ShortArray) -> None: ...
def glVertexStream4dATI(stream: int, x: float, y: float, z: float, w: float) -> None: ...
def glVertexStream4dvATI(stream: int, coords: DoubleArray) -> None: ...
def glVertexStream4fATI(stream: int, x: float, y: float, z: float, w: float) -> None: ...
def glVertexStream4fvATI(stream: int, coords: FloatArray) -> None: ...
def glVertexStream4iATI(stream: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexStream4ivATI(stream: int, coords: IntArray) -> None: ...
def glVertexStream4sATI(stream: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexStream4svATI(stream: int, coords: ShortArray) -> None: ...

def glInitVertexStreamsATI() -> bool: ...

def __getattr__(name: str) -> Any: ...
