"""OpenGL.GL.ATI.vertex_attrib_array_object -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray, FloatArrayResult, IntArray, IntArrayResult

from OpenGL.raw.GL._types import *

def glGetVertexAttribArrayObjectfvATI(index: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetVertexAttribArrayObjectivATI(index: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glVertexAttribArrayObjectATI(index: int, size: int, type: int, normalized: int, stride: int, buffer: int, offset: int) -> None: ...

def glInitVertexAttribArrayObjectATI() -> bool: ...

def __getattr__(name: str) -> Any: ...
