"""OpenGL.GL.ATI.vertex_array_object -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, FloatArray, FloatArrayResult, IntArray, IntArrayResult

from OpenGL.raw.GL._types import *

GL_ARRAY_OBJECT_BUFFER_ATI: int
GL_ARRAY_OBJECT_OFFSET_ATI: int
GL_DISCARD_ATI: int
GL_DYNAMIC_ATI: int
GL_OBJECT_BUFFER_SIZE_ATI: int
GL_OBJECT_BUFFER_USAGE_ATI: int
GL_PRESERVE_ATI: int
GL_STATIC_ATI: int

def glArrayObjectATI(array: int, size: int, type: int, stride: int, buffer: int, offset: int) -> None: ...
def glFreeObjectBufferATI(buffer: int) -> None: ...
def glGetArrayObjectfvATI(array: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetArrayObjectivATI(array: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetObjectBufferfvATI(buffer: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetObjectBufferivATI(buffer: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetVariantArrayObjectfvATI(id: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetVariantArrayObjectivATI(id: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glIsObjectBufferATI(buffer: int) -> int: ...
def glNewObjectBufferATI(size: int, pointer: AnyArray, usage: int) -> int: ...
def glUpdateObjectBufferATI(buffer: int, offset: int, size: int, pointer: AnyArray, preserve: int) -> None: ...
def glVariantArrayObjectATI(id: int, type: int, stride: int, buffer: int, offset: int) -> None: ...

def glInitVertexArrayObjectATI() -> bool: ...

def __getattr__(name: str) -> Any: ...
