'''Autogenerated by get_gl_extensions script, do not edit!'''
from OpenGL import platform as _p
from OpenGL.GL import glget
EXTENSION_NAME = 'GL_SGI_texture_color_table'
_p.unpack_constants( """GL_TEXTURE_COLOR_TABLE_SGI 0x80BC
GL_PROXY_TEXTURE_COLOR_TABLE_SGI 0x80BD""", globals())
glget.addGLGetConstant( GL_TEXTURE_COLOR_TABLE_SGI, (1,) )


def glInitTextureColorTableSGI():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
