"""OpenGL.GL.SUN.global_alpha -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

GL_GLOBAL_ALPHA_FACTOR_SUN: int
GL_GLOBAL_ALPHA_SUN: int

def glGlobalAlphaFactorbSUN(factor: int) -> None: ...
def glGlobalAlphaFactordSUN(factor: float) -> None: ...
def glGlobalAlphaFactorfSUN(factor: float) -> None: ...
def glGlobalAlphaFactoriSUN(factor: int) -> None: ...
def glGlobalAlphaFactorsSUN(factor: int) -> None: ...
def glGlobalAlphaFactorubSUN(factor: int) -> None: ...
def glGlobalAlphaFactoruiSUN(factor: int) -> None: ...
def glGlobalAlphaFactorusSUN(factor: int) -> None: ...

def glInitGlobalAlphaSUN() -> bool: ...

def __getattr__(name: str) -> Any: ...
