"""OpenGL.GL.SUN.vertex -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray, UByteArray, UIntArray

from OpenGL.raw.GL._types import *

def glColor3fVertex3fSUN(r: float, g: float, b: float, x: float, y: float, z: float) -> None: ...
def glColor3fVertex3fvSUN(c: FloatArray, v: FloatArray) -> None: ...
def glColor4fNormal3fVertex3fSUN(r: float, g: float, b: float, a: float, nx: float, ny: float, nz: float, x: float, y: float, z: float) -> None: ...
def glColor4fNormal3fVertex3fvSUN(c: FloatArray, n: FloatArray, v: FloatArray) -> None: ...
def glColor4ubVertex2fSUN(r: int, g: int, b: int, a: int, x: float, y: float) -> None: ...
def glColor4ubVertex2fvSUN(c: UByteArray, v: FloatArray) -> None: ...
def glColor4ubVertex3fSUN(r: int, g: int, b: int, a: int, x: float, y: float, z: float) -> None: ...
def glColor4ubVertex3fvSUN(c: UByteArray, v: FloatArray) -> None: ...
def glNormal3fVertex3fSUN(nx: float, ny: float, nz: float, x: float, y: float, z: float) -> None: ...
def glNormal3fVertex3fvSUN(n: FloatArray, v: FloatArray) -> None: ...
def glReplacementCodeuiColor3fVertex3fSUN(rc: int, r: float, g: float, b: float, x: float, y: float, z: float) -> None: ...
def glReplacementCodeuiColor3fVertex3fvSUN(rc: UIntArray, c: FloatArray, v: FloatArray) -> None: ...
def glReplacementCodeuiColor4fNormal3fVertex3fSUN(rc: int, r: float, g: float, b: float, a: float, nx: float, ny: float, nz: float, x: float, y: float, z: float) -> None: ...
def glReplacementCodeuiColor4fNormal3fVertex3fvSUN(rc: UIntArray, c: FloatArray, n: FloatArray, v: FloatArray) -> None: ...
def glReplacementCodeuiColor4ubVertex3fSUN(rc: int, r: int, g: int, b: int, a: int, x: float, y: float, z: float) -> None: ...
def glReplacementCodeuiColor4ubVertex3fvSUN(rc: UIntArray, c: UByteArray, v: FloatArray) -> None: ...
def glReplacementCodeuiNormal3fVertex3fSUN(rc: int, nx: float, ny: float, nz: float, x: float, y: float, z: float) -> None: ...
def glReplacementCodeuiNormal3fVertex3fvSUN(rc: UIntArray, n: FloatArray, v: FloatArray) -> None: ...
def glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fSUN(rc: int, s: float, t: float, r: float, g: float, b: float, a: float, nx: float, ny: float, nz: float, x: float, y: float, z: float) -> None: ...
def glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN(rc: UIntArray, tc: FloatArray, c: FloatArray, n: FloatArray, v: FloatArray) -> None: ...
def glReplacementCodeuiTexCoord2fNormal3fVertex3fSUN(rc: int, s: float, t: float, nx: float, ny: float, nz: float, x: float, y: float, z: float) -> None: ...
def glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN(rc: UIntArray, tc: FloatArray, n: FloatArray, v: FloatArray) -> None: ...
def glReplacementCodeuiTexCoord2fVertex3fSUN(rc: int, s: float, t: float, x: float, y: float, z: float) -> None: ...
def glReplacementCodeuiTexCoord2fVertex3fvSUN(rc: UIntArray, tc: FloatArray, v: FloatArray) -> None: ...
def glReplacementCodeuiVertex3fSUN(rc: int, x: float, y: float, z: float) -> None: ...
def glReplacementCodeuiVertex3fvSUN(rc: UIntArray, v: FloatArray) -> None: ...
def glTexCoord2fColor3fVertex3fSUN(s: float, t: float, r: float, g: float, b: float, x: float, y: float, z: float) -> None: ...
def glTexCoord2fColor3fVertex3fvSUN(tc: FloatArray, c: FloatArray, v: FloatArray) -> None: ...
def glTexCoord2fColor4fNormal3fVertex3fSUN(s: float, t: float, r: float, g: float, b: float, a: float, nx: float, ny: float, nz: float, x: float, y: float, z: float) -> None: ...
def glTexCoord2fColor4fNormal3fVertex3fvSUN(tc: FloatArray, c: FloatArray, n: FloatArray, v: FloatArray) -> None: ...
def glTexCoord2fColor4ubVertex3fSUN(s: float, t: float, r: int, g: int, b: int, a: int, x: float, y: float, z: float) -> None: ...
def glTexCoord2fColor4ubVertex3fvSUN(tc: FloatArray, c: UByteArray, v: FloatArray) -> None: ...
def glTexCoord2fNormal3fVertex3fSUN(s: float, t: float, nx: float, ny: float, nz: float, x: float, y: float, z: float) -> None: ...
def glTexCoord2fNormal3fVertex3fvSUN(tc: FloatArray, n: FloatArray, v: FloatArray) -> None: ...
def glTexCoord2fVertex3fSUN(s: float, t: float, x: float, y: float, z: float) -> None: ...
def glTexCoord2fVertex3fvSUN(tc: FloatArray, v: FloatArray) -> None: ...
def glTexCoord4fColor4fNormal3fVertex4fSUN(s: float, t: float, p: float, q: float, r: float, g: float, b: float, a: float, nx: float, ny: float, nz: float, x: float, y: float, z: float, w: float) -> None: ...
def glTexCoord4fColor4fNormal3fVertex4fvSUN(tc: FloatArray, c: FloatArray, n: FloatArray, v: FloatArray) -> None: ...
def glTexCoord4fVertex4fSUN(s: float, t: float, p: float, q: float, x: float, y: float, z: float, w: float) -> None: ...
def glTexCoord4fVertex4fvSUN(tc: FloatArray, v: FloatArray) -> None: ...

def glInitVertexSUN() -> bool: ...

def __getattr__(name: str) -> Any: ...
