'''Autogenerated by xml_generate script, do not edit!'''
from OpenGL import platform as _p, arrays
from OpenGL.raw.GL import _types as _cs
from OpenGL.constant import Constant as _C

import ctypes
EXTENSION_NAME = 'GL_DFX_tbuffer'
def _f( function ):
    return _p.createFunction( function,_p.GL,'GL_DFX_tbuffer')

@_f
@_p.types(None,_cs.GLuint)
def glTbufferMask3DFX(mask):pass
