"""OpenGL.GLUT -- generated; regenerate with src/regenerate_c.py.

GLUT is hand-maintained rather than registry-generated (it is not a Khronos
API), so this is emitted from the declarations in ``OpenGL/raw/GLUT`` and
``OpenGL/GLUT`` rather than from the registry.
"""

from collections.abc import Callable, Sequence
from typing import Any

from OpenGL.raw.GL._types import *

GLUT_3_2_CORE_PROFILE: int
GLUT_ACCUM: int
GLUT_ACTION_CONTINUE_EXECUTION: int
GLUT_ACTION_EXIT: int
GLUT_ACTION_GLUTMAINLOOP_RETURNS: int
GLUT_ACTION_ON_WINDOW_CLOSE: int
GLUT_ACTIVE_ALT: int
GLUT_ACTIVE_CTRL: int
GLUT_ACTIVE_SHIFT: int
GLUT_ALLOW_DIRECT_CONTEXT: int
GLUT_ALPHA: int
GLUT_API_VERSION: int
GLUT_AUX: int
GLUT_AUX1: int
GLUT_AUX2: int
GLUT_AUX3: int
GLUT_AUX4: int
GLUT_BITMAP_8_BY_13: Any
GLUT_BITMAP_9_BY_15: Any
GLUT_BITMAP_HELVETICA_10: Any
GLUT_BITMAP_HELVETICA_12: Any
GLUT_BITMAP_HELVETICA_18: Any
GLUT_BITMAP_TIMES_ROMAN_10: Any
GLUT_BITMAP_TIMES_ROMAN_24: Any
GLUT_BLUE: int
GLUT_BORDERLESS: int
GLUT_CAPTIONLESS: int
GLUT_COMPATIBILITY_PROFILE: int
GLUT_CORE_PROFILE: int
GLUT_CREATE_NEW_CONTEXT: int
GLUT_CURSOR_BOTTOM_LEFT_CORNER: int
GLUT_CURSOR_BOTTOM_RIGHT_CORNER: int
GLUT_CURSOR_BOTTOM_SIDE: int
GLUT_CURSOR_CROSSHAIR: int
GLUT_CURSOR_CYCLE: int
GLUT_CURSOR_DESTROY: int
GLUT_CURSOR_FULL_CROSSHAIR: int
GLUT_CURSOR_HELP: int
GLUT_CURSOR_INFO: int
GLUT_CURSOR_INHERIT: int
GLUT_CURSOR_LEFT_ARROW: int
GLUT_CURSOR_LEFT_RIGHT: int
GLUT_CURSOR_LEFT_SIDE: int
GLUT_CURSOR_NONE: int
GLUT_CURSOR_RIGHT_ARROW: int
GLUT_CURSOR_RIGHT_SIDE: int
GLUT_CURSOR_SPRAY: int
GLUT_CURSOR_TEXT: int
GLUT_CURSOR_TOP_LEFT_CORNER: int
GLUT_CURSOR_TOP_RIGHT_CORNER: int
GLUT_CURSOR_TOP_SIDE: int
GLUT_CURSOR_UP_DOWN: int
GLUT_CURSOR_WAIT: int
GLUT_DEBUG: int
GLUT_DEPTH: int
GLUT_DEVICE_IGNORE_KEY_REPEAT: int
GLUT_DEVICE_KEY_REPEAT: int
GLUT_DIRECT_RENDERING: int
GLUT_DISPLAY_MODE_POSSIBLE: int
GLUT_DOUBLE: int
GLUT_DOWN: int
GLUT_ELAPSED_TIME: int
GLUT_ENTERED: int
GLUT_FORCE_DIRECT_CONTEXT: int
GLUT_FORCE_INDIRECT_CONTEXT: int
GLUT_FORWARD_COMPATIBLE: int
GLUT_FULLY_COVERED: int
GLUT_FULLY_RETAINED: int
GLUT_FULL_SCREEN: int
GLUT_GAME_MODE_ACTIVE: int
GLUT_GAME_MODE_DISPLAY_CHANGED: int
GLUT_GAME_MODE_HEIGHT: int
GLUT_GAME_MODE_PIXEL_DEPTH: int
GLUT_GAME_MODE_POSSIBLE: int
GLUT_GAME_MODE_REFRESH_RATE: int
GLUT_GAME_MODE_WIDTH: int
GLUT_GREEN: int
GLUT_GUARD_CALLBACKS: int
GLUT_HAS_DIAL_AND_BUTTON_BOX: int
GLUT_HAS_JOYSTICK: int
GLUT_HAS_KEYBOARD: int
GLUT_HAS_MOUSE: int
GLUT_HAS_OVERLAY: int
GLUT_HAS_SPACEBALL: int
GLUT_HAS_TABLET: int
GLUT_HIDDEN: int
GLUT_INDEX: int
GLUT_INIT_DISPLAY_MODE: int
GLUT_INIT_FLAGS: int
GLUT_INIT_MAJOR_VERSION: int
GLUT_INIT_MINOR_VERSION: int
GLUT_INIT_PROFILE: int
GLUT_INIT_STATE: int
GLUT_INIT_WINDOW_HEIGHT: int
GLUT_INIT_WINDOW_WIDTH: int
GLUT_INIT_WINDOW_X: int
GLUT_INIT_WINDOW_Y: int
GLUT_JOYSTICK_AXES: int
GLUT_JOYSTICK_BUTTONS: int
GLUT_JOYSTICK_BUTTON_A: int
GLUT_JOYSTICK_BUTTON_B: int
GLUT_JOYSTICK_BUTTON_C: int
GLUT_JOYSTICK_BUTTON_D: int
GLUT_JOYSTICK_POLL_RATE: int
GLUT_KEY_BEGIN: int
GLUT_KEY_DELETE: int
GLUT_KEY_DOWN: int
GLUT_KEY_END: int
GLUT_KEY_F1: int
GLUT_KEY_F10: int
GLUT_KEY_F11: int
GLUT_KEY_F12: int
GLUT_KEY_F2: int
GLUT_KEY_F3: int
GLUT_KEY_F4: int
GLUT_KEY_F5: int
GLUT_KEY_F6: int
GLUT_KEY_F7: int
GLUT_KEY_F8: int
GLUT_KEY_F9: int
GLUT_KEY_HOME: int
GLUT_KEY_INSERT: int
GLUT_KEY_LEFT: int
GLUT_KEY_NUM_LOCK: int
GLUT_KEY_PAGE_DOWN: int
GLUT_KEY_PAGE_UP: int
GLUT_KEY_REPEAT_DEFAULT: int
GLUT_KEY_REPEAT_OFF: int
GLUT_KEY_REPEAT_ON: int
GLUT_KEY_RIGHT: int
GLUT_KEY_UP: int
GLUT_LAYER_IN_USE: int
GLUT_LEFT: int
GLUT_LEFT_BUTTON: int
GLUT_LUMINANCE: int
GLUT_MENU_IN_USE: int
GLUT_MENU_NOT_IN_USE: int
GLUT_MENU_NUM_ITEMS: int
GLUT_MIDDLE_BUTTON: int
GLUT_MULTISAMPLE: int
GLUT_NORMAL: int
GLUT_NORMAL_DAMAGED: int
GLUT_NOT_VISIBLE: int
GLUT_NO_RECOVERY: int
GLUT_NUM_BUTTON_BOX_BUTTONS: int
GLUT_NUM_DIALS: int
GLUT_NUM_MOUSE_BUTTONS: int
GLUT_NUM_SPACEBALL_BUTTONS: int
GLUT_NUM_TABLET_BUTTONS: int
GLUT_OVERLAY: int
GLUT_OVERLAY_DAMAGED: int
GLUT_OVERLAY_POSSIBLE: int
GLUT_OWNS_JOYSTICK: int
GLUT_PARTIALLY_RETAINED: int
GLUT_RED: int
GLUT_RENDERING_CONTEXT: int
GLUT_RGB: int
GLUT_RGBA: int
GLUT_RIGHT_BUTTON: int
GLUT_SCREEN_HEIGHT: int
GLUT_SCREEN_HEIGHT_MM: int
GLUT_SCREEN_WIDTH: int
GLUT_SCREEN_WIDTH_MM: int
GLUT_SINGLE: int
GLUT_SRGB: int
GLUT_STENCIL: int
GLUT_STEREO: int
GLUT_STROKE_MONO_ROMAN: Any
GLUT_STROKE_ROMAN: Any
GLUT_TRANSPARENT_INDEX: int
GLUT_TRY_DIRECT_CONTEXT: int
GLUT_UP: int
GLUT_USE_CURRENT_CONTEXT: int
GLUT_VIDEO_RESIZE_HEIGHT: int
GLUT_VIDEO_RESIZE_HEIGHT_DELTA: int
GLUT_VIDEO_RESIZE_IN_USE: int
GLUT_VIDEO_RESIZE_POSSIBLE: int
GLUT_VIDEO_RESIZE_WIDTH: int
GLUT_VIDEO_RESIZE_WIDTH_DELTA: int
GLUT_VIDEO_RESIZE_X: int
GLUT_VIDEO_RESIZE_X_DELTA: int
GLUT_VIDEO_RESIZE_Y: int
GLUT_VIDEO_RESIZE_Y_DELTA: int
GLUT_VISIBLE: int
GLUT_WINDOW_ACCUM_ALPHA_SIZE: int
GLUT_WINDOW_ACCUM_BLUE_SIZE: int
GLUT_WINDOW_ACCUM_GREEN_SIZE: int
GLUT_WINDOW_ACCUM_RED_SIZE: int
GLUT_WINDOW_ALPHA_SIZE: int
GLUT_WINDOW_BLUE_SIZE: int
GLUT_WINDOW_BORDER_WIDTH: int
GLUT_WINDOW_BUFFER_SIZE: int
GLUT_WINDOW_COLORMAP_SIZE: int
GLUT_WINDOW_CURSOR: int
GLUT_WINDOW_DEPTH_SIZE: int
GLUT_WINDOW_DOUBLEBUFFER: int
GLUT_WINDOW_FORMAT_ID: int
GLUT_WINDOW_GREEN_SIZE: int
GLUT_WINDOW_HEADER_HEIGHT: int
GLUT_WINDOW_HEIGHT: int
GLUT_WINDOW_NUM_CHILDREN: int
GLUT_WINDOW_NUM_SAMPLES: int
GLUT_WINDOW_PARENT: int
GLUT_WINDOW_RED_SIZE: int
GLUT_WINDOW_RGBA: int
GLUT_WINDOW_STENCIL_SIZE: int
GLUT_WINDOW_STEREO: int
GLUT_WINDOW_WIDTH: int
GLUT_WINDOW_X: int
GLUT_WINDOW_Y: int
GLUT_XLIB_IMPLEMENTATION: int

def fgDeinitialize(deinitializeGLUT: int) -> None: ...
def glutAddMenuEntry(label: bytes | str, value: int) -> None: ...
def glutAddSubMenu(label: bytes | str, subMenu: int) -> None: ...
def glutAttachMenu(button: int) -> None: ...
def glutBitmapCharacter(font: Any, character: int) -> None: ...
def glutBitmapHeight(font: Any) -> int: ...
def glutBitmapLength(font: Any, string: Any) -> int: ...
def glutBitmapString(font: Any, string: bytes | str) -> None: ...
def glutBitmapWidth(font: Any, character: int) -> int: ...
def glutButtonBoxFunc(function: Callable[..., Any] | None) -> Any: ...
def glutChangeToMenuEntry(item: int, label: bytes | str, value: int) -> None: ...
def glutChangeToSubMenu(item: int, label: bytes | str, value: int) -> None: ...
def glutCheckLoop() -> Any: ...
def glutCloseFunc(function: Callable[..., Any] | None) -> Any: ...
def glutCopyColormap(window: int) -> None: ...
def glutCreateMenu(function: Callable[..., Any] | None) -> int: ...
def glutCreateSubWindow(window: int, x: int, y: int, width: int, height: int) -> int: ...
def glutCreateWindow(title: bytes | str) -> int: ...
def glutDestroyMenu(menu: int) -> Any: ...
def glutDestroyWindow(window: int) -> Any: ...
def glutDetachMenu(button: int) -> None: ...
def glutDeviceGet(query: int) -> int: ...
def glutDialsFunc(function: Callable[..., Any] | None) -> Any: ...
def glutDisplayFunc(function: Callable[..., Any] | None) -> Any: ...
def glutEnterGameMode() -> int: ...
def glutEntryFunc(function: Callable[..., Any] | None) -> Any: ...
def glutEstablishOverlay() -> None: ...
def glutExtensionSupported(extension: bytes | str) -> int: ...
def glutForceJoystickFunc() -> None: ...
def glutFullScreen() -> None: ...
def glutFullScreenToggle() -> None: ...
def glutGameModeGet(query: int) -> int: ...
def glutGameModeString(string: bytes | str) -> None: ...
def glutGet(query: int) -> int: ...
def glutGetColor(color: int, component: int) -> float: ...
def glutGetMenu() -> int: ...
def glutGetMenuData() -> Any: ...
def glutGetModeValues(mode: int, size: Any) -> Any: ...
def glutGetModifiers() -> int: ...
def glutGetProcAddress(procName: bytes | str) -> Any: ...
def glutGetWindow() -> int: ...
def glutGetWindowData() -> Any: ...
def glutHideOverlay() -> None: ...
def glutHideWindow() -> None: ...
def glutIconifyWindow() -> None: ...
def glutIdleFunc(function: Callable[..., Any] | None) -> Any: ...
def glutIgnoreKeyRepeat(ignore: int) -> None: ...
def glutInit(*args: Any) -> Sequence[Any]: ...
def glutInitContextFlags(flags: int) -> None: ...
def glutInitContextProfile(profile: int) -> None: ...
def glutInitContextVersion(majorVersion: int, minorVersion: int) -> None: ...
def glutInitDisplayMode(displayMode: int) -> None: ...
def glutInitDisplayString(displayMode: bytes | str) -> None: ...
def glutInitWindowPosition(x: int, y: int) -> None: ...
def glutInitWindowSize(width: int, height: int) -> None: ...
def glutJoystickFunc(function: Callable[..., Any] | None) -> Any: ...
def glutKeyboardFunc(function: Callable[..., Any] | None) -> Any: ...
def glutKeyboardUpFunc(function: Callable[..., Any] | None) -> Any: ...
def glutLayerGet(query: int) -> int: ...
def glutLeaveGameMode() -> None: ...
def glutLeaveMainLoop() -> None: ...
def glutMainLoop() -> None: ...
def glutMainLoopEvent() -> None: ...
def glutMenuDestroyFunc(function: Callable[..., Any] | None) -> Any: ...
def glutMenuStateFunc(function: Callable[..., Any] | None) -> Any: ...
def glutMenuStatusFunc(function: Callable[..., Any] | None) -> Any: ...
def glutMotionFunc(function: Callable[..., Any] | None) -> Any: ...
def glutMouseFunc(function: Callable[..., Any] | None) -> Any: ...
def glutMouseWheelFunc(function: Callable[..., Any] | None) -> Any: ...
def glutOverlayDisplayFunc(function: Callable[..., Any] | None) -> Any: ...
def glutPassiveMotionFunc(function: Callable[..., Any] | None) -> Any: ...
def glutPopWindow() -> None: ...
def glutPositionWindow(x: int, y: int) -> None: ...
def glutPostOverlayRedisplay() -> None: ...
def glutPostRedisplay() -> None: ...
def glutPostWindowOverlayRedisplay(window: int) -> None: ...
def glutPostWindowRedisplay(window: int) -> None: ...
def glutPushWindow() -> None: ...
def glutRemoveMenuItem(item: int) -> None: ...
def glutRemoveOverlay() -> None: ...
def glutReportErrors() -> None: ...
def glutReshapeFunc(function: Callable[..., Any] | None) -> Any: ...
def glutReshapeWindow(width: int, height: int) -> None: ...
def glutSetColor(color: int, red: float, green: float, blue: float) -> None: ...
def glutSetCursor(cursor: int) -> None: ...
def glutSetIconTitle(title: bytes | str) -> None: ...
def glutSetKeyRepeat(repeatMode: int) -> None: ...
def glutSetMenu(menu: int) -> None: ...
def glutSetMenuData(data: Any) -> None: ...
def glutSetOption(option_flag: int, value: int) -> None: ...
def glutSetWindow(window: int) -> None: ...
def glutSetWindowData(data: Any) -> None: ...
def glutSetWindowTitle(title: bytes | str) -> None: ...
def glutSetupVideoResizing() -> None: ...
def glutShowOverlay() -> None: ...
def glutShowWindow() -> None: ...
def glutSolidCone(base: float, height: float, slices: int, stacks: int) -> None: ...
def glutSolidCube(size: float) -> None: ...
def glutSolidCylinder(radius: float, height: float, slices: int, stacks: int) -> None: ...
def glutSolidDodecahedron() -> None: ...
def glutSolidIcosahedron() -> None: ...
def glutSolidOctahedron() -> None: ...
def glutSolidRhombicDodecahedron() -> None: ...
def glutSolidSierpinskiSponge(levels: int, offset: Any, scale: float) -> None: ...
def glutSolidSphere(radius: float, slices: int, stacks: int) -> None: ...
def glutSolidTeapot(size: float) -> None: ...
def glutSolidTetrahedron() -> None: ...
def glutSolidTorus(innerRadius: float, outerRadius: float, sides: int, rings: int) -> None: ...
def glutSpaceballButtonFunc(function: Callable[..., Any] | None) -> Any: ...
def glutSpaceballMotionFunc(function: Callable[..., Any] | None) -> Any: ...
def glutSpaceballRotateFunc(function: Callable[..., Any] | None) -> Any: ...
def glutSpecialFunc(function: Callable[..., Any] | None) -> Any: ...
def glutSpecialUpFunc(function: Callable[..., Any] | None) -> Any: ...
def glutStopVideoResizing() -> None: ...
def glutStrokeCharacter(font: Any, character: int) -> None: ...
def glutStrokeHeight(font: Any) -> float: ...
def glutStrokeLength(font: Any, string: Any) -> int: ...
def glutStrokeString(font: Any, string: bytes | str) -> None: ...
def glutStrokeWidth(font: Any, character: int) -> int: ...
def glutSwapBuffers() -> None: ...
def glutTabletButtonFunc(function: Callable[..., Any] | None) -> Any: ...
def glutTabletMotionFunc(function: Callable[..., Any] | None) -> Any: ...
def glutTimerFunc(milliseconds: int, function: Callable[..., Any] | None, value: int) -> Any: ...
def glutUseLayer(layer: int) -> None: ...
def glutVideoPan(x: int, y: int, width: int, height: int) -> None: ...
def glutVideoResize(x: int, y: int, width: int, height: int) -> None: ...
def glutVideoResizeGet(query: int) -> int: ...
def glutVisibilityFunc(function: Callable[..., Any] | None) -> Any: ...
def glutWMCloseFunc(function: Callable[..., Any] | None) -> Any: ...
def glutWarpPointer(x: int, y: int) -> None: ...
def glutWindowStatusFunc(function: Callable[..., Any] | None) -> Any: ...
def glutWireCone(base: float, height: float, slices: int, stacks: int) -> None: ...
def glutWireCube(size: float) -> None: ...
def glutWireCylinder(radius: float, height: float, slices: int, stacks: int) -> None: ...
def glutWireDodecahedron() -> None: ...
def glutWireIcosahedron() -> None: ...
def glutWireOctahedron() -> None: ...
def glutWireRhombicDodecahedron() -> None: ...
def glutWireSierpinskiSponge(levels: int, offset: Any, scale: float) -> None: ...
def glutWireSphere(radius: float, slices: int, stacks: int) -> None: ...
def glutWireTeapot(size: float) -> None: ...
def glutWireTetrahedron() -> None: ...
def glutWireTorus(innerRadius: float, outerRadius: float, sides: int, rings: int) -> None: ...

def __getattr__(name: str) -> Any: ...
