"""OpenGL.GLX.AMD.gpu_association -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray, UIntArray

from OpenGL.raw.GLX._types import *

GLX_GPU_CLOCK_AMD: int
GLX_GPU_FASTEST_TARGET_GPUS_AMD: int
GLX_GPU_NUM_PIPES_AMD: int
GLX_GPU_NUM_RB_AMD: int
GLX_GPU_NUM_SIMD_AMD: int
GLX_GPU_NUM_SPI_AMD: int
GLX_GPU_OPENGL_VERSION_STRING_AMD: int
GLX_GPU_RAM_AMD: int
GLX_GPU_RENDERER_STRING_AMD: int
GLX_GPU_VENDOR_AMD: int

def glXBlitContextFramebufferAMD(dstCtx: Any, srcX0: int, srcY0: int, srcX1: int, srcY1: int, dstX0: int, dstY0: int, dstX1: int, dstY1: int, mask: int, filter: int) -> None: ...
def glXCreateAssociatedContextAMD(id: int, share_list: Any) -> Any: ...
def glXCreateAssociatedContextAttribsAMD(id: int, share_context: Any, attribList: IntArray) -> Any: ...
def glXDeleteAssociatedContextAMD(ctx: Any) -> int: ...
def glXGetContextGPUIDAMD(ctx: Any) -> int: ...
def glXGetCurrentAssociatedContextAMD() -> Any: ...
def glXGetGPUIDsAMD(maxCount: int, ids: UIntArray) -> int: ...
def glXGetGPUInfoAMD(id: int, property: int, dataType: int, size: int, data: AnyArray) -> int: ...
def glXMakeAssociatedContextCurrentAMD(ctx: Any) -> int: ...

def glInitGpuAssociationAMD() -> bool: ...

def __getattr__(name: str) -> Any: ...
