"""OpenGL.WGL.OML.sync_control -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.WGL._types import *

def wglGetMscRateOML(hdc: Any, numerator: AnyArray, denominator: AnyArray) -> int: ...
def wglGetSyncValuesOML(hdc: Any, ust: AnyArray, msc: AnyArray, sbc: AnyArray) -> int: ...
def wglSwapBuffersMscOML(hdc: Any, target_msc: int, divisor: int, remainder: int) -> int: ...
def wglSwapLayerBuffersMscOML(hdc: Any, fuPlanes: int, target_msc: int, divisor: int, remainder: int) -> int: ...
def wglWaitForMscOML(hdc: Any, target_msc: int, divisor: int, remainder: int, ust: AnyArray, msc: AnyArray, sbc: AnyArray) -> int: ...
def wglWaitForSbcOML(hdc: Any, target_sbc: int, ust: AnyArray, msc: AnyArray, sbc: AnyArray) -> int: ...

def glInitSyncControlOML() -> bool: ...

def __getattr__(name: str) -> Any: ...
