"""OpenGL.GLES2.VERSION.GLES2_2_0 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, AnyArrayResult, ByteArray, ByteArrayResult, FloatArray, FloatArrayResult, IntArray, IntArrayResult, UByteArray, UByteArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GLES2._types import *

GL_ACTIVE_ATTRIBUTES: int
GL_ACTIVE_ATTRIBUTE_MAX_LENGTH: int
GL_ACTIVE_TEXTURE: int
GL_ACTIVE_UNIFORMS: int
GL_ACTIVE_UNIFORM_MAX_LENGTH: int
GL_ALIASED_LINE_WIDTH_RANGE: int
GL_ALIASED_POINT_SIZE_RANGE: int
GL_ALPHA: int
GL_ALPHA_BITS: int
GL_ALWAYS: int
GL_ARRAY_BUFFER: int
GL_ARRAY_BUFFER_BINDING: int
GL_ATTACHED_SHADERS: int
GL_BACK: int
GL_BLEND: int
GL_BLEND_COLOR: int
GL_BLEND_DST_ALPHA: int
GL_BLEND_DST_RGB: int
GL_BLEND_EQUATION: int
GL_BLEND_EQUATION_ALPHA: int
GL_BLEND_EQUATION_RGB: int
GL_BLEND_SRC_ALPHA: int
GL_BLEND_SRC_RGB: int
GL_BLUE_BITS: int
GL_BOOL: int
GL_BOOL_VEC2: int
GL_BOOL_VEC3: int
GL_BOOL_VEC4: int
GL_BUFFER_SIZE: int
GL_BUFFER_USAGE: int
GL_BYTE: int
GL_CCW: int
GL_CLAMP_TO_EDGE: int
GL_COLOR_ATTACHMENT0: int
GL_COLOR_BUFFER_BIT: int
GL_COLOR_CLEAR_VALUE: int
GL_COLOR_WRITEMASK: int
GL_COMPILE_STATUS: int
GL_COMPRESSED_TEXTURE_FORMATS: int
GL_CONSTANT_ALPHA: int
GL_CONSTANT_COLOR: int
GL_CULL_FACE: int
GL_CULL_FACE_MODE: int
GL_CURRENT_PROGRAM: int
GL_CURRENT_VERTEX_ATTRIB: int
GL_CW: int
GL_DECR: int
GL_DECR_WRAP: int
GL_DELETE_STATUS: int
GL_DEPTH_ATTACHMENT: int
GL_DEPTH_BITS: int
GL_DEPTH_BUFFER_BIT: int
GL_DEPTH_CLEAR_VALUE: int
GL_DEPTH_COMPONENT: int
GL_DEPTH_COMPONENT16: int
GL_DEPTH_FUNC: int
GL_DEPTH_RANGE: int
GL_DEPTH_TEST: int
GL_DEPTH_WRITEMASK: int
GL_DITHER: int
GL_DONT_CARE: int
GL_DST_ALPHA: int
GL_DST_COLOR: int
GL_DYNAMIC_DRAW: int
GL_ELEMENT_ARRAY_BUFFER: int
GL_ELEMENT_ARRAY_BUFFER_BINDING: int
GL_EQUAL: int
GL_EXTENSIONS: int
GL_FALSE: int
GL_FASTEST: int
GL_FIXED: int
GL_FLOAT: int
GL_FLOAT_MAT2: int
GL_FLOAT_MAT3: int
GL_FLOAT_MAT4: int
GL_FLOAT_VEC2: int
GL_FLOAT_VEC3: int
GL_FLOAT_VEC4: int
GL_FRAGMENT_SHADER: int
GL_FRAMEBUFFER: int
GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME: int
GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE: int
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE: int
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL: int
GL_FRAMEBUFFER_BINDING: int
GL_FRAMEBUFFER_COMPLETE: int
GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT: int
GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS: int
GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: int
GL_FRAMEBUFFER_UNSUPPORTED: int
GL_FRONT: int
GL_FRONT_AND_BACK: int
GL_FRONT_FACE: int
GL_FUNC_ADD: int
GL_FUNC_REVERSE_SUBTRACT: int
GL_FUNC_SUBTRACT: int
GL_GENERATE_MIPMAP_HINT: int
GL_GEQUAL: int
GL_GREATER: int
GL_GREEN_BITS: int
GL_HIGH_FLOAT: int
GL_HIGH_INT: int
GL_IMPLEMENTATION_COLOR_READ_FORMAT: int
GL_IMPLEMENTATION_COLOR_READ_TYPE: int
GL_INCR: int
GL_INCR_WRAP: int
GL_INFO_LOG_LENGTH: int
GL_INT: int
GL_INT_VEC2: int
GL_INT_VEC3: int
GL_INT_VEC4: int
GL_INVALID_ENUM: int
GL_INVALID_FRAMEBUFFER_OPERATION: int
GL_INVALID_OPERATION: int
GL_INVALID_VALUE: int
GL_INVERT: int
GL_KEEP: int
GL_LEQUAL: int
GL_LESS: int
GL_LINEAR: int
GL_LINEAR_MIPMAP_LINEAR: int
GL_LINEAR_MIPMAP_NEAREST: int
GL_LINES: int
GL_LINE_LOOP: int
GL_LINE_STRIP: int
GL_LINE_WIDTH: int
GL_LINK_STATUS: int
GL_LOW_FLOAT: int
GL_LOW_INT: int
GL_LUMINANCE: int
GL_LUMINANCE_ALPHA: int
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS: int
GL_MAX_CUBE_MAP_TEXTURE_SIZE: int
GL_MAX_FRAGMENT_UNIFORM_VECTORS: int
GL_MAX_RENDERBUFFER_SIZE: int
GL_MAX_TEXTURE_IMAGE_UNITS: int
GL_MAX_TEXTURE_SIZE: int
GL_MAX_VARYING_VECTORS: int
GL_MAX_VERTEX_ATTRIBS: int
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS: int
GL_MAX_VERTEX_UNIFORM_VECTORS: int
GL_MAX_VIEWPORT_DIMS: int
GL_MEDIUM_FLOAT: int
GL_MEDIUM_INT: int
GL_MIRRORED_REPEAT: int
GL_NEAREST: int
GL_NEAREST_MIPMAP_LINEAR: int
GL_NEAREST_MIPMAP_NEAREST: int
GL_NEVER: int
GL_NICEST: int
GL_NONE: int
GL_NOTEQUAL: int
GL_NO_ERROR: int
GL_NUM_COMPRESSED_TEXTURE_FORMATS: int
GL_NUM_SHADER_BINARY_FORMATS: int
GL_ONE: int
GL_ONE_MINUS_CONSTANT_ALPHA: int
GL_ONE_MINUS_CONSTANT_COLOR: int
GL_ONE_MINUS_DST_ALPHA: int
GL_ONE_MINUS_DST_COLOR: int
GL_ONE_MINUS_SRC_ALPHA: int
GL_ONE_MINUS_SRC_COLOR: int
GL_OUT_OF_MEMORY: int
GL_PACK_ALIGNMENT: int
GL_POINTS: int
GL_POLYGON_OFFSET_FACTOR: int
GL_POLYGON_OFFSET_FILL: int
GL_POLYGON_OFFSET_UNITS: int
GL_RED_BITS: int
GL_RENDERBUFFER: int
GL_RENDERBUFFER_ALPHA_SIZE: int
GL_RENDERBUFFER_BINDING: int
GL_RENDERBUFFER_BLUE_SIZE: int
GL_RENDERBUFFER_DEPTH_SIZE: int
GL_RENDERBUFFER_GREEN_SIZE: int
GL_RENDERBUFFER_HEIGHT: int
GL_RENDERBUFFER_INTERNAL_FORMAT: int
GL_RENDERBUFFER_RED_SIZE: int
GL_RENDERBUFFER_STENCIL_SIZE: int
GL_RENDERBUFFER_WIDTH: int
GL_RENDERER: int
GL_REPEAT: int
GL_REPLACE: int
GL_RGB: int
GL_RGB565: int
GL_RGB5_A1: int
GL_RGBA: int
GL_RGBA4: int
GL_SAMPLER_2D: int
GL_SAMPLER_CUBE: int
GL_SAMPLES: int
GL_SAMPLE_ALPHA_TO_COVERAGE: int
GL_SAMPLE_BUFFERS: int
GL_SAMPLE_COVERAGE: int
GL_SAMPLE_COVERAGE_INVERT: int
GL_SAMPLE_COVERAGE_VALUE: int
GL_SCISSOR_BOX: int
GL_SCISSOR_TEST: int
GL_SHADER_BINARY_FORMATS: int
GL_SHADER_COMPILER: int
GL_SHADER_SOURCE_LENGTH: int
GL_SHADER_TYPE: int
GL_SHADING_LANGUAGE_VERSION: int
GL_SHORT: int
GL_SRC_ALPHA: int
GL_SRC_ALPHA_SATURATE: int
GL_SRC_COLOR: int
GL_STATIC_DRAW: int
GL_STENCIL_ATTACHMENT: int
GL_STENCIL_BACK_FAIL: int
GL_STENCIL_BACK_FUNC: int
GL_STENCIL_BACK_PASS_DEPTH_FAIL: int
GL_STENCIL_BACK_PASS_DEPTH_PASS: int
GL_STENCIL_BACK_REF: int
GL_STENCIL_BACK_VALUE_MASK: int
GL_STENCIL_BACK_WRITEMASK: int
GL_STENCIL_BITS: int
GL_STENCIL_BUFFER_BIT: int
GL_STENCIL_CLEAR_VALUE: int
GL_STENCIL_FAIL: int
GL_STENCIL_FUNC: int
GL_STENCIL_INDEX8: int
GL_STENCIL_PASS_DEPTH_FAIL: int
GL_STENCIL_PASS_DEPTH_PASS: int
GL_STENCIL_REF: int
GL_STENCIL_TEST: int
GL_STENCIL_VALUE_MASK: int
GL_STENCIL_WRITEMASK: int
GL_STREAM_DRAW: int
GL_SUBPIXEL_BITS: int
GL_TEXTURE: int
GL_TEXTURE0: int
GL_TEXTURE1: int
GL_TEXTURE10: int
GL_TEXTURE11: int
GL_TEXTURE12: int
GL_TEXTURE13: int
GL_TEXTURE14: int
GL_TEXTURE15: int
GL_TEXTURE16: int
GL_TEXTURE17: int
GL_TEXTURE18: int
GL_TEXTURE19: int
GL_TEXTURE2: int
GL_TEXTURE20: int
GL_TEXTURE21: int
GL_TEXTURE22: int
GL_TEXTURE23: int
GL_TEXTURE24: int
GL_TEXTURE25: int
GL_TEXTURE26: int
GL_TEXTURE27: int
GL_TEXTURE28: int
GL_TEXTURE29: int
GL_TEXTURE3: int
GL_TEXTURE30: int
GL_TEXTURE31: int
GL_TEXTURE4: int
GL_TEXTURE5: int
GL_TEXTURE6: int
GL_TEXTURE7: int
GL_TEXTURE8: int
GL_TEXTURE9: int
GL_TEXTURE_2D: int
GL_TEXTURE_BINDING_2D: int
GL_TEXTURE_BINDING_CUBE_MAP: int
GL_TEXTURE_CUBE_MAP: int
GL_TEXTURE_CUBE_MAP_NEGATIVE_X: int
GL_TEXTURE_CUBE_MAP_NEGATIVE_Y: int
GL_TEXTURE_CUBE_MAP_NEGATIVE_Z: int
GL_TEXTURE_CUBE_MAP_POSITIVE_X: int
GL_TEXTURE_CUBE_MAP_POSITIVE_Y: int
GL_TEXTURE_CUBE_MAP_POSITIVE_Z: int
GL_TEXTURE_MAG_FILTER: int
GL_TEXTURE_MIN_FILTER: int
GL_TEXTURE_WRAP_S: int
GL_TEXTURE_WRAP_T: int
GL_TRIANGLES: int
GL_TRIANGLE_FAN: int
GL_TRIANGLE_STRIP: int
GL_TRUE: int
GL_UNPACK_ALIGNMENT: int
GL_UNSIGNED_BYTE: int
GL_UNSIGNED_INT: int
GL_UNSIGNED_SHORT: int
GL_UNSIGNED_SHORT_4_4_4_4: int
GL_UNSIGNED_SHORT_5_5_5_1: int
GL_UNSIGNED_SHORT_5_6_5: int
GL_VALIDATE_STATUS: int
GL_VENDOR: int
GL_VERSION: int
GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING: int
GL_VERTEX_ATTRIB_ARRAY_ENABLED: int
GL_VERTEX_ATTRIB_ARRAY_NORMALIZED: int
GL_VERTEX_ATTRIB_ARRAY_POINTER: int
GL_VERTEX_ATTRIB_ARRAY_SIZE: int
GL_VERTEX_ATTRIB_ARRAY_STRIDE: int
GL_VERTEX_ATTRIB_ARRAY_TYPE: int
GL_VERTEX_SHADER: int
GL_VIEWPORT: int
GL_ZERO: int

def glActiveTexture(texture: int) -> None: ...
def glAttachShader(program: int, shader: int) -> None: ...
def glBindAttribLocation(program: int, index: int, name: ByteArray) -> None: ...
def glBindBuffer(target: int, buffer: int) -> None: ...
def glBindFramebuffer(target: int, framebuffer: int) -> None: ...
def glBindRenderbuffer(target: int, renderbuffer: int) -> None: ...
def glBindTexture(target: int, texture: int) -> None: ...
def glBlendColor(red: float, green: float, blue: float, alpha: float) -> None: ...
def glBlendEquation(mode: int) -> None: ...
def glBlendEquationSeparate(modeRGB: int, modeAlpha: int) -> None: ...
def glBlendFunc(sfactor: int, dfactor: int) -> None: ...
def glBlendFuncSeparate(sfactorRGB: int, dfactorRGB: int, sfactorAlpha: int, dfactorAlpha: int) -> None: ...
def glBufferData(target: int, size: int, data: AnyArray, usage: int) -> None: ...
def glBufferSubData(target: int, offset: int, size: int, data: AnyArray) -> None: ...
def glCheckFramebufferStatus(target: int) -> int: ...
def glClear(mask: int) -> None: ...
def glClearColor(red: float, green: float, blue: float, alpha: float) -> None: ...
def glClearDepthf(d: float) -> None: ...
def glClearStencil(s: int) -> None: ...
def glColorMask(red: bool, green: bool, blue: bool, alpha: bool) -> None: ...
def glCompileShader(shader: int) -> None: ...
def glCompressedTexImage2D(target: int, level: int, internalformat: int, width: int, height: int, border: int, imageSize: int, data: AnyArray) -> None: ...
def glCompressedTexSubImage2D(target: int, level: int, xoffset: int, yoffset: int, width: int, height: int, format: int, imageSize: int, data: AnyArray) -> None: ...
def glCopyTexImage2D(target: int, level: int, internalformat: int, x: int, y: int, width: int, height: int, border: int) -> None: ...
def glCopyTexSubImage2D(target: int, level: int, xoffset: int, yoffset: int, x: int, y: int, width: int, height: int) -> None: ...
def glCreateProgram() -> int: ...
def glCreateShader(type: int) -> int: ...
def glCullFace(mode: int) -> None: ...
def glDeleteBuffers(n: int, buffers: UIntArray) -> None: ...
def glDeleteFramebuffers(n: int, framebuffers: UIntArray) -> None: ...
def glDeleteProgram(program: int) -> None: ...
def glDeleteRenderbuffers(n: int, renderbuffers: UIntArray) -> None: ...
def glDeleteShader(shader: int) -> None: ...
def glDeleteTextures(n: int, textures: UIntArray) -> None: ...
def glDepthFunc(func: int) -> None: ...
def glDepthMask(flag: bool) -> None: ...
def glDepthRangef(n: float, f: float) -> None: ...
def glDetachShader(program: int, shader: int) -> None: ...
def glDisable(cap: int) -> None: ...
def glDisableVertexAttribArray(index: int) -> None: ...
def glDrawArrays(mode: int, first: int, count: int) -> None: ...
def glDrawElements(mode: int, count: int, type: int, indices: AnyArray) -> None: ...
def glEnable(cap: int) -> None: ...
def glEnableVertexAttribArray(index: int) -> None: ...
def glFinish() -> None: ...
def glFlush() -> None: ...
def glFramebufferRenderbuffer(target: int, attachment: int, renderbuffertarget: int, renderbuffer: int) -> None: ...
def glFramebufferTexture2D(target: int, attachment: int, textarget: int, texture: int, level: int) -> None: ...
def glFrontFace(mode: int) -> None: ...
def glGenBuffers(n: int, buffers: UIntArray | None = None) -> UIntArrayResult: ...
def glGenFramebuffers(n: int, framebuffers: UIntArray | None = None) -> UIntArrayResult: ...
def glGenRenderbuffers(n: int, renderbuffers: UIntArray | None = None) -> UIntArrayResult: ...
def glGenTextures(n: int, textures: UIntArray | None = None) -> UIntArrayResult: ...
def glGenerateMipmap(target: int) -> None: ...
def glGetActiveAttrib(program: int, index: int, bufSize: int, length: IntArray | None = None, size: IntArray | None = None, type: UIntArray | None = None, name: ByteArray | None = None) -> tuple[IntArrayResult, ByteArrayResult, IntArrayResult, UIntArrayResult]: ...
def glGetActiveUniform(program: int, index: int, bufSize: int, length: IntArray | None = None, size: IntArray | None = None, type: UIntArray | None = None, name: ByteArray | None = None) -> tuple[IntArrayResult, ByteArrayResult, IntArrayResult, UIntArrayResult]: ...
def glGetAttachedShaders(program: int, maxCount: int, count: IntArray, shaders: UIntArray) -> IntArrayResult: ...
def glGetAttribLocation(program: int, name: ByteArray) -> int: ...
def glGetBooleanv(pname: int, data: UByteArray | None = None) -> UByteArrayResult: ...
def glGetBufferParameteriv(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetError() -> int: ...
def glGetFloatv(pname: int, data: FloatArray | None = None) -> FloatArrayResult: ...
def glGetFramebufferAttachmentParameteriv(target: int, attachment: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetIntegerv(pname: int, data: IntArray | None = None) -> IntArrayResult: ...
def glGetProgramInfoLog(program: int, bufSize: int, length: IntArray | None = None, infoLog: ByteArray | None = None) -> tuple[ByteArrayResult, IntArrayResult]: ...
def glGetProgramiv(program: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetRenderbufferParameteriv(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetShaderInfoLog(shader: int, bufSize: int, length: IntArray | None = None, infoLog: ByteArray | None = None) -> tuple[ByteArrayResult, IntArrayResult]: ...
def glGetShaderPrecisionFormat(shadertype: int, precisiontype: int, range: IntArray | None = None, precision: IntArray | None = None) -> tuple[IntArrayResult, IntArrayResult]: ...
def glGetShaderSource(shader: int, bufSize: int, length: IntArray | None = None, source: ByteArray | None = None) -> tuple[IntArrayResult, ByteArrayResult]: ...
def glGetShaderiv(shader: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetString(name: int) -> bytes: ...
def glGetTexParameterfv(target: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetTexParameteriv(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetUniformLocation(program: int, name: ByteArray) -> int: ...
def glGetUniformfv(program: int, location: int, params: FloatArray) -> None: ...
def glGetUniformiv(program: int, location: int, params: IntArray) -> None: ...
def glGetVertexAttribPointerv(index: int, pname: int, pointer: AnyArray | None = None) -> AnyArrayResult: ...
def glGetVertexAttribfv(index: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetVertexAttribiv(index: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glHint(target: int, mode: int) -> None: ...
def glIsBuffer(buffer: int) -> int: ...
def glIsEnabled(cap: int) -> int: ...
def glIsFramebuffer(framebuffer: int) -> int: ...
def glIsProgram(program: int) -> int: ...
def glIsRenderbuffer(renderbuffer: int) -> int: ...
def glIsShader(shader: int) -> int: ...
def glIsTexture(texture: int) -> int: ...
def glLineWidth(width: float) -> None: ...
def glLinkProgram(program: int) -> None: ...
def glPixelStorei(pname: int, param: int) -> None: ...
def glPolygonOffset(factor: float, units: float) -> None: ...
def glReadPixels(x: int, y: int, width: int, height: int, format: int, type: int, pixels: AnyArray | None = None) -> AnyArrayResult: ...
def glReleaseShaderCompiler() -> None: ...
def glRenderbufferStorage(target: int, internalformat: int, width: int, height: int) -> None: ...
def glSampleCoverage(value: float, invert: bool) -> None: ...
def glScissor(x: int, y: int, width: int, height: int) -> None: ...
def glShaderBinary(count: int, shaders: UIntArray, binaryFormat: int, binary: AnyArray, length: int) -> None: ...
def glShaderSource(shader: Any, string: Any) -> None: ...
def glStencilFunc(func: int, ref: int, mask: int) -> None: ...
def glStencilFuncSeparate(face: int, func: int, ref: int, mask: int) -> None: ...
def glStencilMask(mask: int) -> None: ...
def glStencilMaskSeparate(face: int, mask: int) -> None: ...
def glStencilOp(fail: int, zfail: int, zpass: int) -> None: ...
def glStencilOpSeparate(face: int, sfail: int, dpfail: int, dppass: int) -> None: ...
def glTexImage2D(target: int, level: int, internalformat: int, width: int, height: int, border: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glTexParameterf(target: int, pname: int, param: float) -> None: ...
def glTexParameterfv(target: int, pname: int, params: FloatArray) -> None: ...
def glTexParameteri(target: int, pname: int, param: int) -> None: ...
def glTexParameteriv(target: int, pname: int, params: IntArray) -> None: ...
def glTexSubImage2D(target: int, level: int, xoffset: int, yoffset: int, width: int, height: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glUniform1f(location: int, v0: float) -> None: ...
def glUniform1fv(location: int, count: int, value: FloatArray) -> None: ...
def glUniform1i(location: int, v0: int) -> None: ...
def glUniform1iv(location: int, count: int, value: IntArray) -> None: ...
def glUniform2f(location: int, v0: float, v1: float) -> None: ...
def glUniform2fv(location: int, count: int, value: FloatArray) -> None: ...
def glUniform2i(location: int, v0: int, v1: int) -> None: ...
def glUniform2iv(location: int, count: int, value: IntArray) -> None: ...
def glUniform3f(location: int, v0: float, v1: float, v2: float) -> None: ...
def glUniform3fv(location: int, count: int, value: FloatArray) -> None: ...
def glUniform3i(location: int, v0: int, v1: int, v2: int) -> None: ...
def glUniform3iv(location: int, count: int, value: IntArray) -> None: ...
def glUniform4f(location: int, v0: float, v1: float, v2: float, v3: float) -> None: ...
def glUniform4fv(location: int, count: int, value: FloatArray) -> None: ...
def glUniform4i(location: int, v0: int, v1: int, v2: int, v3: int) -> None: ...
def glUniform4iv(location: int, count: int, value: IntArray) -> None: ...
def glUniformMatrix2fv(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUniformMatrix3fv(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUniformMatrix4fv(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUseProgram(program: int) -> None: ...
def glValidateProgram(program: int) -> None: ...
def glVertexAttrib1f(index: int, x: float) -> None: ...
def glVertexAttrib1fv(index: int, v: FloatArray) -> None: ...
def glVertexAttrib2f(index: int, x: float, y: float) -> None: ...
def glVertexAttrib2fv(index: int, v: FloatArray) -> None: ...
def glVertexAttrib3f(index: int, x: float, y: float, z: float) -> None: ...
def glVertexAttrib3fv(index: int, v: FloatArray) -> None: ...
def glVertexAttrib4f(index: int, x: float, y: float, z: float, w: float) -> None: ...
def glVertexAttrib4fv(index: int, v: FloatArray) -> None: ...
def glVertexAttribPointer(index: int, size: int, type: int, normalized: bool, stride: int, pointer: AnyArray) -> None: ...
def glViewport(x: int, y: int, width: int, height: int) -> None: ...

def glInitGles220VERSION() -> bool: ...
conv: Any

def __getattr__(name: str) -> Any: ...
