'''OpenGL extension AMD.pinned_memory

Automatically generated by the get_gl_extensions script, do not edit!
'''
from OpenGL import platform, constants, constant, arrays
from OpenGL import extensions
from OpenGL.GL import glget
import ctypes
EXTENSION_NAME = 'GL_AMD_pinned_memory'
_DEPRECATED = False
GL_EXTERNAL_VIRTUAL_MEMORY_BUFFER_AMD = constant.Constant( 'GL_EXTERNAL_VIRTUAL_MEMORY_BUFFER_AMD', 0x9160 )


def glInitPinnedMemoryAMD():
    '''Return boolean indicating whether this extension is available'''
    return extensions.hasGLExtension( EXTENSION_NAME )
