'''OpenGL extension AMD.transform_feedback3_lines_triangles

Automatically generated by the get_gl_extensions script, do not edit!
'''
from OpenGL import platform, constants, constant, arrays
from OpenGL import extensions
from OpenGL.GL import glget
import ctypes
EXTENSION_NAME = 'GL_AMD_transform_feedback3_lines_triangles'
_DEPRECATED = False



def glInitTransformFeedback3LinesTrianglesAMD():
    '''Return boolean indicating whether this extension is available'''
    return extensions.hasGLExtension( EXTENSION_NAME )
