"""OpenGL.EGL.MESA.query_driver -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.EGL._types import *

def eglGetDisplayDriverConfig(dpy: Any) -> bytes: ...
def eglGetDisplayDriverName(dpy: Any) -> bytes: ...

def eglInitQueryDriverMESA(*args: Any, **named: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
