'''OpenGL extension IBM.texture_mirrored_repeat

Automatically generated by the get_gl_extensions script, do not edit!
'''
from OpenGL import platform as _p
EXTENSION_NAME = 'GL_IBM_texture_mirrored_repeat'
_p.unpack_constants( """GL_MIRRORED_REPEAT_IBM 0x8370""", globals())


def glInitTextureMirroredRepeatIBM():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
