"""OpenGL.GLES2.EXT.base_instance -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.GLES2._types import *

def glDrawArraysInstancedBaseInstanceEXT(mode: int, first: int, count: int, instancecount: int, baseinstance: int) -> None: ...
def glDrawElementsInstancedBaseInstanceEXT(mode: int, count: int, type: int, indices: AnyArray, instancecount: int, baseinstance: int) -> None: ...
def glDrawElementsInstancedBaseVertexBaseInstanceEXT(mode: int, count: int, type: int, indices: AnyArray, instancecount: int, basevertex: int, baseinstance: int) -> None: ...

def glInitBaseInstanceEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
