"""OpenGL.GLES2.EXT.debug_marker -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import ByteArray

from OpenGL.raw.GLES2._types import *

def glInsertEventMarkerEXT(length: int, marker: ByteArray) -> None: ...
def glPopGroupMarkerEXT() -> None: ...
def glPushGroupMarkerEXT(length: int, marker: ByteArray) -> None: ...

def glInitDebugMarkerEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
