"""OpenGL.GLES2.EXT.disjoint_timer_query -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import Int64Array, Int64ArrayResult, IntArray, UInt64Array, UInt64ArrayResult, UIntArray

from OpenGL.raw.GLES2._types import *

GL_CURRENT_QUERY_EXT: int
GL_GPU_DISJOINT_EXT: int
GL_QUERY_COUNTER_BITS_EXT: int
GL_QUERY_RESULT_AVAILABLE_EXT: int
GL_QUERY_RESULT_EXT: int
GL_TIMESTAMP_EXT: int
GL_TIME_ELAPSED_EXT: int

def glBeginQueryEXT(target: int, id: int) -> None: ...
def glDeleteQueriesEXT(n: int, ids: UIntArray) -> None: ...
def glEndQueryEXT(target: int) -> None: ...
def glGenQueriesEXT(n: int, ids: UIntArray) -> None: ...
def glGetInteger64vEXT(pname: int, data: Int64Array) -> None: ...
def glGetQueryObjecti64vEXT(id: int, pname: int, params: Int64Array | None = None) -> Int64ArrayResult: ...
def glGetQueryObjectivEXT(id: int, pname: int, params: IntArray) -> None: ...
def glGetQueryObjectui64vEXT(id: int, pname: int, params: UInt64Array | None = None) -> UInt64ArrayResult: ...
def glGetQueryObjectuivEXT(id: int, pname: int, params: UIntArray) -> None: ...
def glGetQueryivEXT(target: int, pname: int, params: IntArray) -> None: ...
def glIsQueryEXT(id: int) -> int: ...
def glQueryCounterEXT(id: int, target: int) -> None: ...

def glInitDisjointTimerQueryEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
