"""OpenGL.GLES2.EXT.draw_transform_feedback -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GLES2._types import *

def glDrawTransformFeedbackEXT(mode: int, id: int) -> None: ...
def glDrawTransformFeedbackInstancedEXT(mode: int, id: int, instancecount: int) -> None: ...

def glInitDrawTransformFeedbackEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
