"""OpenGL.GLES2.EXT.draw_elements_base_vertex -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray

from OpenGL.raw.GLES2._types import *

def glDrawElementsBaseVertexEXT(mode: int, count: int, type: int, indices: AnyArray, basevertex: int) -> None: ...
def glDrawElementsInstancedBaseVertexEXT(mode: int, count: int, type: int, indices: AnyArray, instancecount: int, basevertex: int) -> None: ...
def glDrawRangeElementsBaseVertexEXT(mode: int, start: int, end: int, count: int, type: int, indices: AnyArray, basevertex: int) -> None: ...
def glMultiDrawElementsBaseVertexEXT(mode: int, count: IntArray, type: int, indices: AnyArray, drawcount: int, basevertex: IntArray) -> None: ...

def glInitDrawElementsBaseVertexEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
