"""OpenGL.GLES2.EXT.draw_buffers -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UIntArray

from OpenGL.raw.GLES2._types import *

GL_COLOR_ATTACHMENT0_EXT: int
GL_COLOR_ATTACHMENT10_EXT: int
GL_COLOR_ATTACHMENT11_EXT: int
GL_COLOR_ATTACHMENT12_EXT: int
GL_COLOR_ATTACHMENT13_EXT: int
GL_COLOR_ATTACHMENT14_EXT: int
GL_COLOR_ATTACHMENT15_EXT: int
GL_COLOR_ATTACHMENT1_EXT: int
GL_COLOR_ATTACHMENT2_EXT: int
GL_COLOR_ATTACHMENT3_EXT: int
GL_COLOR_ATTACHMENT4_EXT: int
GL_COLOR_ATTACHMENT5_EXT: int
GL_COLOR_ATTACHMENT6_EXT: int
GL_COLOR_ATTACHMENT7_EXT: int
GL_COLOR_ATTACHMENT8_EXT: int
GL_COLOR_ATTACHMENT9_EXT: int
GL_DRAW_BUFFER0_EXT: int
GL_DRAW_BUFFER10_EXT: int
GL_DRAW_BUFFER11_EXT: int
GL_DRAW_BUFFER12_EXT: int
GL_DRAW_BUFFER13_EXT: int
GL_DRAW_BUFFER14_EXT: int
GL_DRAW_BUFFER15_EXT: int
GL_DRAW_BUFFER1_EXT: int
GL_DRAW_BUFFER2_EXT: int
GL_DRAW_BUFFER3_EXT: int
GL_DRAW_BUFFER4_EXT: int
GL_DRAW_BUFFER5_EXT: int
GL_DRAW_BUFFER6_EXT: int
GL_DRAW_BUFFER7_EXT: int
GL_DRAW_BUFFER8_EXT: int
GL_DRAW_BUFFER9_EXT: int
GL_MAX_COLOR_ATTACHMENTS_EXT: int
GL_MAX_DRAW_BUFFERS_EXT: int

def glDrawBuffersEXT(n: int, bufs: UIntArray) -> None: ...

def glInitDrawBuffersEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
