"""OpenGL.GLES2.EXT.fragment_shading_rate -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray, UIntArray

from OpenGL.raw.GLES2._types import *

GL_FRAGMENT_SHADING_RATE_ATTACHMENT_WITH_DEFAULT_FRAMEBUFFER_SUPPORTED_EXT: int
GL_FRAGMENT_SHADING_RATE_COMBINER_OP_KEEP_EXT: int
GL_FRAGMENT_SHADING_RATE_COMBINER_OP_MAX_EXT: int
GL_FRAGMENT_SHADING_RATE_COMBINER_OP_MIN_EXT: int
GL_FRAGMENT_SHADING_RATE_COMBINER_OP_MUL_EXT: int
GL_FRAGMENT_SHADING_RATE_COMBINER_OP_REPLACE_EXT: int
GL_FRAGMENT_SHADING_RATE_NON_TRIVIAL_COMBINERS_SUPPORTED_EXT: int
GL_FRAGMENT_SHADING_RATE_WITH_SAMPLE_MASK_SUPPORTED_EXT: int
GL_FRAGMENT_SHADING_RATE_WITH_SHADER_DEPTH_STENCIL_WRITES_SUPPORTED_EXT: int
GL_MAX_FRAGMENT_SHADING_RATE_ATTACHMENT_LAYERS_EXT: int
GL_MAX_FRAGMENT_SHADING_RATE_ATTACHMENT_TEXEL_ASPECT_RATIO_EXT: int
GL_MAX_FRAGMENT_SHADING_RATE_ATTACHMENT_TEXEL_HEIGHT_EXT: int
GL_MAX_FRAGMENT_SHADING_RATE_ATTACHMENT_TEXEL_WIDTH_EXT: int
GL_MIN_FRAGMENT_SHADING_RATE_ATTACHMENT_TEXEL_HEIGHT_EXT: int
GL_MIN_FRAGMENT_SHADING_RATE_ATTACHMENT_TEXEL_WIDTH_EXT: int
GL_SHADING_RATE_1X1_PIXELS_EXT: int
GL_SHADING_RATE_1X2_PIXELS_EXT: int
GL_SHADING_RATE_1X4_PIXELS_EXT: int
GL_SHADING_RATE_2X1_PIXELS_EXT: int
GL_SHADING_RATE_2X2_PIXELS_EXT: int
GL_SHADING_RATE_2X4_PIXELS_EXT: int
GL_SHADING_RATE_4X1_PIXELS_EXT: int
GL_SHADING_RATE_4X2_PIXELS_EXT: int
GL_SHADING_RATE_4X4_PIXELS_EXT: int
GL_SHADING_RATE_ATTACHMENT_EXT: int
GL_SHADING_RATE_EXT: int

def glFramebufferShadingRateEXT(target: int, attachment: int, texture: int, baseLayer: int, numLayers: int, texelWidth: int, texelHeight: int) -> None: ...
def glGetFragmentShadingRatesEXT(samples: int, maxCount: int, count: IntArray, shadingRates: UIntArray) -> None: ...
def glShadingRateCombinerOpsEXT(combinerOp0: int, combinerOp1: int) -> None: ...
def glShadingRateEXT(rate: int) -> None: ...

def glInitFragmentShadingRateEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
