"""OpenGL.GLES2.EXT.geometry_shader -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GLES2._types import *

GL_FIRST_VERTEX_CONVENTION_EXT: int
GL_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT: int
GL_FRAMEBUFFER_DEFAULT_LAYERS_EXT: int
GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT: int
GL_GEOMETRY_LINKED_INPUT_TYPE_EXT: int
GL_GEOMETRY_LINKED_OUTPUT_TYPE_EXT: int
GL_GEOMETRY_LINKED_VERTICES_OUT_EXT: int
GL_GEOMETRY_SHADER_BIT_EXT: int
GL_GEOMETRY_SHADER_EXT: int
GL_GEOMETRY_SHADER_INVOCATIONS_EXT: int
GL_LAST_VERTEX_CONVENTION_EXT: int
GL_LAYER_PROVOKING_VERTEX_EXT: int
GL_LINES_ADJACENCY_EXT: int
GL_LINE_STRIP_ADJACENCY_EXT: int
GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS_EXT: int
GL_MAX_FRAMEBUFFER_LAYERS_EXT: int
GL_MAX_GEOMETRY_ATOMIC_COUNTERS_EXT: int
GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS_EXT: int
GL_MAX_GEOMETRY_IMAGE_UNIFORMS_EXT: int
GL_MAX_GEOMETRY_INPUT_COMPONENTS_EXT: int
GL_MAX_GEOMETRY_OUTPUT_COMPONENTS_EXT: int
GL_MAX_GEOMETRY_OUTPUT_VERTICES_EXT: int
GL_MAX_GEOMETRY_SHADER_INVOCATIONS_EXT: int
GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS_EXT: int
GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT: int
GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT: int
GL_MAX_GEOMETRY_UNIFORM_BLOCKS_EXT: int
GL_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT: int
GL_PRIMITIVES_GENERATED_EXT: int
GL_REFERENCED_BY_GEOMETRY_SHADER_EXT: int
GL_TRIANGLES_ADJACENCY_EXT: int
GL_TRIANGLE_STRIP_ADJACENCY_EXT: int
GL_UNDEFINED_VERTEX_EXT: int

def glFramebufferTextureEXT(target: int, attachment: int, texture: int, level: int) -> None: ...

def glInitGeometryShaderEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
