"""OpenGL.GLES2.EXT.instanced_arrays -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.GLES2._types import *

GL_VERTEX_ATTRIB_ARRAY_DIVISOR_EXT: int

def glDrawArraysInstancedEXT(mode: int, start: int, count: int, primcount: int) -> None: ...
def glDrawElementsInstancedEXT(mode: int, count: int, type: int, indices: AnyArray, primcount: int) -> None: ...
def glVertexAttribDivisorEXT(index: int, divisor: int) -> None: ...

def glInitInstancedArraysEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
