"""OpenGL.GLES2.EXT.occlusion_query_boolean -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray, UIntArray

from OpenGL.raw.GLES2._types import *

GL_ANY_SAMPLES_PASSED_CONSERVATIVE_EXT: int
GL_ANY_SAMPLES_PASSED_EXT: int
GL_CURRENT_QUERY_EXT: int
GL_QUERY_RESULT_AVAILABLE_EXT: int
GL_QUERY_RESULT_EXT: int

def glBeginQueryEXT(target: int, id: int) -> None: ...
def glDeleteQueriesEXT(n: int, ids: UIntArray) -> None: ...
def glEndQueryEXT(target: int) -> None: ...
def glGenQueriesEXT(n: int, ids: UIntArray) -> None: ...
def glGetQueryObjectuivEXT(id: int, pname: int, params: UIntArray) -> None: ...
def glGetQueryivEXT(target: int, pname: int, params: IntArray) -> None: ...
def glIsQueryEXT(id: int) -> int: ...

def glInitOcclusionQueryBooleanEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
