"""OpenGL.GLES2.EXT.separate_shader_objects -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, ByteArray, FloatArray, IntArray, UIntArray

from OpenGL.raw.GLES2._types import *

GL_ACTIVE_PROGRAM_EXT: int
GL_ALL_SHADER_BITS_EXT: int
GL_FRAGMENT_SHADER_BIT_EXT: int
GL_PROGRAM_PIPELINE_BINDING_EXT: int
GL_PROGRAM_SEPARABLE_EXT: int
GL_VERTEX_SHADER_BIT_EXT: int

def glActiveProgramEXT(program: int) -> None: ...
def glActiveShaderProgramEXT(pipeline: int, program: int) -> None: ...
def glBindProgramPipelineEXT(pipeline: int) -> None: ...
def glCreateShaderProgramEXT(type: int, string: ByteArray) -> int: ...
def glCreateShaderProgramvEXT(type: int, count: int, strings: AnyArray) -> int: ...
def glDeleteProgramPipelinesEXT(n: int, pipelines: UIntArray) -> None: ...
def glGenProgramPipelinesEXT(n: int, pipelines: UIntArray) -> None: ...
def glGetProgramPipelineInfoLogEXT(pipeline: int, bufSize: int, length: IntArray, infoLog: ByteArray) -> None: ...
def glGetProgramPipelineivEXT(pipeline: int, pname: int, params: IntArray) -> None: ...
def glIsProgramPipelineEXT(pipeline: int) -> int: ...
def glProgramParameteriEXT(program: int, pname: int, value: int) -> None: ...
def glProgramUniform1fEXT(program: int, location: int, v0: float) -> None: ...
def glProgramUniform1fvEXT(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform1iEXT(program: int, location: int, v0: int) -> None: ...
def glProgramUniform1ivEXT(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform1uiEXT(program: int, location: int, v0: int) -> None: ...
def glProgramUniform1uivEXT(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniform2fEXT(program: int, location: int, v0: float, v1: float) -> None: ...
def glProgramUniform2fvEXT(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform2iEXT(program: int, location: int, v0: int, v1: int) -> None: ...
def glProgramUniform2ivEXT(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform2uiEXT(program: int, location: int, v0: int, v1: int) -> None: ...
def glProgramUniform2uivEXT(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniform3fEXT(program: int, location: int, v0: float, v1: float, v2: float) -> None: ...
def glProgramUniform3fvEXT(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform3iEXT(program: int, location: int, v0: int, v1: int, v2: int) -> None: ...
def glProgramUniform3ivEXT(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform3uiEXT(program: int, location: int, v0: int, v1: int, v2: int) -> None: ...
def glProgramUniform3uivEXT(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniform4fEXT(program: int, location: int, v0: float, v1: float, v2: float, v3: float) -> None: ...
def glProgramUniform4fvEXT(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform4iEXT(program: int, location: int, v0: int, v1: int, v2: int, v3: int) -> None: ...
def glProgramUniform4ivEXT(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform4uiEXT(program: int, location: int, v0: int, v1: int, v2: int, v3: int) -> None: ...
def glProgramUniform4uivEXT(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniformMatrix2fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix2x3fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix2x4fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix3fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix3x2fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix3x4fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix4fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix4x2fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix4x3fvEXT(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUseProgramStagesEXT(pipeline: int, stages: int, program: int) -> None: ...
def glUseShaderProgramEXT(type: int, program: int) -> None: ...
def glValidateProgramPipelineEXT(pipeline: int) -> None: ...

def glInitSeparateShaderObjectsEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
