"""OpenGL.GLES2.EXT.tessellation_shader -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GLES2._types import *

GL_CCW: int
GL_CW: int
GL_EQUAL: int
GL_FRACTIONAL_EVEN_EXT: int
GL_FRACTIONAL_ODD_EXT: int
GL_ISOLINES_EXT: int
GL_IS_PER_PATCH_EXT: int
GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS_EXT: int
GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS_EXT: int
GL_MAX_PATCH_VERTICES_EXT: int
GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS_EXT: int
GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS_EXT: int
GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS_EXT: int
GL_MAX_TESS_CONTROL_INPUT_COMPONENTS_EXT: int
GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS_EXT: int
GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS_EXT: int
GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS_EXT: int
GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS_EXT: int
GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS_EXT: int
GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS_EXT: int
GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS_EXT: int
GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS_EXT: int
GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS_EXT: int
GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS_EXT: int
GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS_EXT: int
GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS_EXT: int
GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS_EXT: int
GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS_EXT: int
GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS_EXT: int
GL_MAX_TESS_GEN_LEVEL_EXT: int
GL_MAX_TESS_PATCH_COMPONENTS_EXT: int
GL_PATCHES_EXT: int
GL_PATCH_VERTICES_EXT: int
GL_PRIMITIVE_RESTART_FOR_PATCHES_SUPPORTED: int
GL_QUADS_EXT: int
GL_REFERENCED_BY_TESS_CONTROL_SHADER_EXT: int
GL_REFERENCED_BY_TESS_EVALUATION_SHADER_EXT: int
GL_TESS_CONTROL_OUTPUT_VERTICES_EXT: int
GL_TESS_CONTROL_SHADER_BIT_EXT: int
GL_TESS_CONTROL_SHADER_EXT: int
GL_TESS_EVALUATION_SHADER_BIT_EXT: int
GL_TESS_EVALUATION_SHADER_EXT: int
GL_TESS_GEN_MODE_EXT: int
GL_TESS_GEN_POINT_MODE_EXT: int
GL_TESS_GEN_SPACING_EXT: int
GL_TESS_GEN_VERTEX_ORDER_EXT: int
GL_TRIANGLES: int

def glPatchParameteriEXT(pname: int, value: int) -> None: ...

def glInitTessellationShaderEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
