"""OpenGL.GLES2.EXT.texture_border_clamp -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray, IntArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GLES2._types import *

GL_CLAMP_TO_BORDER_EXT: int
GL_TEXTURE_BORDER_COLOR_EXT: int

def glGetSamplerParameterIivEXT(sampler: int, pname: int, params: IntArray) -> None: ...
def glGetSamplerParameterIuivEXT(sampler: int, pname: int, params: UIntArray) -> None: ...
def glGetTexParameterIivEXT(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetTexParameterIuivEXT(target: int, pname: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glSamplerParameterIivEXT(sampler: int, pname: int, param: IntArray) -> None: ...
def glSamplerParameterIuivEXT(sampler: int, pname: int, param: UIntArray) -> None: ...
def glTexParameterIivEXT(target: int, pname: int, params: IntArray) -> None: ...
def glTexParameterIuivEXT(target: int, pname: int, params: UIntArray) -> None: ...

def glInitTextureBorderClampEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
