"""OpenGL.GLE -- generated; regenerate with src/regenerate_c.py.

GLE is hand-maintained rather than registry-generated (it is not a Khronos
API), so this is emitted from the declarations in ``OpenGL/raw/GLE`` and
``OpenGL/GLE`` rather than from the registry.
"""

from collections.abc import Callable, Sequence
from typing import Any

from OpenGL.raw.GL._types import *

GLE_TEXTURE_ENABLE: int
GLE_TEXTURE_NORMAL_CYL: int
GLE_TEXTURE_NORMAL_FLAT: int
GLE_TEXTURE_NORMAL_MODEL_CYL: int
GLE_TEXTURE_NORMAL_MODEL_FLAT: int
GLE_TEXTURE_NORMAL_MODEL_SPH: int
GLE_TEXTURE_NORMAL_SPH: int
GLE_TEXTURE_STYLE_MASK: int
GLE_TEXTURE_VERTEX_CYL: int
GLE_TEXTURE_VERTEX_FLAT: int
GLE_TEXTURE_VERTEX_MODEL_CYL: int
GLE_TEXTURE_VERTEX_MODEL_FLAT: int
GLE_TEXTURE_VERTEX_MODEL_SPH: int
GLE_TEXTURE_VERTEX_SPH: int
TUBE_CONTOUR_CLOSED: int
TUBE_JN_ANGLE: int
TUBE_JN_CAP: int
TUBE_JN_CUT: int
TUBE_JN_MASK: int
TUBE_JN_RAW: int
TUBE_JN_ROUND: int
TUBE_NORM_EDGE: int
TUBE_NORM_FACET: int
TUBE_NORM_MASK: int
TUBE_NORM_PATH_EDGE: int
gleAffine: Any
gleDouble: Any

def gleExtrusion(contour: Any, cont_normal: Any, up: Any, point_array: Any, color_array: Any) -> Any: ...
def gleGetJoinStyle() -> int: ...
def gleGetNumSides() -> int: ...
def gleHelicoid(rToroid: Any, startRadius: Any, drdTheta: Any, startZ: Any, dzdTheta: Any, startXform: Any, dXformdTheta: Any, startTheta: Any, sweepTheta: Any) -> Any: ...
def gleLathe(contour: Any, cont_normal: Any, up: Any, startRadius: Any, drdTheta: Any, startZ: Any, dzdTheta: Any, startXform: Any, dXformdTheta: Any, startTheta: Any, sweepTheta: Any) -> Any: ...
def glePolyCone(point_array: Any, color_array: Any, radius_array: Any) -> Any: ...
def glePolyCylinder(point_array: Any, color_array: Any, radius: Any) -> Any: ...
def gleScrew(contour: Any, cont_normal: Any, up: Any, startz: Any, endz: Any, twist: Any) -> Any: ...
def gleSetJoinStyle(style: int) -> None: ...
def gleSetNumSides(slices: int) -> None: ...
def gleSpiral(contour: Any, cont_normal: Any, up: Any, startRadius: Any, drdTheta: Any, startZ: Any, dzdTheta: Any, startXform: Any, dXformdTheta: Any, startTheta: Any, sweepTheta: Any) -> Any: ...
def gleSuperExtrusion(contour: Any, cont_normal: Any, up: Any, point_array: Any, color_array: Any, xform_array: Any) -> Any: ...
def gleTextureMode(mode: int) -> None: ...
def gleToroid(rToroid: Any, startRadius: Any, drdTheta: Any, startZ: Any, dzdTheta: Any, startXform: Any, dXformdTheta: Any, startTheta: Any, sweepTheta: Any) -> Any: ...
def gleTwistExtrusion(contour: Any, cont_normal: Any, up: Any, point_array: Any, color_array: Any, twist_array: Any) -> Any: ...
def rot_about_axis(angle: Any, axis: Any) -> Any: ...
def rot_axis(omega: Any, axis: Any) -> Any: ...
def rot_omega(axis: Any) -> Any: ...
def rot_prince(omega: float, axis: Any) -> None: ...
def urot_about_axis(m: Any, angle: Any, axis: Any) -> Any: ...
def urot_axis(m: Any, omega: Any, axis: Any) -> Any: ...
def urot_omega(m: Any, axis: Any) -> Any: ...
def urot_prince(m: Any, omega: Any, axis: Any) -> Any: ...
def uview_direction(m: Any, v21: Any, up: Any) -> Any: ...
def uviewpoint(m: Any, v1: Any, v2: Any, up: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
