"""OpenGL.GLES2.KHR.texture_compression_astc_hdr -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GLES2._types import *

GL_COMPRESSED_RGBA_ASTC_10x10_KHR: int
GL_COMPRESSED_RGBA_ASTC_10x5_KHR: int
GL_COMPRESSED_RGBA_ASTC_10x6_KHR: int
GL_COMPRESSED_RGBA_ASTC_10x8_KHR: int
GL_COMPRESSED_RGBA_ASTC_12x10_KHR: int
GL_COMPRESSED_RGBA_ASTC_12x12_KHR: int
GL_COMPRESSED_RGBA_ASTC_4x4_KHR: int
GL_COMPRESSED_RGBA_ASTC_5x4_KHR: int
GL_COMPRESSED_RGBA_ASTC_5x5_KHR: int
GL_COMPRESSED_RGBA_ASTC_6x5_KHR: int
GL_COMPRESSED_RGBA_ASTC_6x6_KHR: int
GL_COMPRESSED_RGBA_ASTC_8x5_KHR: int
GL_COMPRESSED_RGBA_ASTC_8x6_KHR: int
GL_COMPRESSED_RGBA_ASTC_8x8_KHR: int
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR: int
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR: int
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR: int
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR: int
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR: int
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR: int
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR: int
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR: int
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR: int
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR: int
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR: int
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR: int
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR: int
GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR: int

def glInitTextureCompressionAstcHdrKHR() -> bool: ...

def __getattr__(name: str) -> Any: ...
