'''Autogenerated by xml_generate script, do not edit!'''
from OpenGL import platform as _p, arrays
from OpenGL.raw.GL import _types as _cs
from OpenGL.constant import Constant as _C

import ctypes
EXTENSION_NAME = 'GL_SGIX_calligraphic_fragment'
def _f( function ):
    return _p.createFunction( function,_p.GL,'GL_SGIX_calligraphic_fragment')
GL_CALLIGRAPHIC_FRAGMENT_SGIX=_C('GL_CALLIGRAPHIC_FRAGMENT_SGIX',0x8183)

