'''Autogenerated by xml_generate script, do not edit!'''
from OpenGL import platform as _p, arrays
from OpenGL.raw.GL import _types as _cs
from OpenGL.constant import Constant as _C

import ctypes
EXTENSION_NAME = 'GL_SGIX_reference_plane'
def _f( function ):
    return _p.createFunction( function,_p.GL,'GL_SGIX_reference_plane')
GL_REFERENCE_PLANE_EQUATION_SGIX=_C('GL_REFERENCE_PLANE_EQUATION_SGIX',0x817E)
GL_REFERENCE_PLANE_SGIX=_C('GL_REFERENCE_PLANE_SGIX',0x817D)
@_f
@_p.types(None,arrays.GLdoubleArray)
def glReferencePlaneSGIX(equation):pass
