"""OpenGL.EGL.EXT.compositor -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray

from OpenGL.raw.EGL._types import *

EGL_COMPOSITOR_DROP_NEWEST_FRAME_EXT: int
EGL_COMPOSITOR_KEEP_NEWEST_FRAME_EXT: int
EGL_EXTERNAL_REF_ID_EXT: int
EGL_PRIMARY_COMPOSITOR_CONTEXT_EXT: int

def eglCompositorBindTexWindowEXT(external_win_id: int) -> int: ...
def eglCompositorSetContextAttributesEXT(external_ref_id: int, context_attributes: IntArray, num_entries: int) -> int: ...
def eglCompositorSetContextListEXT(external_ref_ids: IntArray, num_entries: int) -> int: ...
def eglCompositorSetSizeEXT(external_win_id: int, width: int, height: int) -> int: ...
def eglCompositorSetWindowAttributesEXT(external_win_id: int, window_attributes: IntArray, num_entries: int) -> int: ...
def eglCompositorSetWindowListEXT(external_ref_id: int, external_win_ids: IntArray, num_entries: int) -> int: ...
def eglCompositorSwapPolicyEXT(external_win_id: int, policy: int) -> int: ...

def eglInitCompositorEXT(*args: Any, **named: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
