"""OpenGL.EGL.EXT.device_base -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, Int64Array, IntArray

from OpenGL.raw.EGL._types import *

EGL_BAD_DEVICE_EXT: int
EGL_DEVICE_EXT: int

def eglQueryDeviceAttribEXT(device: Any, attribute: int, value: Int64Array) -> int: ...
def eglQueryDeviceStringEXT(device: Any, name: int) -> bytes: ...
def eglQueryDevicesEXT(max_devices: int, devices: AnyArray, num_devices: IntArray) -> int: ...
def eglQueryDisplayAttribEXT(dpy: Any, attribute: int, value: Int64Array) -> int: ...

def glInitDeviceBaseEXT() -> bool: ...
def egl_get_devices(*args: Any, **named: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
