"""OpenGL.EGL.EXT.image_dma_buf_import -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.EGL._types import *

EGL_DMA_BUF_PLANE0_FD_EXT: int
EGL_DMA_BUF_PLANE0_OFFSET_EXT: int
EGL_DMA_BUF_PLANE0_PITCH_EXT: int
EGL_DMA_BUF_PLANE1_FD_EXT: int
EGL_DMA_BUF_PLANE1_OFFSET_EXT: int
EGL_DMA_BUF_PLANE1_PITCH_EXT: int
EGL_DMA_BUF_PLANE2_FD_EXT: int
EGL_DMA_BUF_PLANE2_OFFSET_EXT: int
EGL_DMA_BUF_PLANE2_PITCH_EXT: int
EGL_ITU_REC2020_EXT: int
EGL_ITU_REC601_EXT: int
EGL_ITU_REC709_EXT: int
EGL_LINUX_DMA_BUF_EXT: int
EGL_LINUX_DRM_FOURCC_EXT: int
EGL_SAMPLE_RANGE_HINT_EXT: int
EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT: int
EGL_YUV_CHROMA_SITING_0_5_EXT: int
EGL_YUV_CHROMA_SITING_0_EXT: int
EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT: int
EGL_YUV_COLOR_SPACE_HINT_EXT: int
EGL_YUV_FULL_RANGE_EXT: int
EGL_YUV_NARROW_RANGE_EXT: int

def glInitImageDmaBufImportEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
