"""OpenGL.EGL.EXT.output_base -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, Int64Array, IntArray

from OpenGL.raw.EGL._types import *

EGL_BAD_OUTPUT_LAYER_EXT: int
EGL_BAD_OUTPUT_PORT_EXT: int
EGL_SWAP_INTERVAL_EXT: int

def eglGetOutputLayersEXT(dpy: Any, attrib_list: Int64Array, layers: AnyArray, max_layers: int, num_layers: IntArray) -> int: ...
def eglGetOutputPortsEXT(dpy: Any, attrib_list: Int64Array, ports: AnyArray, max_ports: int, num_ports: IntArray) -> int: ...
def eglOutputLayerAttribEXT(dpy: Any, layer: Any, attribute: int, value: int) -> int: ...
def eglOutputPortAttribEXT(dpy: Any, port: Any, attribute: int, value: int) -> int: ...
def eglQueryOutputLayerAttribEXT(dpy: Any, layer: Any, attribute: int, value: Int64Array) -> int: ...
def eglQueryOutputLayerStringEXT(dpy: Any, layer: Any, name: int) -> bytes: ...
def eglQueryOutputPortAttribEXT(dpy: Any, port: Any, attribute: int, value: Int64Array) -> int: ...
def eglQueryOutputPortStringEXT(dpy: Any, port: Any, name: int) -> bytes: ...

def glInitOutputBaseEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
