"""OpenGL.EGL.EXT.platform_base -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray

from OpenGL.raw.EGL._types import *

def eglCreatePlatformPixmapSurfaceEXT(dpy: Any, config: Any, native_pixmap: AnyArray, attrib_list: IntArray) -> Any: ...
def eglCreatePlatformWindowSurfaceEXT(dpy: Any, config: Any, native_window: AnyArray, attrib_list: IntArray) -> Any: ...
def eglGetPlatformDisplayEXT(platform: int, native_display: AnyArray, attrib_list: IntArray) -> Any: ...

def glInitPlatformBaseEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
