"""OpenGL.EGL.EXT.surface_compression -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import Int64Array, IntArray

from OpenGL.raw.EGL._types import *

EGL_SURFACE_COMPRESSION_EXT: int
EGL_SURFACE_COMPRESSION_FIXED_RATE_10BPC_EXT: int
EGL_SURFACE_COMPRESSION_FIXED_RATE_11BPC_EXT: int
EGL_SURFACE_COMPRESSION_FIXED_RATE_12BPC_EXT: int
EGL_SURFACE_COMPRESSION_FIXED_RATE_1BPC_EXT: int
EGL_SURFACE_COMPRESSION_FIXED_RATE_2BPC_EXT: int
EGL_SURFACE_COMPRESSION_FIXED_RATE_3BPC_EXT: int
EGL_SURFACE_COMPRESSION_FIXED_RATE_4BPC_EXT: int
EGL_SURFACE_COMPRESSION_FIXED_RATE_5BPC_EXT: int
EGL_SURFACE_COMPRESSION_FIXED_RATE_6BPC_EXT: int
EGL_SURFACE_COMPRESSION_FIXED_RATE_7BPC_EXT: int
EGL_SURFACE_COMPRESSION_FIXED_RATE_8BPC_EXT: int
EGL_SURFACE_COMPRESSION_FIXED_RATE_9BPC_EXT: int
EGL_SURFACE_COMPRESSION_FIXED_RATE_DEFAULT_EXT: int
EGL_SURFACE_COMPRESSION_FIXED_RATE_NONE_EXT: int
EGL_SURFACE_COMPRESSION_PLANE1_EXT: int
EGL_SURFACE_COMPRESSION_PLANE2_EXT: int

def eglQuerySupportedCompressionRatesEXT(dpy: Any, config: Any, attrib_list: Int64Array, rates: IntArray, rate_size: int, num_rates: IntArray) -> int: ...

def eglInitSurfaceCompressionEXT(*args: Any, **named: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
