"""OpenGL.EGL.EXT.yuv_surface -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.EGL._types import *

EGL_YUV_BUFFER_EXT: int
EGL_YUV_CSC_STANDARD_2020_EXT: int
EGL_YUV_CSC_STANDARD_601_EXT: int
EGL_YUV_CSC_STANDARD_709_EXT: int
EGL_YUV_CSC_STANDARD_EXT: int
EGL_YUV_DEPTH_RANGE_EXT: int
EGL_YUV_DEPTH_RANGE_FULL_EXT: int
EGL_YUV_DEPTH_RANGE_LIMITED_EXT: int
EGL_YUV_NUMBER_OF_PLANES_EXT: int
EGL_YUV_ORDER_AYUV_EXT: int
EGL_YUV_ORDER_EXT: int
EGL_YUV_ORDER_UYVY_EXT: int
EGL_YUV_ORDER_VYUY_EXT: int
EGL_YUV_ORDER_YUV_EXT: int
EGL_YUV_ORDER_YUYV_EXT: int
EGL_YUV_ORDER_YVU_EXT: int
EGL_YUV_ORDER_YVYU_EXT: int
EGL_YUV_PLANE_BPP_0_EXT: int
EGL_YUV_PLANE_BPP_10_EXT: int
EGL_YUV_PLANE_BPP_8_EXT: int
EGL_YUV_PLANE_BPP_EXT: int
EGL_YUV_SUBSAMPLE_4_2_0_EXT: int
EGL_YUV_SUBSAMPLE_4_2_2_EXT: int
EGL_YUV_SUBSAMPLE_4_4_4_EXT: int
EGL_YUV_SUBSAMPLE_EXT: int

def glInitYuvSurfaceEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
