"""OpenGL.GLX.EXT.import_context -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray

from OpenGL.raw.GLX._types import *

GLX_SCREEN_EXT: int
GLX_SHARE_CONTEXT_EXT: int
GLX_VISUAL_ID_EXT: int

def glXFreeContextEXT(dpy: AnyArray, context: Any) -> None: ...
def glXGetContextIDEXT(context: Any) -> Any: ...
def glXGetCurrentDisplayEXT() -> bytes: ...
def glXImportContextEXT(dpy: AnyArray, contextID: Any) -> Any: ...
def glXQueryContextInfoEXT(dpy: AnyArray, context: Any, attribute: int, value: IntArray) -> int: ...

def glInitImportContextEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
