# mypy: ignore-errors
# The names in this module arrive from the declaration tables at import
# time, so a checker reading this file sees calls to things it cannot
# find.  The typed surface is the .pyi stub beside the package.
'''OpenGL extension VERSION.GL_1_0

This module customises the behaviour of the 
OpenGL.raw.GL.VERSION.GL_1_0 to provide a more 
Python-friendly API

The official definition of this extension is available here:
http://www.opengl.org/registry/specs/VERSION/GL_1_0.txt
'''
from OpenGL import platform, constant, arrays
from OpenGL import extensions, wrapper
import ctypes
from OpenGL.raw.GL import _types, _glgets
from OpenGL._declarations import define as _define
_EXTENSION_NAME = _define(globals(), 'OpenGL.raw.GL.VERSION.GL_1_0', customise=True)

def glInitGl10VERSION():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( _EXTENSION_NAME )

# INPUT glTexParameterfv.params size not checked against 'pname'
# INPUT glTexParameteriv.params size not checked against 'pname'
# INPUT glTexImage1D.pixels size not checked against 'format,type,width'
# INPUT glTexImage2D.pixels size not checked against 'format,type,width,height'
# OUTPUT glReadPixels.pixels COMPSIZE(format, type, width, height) 
# OUTPUT glGetTexImage.pixels COMPSIZE(target, level, format, type) 
# INPUT glCallLists.lists size not checked against 'n,type'
# INPUT glBitmap.bitmap size not checked against 'width,height'
# INPUT glFogfv.params size not checked against 'pname'
# INPUT glFogiv.params size not checked against 'pname'
# INPUT glLightfv.params size not checked against 'pname'
# INPUT glLightiv.params size not checked against 'pname'
# INPUT glLightModelfv.params size not checked against 'pname'
# INPUT glLightModeliv.params size not checked against 'pname'
# INPUT glMaterialfv.params size not checked against 'pname'
# INPUT glMaterialiv.params size not checked against 'pname'
# INPUT glPolygonStipple.mask size not checked against ''
# INPUT glTexEnvfv.params size not checked against 'pname'
# INPUT glTexEnviv.params size not checked against 'pname'
# INPUT glTexGendv.params size not checked against 'pname'
# INPUT glTexGenfv.params size not checked against 'pname'
# INPUT glTexGeniv.params size not checked against 'pname'
# INPUT glMap1d.points size not checked against 'target,stride,order'
# INPUT glMap1f.points size not checked against 'target,stride,order'
# INPUT glMap2d.points size not checked against 'target,ustride,uorder,vstride,vorder'
# INPUT glMap2f.points size not checked against 'target,ustride,uorder,vstride,vorder'
# INPUT glPixelMapfv.values size not checked against mapsize
# INPUT glPixelMapuiv.values size not checked against mapsize
# INPUT glPixelMapusv.values size not checked against mapsize
# INPUT glDrawPixels.pixels size not checked against 'format,type,width,height'
# OUTPUT glGetMapdv.v COMPSIZE(target, query) 
# OUTPUT glGetMapfv.v COMPSIZE(target, query) 
# OUTPUT glGetMapiv.v COMPSIZE(target, query) 
### END AUTOGENERATED SECTION