"""OpenGL.GL.VERSION.GL_1_0 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, AnyArrayResult, ByteArray, DoubleArray, DoubleArrayResult, FloatArray, FloatArrayResult, IntArray, IntArrayResult, ShortArray, UByteArray, UByteArrayResult, UIntArray, UIntArrayResult, UShortArray, UShortArrayResult

from OpenGL.raw.GL._types import *

GL_2D: int
GL_2_BYTES: int
GL_3D: int
GL_3D_COLOR: int
GL_3D_COLOR_TEXTURE: int
GL_3_BYTES: int
GL_4D_COLOR_TEXTURE: int
GL_4_BYTES: int
GL_ACCUM: int
GL_ACCUM_ALPHA_BITS: int
GL_ACCUM_BLUE_BITS: int
GL_ACCUM_BUFFER_BIT: int
GL_ACCUM_CLEAR_VALUE: int
GL_ACCUM_GREEN_BITS: int
GL_ACCUM_RED_BITS: int
GL_ADD: int
GL_ALL_ATTRIB_BITS: int
GL_ALPHA: int
GL_ALPHA_BIAS: int
GL_ALPHA_BITS: int
GL_ALPHA_SCALE: int
GL_ALPHA_TEST: int
GL_ALPHA_TEST_FUNC: int
GL_ALPHA_TEST_REF: int
GL_ALWAYS: int
GL_AMBIENT: int
GL_AMBIENT_AND_DIFFUSE: int
GL_AND: int
GL_AND_INVERTED: int
GL_AND_REVERSE: int
GL_ATTRIB_STACK_DEPTH: int
GL_AUTO_NORMAL: int
GL_AUX0: int
GL_AUX1: int
GL_AUX2: int
GL_AUX3: int
GL_AUX_BUFFERS: int
GL_BACK: int
GL_BACK_LEFT: int
GL_BACK_RIGHT: int
GL_BITMAP: int
GL_BITMAP_TOKEN: int
GL_BLEND: int
GL_BLEND_DST: int
GL_BLEND_SRC: int
GL_BLUE: int
GL_BLUE_BIAS: int
GL_BLUE_BITS: int
GL_BLUE_SCALE: int
GL_CCW: int
GL_CLAMP: int
GL_CLEAR: int
GL_CLIP_PLANE0: int
GL_CLIP_PLANE1: int
GL_CLIP_PLANE2: int
GL_CLIP_PLANE3: int
GL_CLIP_PLANE4: int
GL_CLIP_PLANE5: int
GL_COEFF: int
GL_COLOR: int
GL_COLOR_BUFFER_BIT: int
GL_COLOR_CLEAR_VALUE: int
GL_COLOR_INDEX: int
GL_COLOR_INDEXES: int
GL_COLOR_MATERIAL: int
GL_COLOR_MATERIAL_FACE: int
GL_COLOR_MATERIAL_PARAMETER: int
GL_COLOR_WRITEMASK: int
GL_COMPILE: int
GL_COMPILE_AND_EXECUTE: int
GL_CONSTANT_ATTENUATION: int
GL_COPY: int
GL_COPY_INVERTED: int
GL_COPY_PIXEL_TOKEN: int
GL_CULL_FACE: int
GL_CULL_FACE_MODE: int
GL_CURRENT_BIT: int
GL_CURRENT_COLOR: int
GL_CURRENT_INDEX: int
GL_CURRENT_NORMAL: int
GL_CURRENT_RASTER_COLOR: int
GL_CURRENT_RASTER_DISTANCE: int
GL_CURRENT_RASTER_INDEX: int
GL_CURRENT_RASTER_POSITION: int
GL_CURRENT_RASTER_POSITION_VALID: int
GL_CURRENT_RASTER_TEXTURE_COORDS: int
GL_CURRENT_TEXTURE_COORDS: int
GL_CW: int
GL_DECAL: int
GL_DECR: int
GL_DEPTH: int
GL_DEPTH_BIAS: int
GL_DEPTH_BITS: int
GL_DEPTH_BUFFER_BIT: int
GL_DEPTH_CLEAR_VALUE: int
GL_DEPTH_COMPONENT: int
GL_DEPTH_FUNC: int
GL_DEPTH_RANGE: int
GL_DEPTH_SCALE: int
GL_DEPTH_TEST: int
GL_DEPTH_WRITEMASK: int
GL_DIFFUSE: int
GL_DITHER: int
GL_DOMAIN: int
GL_DONT_CARE: int
GL_DOUBLEBUFFER: int
GL_DRAW_BUFFER: int
GL_DRAW_PIXEL_TOKEN: int
GL_DST_ALPHA: int
GL_DST_COLOR: int
GL_EDGE_FLAG: int
GL_EMISSION: int
GL_ENABLE_BIT: int
GL_EQUAL: int
GL_EQUIV: int
GL_EVAL_BIT: int
GL_EXP: int
GL_EXP2: int
GL_EXTENSIONS: int
GL_EYE_LINEAR: int
GL_EYE_PLANE: int
GL_FASTEST: int
GL_FEEDBACK: int
GL_FILL: int
GL_FLAT: int
GL_FOG: int
GL_FOG_BIT: int
GL_FOG_COLOR: int
GL_FOG_DENSITY: int
GL_FOG_END: int
GL_FOG_HINT: int
GL_FOG_INDEX: int
GL_FOG_MODE: int
GL_FOG_START: int
GL_FRONT: int
GL_FRONT_AND_BACK: int
GL_FRONT_FACE: int
GL_FRONT_LEFT: int
GL_FRONT_RIGHT: int
GL_GEQUAL: int
GL_GREATER: int
GL_GREEN: int
GL_GREEN_BIAS: int
GL_GREEN_BITS: int
GL_GREEN_SCALE: int
GL_HINT_BIT: int
GL_INCR: int
GL_INDEX_BITS: int
GL_INDEX_CLEAR_VALUE: int
GL_INDEX_MODE: int
GL_INDEX_OFFSET: int
GL_INDEX_SHIFT: int
GL_INDEX_WRITEMASK: int
GL_INVALID_ENUM: int
GL_INVALID_OPERATION: int
GL_INVALID_VALUE: int
GL_INVERT: int
GL_KEEP: int
GL_LEFT: int
GL_LEQUAL: int
GL_LESS: int
GL_LIGHT0: int
GL_LIGHT1: int
GL_LIGHT2: int
GL_LIGHT3: int
GL_LIGHT4: int
GL_LIGHT5: int
GL_LIGHT6: int
GL_LIGHT7: int
GL_LIGHTING: int
GL_LIGHTING_BIT: int
GL_LIGHT_MODEL_AMBIENT: int
GL_LIGHT_MODEL_LOCAL_VIEWER: int
GL_LIGHT_MODEL_TWO_SIDE: int
GL_LINE: int
GL_LINEAR: int
GL_LINEAR_ATTENUATION: int
GL_LINEAR_MIPMAP_LINEAR: int
GL_LINEAR_MIPMAP_NEAREST: int
GL_LINES: int
GL_LINE_BIT: int
GL_LINE_LOOP: int
GL_LINE_RESET_TOKEN: int
GL_LINE_SMOOTH: int
GL_LINE_SMOOTH_HINT: int
GL_LINE_STIPPLE: int
GL_LINE_STIPPLE_PATTERN: int
GL_LINE_STIPPLE_REPEAT: int
GL_LINE_STRIP: int
GL_LINE_TOKEN: int
GL_LINE_WIDTH: int
GL_LINE_WIDTH_GRANULARITY: int
GL_LINE_WIDTH_RANGE: int
GL_LIST_BASE: int
GL_LIST_BIT: int
GL_LIST_INDEX: int
GL_LIST_MODE: int
GL_LOAD: int
GL_LOGIC_OP: int
GL_LOGIC_OP_MODE: int
GL_LUMINANCE: int
GL_LUMINANCE_ALPHA: int
GL_MAP1_COLOR_4: int
GL_MAP1_GRID_DOMAIN: int
GL_MAP1_GRID_SEGMENTS: int
GL_MAP1_INDEX: int
GL_MAP1_NORMAL: int
GL_MAP1_TEXTURE_COORD_1: int
GL_MAP1_TEXTURE_COORD_2: int
GL_MAP1_TEXTURE_COORD_3: int
GL_MAP1_TEXTURE_COORD_4: int
GL_MAP1_VERTEX_3: int
GL_MAP1_VERTEX_4: int
GL_MAP2_COLOR_4: int
GL_MAP2_GRID_DOMAIN: int
GL_MAP2_GRID_SEGMENTS: int
GL_MAP2_INDEX: int
GL_MAP2_NORMAL: int
GL_MAP2_TEXTURE_COORD_1: int
GL_MAP2_TEXTURE_COORD_2: int
GL_MAP2_TEXTURE_COORD_3: int
GL_MAP2_TEXTURE_COORD_4: int
GL_MAP2_VERTEX_3: int
GL_MAP2_VERTEX_4: int
GL_MAP_COLOR: int
GL_MAP_STENCIL: int
GL_MATRIX_MODE: int
GL_MAX_ATTRIB_STACK_DEPTH: int
GL_MAX_CLIP_PLANES: int
GL_MAX_EVAL_ORDER: int
GL_MAX_LIGHTS: int
GL_MAX_LIST_NESTING: int
GL_MAX_MODELVIEW_STACK_DEPTH: int
GL_MAX_NAME_STACK_DEPTH: int
GL_MAX_PIXEL_MAP_TABLE: int
GL_MAX_PROJECTION_STACK_DEPTH: int
GL_MAX_TEXTURE_SIZE: int
GL_MAX_TEXTURE_STACK_DEPTH: int
GL_MAX_VIEWPORT_DIMS: int
GL_MODELVIEW: int
GL_MODELVIEW_MATRIX: int
GL_MODELVIEW_STACK_DEPTH: int
GL_MODULATE: int
GL_MULT: int
GL_NAME_STACK_DEPTH: int
GL_NAND: int
GL_NEAREST: int
GL_NEAREST_MIPMAP_LINEAR: int
GL_NEAREST_MIPMAP_NEAREST: int
GL_NEVER: int
GL_NICEST: int
GL_NONE: int
GL_NOOP: int
GL_NOR: int
GL_NORMALIZE: int
GL_NOTEQUAL: int
GL_NO_ERROR: int
GL_OBJECT_LINEAR: int
GL_OBJECT_PLANE: int
GL_ONE: int
GL_ONE_MINUS_DST_ALPHA: int
GL_ONE_MINUS_DST_COLOR: int
GL_ONE_MINUS_SRC_ALPHA: int
GL_ONE_MINUS_SRC_COLOR: int
GL_OR: int
GL_ORDER: int
GL_OR_INVERTED: int
GL_OR_REVERSE: int
GL_OUT_OF_MEMORY: int
GL_PACK_ALIGNMENT: int
GL_PACK_LSB_FIRST: int
GL_PACK_ROW_LENGTH: int
GL_PACK_SKIP_PIXELS: int
GL_PACK_SKIP_ROWS: int
GL_PACK_SWAP_BYTES: int
GL_PASS_THROUGH_TOKEN: int
GL_PERSPECTIVE_CORRECTION_HINT: int
GL_PIXEL_MAP_A_TO_A: int
GL_PIXEL_MAP_A_TO_A_SIZE: int
GL_PIXEL_MAP_B_TO_B: int
GL_PIXEL_MAP_B_TO_B_SIZE: int
GL_PIXEL_MAP_G_TO_G: int
GL_PIXEL_MAP_G_TO_G_SIZE: int
GL_PIXEL_MAP_I_TO_A: int
GL_PIXEL_MAP_I_TO_A_SIZE: int
GL_PIXEL_MAP_I_TO_B: int
GL_PIXEL_MAP_I_TO_B_SIZE: int
GL_PIXEL_MAP_I_TO_G: int
GL_PIXEL_MAP_I_TO_G_SIZE: int
GL_PIXEL_MAP_I_TO_I: int
GL_PIXEL_MAP_I_TO_I_SIZE: int
GL_PIXEL_MAP_I_TO_R: int
GL_PIXEL_MAP_I_TO_R_SIZE: int
GL_PIXEL_MAP_R_TO_R: int
GL_PIXEL_MAP_R_TO_R_SIZE: int
GL_PIXEL_MAP_S_TO_S: int
GL_PIXEL_MAP_S_TO_S_SIZE: int
GL_PIXEL_MODE_BIT: int
GL_POINT: int
GL_POINTS: int
GL_POINT_BIT: int
GL_POINT_SIZE: int
GL_POINT_SIZE_GRANULARITY: int
GL_POINT_SIZE_RANGE: int
GL_POINT_SMOOTH: int
GL_POINT_SMOOTH_HINT: int
GL_POINT_TOKEN: int
GL_POLYGON: int
GL_POLYGON_BIT: int
GL_POLYGON_MODE: int
GL_POLYGON_SMOOTH: int
GL_POLYGON_SMOOTH_HINT: int
GL_POLYGON_STIPPLE: int
GL_POLYGON_STIPPLE_BIT: int
GL_POLYGON_TOKEN: int
GL_POSITION: int
GL_PROJECTION: int
GL_PROJECTION_MATRIX: int
GL_PROJECTION_STACK_DEPTH: int
GL_Q: int
GL_QUADRATIC_ATTENUATION: int
GL_QUADS: int
GL_QUAD_STRIP: int
GL_R: int
GL_READ_BUFFER: int
GL_RED: int
GL_RED_BIAS: int
GL_RED_BITS: int
GL_RED_SCALE: int
GL_RENDER: int
GL_RENDERER: int
GL_RENDER_MODE: int
GL_REPEAT: int
GL_REPLACE: int
GL_RETURN: int
GL_RGB: int
GL_RGBA: int
GL_RGBA_MODE: int
GL_RIGHT: int
GL_S: int
GL_SCISSOR_BIT: int
GL_SCISSOR_BOX: int
GL_SCISSOR_TEST: int
GL_SELECT: int
GL_SET: int
GL_SHADE_MODEL: int
GL_SHININESS: int
GL_SMOOTH: int
GL_SPECULAR: int
GL_SPHERE_MAP: int
GL_SPOT_CUTOFF: int
GL_SPOT_DIRECTION: int
GL_SPOT_EXPONENT: int
GL_SRC_ALPHA: int
GL_SRC_ALPHA_SATURATE: int
GL_SRC_COLOR: int
GL_STACK_OVERFLOW: int
GL_STACK_UNDERFLOW: int
GL_STENCIL: int
GL_STENCIL_BITS: int
GL_STENCIL_BUFFER_BIT: int
GL_STENCIL_CLEAR_VALUE: int
GL_STENCIL_FAIL: int
GL_STENCIL_FUNC: int
GL_STENCIL_INDEX: int
GL_STENCIL_PASS_DEPTH_FAIL: int
GL_STENCIL_PASS_DEPTH_PASS: int
GL_STENCIL_REF: int
GL_STENCIL_TEST: int
GL_STENCIL_VALUE_MASK: int
GL_STENCIL_WRITEMASK: int
GL_STEREO: int
GL_SUBPIXEL_BITS: int
GL_T: int
GL_TEXTURE: int
GL_TEXTURE_1D: int
GL_TEXTURE_2D: int
GL_TEXTURE_BIT: int
GL_TEXTURE_BORDER: int
GL_TEXTURE_BORDER_COLOR: int
GL_TEXTURE_COMPONENTS: int
GL_TEXTURE_ENV: int
GL_TEXTURE_ENV_COLOR: int
GL_TEXTURE_ENV_MODE: int
GL_TEXTURE_GEN_MODE: int
GL_TEXTURE_GEN_Q: int
GL_TEXTURE_GEN_R: int
GL_TEXTURE_GEN_S: int
GL_TEXTURE_GEN_T: int
GL_TEXTURE_HEIGHT: int
GL_TEXTURE_MAG_FILTER: int
GL_TEXTURE_MATRIX: int
GL_TEXTURE_MIN_FILTER: int
GL_TEXTURE_STACK_DEPTH: int
GL_TEXTURE_WIDTH: int
GL_TEXTURE_WRAP_S: int
GL_TEXTURE_WRAP_T: int
GL_TRANSFORM_BIT: int
GL_TRIANGLES: int
GL_TRIANGLE_FAN: int
GL_TRIANGLE_STRIP: int
GL_UNPACK_ALIGNMENT: int
GL_UNPACK_LSB_FIRST: int
GL_UNPACK_ROW_LENGTH: int
GL_UNPACK_SKIP_PIXELS: int
GL_UNPACK_SKIP_ROWS: int
GL_UNPACK_SWAP_BYTES: int
GL_VENDOR: int
GL_VERSION: int
GL_VIEWPORT: int
GL_VIEWPORT_BIT: int
GL_XOR: int
GL_ZERO: int
GL_ZOOM_X: int
GL_ZOOM_Y: int

def glAccum(op: int, value: float) -> None: ...
def glAlphaFunc(func: int, ref: float) -> None: ...
def glBegin(mode: int) -> None: ...
def glBitmap(width: int, height: int, xorig: float, yorig: float, xmove: float, ymove: float, bitmap: UByteArray) -> None: ...
def glBlendFunc(sfactor: int, dfactor: int) -> None: ...
def glCallList(list: int) -> None: ...
def glCallLists(n: int, type: int, lists: AnyArray) -> None: ...
def glClear(mask: int) -> None: ...
def glClearAccum(red: float, green: float, blue: float, alpha: float) -> None: ...
def glClearColor(red: float, green: float, blue: float, alpha: float) -> None: ...
def glClearDepth(depth: float) -> None: ...
def glClearIndex(c: float) -> None: ...
def glClearStencil(s: int) -> None: ...
def glClipPlane(plane: int, equation: DoubleArray) -> None: ...
def glColor3b(red: int, green: int, blue: int) -> None: ...
def glColor3bv(v: ByteArray) -> None: ...
def glColor3d(red: float, green: float, blue: float) -> None: ...
def glColor3dv(v: DoubleArray) -> None: ...
def glColor3f(red: float, green: float, blue: float) -> None: ...
def glColor3fv(v: FloatArray) -> None: ...
def glColor3i(red: int, green: int, blue: int) -> None: ...
def glColor3iv(v: IntArray) -> None: ...
def glColor3s(red: int, green: int, blue: int) -> None: ...
def glColor3sv(v: ShortArray) -> None: ...
def glColor3ub(red: int, green: int, blue: int) -> None: ...
def glColor3ubv(v: UByteArray) -> None: ...
def glColor3ui(red: int, green: int, blue: int) -> None: ...
def glColor3uiv(v: UIntArray) -> None: ...
def glColor3us(red: int, green: int, blue: int) -> None: ...
def glColor3usv(v: UShortArray) -> None: ...
def glColor4b(red: int, green: int, blue: int, alpha: int) -> None: ...
def glColor4bv(v: ByteArray) -> None: ...
def glColor4d(red: float, green: float, blue: float, alpha: float) -> None: ...
def glColor4dv(v: DoubleArray) -> None: ...
def glColor4f(red: float, green: float, blue: float, alpha: float) -> None: ...
def glColor4fv(v: FloatArray) -> None: ...
def glColor4i(red: int, green: int, blue: int, alpha: int) -> None: ...
def glColor4iv(v: IntArray) -> None: ...
def glColor4s(red: int, green: int, blue: int, alpha: int) -> None: ...
def glColor4sv(v: ShortArray) -> None: ...
def glColor4ub(red: int, green: int, blue: int, alpha: int) -> None: ...
def glColor4ubv(v: UByteArray) -> None: ...
def glColor4ui(red: int, green: int, blue: int, alpha: int) -> None: ...
def glColor4uiv(v: UIntArray) -> None: ...
def glColor4us(red: int, green: int, blue: int, alpha: int) -> None: ...
def glColor4usv(v: UShortArray) -> None: ...
def glColorMask(red: int, green: int, blue: int, alpha: int) -> None: ...
def glColorMaterial(face: int, mode: int) -> None: ...
def glCopyPixels(x: int, y: int, width: int, height: int, type: int) -> None: ...
def glCullFace(mode: int) -> None: ...
def glDeleteLists(list: int, range: int) -> None: ...
def glDepthFunc(func: int) -> None: ...
def glDepthMask(flag: int) -> None: ...
def glDepthRange(n: float, f: float) -> None: ...
def glDisable(cap: int) -> None: ...
def glDrawBuffer(buf: int) -> None: ...
def glDrawPixels(width: int, height: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glEdgeFlag(flag: int) -> None: ...
def glEdgeFlagv(flag: UByteArray) -> None: ...
def glEnable(cap: int) -> None: ...
def glEnd() -> None: ...
def glEndList() -> None: ...
def glEvalCoord1d(u: float) -> None: ...
def glEvalCoord1dv(u: DoubleArray) -> None: ...
def glEvalCoord1f(u: float) -> None: ...
def glEvalCoord1fv(u: FloatArray) -> None: ...
def glEvalCoord2d(u: float, v: float) -> None: ...
def glEvalCoord2dv(u: DoubleArray) -> None: ...
def glEvalCoord2f(u: float, v: float) -> None: ...
def glEvalCoord2fv(u: FloatArray) -> None: ...
def glEvalMesh1(mode: int, i1: int, i2: int) -> None: ...
def glEvalMesh2(mode: int, i1: int, i2: int, j1: int, j2: int) -> None: ...
def glEvalPoint1(i: int) -> None: ...
def glEvalPoint2(i: int, j: int) -> None: ...
def glFeedbackBuffer(size: int, type: int, buffer: FloatArray | None = None) -> FloatArrayResult: ...
def glFinish() -> None: ...
def glFlush() -> None: ...
def glFogf(pname: int, param: float) -> None: ...
def glFogfv(pname: int, params: FloatArray) -> None: ...
def glFogi(pname: int, param: int) -> None: ...
def glFogiv(pname: int, params: IntArray) -> None: ...
def glFrontFace(mode: int) -> None: ...
def glFrustum(left: float, right: float, bottom: float, top: float, zNear: float, zFar: float) -> None: ...
def glGenLists(range: int) -> int: ...
def glGetBooleanv(pname: int, data: UByteArray | None = None) -> UByteArrayResult: ...
def glGetClipPlane(plane: int, equation: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetDoublev(pname: int, data: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetError() -> int: ...
def glGetFloatv(pname: int, data: FloatArray | None = None) -> FloatArrayResult: ...
def glGetIntegerv(pname: int, data: IntArray | None = None) -> IntArrayResult: ...
def glGetLightfv(light: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetLightiv(light: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetMapdv(target: int, query: int, v: DoubleArray) -> None: ...
def glGetMapfv(target: int, query: int, v: FloatArray) -> None: ...
def glGetMapiv(target: int, query: int, v: IntArray) -> None: ...
def glGetMaterialfv(face: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetMaterialiv(face: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetPixelMapfv(map: int, values: FloatArray | None = None) -> FloatArrayResult: ...
def glGetPixelMapuiv(map: int, values: UIntArray | None = None) -> UIntArrayResult: ...
def glGetPixelMapusv(map: int, values: UShortArray | None = None) -> UShortArrayResult: ...
def glGetPolygonStipple(mask: UByteArray | None = None) -> UByteArrayResult: ...
def glGetString(name: int) -> bytes: ...
def glGetTexEnvfv(target: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetTexEnviv(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetTexGendv(coord: int, pname: int, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetTexGenfv(coord: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetTexGeniv(coord: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetTexImage(target: int, level: int, format: int, type: int, pixels: AnyArray | None = None) -> AnyArrayResult: ...
def glGetTexLevelParameterfv(target: int, level: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetTexLevelParameteriv(target: int, level: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetTexParameterfv(target: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetTexParameteriv(target: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glHint(target: int, mode: int) -> None: ...
def glIndexMask(mask: int) -> None: ...
def glIndexd(c: float) -> None: ...
def glIndexdv(c: DoubleArray) -> None: ...
def glIndexf(c: float) -> None: ...
def glIndexfv(c: FloatArray) -> None: ...
def glIndexi(c: int) -> None: ...
def glIndexiv(c: IntArray) -> None: ...
def glIndexs(c: int) -> None: ...
def glIndexsv(c: ShortArray) -> None: ...
def glInitNames() -> None: ...
def glIsEnabled(cap: int) -> int: ...
def glIsList(list: int) -> int: ...
def glLightModelf(pname: int, param: float) -> None: ...
def glLightModelfv(pname: int, params: FloatArray) -> None: ...
def glLightModeli(pname: int, param: int) -> None: ...
def glLightModeliv(pname: int, params: IntArray) -> None: ...
def glLightf(light: int, pname: int, param: float) -> None: ...
def glLightfv(light: int, pname: int, params: FloatArray) -> None: ...
def glLighti(light: int, pname: int, param: int) -> None: ...
def glLightiv(light: int, pname: int, params: IntArray) -> None: ...
def glLineStipple(factor: int, pattern: int) -> None: ...
def glLineWidth(width: float) -> None: ...
def glListBase(base: int) -> None: ...
def glLoadIdentity() -> None: ...
def glLoadMatrixd(m: DoubleArray) -> None: ...
def glLoadMatrixf(m: FloatArray) -> None: ...
def glLoadName(name: int) -> None: ...
def glLogicOp(opcode: int) -> None: ...
def glMap1d(target: int, u1: float, u2: float, stride: int, order: int, points: DoubleArray) -> None: ...
def glMap1f(target: int, u1: float, u2: float, stride: int, order: int, points: FloatArray) -> None: ...
def glMap2d(target: int, u1: float, u2: float, ustride: int, uorder: int, v1: float, v2: float, vstride: int, vorder: int, points: DoubleArray) -> None: ...
def glMap2f(target: int, u1: float, u2: float, ustride: int, uorder: int, v1: float, v2: float, vstride: int, vorder: int, points: FloatArray) -> None: ...
def glMapGrid1d(un: int, u1: float, u2: float) -> None: ...
def glMapGrid1f(un: int, u1: float, u2: float) -> None: ...
def glMapGrid2d(un: int, u1: float, u2: float, vn: int, v1: float, v2: float) -> None: ...
def glMapGrid2f(un: int, u1: float, u2: float, vn: int, v1: float, v2: float) -> None: ...
def glMaterialf(face: int, pname: int, param: float) -> None: ...
def glMaterialfv(face: int, pname: int, params: FloatArray) -> None: ...
def glMateriali(face: int, pname: int, param: int) -> None: ...
def glMaterialiv(face: int, pname: int, params: IntArray) -> None: ...
def glMatrixMode(mode: int) -> None: ...
def glMultMatrixd(m: DoubleArray) -> None: ...
def glMultMatrixf(m: FloatArray) -> None: ...
def glNewList(list: int, mode: int) -> None: ...
def glNormal3b(nx: int, ny: int, nz: int) -> None: ...
def glNormal3bv(v: ByteArray) -> None: ...
def glNormal3d(nx: float, ny: float, nz: float) -> None: ...
def glNormal3dv(v: DoubleArray) -> None: ...
def glNormal3f(nx: float, ny: float, nz: float) -> None: ...
def glNormal3fv(v: FloatArray) -> None: ...
def glNormal3i(nx: int, ny: int, nz: int) -> None: ...
def glNormal3iv(v: IntArray) -> None: ...
def glNormal3s(nx: int, ny: int, nz: int) -> None: ...
def glNormal3sv(v: ShortArray) -> None: ...
def glOrtho(left: float, right: float, bottom: float, top: float, zNear: float, zFar: float) -> None: ...
def glPassThrough(token: float) -> None: ...
def glPixelMapfv(map: int, mapsize: int, values: FloatArray) -> None: ...
def glPixelMapuiv(map: int, mapsize: int, values: UIntArray) -> None: ...
def glPixelMapusv(map: int, mapsize: int, values: UShortArray) -> None: ...
def glPixelStoref(pname: int, param: float) -> None: ...
def glPixelStorei(pname: int, param: int) -> None: ...
def glPixelTransferf(pname: int, param: float) -> None: ...
def glPixelTransferi(pname: int, param: int) -> None: ...
def glPixelZoom(xfactor: float, yfactor: float) -> None: ...
def glPointSize(size: float) -> None: ...
def glPolygonMode(face: int, mode: int) -> None: ...
def glPolygonStipple(mask: UByteArray) -> None: ...
def glPopAttrib() -> None: ...
def glPopMatrix() -> None: ...
def glPopName() -> None: ...
def glPushAttrib(mask: int) -> None: ...
def glPushMatrix() -> None: ...
def glPushName(name: int) -> None: ...
def glRasterPos2d(x: float, y: float) -> None: ...
def glRasterPos2dv(v: DoubleArray) -> None: ...
def glRasterPos2f(x: float, y: float) -> None: ...
def glRasterPos2fv(v: FloatArray) -> None: ...
def glRasterPos2i(x: int, y: int) -> None: ...
def glRasterPos2iv(v: IntArray) -> None: ...
def glRasterPos2s(x: int, y: int) -> None: ...
def glRasterPos2sv(v: ShortArray) -> None: ...
def glRasterPos3d(x: float, y: float, z: float) -> None: ...
def glRasterPos3dv(v: DoubleArray) -> None: ...
def glRasterPos3f(x: float, y: float, z: float) -> None: ...
def glRasterPos3fv(v: FloatArray) -> None: ...
def glRasterPos3i(x: int, y: int, z: int) -> None: ...
def glRasterPos3iv(v: IntArray) -> None: ...
def glRasterPos3s(x: int, y: int, z: int) -> None: ...
def glRasterPos3sv(v: ShortArray) -> None: ...
def glRasterPos4d(x: float, y: float, z: float, w: float) -> None: ...
def glRasterPos4dv(v: DoubleArray) -> None: ...
def glRasterPos4f(x: float, y: float, z: float, w: float) -> None: ...
def glRasterPos4fv(v: FloatArray) -> None: ...
def glRasterPos4i(x: int, y: int, z: int, w: int) -> None: ...
def glRasterPos4iv(v: IntArray) -> None: ...
def glRasterPos4s(x: int, y: int, z: int, w: int) -> None: ...
def glRasterPos4sv(v: ShortArray) -> None: ...
def glReadBuffer(src: int) -> None: ...
def glReadPixels(x: int, y: int, width: int, height: int, format: int, type: int, pixels: AnyArray | None = None) -> AnyArrayResult: ...
def glRectd(x1: float, y1: float, x2: float, y2: float) -> None: ...
def glRectdv(v1: DoubleArray, v2: DoubleArray) -> None: ...
def glRectf(x1: float, y1: float, x2: float, y2: float) -> None: ...
def glRectfv(v1: FloatArray, v2: FloatArray) -> None: ...
def glRecti(x1: int, y1: int, x2: int, y2: int) -> None: ...
def glRectiv(v1: IntArray, v2: IntArray) -> None: ...
def glRects(x1: int, y1: int, x2: int, y2: int) -> None: ...
def glRectsv(v1: ShortArray, v2: ShortArray) -> None: ...
def glRenderMode(mode: int) -> int: ...
def glRotated(angle: float, x: float, y: float, z: float) -> None: ...
def glRotatef(angle: float, x: float, y: float, z: float) -> None: ...
def glScaled(x: float, y: float, z: float) -> None: ...
def glScalef(x: float, y: float, z: float) -> None: ...
def glScissor(x: int, y: int, width: int, height: int) -> None: ...
def glSelectBuffer(size: int, buffer: UIntArray | None = None) -> UIntArrayResult: ...
def glShadeModel(mode: int) -> None: ...
def glStencilFunc(func: int, ref: int, mask: int) -> None: ...
def glStencilMask(mask: int) -> None: ...
def glStencilOp(fail: int, zfail: int, zpass: int) -> None: ...
def glTexCoord1d(s: float) -> None: ...
def glTexCoord1dv(v: DoubleArray) -> None: ...
def glTexCoord1f(s: float) -> None: ...
def glTexCoord1fv(v: FloatArray) -> None: ...
def glTexCoord1i(s: int) -> None: ...
def glTexCoord1iv(v: IntArray) -> None: ...
def glTexCoord1s(s: int) -> None: ...
def glTexCoord1sv(v: ShortArray) -> None: ...
def glTexCoord2d(s: float, t: float) -> None: ...
def glTexCoord2dv(v: DoubleArray) -> None: ...
def glTexCoord2f(s: float, t: float) -> None: ...
def glTexCoord2fv(v: FloatArray) -> None: ...
def glTexCoord2i(s: int, t: int) -> None: ...
def glTexCoord2iv(v: IntArray) -> None: ...
def glTexCoord2s(s: int, t: int) -> None: ...
def glTexCoord2sv(v: ShortArray) -> None: ...
def glTexCoord3d(s: float, t: float, r: float) -> None: ...
def glTexCoord3dv(v: DoubleArray) -> None: ...
def glTexCoord3f(s: float, t: float, r: float) -> None: ...
def glTexCoord3fv(v: FloatArray) -> None: ...
def glTexCoord3i(s: int, t: int, r: int) -> None: ...
def glTexCoord3iv(v: IntArray) -> None: ...
def glTexCoord3s(s: int, t: int, r: int) -> None: ...
def glTexCoord3sv(v: ShortArray) -> None: ...
def glTexCoord4d(s: float, t: float, r: float, q: float) -> None: ...
def glTexCoord4dv(v: DoubleArray) -> None: ...
def glTexCoord4f(s: float, t: float, r: float, q: float) -> None: ...
def glTexCoord4fv(v: FloatArray) -> None: ...
def glTexCoord4i(s: int, t: int, r: int, q: int) -> None: ...
def glTexCoord4iv(v: IntArray) -> None: ...
def glTexCoord4s(s: int, t: int, r: int, q: int) -> None: ...
def glTexCoord4sv(v: ShortArray) -> None: ...
def glTexEnvf(target: int, pname: int, param: float) -> None: ...
def glTexEnvfv(target: int, pname: int, params: FloatArray) -> None: ...
def glTexEnvi(target: int, pname: int, param: int) -> None: ...
def glTexEnviv(target: int, pname: int, params: IntArray) -> None: ...
def glTexGend(coord: int, pname: int, param: float) -> None: ...
def glTexGendv(coord: int, pname: int, params: DoubleArray) -> None: ...
def glTexGenf(coord: int, pname: int, param: float) -> None: ...
def glTexGenfv(coord: int, pname: int, params: FloatArray) -> None: ...
def glTexGeni(coord: int, pname: int, param: int) -> None: ...
def glTexGeniv(coord: int, pname: int, params: IntArray) -> None: ...
def glTexImage1D(target: int, level: int, internalformat: int, width: int, border: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glTexImage2D(target: int, level: int, internalformat: int, width: int, height: int, border: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glTexParameterf(target: int, pname: int, param: float) -> None: ...
def glTexParameterfv(target: int, pname: int, params: FloatArray) -> None: ...
def glTexParameteri(target: int, pname: int, param: int) -> None: ...
def glTexParameteriv(target: int, pname: int, params: IntArray) -> None: ...
def glTranslated(x: float, y: float, z: float) -> None: ...
def glTranslatef(x: float, y: float, z: float) -> None: ...
def glVertex2d(x: float, y: float) -> None: ...
def glVertex2dv(v: DoubleArray) -> None: ...
def glVertex2f(x: float, y: float) -> None: ...
def glVertex2fv(v: FloatArray) -> None: ...
def glVertex2i(x: int, y: int) -> None: ...
def glVertex2iv(v: IntArray) -> None: ...
def glVertex2s(x: int, y: int) -> None: ...
def glVertex2sv(v: ShortArray) -> None: ...
def glVertex3d(x: float, y: float, z: float) -> None: ...
def glVertex3dv(v: DoubleArray) -> None: ...
def glVertex3f(x: float, y: float, z: float) -> None: ...
def glVertex3fv(v: FloatArray) -> None: ...
def glVertex3i(x: int, y: int, z: int) -> None: ...
def glVertex3iv(v: IntArray) -> None: ...
def glVertex3s(x: int, y: int, z: int) -> None: ...
def glVertex3sv(v: ShortArray) -> None: ...
def glVertex4d(x: float, y: float, z: float, w: float) -> None: ...
def glVertex4dv(v: DoubleArray) -> None: ...
def glVertex4f(x: float, y: float, z: float, w: float) -> None: ...
def glVertex4fv(v: FloatArray) -> None: ...
def glVertex4i(x: int, y: int, z: int, w: int) -> None: ...
def glVertex4iv(v: IntArray) -> None: ...
def glVertex4s(x: int, y: int, z: int, w: int) -> None: ...
def glVertex4sv(v: ShortArray) -> None: ...
def glViewport(x: int, y: int, width: int, height: int) -> None: ...

def glInitGl10VERSION() -> bool: ...

def __getattr__(name: str) -> Any: ...
