"""OpenGL.GL.VERSION.GL_1_4 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, ByteArray, DoubleArray, FloatArray, IntArray, ShortArray, UByteArray, UIntArray, UShortArray

from OpenGL.raw.GL._types import *

GL_BLEND_COLOR: int
GL_BLEND_DST_ALPHA: int
GL_BLEND_DST_RGB: int
GL_BLEND_EQUATION: int
GL_BLEND_SRC_ALPHA: int
GL_BLEND_SRC_RGB: int
GL_COLOR_SUM: int
GL_COMPARE_R_TO_TEXTURE: int
GL_CONSTANT_ALPHA: int
GL_CONSTANT_COLOR: int
GL_CURRENT_FOG_COORDINATE: int
GL_CURRENT_SECONDARY_COLOR: int
GL_DECR_WRAP: int
GL_DEPTH_COMPONENT16: int
GL_DEPTH_COMPONENT24: int
GL_DEPTH_COMPONENT32: int
GL_DEPTH_TEXTURE_MODE: int
GL_FOG_COORDINATE: int
GL_FOG_COORDINATE_ARRAY: int
GL_FOG_COORDINATE_ARRAY_POINTER: int
GL_FOG_COORDINATE_ARRAY_STRIDE: int
GL_FOG_COORDINATE_ARRAY_TYPE: int
GL_FOG_COORDINATE_SOURCE: int
GL_FRAGMENT_DEPTH: int
GL_FUNC_ADD: int
GL_FUNC_REVERSE_SUBTRACT: int
GL_FUNC_SUBTRACT: int
GL_GENERATE_MIPMAP: int
GL_GENERATE_MIPMAP_HINT: int
GL_INCR_WRAP: int
GL_MAX: int
GL_MAX_TEXTURE_LOD_BIAS: int
GL_MIN: int
GL_MIRRORED_REPEAT: int
GL_ONE_MINUS_CONSTANT_ALPHA: int
GL_ONE_MINUS_CONSTANT_COLOR: int
GL_POINT_DISTANCE_ATTENUATION: int
GL_POINT_FADE_THRESHOLD_SIZE: int
GL_POINT_SIZE_MAX: int
GL_POINT_SIZE_MIN: int
GL_SECONDARY_COLOR_ARRAY: int
GL_SECONDARY_COLOR_ARRAY_POINTER: int
GL_SECONDARY_COLOR_ARRAY_SIZE: int
GL_SECONDARY_COLOR_ARRAY_STRIDE: int
GL_SECONDARY_COLOR_ARRAY_TYPE: int
GL_TEXTURE_COMPARE_FUNC: int
GL_TEXTURE_COMPARE_MODE: int
GL_TEXTURE_DEPTH_SIZE: int
GL_TEXTURE_FILTER_CONTROL: int
GL_TEXTURE_LOD_BIAS: int

def glBlendColor(red: float, green: float, blue: float, alpha: float) -> None: ...
def glBlendEquation(mode: int) -> None: ...
def glBlendFuncSeparate(sfactorRGB: int, dfactorRGB: int, sfactorAlpha: int, dfactorAlpha: int) -> None: ...
def glFogCoordPointer(type: int, stride: int, pointer: AnyArray) -> None: ...
def glFogCoordd(coord: float) -> None: ...
def glFogCoorddv(coord: DoubleArray) -> None: ...
def glFogCoordf(coord: float) -> None: ...
def glFogCoordfv(coord: FloatArray) -> None: ...
def glMultiDrawArrays(mode: int, first: IntArray, count: IntArray, drawcount: int) -> None: ...
def glMultiDrawElements(mode: int, count: IntArray, type: int, indices: AnyArray, drawcount: int) -> None: ...
def glPointParameterf(pname: int, param: float) -> None: ...
def glPointParameterfv(pname: int, params: FloatArray) -> None: ...
def glPointParameteri(pname: int, param: int) -> None: ...
def glPointParameteriv(pname: int, params: IntArray) -> None: ...
def glSecondaryColor3b(red: int, green: int, blue: int) -> None: ...
def glSecondaryColor3bv(v: ByteArray) -> None: ...
def glSecondaryColor3d(red: float, green: float, blue: float) -> None: ...
def glSecondaryColor3dv(v: DoubleArray) -> None: ...
def glSecondaryColor3f(red: float, green: float, blue: float) -> None: ...
def glSecondaryColor3fv(v: FloatArray) -> None: ...
def glSecondaryColor3i(red: int, green: int, blue: int) -> None: ...
def glSecondaryColor3iv(v: IntArray) -> None: ...
def glSecondaryColor3s(red: int, green: int, blue: int) -> None: ...
def glSecondaryColor3sv(v: ShortArray) -> None: ...
def glSecondaryColor3ub(red: int, green: int, blue: int) -> None: ...
def glSecondaryColor3ubv(v: UByteArray) -> None: ...
def glSecondaryColor3ui(red: int, green: int, blue: int) -> None: ...
def glSecondaryColor3uiv(v: UIntArray) -> None: ...
def glSecondaryColor3us(red: int, green: int, blue: int) -> None: ...
def glSecondaryColor3usv(v: UShortArray) -> None: ...
def glSecondaryColorPointer(size: int, type: int, stride: int, pointer: AnyArray) -> None: ...
def glWindowPos2d(x: float, y: float) -> None: ...
def glWindowPos2dv(v: DoubleArray) -> None: ...
def glWindowPos2f(x: float, y: float) -> None: ...
def glWindowPos2fv(v: FloatArray) -> None: ...
def glWindowPos2i(x: int, y: int) -> None: ...
def glWindowPos2iv(v: IntArray) -> None: ...
def glWindowPos2s(x: int, y: int) -> None: ...
def glWindowPos2sv(v: ShortArray) -> None: ...
def glWindowPos3d(x: float, y: float, z: float) -> None: ...
def glWindowPos3dv(v: DoubleArray) -> None: ...
def glWindowPos3f(x: float, y: float, z: float) -> None: ...
def glWindowPos3fv(v: FloatArray) -> None: ...
def glWindowPos3i(x: int, y: int, z: int) -> None: ...
def glWindowPos3iv(v: IntArray) -> None: ...
def glWindowPos3s(x: int, y: int, z: int) -> None: ...
def glWindowPos3sv(v: ShortArray) -> None: ...

def glInitGl14VERSION() -> bool: ...
GL_CURRENT_FOG_COORD: int
GL_FOG_COORD: int
GL_FOG_COORD_ARRAY: int
GL_FOG_COORD_ARRAY_POINTER: int
GL_FOG_COORD_ARRAY_STRIDE: int
GL_FOG_COORD_ARRAY_TYPE: int
GL_FOG_COORD_SRC: int

def __getattr__(name: str) -> Any: ...
