"""OpenGL.GL.VERSION.GL_2_0 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, AnyArrayResult, ByteArray, ByteArrayResult, DoubleArray, DoubleArrayResult, FloatArray, FloatArrayResult, IntArray, IntArrayResult, ShortArray, UByteArray, UIntArray, UIntArrayResult, UShortArray

from OpenGL.raw.GL._types import *

GL_ACTIVE_ATTRIBUTES: int
GL_ACTIVE_ATTRIBUTE_MAX_LENGTH: int
GL_ACTIVE_UNIFORMS: int
GL_ACTIVE_UNIFORM_MAX_LENGTH: int
GL_ATTACHED_SHADERS: int
GL_BLEND_EQUATION_ALPHA: int
GL_BLEND_EQUATION_RGB: int
GL_BOOL: int
GL_BOOL_VEC2: int
GL_BOOL_VEC3: int
GL_BOOL_VEC4: int
GL_COMPILE_STATUS: int
GL_COORD_REPLACE: int
GL_CURRENT_PROGRAM: int
GL_CURRENT_VERTEX_ATTRIB: int
GL_DELETE_STATUS: int
GL_DRAW_BUFFER0: int
GL_DRAW_BUFFER1: int
GL_DRAW_BUFFER10: int
GL_DRAW_BUFFER11: int
GL_DRAW_BUFFER12: int
GL_DRAW_BUFFER13: int
GL_DRAW_BUFFER14: int
GL_DRAW_BUFFER15: int
GL_DRAW_BUFFER2: int
GL_DRAW_BUFFER3: int
GL_DRAW_BUFFER4: int
GL_DRAW_BUFFER5: int
GL_DRAW_BUFFER6: int
GL_DRAW_BUFFER7: int
GL_DRAW_BUFFER8: int
GL_DRAW_BUFFER9: int
GL_FLOAT_MAT2: int
GL_FLOAT_MAT3: int
GL_FLOAT_MAT4: int
GL_FLOAT_VEC2: int
GL_FLOAT_VEC3: int
GL_FLOAT_VEC4: int
GL_FRAGMENT_SHADER: int
GL_FRAGMENT_SHADER_DERIVATIVE_HINT: int
GL_INFO_LOG_LENGTH: int
GL_INT_VEC2: int
GL_INT_VEC3: int
GL_INT_VEC4: int
GL_LINK_STATUS: int
GL_LOWER_LEFT: int
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS: int
GL_MAX_DRAW_BUFFERS: int
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS: int
GL_MAX_TEXTURE_COORDS: int
GL_MAX_TEXTURE_IMAGE_UNITS: int
GL_MAX_VARYING_FLOATS: int
GL_MAX_VERTEX_ATTRIBS: int
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS: int
GL_MAX_VERTEX_UNIFORM_COMPONENTS: int
GL_POINT_SPRITE: int
GL_POINT_SPRITE_COORD_ORIGIN: int
GL_SAMPLER_1D: int
GL_SAMPLER_1D_SHADOW: int
GL_SAMPLER_2D: int
GL_SAMPLER_2D_SHADOW: int
GL_SAMPLER_3D: int
GL_SAMPLER_CUBE: int
GL_SHADER_SOURCE_LENGTH: int
GL_SHADER_TYPE: int
GL_SHADING_LANGUAGE_VERSION: int
GL_STENCIL_BACK_FAIL: int
GL_STENCIL_BACK_FUNC: int
GL_STENCIL_BACK_PASS_DEPTH_FAIL: int
GL_STENCIL_BACK_PASS_DEPTH_PASS: int
GL_STENCIL_BACK_REF: int
GL_STENCIL_BACK_VALUE_MASK: int
GL_STENCIL_BACK_WRITEMASK: int
GL_UPPER_LEFT: int
GL_VALIDATE_STATUS: int
GL_VERTEX_ATTRIB_ARRAY_ENABLED: int
GL_VERTEX_ATTRIB_ARRAY_NORMALIZED: int
GL_VERTEX_ATTRIB_ARRAY_POINTER: int
GL_VERTEX_ATTRIB_ARRAY_SIZE: int
GL_VERTEX_ATTRIB_ARRAY_STRIDE: int
GL_VERTEX_ATTRIB_ARRAY_TYPE: int
GL_VERTEX_PROGRAM_POINT_SIZE: int
GL_VERTEX_PROGRAM_TWO_SIDE: int
GL_VERTEX_SHADER: int

def glAttachShader(program: int, shader: int) -> None: ...
def glBindAttribLocation(program: int, index: int, name: ByteArray) -> None: ...
def glBlendEquationSeparate(modeRGB: int, modeAlpha: int) -> None: ...
def glCompileShader(shader: int) -> None: ...
def glCreateProgram() -> int: ...
def glCreateShader(type: int) -> int: ...
def glDeleteProgram(program: int) -> None: ...
def glDeleteShader(shader: int) -> None: ...
def glDetachShader(program: int, shader: int) -> None: ...
def glDisableVertexAttribArray(index: int) -> None: ...
def glDrawBuffers(n: int, bufs: UIntArray) -> None: ...
def glEnableVertexAttribArray(index: int) -> None: ...
def glGetActiveAttrib(program: int, index: int, bufSize: int, length: IntArray | None = None, size: IntArray | None = None, type: UIntArray | None = None, name: ByteArray | None = None) -> tuple[IntArrayResult, ByteArrayResult, IntArrayResult, UIntArrayResult]: ...
def glGetActiveUniform(program: int, index: int, bufSize: int, length: IntArray | None = None, size: IntArray | None = None, type: UIntArray | None = None, name: ByteArray | None = None) -> tuple[IntArrayResult, ByteArrayResult, IntArrayResult, UIntArrayResult]: ...
def glGetAttachedShaders(program: int, maxCount: int, count: IntArray, shaders: UIntArray) -> IntArrayResult: ...
def glGetAttribLocation(program: int, name: ByteArray) -> int: ...
def glGetProgramInfoLog(program: int, bufSize: int, length: IntArray | None = None, infoLog: ByteArray | None = None) -> tuple[ByteArrayResult, IntArrayResult]: ...
def glGetProgramiv(program: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetShaderInfoLog(shader: int, bufSize: int, length: IntArray | None = None, infoLog: ByteArray | None = None) -> tuple[ByteArrayResult, IntArrayResult]: ...
def glGetShaderSource(shader: int, bufSize: int, length: IntArray | None = None, source: ByteArray | None = None) -> tuple[IntArrayResult, ByteArrayResult]: ...
def glGetShaderiv(shader: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetUniformLocation(program: int, name: ByteArray) -> int: ...
def glGetUniformfv(program: int, location: int, params: FloatArray) -> None: ...
def glGetUniformiv(program: int, location: int, params: IntArray) -> None: ...
def glGetVertexAttribPointerv(index: int, pname: int, pointer: AnyArray | None = None) -> AnyArrayResult: ...
def glGetVertexAttribdv(index: int, pname: int, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetVertexAttribfv(index: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetVertexAttribiv(index: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glIsProgram(program: int) -> int: ...
def glIsShader(shader: int) -> int: ...
def glLinkProgram(program: int) -> None: ...
def glShaderSource(shader: Any, string: Any) -> None: ...
def glStencilFuncSeparate(face: int, func: int, ref: int, mask: int) -> None: ...
def glStencilMaskSeparate(face: int, mask: int) -> None: ...
def glStencilOpSeparate(face: int, sfail: int, dpfail: int, dppass: int) -> None: ...
def glUniform1f(location: int, v0: float) -> None: ...
def glUniform1fv(location: int, count: int, value: FloatArray) -> None: ...
def glUniform1i(location: int, v0: int) -> None: ...
def glUniform1iv(location: int, count: int, value: IntArray) -> None: ...
def glUniform2f(location: int, v0: float, v1: float) -> None: ...
def glUniform2fv(location: int, count: int, value: FloatArray) -> None: ...
def glUniform2i(location: int, v0: int, v1: int) -> None: ...
def glUniform2iv(location: int, count: int, value: IntArray) -> None: ...
def glUniform3f(location: int, v0: float, v1: float, v2: float) -> None: ...
def glUniform3fv(location: int, count: int, value: FloatArray) -> None: ...
def glUniform3i(location: int, v0: int, v1: int, v2: int) -> None: ...
def glUniform3iv(location: int, count: int, value: IntArray) -> None: ...
def glUniform4f(location: int, v0: float, v1: float, v2: float, v3: float) -> None: ...
def glUniform4fv(location: int, count: int, value: FloatArray) -> None: ...
def glUniform4i(location: int, v0: int, v1: int, v2: int, v3: int) -> None: ...
def glUniform4iv(location: int, count: int, value: IntArray) -> None: ...
def glUniformMatrix2fv(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUniformMatrix3fv(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUniformMatrix4fv(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUseProgram(program: int) -> None: ...
def glValidateProgram(program: int) -> None: ...
def glVertexAttrib1d(index: int, x: float) -> None: ...
def glVertexAttrib1dv(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib1f(index: int, x: float) -> None: ...
def glVertexAttrib1fv(index: int, v: FloatArray) -> None: ...
def glVertexAttrib1s(index: int, x: int) -> None: ...
def glVertexAttrib1sv(index: int, v: ShortArray) -> None: ...
def glVertexAttrib2d(index: int, x: float, y: float) -> None: ...
def glVertexAttrib2dv(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib2f(index: int, x: float, y: float) -> None: ...
def glVertexAttrib2fv(index: int, v: FloatArray) -> None: ...
def glVertexAttrib2s(index: int, x: int, y: int) -> None: ...
def glVertexAttrib2sv(index: int, v: ShortArray) -> None: ...
def glVertexAttrib3d(index: int, x: float, y: float, z: float) -> None: ...
def glVertexAttrib3dv(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib3f(index: int, x: float, y: float, z: float) -> None: ...
def glVertexAttrib3fv(index: int, v: FloatArray) -> None: ...
def glVertexAttrib3s(index: int, x: int, y: int, z: int) -> None: ...
def glVertexAttrib3sv(index: int, v: ShortArray) -> None: ...
def glVertexAttrib4Nbv(index: int, v: ByteArray) -> None: ...
def glVertexAttrib4Niv(index: int, v: IntArray) -> None: ...
def glVertexAttrib4Nsv(index: int, v: ShortArray) -> None: ...
def glVertexAttrib4Nub(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttrib4Nubv(index: int, v: UByteArray) -> None: ...
def glVertexAttrib4Nuiv(index: int, v: UIntArray) -> None: ...
def glVertexAttrib4Nusv(index: int, v: UShortArray) -> None: ...
def glVertexAttrib4bv(index: int, v: ByteArray) -> None: ...
def glVertexAttrib4d(index: int, x: float, y: float, z: float, w: float) -> None: ...
def glVertexAttrib4dv(index: int, v: DoubleArray) -> None: ...
def glVertexAttrib4f(index: int, x: float, y: float, z: float, w: float) -> None: ...
def glVertexAttrib4fv(index: int, v: FloatArray) -> None: ...
def glVertexAttrib4iv(index: int, v: IntArray) -> None: ...
def glVertexAttrib4s(index: int, x: int, y: int, z: int, w: int) -> None: ...
def glVertexAttrib4sv(index: int, v: ShortArray) -> None: ...
def glVertexAttrib4ubv(index: int, v: UByteArray) -> None: ...
def glVertexAttrib4uiv(index: int, v: UIntArray) -> None: ...
def glVertexAttrib4usv(index: int, v: UShortArray) -> None: ...
def glVertexAttribPointer(index: int, size: int, type: int, normalized: bool, stride: int, pointer: AnyArray) -> None: ...

def glInitGl20VERSION() -> bool: ...
conv: Any

def __getattr__(name: str) -> Any: ...
