"""OpenGL.GL.VERSION.GL_3_3 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import ByteArray, FloatArray, FloatArrayResult, Int64Array, Int64ArrayResult, IntArray, IntArrayResult, UInt64Array, UInt64ArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_ANY_SAMPLES_PASSED: int
GL_INT_2_10_10_10_REV: int
GL_MAX_DUAL_SOURCE_DRAW_BUFFERS: int
GL_ONE_MINUS_SRC1_ALPHA: int
GL_ONE_MINUS_SRC1_COLOR: int
GL_RGB10_A2UI: int
GL_SAMPLER_BINDING: int
GL_SRC1_COLOR: int
GL_TEXTURE_SWIZZLE_A: int
GL_TEXTURE_SWIZZLE_B: int
GL_TEXTURE_SWIZZLE_G: int
GL_TEXTURE_SWIZZLE_R: int
GL_TEXTURE_SWIZZLE_RGBA: int
GL_TIMESTAMP: int
GL_TIME_ELAPSED: int
GL_VERTEX_ATTRIB_ARRAY_DIVISOR: int

def glBindFragDataLocationIndexed(program: int, colorNumber: int, index: int, name: ByteArray) -> None: ...
def glBindSampler(unit: int, sampler: int) -> None: ...
def glColorP3ui(type: int, color: int) -> None: ...
def glColorP3uiv(type: int, color: UIntArray) -> None: ...
def glColorP4ui(type: int, color: int) -> None: ...
def glColorP4uiv(type: int, color: UIntArray) -> None: ...
def glDeleteSamplers(count: int, samplers: UIntArray) -> None: ...
def glGenSamplers(count: int, samplers: UIntArray | None = None) -> UIntArrayResult: ...
def glGetFragDataIndex(program: int, name: ByteArray) -> int: ...
def glGetQueryObjecti64v(id: int, pname: int, params: Int64Array | None = None) -> Int64ArrayResult: ...
def glGetQueryObjectui64v(id: int, pname: int, params: UInt64Array | None = None) -> UInt64ArrayResult: ...
def glGetSamplerParameterIiv(sampler: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetSamplerParameterIuiv(sampler: int, pname: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glGetSamplerParameterfv(sampler: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetSamplerParameteriv(sampler: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glIsSampler(sampler: int) -> int: ...
def glMultiTexCoordP1ui(texture: int, type: int, coords: int) -> None: ...
def glMultiTexCoordP1uiv(texture: int, type: int, coords: UIntArray) -> None: ...
def glMultiTexCoordP2ui(texture: int, type: int, coords: int) -> None: ...
def glMultiTexCoordP2uiv(texture: int, type: int, coords: UIntArray) -> None: ...
def glMultiTexCoordP3ui(texture: int, type: int, coords: int) -> None: ...
def glMultiTexCoordP3uiv(texture: int, type: int, coords: UIntArray) -> None: ...
def glMultiTexCoordP4ui(texture: int, type: int, coords: int) -> None: ...
def glMultiTexCoordP4uiv(texture: int, type: int, coords: UIntArray) -> None: ...
def glNormalP3ui(type: int, coords: int) -> None: ...
def glNormalP3uiv(type: int, coords: UIntArray) -> None: ...
def glQueryCounter(id: int, target: int) -> None: ...
def glSamplerParameterIiv(sampler: int, pname: int, param: IntArray) -> None: ...
def glSamplerParameterIuiv(sampler: int, pname: int, param: UIntArray) -> None: ...
def glSamplerParameterf(sampler: int, pname: int, param: float) -> None: ...
def glSamplerParameterfv(sampler: int, pname: int, param: FloatArray) -> None: ...
def glSamplerParameteri(sampler: int, pname: int, param: int) -> None: ...
def glSamplerParameteriv(sampler: int, pname: int, param: IntArray) -> None: ...
def glSecondaryColorP3ui(type: int, color: int) -> None: ...
def glSecondaryColorP3uiv(type: int, color: UIntArray) -> None: ...
def glTexCoordP1ui(type: int, coords: int) -> None: ...
def glTexCoordP1uiv(type: int, coords: UIntArray) -> None: ...
def glTexCoordP2ui(type: int, coords: int) -> None: ...
def glTexCoordP2uiv(type: int, coords: UIntArray) -> None: ...
def glTexCoordP3ui(type: int, coords: int) -> None: ...
def glTexCoordP3uiv(type: int, coords: UIntArray) -> None: ...
def glTexCoordP4ui(type: int, coords: int) -> None: ...
def glTexCoordP4uiv(type: int, coords: UIntArray) -> None: ...
def glVertexAttribDivisor(index: int, divisor: int) -> None: ...
def glVertexAttribP1ui(index: int, type: int, normalized: int, value: int) -> None: ...
def glVertexAttribP1uiv(index: int, type: int, normalized: int, value: UIntArray) -> None: ...
def glVertexAttribP2ui(index: int, type: int, normalized: int, value: int) -> None: ...
def glVertexAttribP2uiv(index: int, type: int, normalized: int, value: UIntArray) -> None: ...
def glVertexAttribP3ui(index: int, type: int, normalized: int, value: int) -> None: ...
def glVertexAttribP3uiv(index: int, type: int, normalized: int, value: UIntArray) -> None: ...
def glVertexAttribP4ui(index: int, type: int, normalized: int, value: int) -> None: ...
def glVertexAttribP4uiv(index: int, type: int, normalized: int, value: UIntArray) -> None: ...
def glVertexP2ui(type: int, value: int) -> None: ...
def glVertexP2uiv(type: int, value: UIntArray) -> None: ...
def glVertexP3ui(type: int, value: int) -> None: ...
def glVertexP3uiv(type: int, value: UIntArray) -> None: ...
def glVertexP4ui(type: int, value: int) -> None: ...
def glVertexP4uiv(type: int, value: UIntArray) -> None: ...

def glInitGl33VERSION() -> bool: ...

def __getattr__(name: str) -> Any: ...
