# mypy: ignore-errors
# The names in this module arrive from the declaration tables at import
# time, so a checker reading this file sees calls to things it cannot
# find.  The typed surface is the .pyi stub beside the package.
'''OpenGL extension VERSION.GL_4_1

This module customises the behaviour of the 
OpenGL.raw.GL.VERSION.GL_4_1 to provide a more 
Python-friendly API

The official definition of this extension is available here:
http://www.opengl.org/registry/specs/VERSION/GL_4_1.txt
'''
from OpenGL import platform, constant, arrays
from OpenGL import extensions, wrapper
import ctypes
from OpenGL.raw.GL import _types, _glgets
from OpenGL._declarations import define as _define
_EXTENSION_NAME = _define(globals(), 'OpenGL.raw.GL.VERSION.GL_4_1', customise=True)

def glInitGl41VERSION():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( _EXTENSION_NAME )

# INPUT glShaderBinary.binary size not checked against length
# INPUT glShaderBinary.shaders size not checked against count
# INPUT glProgramBinary.binary size not checked against length
# INPUT glCreateShaderProgramv.strings size not checked against count
# INPUT glDeleteProgramPipelines.pipelines size not checked against n
# INPUT glProgramUniform1iv.value size not checked against count
# INPUT glProgramUniform1fv.value size not checked against count
# INPUT glProgramUniform1dv.value size not checked against count
# INPUT glProgramUniform1uiv.value size not checked against count
# INPUT glProgramUniform2iv.value size not checked against count*2
# INPUT glProgramUniform2fv.value size not checked against count*2
# INPUT glProgramUniform2dv.value size not checked against count*2
# INPUT glProgramUniform2uiv.value size not checked against count*2
# INPUT glProgramUniform3iv.value size not checked against count*3
# INPUT glProgramUniform3fv.value size not checked against count*3
# INPUT glProgramUniform3dv.value size not checked against count*3
# INPUT glProgramUniform3uiv.value size not checked against count*3
# INPUT glProgramUniform4iv.value size not checked against count*4
# INPUT glProgramUniform4fv.value size not checked against count*4
# INPUT glProgramUniform4dv.value size not checked against count*4
# INPUT glProgramUniform4uiv.value size not checked against count*4
# INPUT glProgramUniformMatrix2fv.value size not checked against count*4
# INPUT glProgramUniformMatrix3fv.value size not checked against count*9
# INPUT glProgramUniformMatrix4fv.value size not checked against count*16
# INPUT glProgramUniformMatrix2dv.value size not checked against count*4
# INPUT glProgramUniformMatrix3dv.value size not checked against count*9
# INPUT glProgramUniformMatrix4dv.value size not checked against count*16
# INPUT glProgramUniformMatrix2x3fv.value size not checked against count*6
# INPUT glProgramUniformMatrix3x2fv.value size not checked against count*6
# INPUT glProgramUniformMatrix2x4fv.value size not checked against count*8
# INPUT glProgramUniformMatrix4x2fv.value size not checked against count*8
# INPUT glProgramUniformMatrix3x4fv.value size not checked against count*12
# INPUT glProgramUniformMatrix4x3fv.value size not checked against count*12
# INPUT glProgramUniformMatrix2x3dv.value size not checked against count*6
# INPUT glProgramUniformMatrix3x2dv.value size not checked against count*6
# INPUT glProgramUniformMatrix2x4dv.value size not checked against count*8
# INPUT glProgramUniformMatrix4x2dv.value size not checked against count*8
# INPUT glProgramUniformMatrix3x4dv.value size not checked against count*12
# INPUT glProgramUniformMatrix4x3dv.value size not checked against count*12
# INPUT glViewportArrayv.v size not checked against 'count'
# INPUT glScissorArrayv.v size not checked against 'count'
# INPUT glDepthRangeArrayv.v size not checked against 'count'
### END AUTOGENERATED SECTION
from OpenGL.GL.ARB.ES2_compatibility import *
from OpenGL.GL.ARB.get_program_binary import *
from OpenGL.GL.ARB.separate_shader_objects import *
from OpenGL.GL.ARB.shader_precision import *
from OpenGL.GL.ARB.vertex_attrib_64bit import *
from OpenGL.GL.ARB.viewport_array import *
