"""OpenGL.GL.VERSION.GL_4_2 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray, IntArrayResult

from OpenGL.raw.GL._types import *

GL_ACTIVE_ATOMIC_COUNTER_BUFFERS: int
GL_ALL_BARRIER_BITS: int
GL_ATOMIC_COUNTER_BARRIER_BIT: int
GL_ATOMIC_COUNTER_BUFFER: int
GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS: int
GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTER_INDICES: int
GL_ATOMIC_COUNTER_BUFFER_BINDING: int
GL_ATOMIC_COUNTER_BUFFER_DATA_SIZE: int
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_FRAGMENT_SHADER: int
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_GEOMETRY_SHADER: int
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_CONTROL_SHADER: int
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_EVALUATION_SHADER: int
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_VERTEX_SHADER: int
GL_ATOMIC_COUNTER_BUFFER_SIZE: int
GL_ATOMIC_COUNTER_BUFFER_START: int
GL_BUFFER_UPDATE_BARRIER_BIT: int
GL_COMMAND_BARRIER_BIT: int
GL_COMPRESSED_RGBA_BPTC_UNORM: int
GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT: int
GL_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT: int
GL_COMPRESSED_SRGB_ALPHA_BPTC_UNORM: int
GL_COPY_READ_BUFFER_BINDING: int
GL_COPY_WRITE_BUFFER_BINDING: int
GL_ELEMENT_ARRAY_BARRIER_BIT: int
GL_FRAMEBUFFER_BARRIER_BIT: int
GL_IMAGE_1D: int
GL_IMAGE_1D_ARRAY: int
GL_IMAGE_2D: int
GL_IMAGE_2D_ARRAY: int
GL_IMAGE_2D_MULTISAMPLE: int
GL_IMAGE_2D_MULTISAMPLE_ARRAY: int
GL_IMAGE_2D_RECT: int
GL_IMAGE_3D: int
GL_IMAGE_BINDING_ACCESS: int
GL_IMAGE_BINDING_FORMAT: int
GL_IMAGE_BINDING_LAYER: int
GL_IMAGE_BINDING_LAYERED: int
GL_IMAGE_BINDING_LEVEL: int
GL_IMAGE_BINDING_NAME: int
GL_IMAGE_BUFFER: int
GL_IMAGE_CUBE: int
GL_IMAGE_CUBE_MAP_ARRAY: int
GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS: int
GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE: int
GL_IMAGE_FORMAT_COMPATIBILITY_TYPE: int
GL_INT_IMAGE_1D: int
GL_INT_IMAGE_1D_ARRAY: int
GL_INT_IMAGE_2D: int
GL_INT_IMAGE_2D_ARRAY: int
GL_INT_IMAGE_2D_MULTISAMPLE: int
GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY: int
GL_INT_IMAGE_2D_RECT: int
GL_INT_IMAGE_3D: int
GL_INT_IMAGE_BUFFER: int
GL_INT_IMAGE_CUBE: int
GL_INT_IMAGE_CUBE_MAP_ARRAY: int
GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS: int
GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE: int
GL_MAX_COMBINED_ATOMIC_COUNTERS: int
GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS: int
GL_MAX_COMBINED_IMAGE_UNIFORMS: int
GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS: int
GL_MAX_FRAGMENT_ATOMIC_COUNTERS: int
GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS: int
GL_MAX_FRAGMENT_IMAGE_UNIFORMS: int
GL_MAX_GEOMETRY_ATOMIC_COUNTERS: int
GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS: int
GL_MAX_GEOMETRY_IMAGE_UNIFORMS: int
GL_MAX_IMAGE_SAMPLES: int
GL_MAX_IMAGE_UNITS: int
GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS: int
GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS: int
GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS: int
GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS: int
GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS: int
GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS: int
GL_MAX_VERTEX_ATOMIC_COUNTERS: int
GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS: int
GL_MAX_VERTEX_IMAGE_UNIFORMS: int
GL_MIN_MAP_BUFFER_ALIGNMENT: int
GL_NUM_SAMPLE_COUNTS: int
GL_PACK_COMPRESSED_BLOCK_DEPTH: int
GL_PACK_COMPRESSED_BLOCK_HEIGHT: int
GL_PACK_COMPRESSED_BLOCK_SIZE: int
GL_PACK_COMPRESSED_BLOCK_WIDTH: int
GL_PIXEL_BUFFER_BARRIER_BIT: int
GL_SHADER_IMAGE_ACCESS_BARRIER_BIT: int
GL_TEXTURE_FETCH_BARRIER_BIT: int
GL_TEXTURE_IMMUTABLE_FORMAT: int
GL_TEXTURE_UPDATE_BARRIER_BIT: int
GL_TRANSFORM_FEEDBACK_ACTIVE: int
GL_TRANSFORM_FEEDBACK_BARRIER_BIT: int
GL_TRANSFORM_FEEDBACK_PAUSED: int
GL_UNIFORM_ATOMIC_COUNTER_BUFFER_INDEX: int
GL_UNIFORM_BARRIER_BIT: int
GL_UNPACK_COMPRESSED_BLOCK_DEPTH: int
GL_UNPACK_COMPRESSED_BLOCK_HEIGHT: int
GL_UNPACK_COMPRESSED_BLOCK_SIZE: int
GL_UNPACK_COMPRESSED_BLOCK_WIDTH: int
GL_UNSIGNED_INT_ATOMIC_COUNTER: int
GL_UNSIGNED_INT_IMAGE_1D: int
GL_UNSIGNED_INT_IMAGE_1D_ARRAY: int
GL_UNSIGNED_INT_IMAGE_2D: int
GL_UNSIGNED_INT_IMAGE_2D_ARRAY: int
GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE: int
GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY: int
GL_UNSIGNED_INT_IMAGE_2D_RECT: int
GL_UNSIGNED_INT_IMAGE_3D: int
GL_UNSIGNED_INT_IMAGE_BUFFER: int
GL_UNSIGNED_INT_IMAGE_CUBE: int
GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY: int
GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT: int

def glBindImageTexture(unit: int, texture: int, level: int, layered: bool, layer: int, access: int, format: int) -> None: ...
def glDrawArraysInstancedBaseInstance(mode: int, first: int, count: int, instancecount: int, baseinstance: int) -> None: ...
def glDrawElementsInstancedBaseInstance(mode: int, count: int, type: int, indices: AnyArray, instancecount: int, baseinstance: int) -> None: ...
def glDrawElementsInstancedBaseVertexBaseInstance(mode: int, count: int, type: int, indices: AnyArray, instancecount: int, basevertex: int, baseinstance: int) -> None: ...
def glDrawTransformFeedbackInstanced(mode: int, id: int, instancecount: int) -> None: ...
def glDrawTransformFeedbackStreamInstanced(mode: int, id: int, stream: int, instancecount: int) -> None: ...
def glGetActiveAtomicCounterBufferiv(program: int, bufferIndex: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetInternalformativ(target: int, internalformat: int, pname: int, count: int, params: IntArray | None = None) -> IntArrayResult: ...
def glMemoryBarrier(barriers: int) -> None: ...
def glTexStorage1D(target: int, levels: int, internalformat: int, width: int) -> None: ...
def glTexStorage2D(target: int, levels: int, internalformat: int, width: int, height: int) -> None: ...
def glTexStorage3D(target: int, levels: int, internalformat: int, width: int, height: int, depth: int) -> None: ...

def glInitGl42VERSION() -> bool: ...

def __getattr__(name: str) -> Any: ...
