"""OpenGL.GL.VERSION.GL_4_5 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, DoubleArray, FloatArray, Int64Array, IntArray, UByteArray, UIntArray, UShortArray

from OpenGL.raw.GL._types import *

GL_BACK: int
GL_CLIP_DEPTH_MODE: int
GL_CLIP_ORIGIN: int
GL_COLOR_TABLE: int
GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT: int
GL_CONTEXT_LOST: int
GL_CONTEXT_RELEASE_BEHAVIOR: int
GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH: int
GL_CONVOLUTION_1D: int
GL_CONVOLUTION_2D: int
GL_GUILTY_CONTEXT_RESET: int
GL_HISTOGRAM: int
GL_INNOCENT_CONTEXT_RESET: int
GL_LOSE_CONTEXT_ON_RESET: int
GL_LOWER_LEFT: int
GL_MAX_COMBINED_CLIP_AND_CULL_DISTANCES: int
GL_MAX_CULL_DISTANCES: int
GL_MINMAX: int
GL_NEGATIVE_ONE_TO_ONE: int
GL_NONE: int
GL_NO_ERROR: int
GL_NO_RESET_NOTIFICATION: int
GL_POST_COLOR_MATRIX_COLOR_TABLE: int
GL_POST_CONVOLUTION_COLOR_TABLE: int
GL_PROXY_COLOR_TABLE: int
GL_PROXY_HISTOGRAM: int
GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE: int
GL_PROXY_POST_CONVOLUTION_COLOR_TABLE: int
GL_QUERY_BY_REGION_NO_WAIT_INVERTED: int
GL_QUERY_BY_REGION_WAIT_INVERTED: int
GL_QUERY_NO_WAIT_INVERTED: int
GL_QUERY_TARGET: int
GL_QUERY_WAIT_INVERTED: int
GL_RESET_NOTIFICATION_STRATEGY: int
GL_SEPARABLE_2D: int
GL_TEXTURE_BINDING_1D: int
GL_TEXTURE_BINDING_1D_ARRAY: int
GL_TEXTURE_BINDING_2D: int
GL_TEXTURE_BINDING_2D_ARRAY: int
GL_TEXTURE_BINDING_2D_MULTISAMPLE: int
GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY: int
GL_TEXTURE_BINDING_3D: int
GL_TEXTURE_BINDING_BUFFER: int
GL_TEXTURE_BINDING_CUBE_MAP: int
GL_TEXTURE_BINDING_CUBE_MAP_ARRAY: int
GL_TEXTURE_BINDING_RECTANGLE: int
GL_TEXTURE_TARGET: int
GL_UNKNOWN_CONTEXT_RESET: int
GL_UPPER_LEFT: int
GL_ZERO_TO_ONE: int

def glBindTextureUnit(unit: int, texture: int) -> None: ...
def glBlitNamedFramebuffer(readFramebuffer: int, drawFramebuffer: int, srcX0: int, srcY0: int, srcX1: int, srcY1: int, dstX0: int, dstY0: int, dstX1: int, dstY1: int, mask: int, filter: int) -> None: ...
def glCheckNamedFramebufferStatus(framebuffer: int, target: int) -> int: ...
def glClearNamedBufferData(buffer: int, internalformat: int, format: int, type: int, data: AnyArray) -> None: ...
def glClearNamedBufferSubData(buffer: int, internalformat: int, offset: int, size: int, format: int, type: int, data: AnyArray) -> None: ...
def glClearNamedFramebufferfi(framebuffer: int, buffer: int, drawbuffer: int, depth: float, stencil: int) -> None: ...
def glClearNamedFramebufferfv(framebuffer: int, buffer: int, drawbuffer: int, value: FloatArray) -> None: ...
def glClearNamedFramebufferiv(framebuffer: int, buffer: int, drawbuffer: int, value: IntArray) -> None: ...
def glClearNamedFramebufferuiv(framebuffer: int, buffer: int, drawbuffer: int, value: UIntArray) -> None: ...
def glClipControl(origin: int, depth: int) -> None: ...
def glCompressedTextureSubImage1D(texture: int, level: int, xoffset: int, width: int, format: int, imageSize: int, data: AnyArray) -> None: ...
def glCompressedTextureSubImage2D(texture: int, level: int, xoffset: int, yoffset: int, width: int, height: int, format: int, imageSize: int, data: AnyArray) -> None: ...
def glCompressedTextureSubImage3D(texture: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, imageSize: int, data: AnyArray) -> None: ...
def glCopyNamedBufferSubData(readBuffer: int, writeBuffer: int, readOffset: int, writeOffset: int, size: int) -> None: ...
def glCopyTextureSubImage1D(texture: int, level: int, xoffset: int, x: int, y: int, width: int) -> None: ...
def glCopyTextureSubImage2D(texture: int, level: int, xoffset: int, yoffset: int, x: int, y: int, width: int, height: int) -> None: ...
def glCopyTextureSubImage3D(texture: int, level: int, xoffset: int, yoffset: int, zoffset: int, x: int, y: int, width: int, height: int) -> None: ...
def glCreateBuffers(n: int, buffers: UIntArray) -> None: ...
def glCreateFramebuffers(n: int, framebuffers: UIntArray) -> None: ...
def glCreateProgramPipelines(n: int, pipelines: UIntArray) -> None: ...
def glCreateQueries(target: int, n: int, ids: UIntArray) -> None: ...
def glCreateRenderbuffers(n: int, renderbuffers: UIntArray) -> None: ...
def glCreateSamplers(n: int, samplers: UIntArray) -> None: ...
def glCreateTextures(target: int, n: int, textures: UIntArray) -> None: ...
def glCreateTransformFeedbacks(n: int, ids: UIntArray) -> None: ...
def glCreateVertexArrays(n: int, arrays: UIntArray) -> None: ...
def glDisableVertexArrayAttrib(vaobj: int, index: int) -> None: ...
def glEnableVertexArrayAttrib(vaobj: int, index: int) -> None: ...
def glFlushMappedNamedBufferRange(buffer: int, offset: int, length: int) -> None: ...
def glGenerateTextureMipmap(texture: int) -> None: ...
def glGetCompressedTextureImage(texture: int, level: int, bufSize: int, pixels: AnyArray) -> None: ...
def glGetCompressedTextureSubImage(texture: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, bufSize: int, pixels: AnyArray) -> None: ...
def glGetGraphicsResetStatus() -> int: ...
def glGetNamedBufferParameteri64v(buffer: int, pname: int, params: Int64Array) -> None: ...
def glGetNamedBufferParameteriv(buffer: int, pname: int, params: IntArray) -> None: ...
def glGetNamedBufferPointerv(buffer: int, pname: int, params: AnyArray) -> None: ...
def glGetNamedBufferSubData(buffer: int, offset: int, size: int, data: AnyArray) -> None: ...
def glGetNamedFramebufferAttachmentParameteriv(framebuffer: int, attachment: int, pname: int, params: IntArray) -> None: ...
def glGetNamedFramebufferParameteriv(framebuffer: int, pname: int, param: IntArray) -> None: ...
def glGetNamedRenderbufferParameteriv(renderbuffer: int, pname: int, params: IntArray) -> None: ...
def glGetQueryBufferObjecti64v(id: int, buffer: int, pname: int, offset: int) -> None: ...
def glGetQueryBufferObjectiv(id: int, buffer: int, pname: int, offset: int) -> None: ...
def glGetQueryBufferObjectui64v(id: int, buffer: int, pname: int, offset: int) -> None: ...
def glGetQueryBufferObjectuiv(id: int, buffer: int, pname: int, offset: int) -> None: ...
def glGetTextureImage(texture: int, level: int, format: int, type: int, bufSize: int, pixels: AnyArray) -> None: ...
def glGetTextureLevelParameterfv(texture: int, level: int, pname: int, params: FloatArray) -> None: ...
def glGetTextureLevelParameteriv(texture: int, level: int, pname: int, params: IntArray) -> None: ...
def glGetTextureParameterIiv(texture: int, pname: int, params: IntArray) -> None: ...
def glGetTextureParameterIuiv(texture: int, pname: int, params: UIntArray) -> None: ...
def glGetTextureParameterfv(texture: int, pname: int, params: FloatArray) -> None: ...
def glGetTextureParameteriv(texture: int, pname: int, params: IntArray) -> None: ...
def glGetTextureSubImage(texture: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, type: int, bufSize: int, pixels: AnyArray) -> None: ...
def glGetTransformFeedbacki64_v(xfb: int, pname: int, index: int, param: Int64Array) -> None: ...
def glGetTransformFeedbacki_v(xfb: int, pname: int, index: int, param: IntArray) -> None: ...
def glGetTransformFeedbackiv(xfb: int, pname: int, param: IntArray) -> None: ...
def glGetVertexArrayIndexed64iv(vaobj: int, index: int, pname: int, param: Int64Array) -> None: ...
def glGetVertexArrayIndexediv(vaobj: int, index: int, pname: int, param: IntArray) -> None: ...
def glGetVertexArrayiv(vaobj: int, pname: int, param: IntArray) -> None: ...
def glGetnColorTable(target: int, format: int, type: int, bufSize: int, table: AnyArray) -> None: ...
def glGetnCompressedTexImage(target: int, lod: int, bufSize: int, pixels: AnyArray) -> None: ...
def glGetnConvolutionFilter(target: int, format: int, type: int, bufSize: int, image: AnyArray) -> None: ...
def glGetnHistogram(target: int, reset: int, format: int, type: int, bufSize: int, values: AnyArray) -> None: ...
def glGetnMapdv(target: int, query: int, bufSize: int, v: DoubleArray) -> None: ...
def glGetnMapfv(target: int, query: int, bufSize: int, v: FloatArray) -> None: ...
def glGetnMapiv(target: int, query: int, bufSize: int, v: IntArray) -> None: ...
def glGetnMinmax(target: int, reset: int, format: int, type: int, bufSize: int, values: AnyArray) -> None: ...
def glGetnPixelMapfv(map: int, bufSize: int, values: FloatArray) -> None: ...
def glGetnPixelMapuiv(map: int, bufSize: int, values: UIntArray) -> None: ...
def glGetnPixelMapusv(map: int, bufSize: int, values: UShortArray) -> None: ...
def glGetnPolygonStipple(bufSize: int, pattern: UByteArray) -> None: ...
def glGetnSeparableFilter(target: int, format: int, type: int, rowBufSize: int, row: AnyArray, columnBufSize: int, column: AnyArray, span: AnyArray) -> None: ...
def glGetnTexImage(target: int, level: int, format: int, type: int, bufSize: int, pixels: AnyArray) -> None: ...
def glGetnUniformdv(program: int, location: int, bufSize: int, params: DoubleArray) -> None: ...
def glGetnUniformfv(program: int, location: int, bufSize: int, params: FloatArray) -> None: ...
def glGetnUniformiv(program: int, location: int, bufSize: int, params: IntArray) -> None: ...
def glGetnUniformuiv(program: int, location: int, bufSize: int, params: UIntArray) -> None: ...
def glInvalidateNamedFramebufferData(framebuffer: int, numAttachments: int, attachments: UIntArray) -> None: ...
def glInvalidateNamedFramebufferSubData(framebuffer: int, numAttachments: int, attachments: UIntArray, x: int, y: int, width: int, height: int) -> None: ...
def glMapNamedBuffer(buffer: int, access: int) -> int | None: ...
def glMapNamedBufferRange(buffer: int, offset: int, length: int, access: int) -> int | None: ...
def glMemoryBarrierByRegion(barriers: int) -> None: ...
def glNamedBufferData(buffer: int, size: int, data: AnyArray, usage: int) -> None: ...
def glNamedBufferStorage(buffer: int, size: int, data: AnyArray, flags: int) -> None: ...
def glNamedBufferSubData(buffer: int, offset: int, size: int, data: AnyArray) -> None: ...
def glNamedFramebufferDrawBuffer(framebuffer: int, buf: int) -> None: ...
def glNamedFramebufferDrawBuffers(framebuffer: int, n: int, bufs: UIntArray) -> None: ...
def glNamedFramebufferParameteri(framebuffer: int, pname: int, param: int) -> None: ...
def glNamedFramebufferReadBuffer(framebuffer: int, src: int) -> None: ...
def glNamedFramebufferRenderbuffer(framebuffer: int, attachment: int, renderbuffertarget: int, renderbuffer: int) -> None: ...
def glNamedFramebufferTexture(framebuffer: int, attachment: int, texture: int, level: int) -> None: ...
def glNamedFramebufferTextureLayer(framebuffer: int, attachment: int, texture: int, level: int, layer: int) -> None: ...
def glNamedRenderbufferStorage(renderbuffer: int, internalformat: int, width: int, height: int) -> None: ...
def glNamedRenderbufferStorageMultisample(renderbuffer: int, samples: int, internalformat: int, width: int, height: int) -> None: ...
def glReadnPixels(x: int, y: int, width: int, height: int, format: int, type: int, bufSize: int, data: AnyArray) -> None: ...
def glTextureBarrier() -> None: ...
def glTextureBuffer(texture: int, internalformat: int, buffer: int) -> None: ...
def glTextureBufferRange(texture: int, internalformat: int, buffer: int, offset: int, size: int) -> None: ...
def glTextureParameterIiv(texture: int, pname: int, params: IntArray) -> None: ...
def glTextureParameterIuiv(texture: int, pname: int, params: UIntArray) -> None: ...
def glTextureParameterf(texture: int, pname: int, param: float) -> None: ...
def glTextureParameterfv(texture: int, pname: int, param: FloatArray) -> None: ...
def glTextureParameteri(texture: int, pname: int, param: int) -> None: ...
def glTextureParameteriv(texture: int, pname: int, param: IntArray) -> None: ...
def glTextureStorage1D(texture: int, levels: int, internalformat: int, width: int) -> None: ...
def glTextureStorage2D(texture: int, levels: int, internalformat: int, width: int, height: int) -> None: ...
def glTextureStorage2DMultisample(texture: int, samples: int, internalformat: int, width: int, height: int, fixedsamplelocations: int) -> None: ...
def glTextureStorage3D(texture: int, levels: int, internalformat: int, width: int, height: int, depth: int) -> None: ...
def glTextureStorage3DMultisample(texture: int, samples: int, internalformat: int, width: int, height: int, depth: int, fixedsamplelocations: int) -> None: ...
def glTextureSubImage1D(texture: int, level: int, xoffset: int, width: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glTextureSubImage2D(texture: int, level: int, xoffset: int, yoffset: int, width: int, height: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glTextureSubImage3D(texture: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glTransformFeedbackBufferBase(xfb: int, index: int, buffer: int) -> None: ...
def glTransformFeedbackBufferRange(xfb: int, index: int, buffer: int, offset: int, size: int) -> None: ...
def glUnmapNamedBuffer(buffer: int) -> int: ...
def glVertexArrayAttribBinding(vaobj: int, attribindex: int, bindingindex: int) -> None: ...
def glVertexArrayAttribFormat(vaobj: int, attribindex: int, size: int, type: int, normalized: int, relativeoffset: int) -> None: ...
def glVertexArrayAttribIFormat(vaobj: int, attribindex: int, size: int, type: int, relativeoffset: int) -> None: ...
def glVertexArrayAttribLFormat(vaobj: int, attribindex: int, size: int, type: int, relativeoffset: int) -> None: ...
def glVertexArrayBindingDivisor(vaobj: int, bindingindex: int, divisor: int) -> None: ...
def glVertexArrayElementBuffer(vaobj: int, buffer: int) -> None: ...
def glVertexArrayVertexBuffer(vaobj: int, bindingindex: int, buffer: int, offset: int, stride: int) -> None: ...
def glVertexArrayVertexBuffers(vaobj: int, first: int, count: int, buffers: UIntArray, offsets: Int64Array, strides: IntArray) -> None: ...

def glInitGl45VERSION() -> bool: ...

def __getattr__(name: str) -> Any: ...
