"""OpenGL.GL.VERSION.GL_4_1 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, AnyArrayResult, ByteArray, ByteArrayResult, DoubleArray, DoubleArrayResult, FloatArray, FloatArrayResult, IntArray, IntArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_ACTIVE_PROGRAM: int
GL_ALL_SHADER_BITS: int
GL_FRAGMENT_SHADER_BIT: int
GL_GEOMETRY_SHADER_BIT: int
GL_HIGH_FLOAT: int
GL_HIGH_INT: int
GL_IMPLEMENTATION_COLOR_READ_FORMAT: int
GL_IMPLEMENTATION_COLOR_READ_TYPE: int
GL_LAYER_PROVOKING_VERTEX: int
GL_LOW_FLOAT: int
GL_LOW_INT: int
GL_MAX_FRAGMENT_UNIFORM_VECTORS: int
GL_MAX_VARYING_VECTORS: int
GL_MAX_VERTEX_UNIFORM_VECTORS: int
GL_MAX_VIEWPORTS: int
GL_MEDIUM_FLOAT: int
GL_MEDIUM_INT: int
GL_NUM_PROGRAM_BINARY_FORMATS: int
GL_NUM_SHADER_BINARY_FORMATS: int
GL_PROGRAM_BINARY_FORMATS: int
GL_PROGRAM_BINARY_LENGTH: int
GL_PROGRAM_BINARY_RETRIEVABLE_HINT: int
GL_PROGRAM_PIPELINE_BINDING: int
GL_PROGRAM_SEPARABLE: int
GL_RGB565: int
GL_SHADER_BINARY_FORMATS: int
GL_SHADER_COMPILER: int
GL_TESS_CONTROL_SHADER_BIT: int
GL_TESS_EVALUATION_SHADER_BIT: int
GL_UNDEFINED_VERTEX: int
GL_VERTEX_SHADER_BIT: int
GL_VIEWPORT_BOUNDS_RANGE: int
GL_VIEWPORT_INDEX_PROVOKING_VERTEX: int
GL_VIEWPORT_SUBPIXEL_BITS: int

def glActiveShaderProgram(pipeline: int, program: int) -> None: ...
def glBindProgramPipeline(pipeline: int) -> None: ...
def glClearDepthf(d: float) -> None: ...
def glCreateShaderProgramv(type: int, count: int, strings: AnyArray) -> int: ...
def glDeleteProgramPipelines(n: int, pipelines: UIntArray) -> None: ...
def glDepthRangeArrayv(first: int, count: int, v: DoubleArray) -> None: ...
def glDepthRangeIndexed(index: int, n: float, f: float) -> None: ...
def glDepthRangef(n: float, f: float) -> None: ...
def glGenProgramPipelines(n: int, pipelines: UIntArray | None = None) -> UIntArrayResult: ...
def glGetDoublei_v(target: int, index: int, data: DoubleArray | None = None) -> DoubleArrayResult: ...
def glGetFloati_v(target: int, index: int, data: FloatArray | None = None) -> FloatArrayResult: ...
def glGetProgramBinary(program: int, bufSize: int, length: IntArray | None = None, binaryFormat: UIntArray | None = None, binary: AnyArray | None = None) -> tuple[AnyArrayResult, UIntArrayResult, IntArrayResult]: ...
def glGetProgramPipelineInfoLog(pipeline: int, bufSize: int, length: IntArray | None = None, infoLog: ByteArray | None = None) -> tuple[ByteArrayResult, IntArrayResult]: ...
def glGetProgramPipelineiv(pipeline: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetShaderPrecisionFormat(shadertype: int, precisiontype: int, range: IntArray | None = None, precision: IntArray | None = None) -> tuple[IntArrayResult, IntArrayResult]: ...
def glGetVertexAttribLdv(index: int, pname: int, params: DoubleArray | None = None) -> DoubleArrayResult: ...
def glIsProgramPipeline(pipeline: int) -> int: ...
def glProgramBinary(program: int, binaryFormat: int, binary: AnyArray, length: int) -> None: ...
def glProgramParameteri(program: int, pname: int, value: int) -> None: ...
def glProgramUniform1d(program: int, location: int, v0: float) -> None: ...
def glProgramUniform1dv(program: int, location: int, count: int, value: DoubleArray) -> None: ...
def glProgramUniform1f(program: int, location: int, v0: float) -> None: ...
def glProgramUniform1fv(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform1i(program: int, location: int, v0: int) -> None: ...
def glProgramUniform1iv(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform1ui(program: int, location: int, v0: int) -> None: ...
def glProgramUniform1uiv(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniform2d(program: int, location: int, v0: float, v1: float) -> None: ...
def glProgramUniform2dv(program: int, location: int, count: int, value: DoubleArray) -> None: ...
def glProgramUniform2f(program: int, location: int, v0: float, v1: float) -> None: ...
def glProgramUniform2fv(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform2i(program: int, location: int, v0: int, v1: int) -> None: ...
def glProgramUniform2iv(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform2ui(program: int, location: int, v0: int, v1: int) -> None: ...
def glProgramUniform2uiv(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniform3d(program: int, location: int, v0: float, v1: float, v2: float) -> None: ...
def glProgramUniform3dv(program: int, location: int, count: int, value: DoubleArray) -> None: ...
def glProgramUniform3f(program: int, location: int, v0: float, v1: float, v2: float) -> None: ...
def glProgramUniform3fv(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform3i(program: int, location: int, v0: int, v1: int, v2: int) -> None: ...
def glProgramUniform3iv(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform3ui(program: int, location: int, v0: int, v1: int, v2: int) -> None: ...
def glProgramUniform3uiv(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniform4d(program: int, location: int, v0: float, v1: float, v2: float, v3: float) -> None: ...
def glProgramUniform4dv(program: int, location: int, count: int, value: DoubleArray) -> None: ...
def glProgramUniform4f(program: int, location: int, v0: float, v1: float, v2: float, v3: float) -> None: ...
def glProgramUniform4fv(program: int, location: int, count: int, value: FloatArray) -> None: ...
def glProgramUniform4i(program: int, location: int, v0: int, v1: int, v2: int, v3: int) -> None: ...
def glProgramUniform4iv(program: int, location: int, count: int, value: IntArray) -> None: ...
def glProgramUniform4ui(program: int, location: int, v0: int, v1: int, v2: int, v3: int) -> None: ...
def glProgramUniform4uiv(program: int, location: int, count: int, value: UIntArray) -> None: ...
def glProgramUniformMatrix2dv(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix2fv(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix2x3dv(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix2x3fv(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix2x4dv(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix2x4fv(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix3dv(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix3fv(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix3x2dv(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix3x2fv(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix3x4dv(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix3x4fv(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix4dv(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix4fv(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix4x2dv(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix4x2fv(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glProgramUniformMatrix4x3dv(program: int, location: int, count: int, transpose: bool, value: DoubleArray) -> None: ...
def glProgramUniformMatrix4x3fv(program: int, location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glReleaseShaderCompiler() -> None: ...
def glScissorArrayv(first: int, count: int, v: IntArray) -> None: ...
def glScissorIndexed(index: int, left: int, bottom: int, width: int, height: int) -> None: ...
def glScissorIndexedv(index: int, v: IntArray) -> None: ...
def glShaderBinary(count: int, shaders: UIntArray, binaryFormat: int, binary: AnyArray, length: int) -> None: ...
def glUseProgramStages(pipeline: int, stages: int, program: int) -> None: ...
def glValidateProgramPipeline(pipeline: int) -> None: ...
def glVertexAttribL1d(index: int, x: float) -> None: ...
def glVertexAttribL1dv(index: int, v: DoubleArray) -> None: ...
def glVertexAttribL2d(index: int, x: float, y: float) -> None: ...
def glVertexAttribL2dv(index: int, v: DoubleArray) -> None: ...
def glVertexAttribL3d(index: int, x: float, y: float, z: float) -> None: ...
def glVertexAttribL3dv(index: int, v: DoubleArray) -> None: ...
def glVertexAttribL4d(index: int, x: float, y: float, z: float, w: float) -> None: ...
def glVertexAttribL4dv(index: int, v: DoubleArray) -> None: ...
def glVertexAttribLPointer(index: int, size: int, type: int, stride: int, pointer: AnyArray) -> None: ...
def glViewportArrayv(first: int, count: int, v: FloatArray) -> None: ...
def glViewportIndexedf(index: int, x: float, y: float, w: float, h: float) -> None: ...
def glViewportIndexedfv(index: int, v: FloatArray) -> None: ...

def glInitGl41VERSION() -> bool: ...

def __getattr__(name: str) -> Any: ...
