"""OpenGL.GL.VERSION.GL_4_0 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, ByteArray, ByteArrayResult, DoubleArray, FloatArray, IntArray, IntArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_ACTIVE_SUBROUTINES: int
GL_ACTIVE_SUBROUTINE_MAX_LENGTH: int
GL_ACTIVE_SUBROUTINE_UNIFORMS: int
GL_ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS: int
GL_ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH: int
GL_COMPATIBLE_SUBROUTINES: int
GL_DOUBLE_MAT2: int
GL_DOUBLE_MAT2x3: int
GL_DOUBLE_MAT2x4: int
GL_DOUBLE_MAT3: int
GL_DOUBLE_MAT3x2: int
GL_DOUBLE_MAT3x4: int
GL_DOUBLE_MAT4: int
GL_DOUBLE_MAT4x2: int
GL_DOUBLE_MAT4x3: int
GL_DOUBLE_VEC2: int
GL_DOUBLE_VEC3: int
GL_DOUBLE_VEC4: int
GL_DRAW_INDIRECT_BUFFER: int
GL_DRAW_INDIRECT_BUFFER_BINDING: int
GL_FRACTIONAL_EVEN: int
GL_FRACTIONAL_ODD: int
GL_FRAGMENT_INTERPOLATION_OFFSET_BITS: int
GL_GEOMETRY_SHADER_INVOCATIONS: int
GL_INT_SAMPLER_CUBE_MAP_ARRAY: int
GL_ISOLINES: int
GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS: int
GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS: int
GL_MAX_FRAGMENT_INTERPOLATION_OFFSET: int
GL_MAX_GEOMETRY_SHADER_INVOCATIONS: int
GL_MAX_PATCH_VERTICES: int
GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET: int
GL_MAX_SUBROUTINES: int
GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS: int
GL_MAX_TESS_CONTROL_INPUT_COMPONENTS: int
GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS: int
GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS: int
GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS: int
GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS: int
GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS: int
GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS: int
GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS: int
GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS: int
GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS: int
GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS: int
GL_MAX_TESS_GEN_LEVEL: int
GL_MAX_TESS_PATCH_COMPONENTS: int
GL_MAX_TRANSFORM_FEEDBACK_BUFFERS: int
GL_MAX_VERTEX_STREAMS: int
GL_MIN_FRAGMENT_INTERPOLATION_OFFSET: int
GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET: int
GL_MIN_SAMPLE_SHADING_VALUE: int
GL_NUM_COMPATIBLE_SUBROUTINES: int
GL_PATCHES: int
GL_PATCH_DEFAULT_INNER_LEVEL: int
GL_PATCH_DEFAULT_OUTER_LEVEL: int
GL_PATCH_VERTICES: int
GL_PROXY_TEXTURE_CUBE_MAP_ARRAY: int
GL_QUADS: int
GL_SAMPLER_CUBE_MAP_ARRAY: int
GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW: int
GL_SAMPLE_SHADING: int
GL_TESS_CONTROL_OUTPUT_VERTICES: int
GL_TESS_CONTROL_SHADER: int
GL_TESS_EVALUATION_SHADER: int
GL_TESS_GEN_MODE: int
GL_TESS_GEN_POINT_MODE: int
GL_TESS_GEN_SPACING: int
GL_TESS_GEN_VERTEX_ORDER: int
GL_TEXTURE_BINDING_CUBE_MAP_ARRAY: int
GL_TEXTURE_CUBE_MAP_ARRAY: int
GL_TRANSFORM_FEEDBACK: int
GL_TRANSFORM_FEEDBACK_BINDING: int
GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE: int
GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED: int
GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER: int
GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER: int
GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY: int

def glBeginQueryIndexed(target: int, index: int, id: int) -> None: ...
def glBindTransformFeedback(target: int, id: int) -> None: ...
def glBlendEquationSeparatei(buf: int, modeRGB: int, modeAlpha: int) -> None: ...
def glBlendEquationi(buf: int, mode: int) -> None: ...
def glBlendFuncSeparatei(buf: int, srcRGB: int, dstRGB: int, srcAlpha: int, dstAlpha: int) -> None: ...
def glBlendFunci(buf: int, src: int, dst: int) -> None: ...
def glDeleteTransformFeedbacks(n: int, ids: UIntArray) -> None: ...
def glDrawArraysIndirect(mode: int, indirect: AnyArray) -> None: ...
def glDrawElementsIndirect(mode: int, type: int, indirect: AnyArray) -> None: ...
def glDrawTransformFeedback(mode: int, id: int) -> None: ...
def glDrawTransformFeedbackStream(mode: int, id: int, stream: int) -> None: ...
def glEndQueryIndexed(target: int, index: int) -> None: ...
def glGenTransformFeedbacks(n: int, ids: UIntArray | None = None) -> UIntArrayResult: ...
def glGetActiveSubroutineName(program: int, shadertype: int, index: int, bufSize: int, length: IntArray | None = None, name: ByteArray | None = None) -> tuple[IntArrayResult, ByteArrayResult]: ...
def glGetActiveSubroutineUniformName(program: int, shadertype: int, index: int, bufSize: int, length: IntArray | None = None, name: ByteArray | None = None) -> tuple[IntArrayResult, ByteArrayResult]: ...
def glGetActiveSubroutineUniformiv(program: int, shadertype: int, index: int, pname: int, values: IntArray | None = None) -> IntArrayResult: ...
def glGetProgramStageiv(program: int, shadertype: int, pname: int, values: IntArray | None = None) -> IntArrayResult: ...
def glGetQueryIndexediv(target: int, index: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetSubroutineIndex(program: int, shadertype: int, name: ByteArray) -> int: ...
def glGetSubroutineUniformLocation(program: int, shadertype: int, name: ByteArray) -> int: ...
def glGetUniformSubroutineuiv(shadertype: int, location: int, params: UIntArray | None = None) -> UIntArrayResult: ...
def glGetUniformdv(program: int, location: int, params: DoubleArray) -> None: ...
def glIsTransformFeedback(id: int) -> int: ...
def glMinSampleShading(value: float) -> None: ...
def glPatchParameterfv(pname: int, values: FloatArray) -> None: ...
def glPatchParameteri(pname: int, value: int) -> None: ...
def glPauseTransformFeedback() -> None: ...
def glResumeTransformFeedback() -> None: ...
def glUniform1d(location: int, x: float) -> None: ...
def glUniform1dv(location: int, count: int, value: DoubleArray) -> None: ...
def glUniform2d(location: int, x: float, y: float) -> None: ...
def glUniform2dv(location: int, count: int, value: DoubleArray) -> None: ...
def glUniform3d(location: int, x: float, y: float, z: float) -> None: ...
def glUniform3dv(location: int, count: int, value: DoubleArray) -> None: ...
def glUniform4d(location: int, x: float, y: float, z: float, w: float) -> None: ...
def glUniform4dv(location: int, count: int, value: DoubleArray) -> None: ...
def glUniformMatrix2dv(location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glUniformMatrix2x3dv(location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glUniformMatrix2x4dv(location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glUniformMatrix3dv(location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glUniformMatrix3x2dv(location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glUniformMatrix3x4dv(location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glUniformMatrix4dv(location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glUniformMatrix4x2dv(location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glUniformMatrix4x3dv(location: int, count: int, transpose: int, value: DoubleArray) -> None: ...
def glUniformSubroutinesuiv(shadertype: int, count: int, indices: UIntArray) -> None: ...

def glInitGl40VERSION() -> bool: ...

def __getattr__(name: str) -> Any: ...
