'''OpenGL extension IBM.cull_vertex

This module customises the behaviour of the 
OpenGL.raw.GL.IBM.cull_vertex to provide a more 
Python-friendly API

The official definition of this extension is available here:
http://www.opengl.org/registry/specs/IBM/cull_vertex.txt
'''
from OpenGL import platform, constant, arrays
from OpenGL import extensions, wrapper
from OpenGL.GL import glget
import ctypes
from OpenGL.raw.GL import _types
from OpenGL.raw.GL.IBM.cull_vertex import *
from OpenGL.raw.GL.IBM.cull_vertex import _EXTENSION_NAME

def glInitCullVertexIBM():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( _EXTENSION_NAME )

### END AUTOGENERATED SECTION