'''OpenGL extension GREMEDY.frame_terminator

This module customises the behaviour of the 
OpenGL.raw.GL.GREMEDY.frame_terminator to provide a more 
Python-friendly API
'''
from OpenGL import platform, constants, constant, arrays
from OpenGL import extensions, wrapper
from OpenGL.GL import glget
import ctypes
from OpenGL.raw.GL.GREMEDY.frame_terminator import *
### END AUTOGENERATED SECTION