"""OpenGL.WGL.EXT.display_color_table -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UShortArray

from OpenGL.raw.WGL._types import *

def wglBindDisplayColorTableEXT(id: int) -> int: ...
def wglCreateDisplayColorTableEXT(id: int) -> int: ...
def wglDestroyDisplayColorTableEXT(id: int) -> Any: ...
def wglLoadDisplayColorTableEXT(table: UShortArray, length: int) -> int: ...

def glInitDisplayColorTableEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
