"""OpenGL.WGL.EXT.swap_control -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.WGL._types import *

def wglGetSwapIntervalEXT() -> int: ...
def wglSwapIntervalEXT(interval: int) -> int: ...

def glInitSwapControlEXT() -> bool: ...

def __getattr__(name: str) -> Any: ...
