"""Type stubs for OpenGL.GLSC2, generated by src/cdispatch.

Regenerate with:  python src/regenerate_c.py
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, TypeAlias

#: Anything the layer accepts where an array of this element type is wanted.
#: A matching buffer is used directly and anything else is converted, so the
#: alias is deliberately wide.
ByteArray: TypeAlias = Any | Sequence[Any] | bytes | memoryview | None
DoubleArray: TypeAlias = Any | Sequence[Any] | bytes | memoryview | None
FloatArray: TypeAlias = Any | Sequence[Any] | bytes | memoryview | None
Int64Array: TypeAlias = Any | Sequence[Any] | bytes | memoryview | None
IntArray: TypeAlias = Any | Sequence[Any] | bytes | memoryview | None
ShortArray: TypeAlias = Any | Sequence[Any] | bytes | memoryview | None
UByteArray: TypeAlias = Any | Sequence[Any] | bytes | memoryview | None
UInt64Array: TypeAlias = Any | Sequence[Any] | bytes | memoryview | None
UIntArray: TypeAlias = Any | Sequence[Any] | bytes | memoryview | None
UShortArray: TypeAlias = Any | Sequence[Any] | bytes | memoryview | None
AnyArray: TypeAlias = Any | Sequence[Any] | bytes | memoryview | None

def glActiveTexture(texture: int) -> None:
    """glActiveTexture(texture) -> None"""

def glBindBuffer(target: int, buffer: int) -> None:
    """glBindBuffer(target, buffer) -> None"""

def glBindFramebuffer(target: int, framebuffer: int) -> None:
    """glBindFramebuffer(target, framebuffer) -> None"""

def glBindRenderbuffer(target: int, renderbuffer: int) -> None:
    """glBindRenderbuffer(target, renderbuffer) -> None"""

def glBindTexture(target: int, texture: int) -> None:
    """glBindTexture(target, texture) -> None"""

def glBlendColor(red: float, green: float, blue: float, alpha: float) -> None:
    """glBlendColor(red, green, blue, alpha) -> None"""

def glBlendEquation(mode: int) -> None:
    """glBlendEquation(mode) -> None"""

def glBlendEquationSeparate(modeRGB: int, modeAlpha: int) -> None:
    """glBlendEquationSeparate(modeRGB, modeAlpha) -> None"""

def glBlendFunc(sfactor: int, dfactor: int) -> None:
    """glBlendFunc(sfactor, dfactor) -> None"""

def glBlendFuncSeparate(sfactorRGB: int, dfactorRGB: int, sfactorAlpha: int, dfactorAlpha: int) -> None:
    """glBlendFuncSeparate(sfactorRGB, dfactorRGB, sfactorAlpha, dfactorAlpha) -> None"""

def glBufferData(target: int, size: int, data: AnyArray, usage: int) -> None:
    """glBufferData(target, size, data, usage) -> None"""

def glBufferSubData(target: int, offset: int, size: int, data: AnyArray) -> None:
    """glBufferSubData(target, offset, size, data) -> None"""

def glCheckFramebufferStatus(target: int) -> int:
    """glCheckFramebufferStatus(target) -> GLenum"""

def glClear(mask: int) -> None:
    """glClear(mask) -> None"""

def glClearColor(red: float, green: float, blue: float, alpha: float) -> None:
    """glClearColor(red, green, blue, alpha) -> None"""

def glClearDepthf(d: float) -> None:
    """glClearDepthf(d) -> None"""

def glClearStencil(s: int) -> None:
    """glClearStencil(s) -> None"""

def glColorMask(red: bool, green: bool, blue: bool, alpha: bool) -> None:
    """glColorMask(red, green, blue, alpha) -> None"""

def glCompressedTexSubImage2D(target: int, level: int, xoffset: int, yoffset: int, width: int, height: int, format: int, imageSize: int, data: AnyArray) -> None:
    """glCompressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, imageSize, data) -> None"""

def glCreateProgram() -> int:
    """glCreateProgram() -> GLuint"""

def glCullFace(mode: int) -> None:
    """glCullFace(mode) -> None"""

def glDepthFunc(func: int) -> None:
    """glDepthFunc(func) -> None"""

def glDepthMask(flag: bool) -> None:
    """glDepthMask(flag) -> None"""

def glDepthRangef(n: float, f: float) -> None:
    """glDepthRangef(n, f) -> None"""

def glDisable(cap: int) -> None:
    """glDisable(cap) -> None"""

def glDisableVertexAttribArray(index: int) -> None:
    """glDisableVertexAttribArray(index) -> None"""

def glDrawArrays(mode: int, first: int, count: int) -> None:
    """glDrawArrays(mode, first, count) -> None"""

def glDrawRangeElements(mode: int, start: int, end: int, count: int, type: int, indices: AnyArray) -> None:
    """glDrawRangeElements(mode, start, end, count, type, indices) -> None"""

def glEnable(cap: int) -> None:
    """glEnable(cap) -> None"""

def glEnableVertexAttribArray(index: int) -> None:
    """glEnableVertexAttribArray(index) -> None"""

def glFinish() -> None:
    """glFinish() -> None"""

def glFlush() -> None:
    """glFlush() -> None"""

def glFramebufferRenderbuffer(target: int, attachment: int, renderbuffertarget: int, renderbuffer: int) -> None:
    """glFramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer) -> None"""

def glFramebufferTexture2D(target: int, attachment: int, textarget: int, texture: int, level: int) -> None:
    """glFramebufferTexture2D(target, attachment, textarget, texture, level) -> None"""

def glFrontFace(mode: int) -> None:
    """glFrontFace(mode) -> None"""

def glGenBuffers(n: int, buffers: UIntArray | None = None) -> UIntArray:
    """glGenBuffers(n) -> buffers"""

def glGenFramebuffers(n: int, framebuffers: UIntArray | None = None) -> UIntArray:
    """glGenFramebuffers(n) -> framebuffers"""

def glGenRenderbuffers(n: int, renderbuffers: UIntArray | None = None) -> UIntArray:
    """glGenRenderbuffers(n) -> renderbuffers"""

def glGenTextures(n: int, textures: UIntArray | None = None) -> UIntArray:
    """glGenTextures(n) -> textures"""

def glGenerateMipmap(target: int) -> None:
    """glGenerateMipmap(target) -> None"""

def glGetAttribLocation(program: int, name: ByteArray) -> int:
    """glGetAttribLocation(program, name) -> GLint"""

def glGetBooleanv(pname: int, data: UByteArray | None = None) -> UByteArray:
    """glGetBooleanv(pname) -> data"""

def glGetBufferParameteriv(target: int, pname: int, params: IntArray | None = None) -> IntArray:
    """glGetBufferParameteriv(target, pname) -> params"""

def glGetError() -> int:
    """glGetError() -> GLenum"""

def glGetFloatv(pname: int, data: FloatArray | None = None) -> FloatArray:
    """glGetFloatv(pname) -> data"""

def glGetFramebufferAttachmentParameteriv(target: int, attachment: int, pname: int, params: IntArray | None = None) -> IntArray:
    """glGetFramebufferAttachmentParameteriv(target, attachment, pname) -> params"""

def glGetGraphicsResetStatus() -> int:
    """glGetGraphicsResetStatus() -> GLenum"""

def glGetIntegerv(pname: int, data: IntArray | None = None) -> IntArray:
    """glGetIntegerv(pname) -> data"""

def glGetProgramiv(program: int, pname: int, params: IntArray | None = None) -> IntArray:
    """glGetProgramiv(program, pname) -> params"""

def glGetRenderbufferParameteriv(target: int, pname: int, params: IntArray | None = None) -> IntArray:
    """glGetRenderbufferParameteriv(target, pname) -> params"""

def glGetString(name: int) -> bytes:
    """glGetString(name) -> GLubyte"""

def glGetTexParameterfv(target: int, pname: int, params: FloatArray | None = None) -> FloatArray:
    """glGetTexParameterfv(target, pname) -> params"""

def glGetTexParameteriv(target: int, pname: int, params: IntArray | None = None) -> IntArray:
    """glGetTexParameteriv(target, pname) -> params"""

def glGetUniformLocation(program: int, name: ByteArray) -> int:
    """glGetUniformLocation(program, name) -> GLint"""

def glGetVertexAttribPointerv(index: int, pname: int, pointer: AnyArray | None = None) -> AnyArray:
    """glGetVertexAttribPointerv(index, pname) -> pointer"""

def glGetVertexAttribfv(index: int, pname: int, params: FloatArray | None = None) -> FloatArray:
    """glGetVertexAttribfv(index, pname) -> params"""

def glGetVertexAttribiv(index: int, pname: int, params: IntArray | None = None) -> IntArray:
    """glGetVertexAttribiv(index, pname) -> params"""

def glGetnUniformfv(program: int, location: int, bufSize: int, params: FloatArray) -> None:
    """glGetnUniformfv(program, location, bufSize, params) -> None"""

def glGetnUniformiv(program: int, location: int, bufSize: int, params: IntArray) -> None:
    """glGetnUniformiv(program, location, bufSize, params) -> None"""

def glHint(target: int, mode: int) -> None:
    """glHint(target, mode) -> None"""

def glIsEnabled(cap: int) -> int:
    """glIsEnabled(cap) -> GLboolean"""

def glLineWidth(width: float) -> None:
    """glLineWidth(width) -> None"""

def glPixelStorei(pname: int, param: int) -> None:
    """glPixelStorei(pname, param) -> None"""

def glPolygonOffset(factor: float, units: float) -> None:
    """glPolygonOffset(factor, units) -> None"""

def glProgramBinary(program: int, binaryFormat: int, binary: AnyArray, length: int) -> None:
    """glProgramBinary(program, binaryFormat, binary, length) -> None"""

def glReadnPixels(x: int, y: int, width: int, height: int, format: int, type: int, bufSize: int, data: AnyArray) -> None:
    """glReadnPixels(x, y, width, height, format, type, bufSize, data) -> None"""

def glRenderbufferStorage(target: int, internalformat: int, width: int, height: int) -> None:
    """glRenderbufferStorage(target, internalformat, width, height) -> None"""

def glSampleCoverage(value: float, invert: bool) -> None:
    """glSampleCoverage(value, invert) -> None"""

def glScissor(x: int, y: int, width: int, height: int) -> None:
    """glScissor(x, y, width, height) -> None"""

def glStencilFunc(func: int, ref: int, mask: int) -> None:
    """glStencilFunc(func, ref, mask) -> None"""

def glStencilFuncSeparate(face: int, func: int, ref: int, mask: int) -> None:
    """glStencilFuncSeparate(face, func, ref, mask) -> None"""

def glStencilMask(mask: int) -> None:
    """glStencilMask(mask) -> None"""

def glStencilMaskSeparate(face: int, mask: int) -> None:
    """glStencilMaskSeparate(face, mask) -> None"""

def glStencilOp(fail: int, zfail: int, zpass: int) -> None:
    """glStencilOp(fail, zfail, zpass) -> None"""

def glStencilOpSeparate(face: int, sfail: int, dpfail: int, dppass: int) -> None:
    """glStencilOpSeparate(face, sfail, dpfail, dppass) -> None"""

def glTexParameterf(target: int, pname: int, param: float) -> None:
    """glTexParameterf(target, pname, param) -> None"""

def glTexParameterfv(target: int, pname: int, params: FloatArray) -> None:
    """glTexParameterfv(target, pname, params) -> None"""

def glTexParameteri(target: int, pname: int, param: int) -> None:
    """glTexParameteri(target, pname, param) -> None"""

def glTexParameteriv(target: int, pname: int, params: IntArray) -> None:
    """glTexParameteriv(target, pname, params) -> None"""

def glTexStorage2D(target: int, levels: int, internalformat: int, width: int, height: int) -> None:
    """glTexStorage2D(target, levels, internalformat, width, height) -> None"""

def glTexSubImage2D(target: int, level: int, xoffset: int, yoffset: int, width: int, height: int, format: int, type: int, pixels: AnyArray) -> None:
    """glTexSubImage2D(target, level, xoffset, yoffset, width, height, format, type, pixels) -> None"""

def glUniform1f(location: int, v0: float) -> None:
    """glUniform1f(location, v0) -> None"""

def glUniform1fv(location: int, count: int, value: FloatArray) -> None:
    """glUniform1fv(location, count, value) -> None"""

def glUniform1i(location: int, v0: int) -> None:
    """glUniform1i(location, v0) -> None"""

def glUniform1iv(location: int, count: int, value: IntArray) -> None:
    """glUniform1iv(location, count, value) -> None"""

def glUniform2f(location: int, v0: float, v1: float) -> None:
    """glUniform2f(location, v0, v1) -> None"""

def glUniform2fv(location: int, count: int, value: FloatArray) -> None:
    """glUniform2fv(location, count, value) -> None"""

def glUniform2i(location: int, v0: int, v1: int) -> None:
    """glUniform2i(location, v0, v1) -> None"""

def glUniform2iv(location: int, count: int, value: IntArray) -> None:
    """glUniform2iv(location, count, value) -> None"""

def glUniform3f(location: int, v0: float, v1: float, v2: float) -> None:
    """glUniform3f(location, v0, v1, v2) -> None"""

def glUniform3fv(location: int, count: int, value: FloatArray) -> None:
    """glUniform3fv(location, count, value) -> None"""

def glUniform3i(location: int, v0: int, v1: int, v2: int) -> None:
    """glUniform3i(location, v0, v1, v2) -> None"""

def glUniform3iv(location: int, count: int, value: IntArray) -> None:
    """glUniform3iv(location, count, value) -> None"""

def glUniform4f(location: int, v0: float, v1: float, v2: float, v3: float) -> None:
    """glUniform4f(location, v0, v1, v2, v3) -> None"""

def glUniform4fv(location: int, count: int, value: FloatArray) -> None:
    """glUniform4fv(location, count, value) -> None"""

def glUniform4i(location: int, v0: int, v1: int, v2: int, v3: int) -> None:
    """glUniform4i(location, v0, v1, v2, v3) -> None"""

def glUniform4iv(location: int, count: int, value: IntArray) -> None:
    """glUniform4iv(location, count, value) -> None"""

def glUniformMatrix2fv(location: int, count: int, transpose: bool, value: FloatArray) -> None:
    """glUniformMatrix2fv(location, count, transpose, value) -> None"""

def glUniformMatrix3fv(location: int, count: int, transpose: bool, value: FloatArray) -> None:
    """glUniformMatrix3fv(location, count, transpose, value) -> None"""

def glUniformMatrix4fv(location: int, count: int, transpose: bool, value: FloatArray) -> None:
    """glUniformMatrix4fv(location, count, transpose, value) -> None"""

def glUseProgram(program: int) -> None:
    """glUseProgram(program) -> None"""

def glVertexAttrib1f(index: int, x: float) -> None:
    """glVertexAttrib1f(index, x) -> None"""

def glVertexAttrib1fv(index: int, v: FloatArray) -> None:
    """glVertexAttrib1fv(index, v) -> None"""

def glVertexAttrib2f(index: int, x: float, y: float) -> None:
    """glVertexAttrib2f(index, x, y) -> None"""

def glVertexAttrib2fv(index: int, v: FloatArray) -> None:
    """glVertexAttrib2fv(index, v) -> None"""

def glVertexAttrib3f(index: int, x: float, y: float, z: float) -> None:
    """glVertexAttrib3f(index, x, y, z) -> None"""

def glVertexAttrib3fv(index: int, v: FloatArray) -> None:
    """glVertexAttrib3fv(index, v) -> None"""

def glVertexAttrib4f(index: int, x: float, y: float, z: float, w: float) -> None:
    """glVertexAttrib4f(index, x, y, z, w) -> None"""

def glVertexAttrib4fv(index: int, v: FloatArray) -> None:
    """glVertexAttrib4fv(index, v) -> None"""

def glVertexAttribPointer(index: int, size: int, type: int, normalized: bool, stride: int, pointer: AnyArray) -> None:
    """glVertexAttribPointer(index, size, type, normalized, stride, pointer) -> None"""

def glViewport(x: int, y: int, width: int, height: int) -> None:
    """glViewport(x, y, width, height) -> None"""
