"""OpenGL.GLES2.NV.draw_instanced -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.GLES2._types import *

def glDrawArraysInstancedNV(mode: int, first: int, count: int, primcount: int) -> None: ...
def glDrawElementsInstancedNV(mode: int, count: int, type: int, indices: AnyArray, primcount: int) -> None: ...

def glInitDrawInstancedNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
