"""OpenGL.GLES2.NV.fence -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray, IntArrayResult, UIntArray, UIntArrayResult

from OpenGL.raw.GLES2._types import *

GL_ALL_COMPLETED_NV: int
GL_FENCE_CONDITION_NV: int
GL_FENCE_STATUS_NV: int

def glDeleteFencesNV(n: int, fences: UIntArray) -> None: ...
def glFinishFenceNV(fence: int) -> None: ...
def glGenFencesNV(n: int, fences: UIntArray | None = None) -> UIntArrayResult: ...
def glGetFenceivNV(fence: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glIsFenceNV(fence: int) -> int: ...
def glSetFenceNV(fence: int, condition: int) -> None: ...
def glTestFenceNV(fence: int) -> int: ...

def glInitFenceNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
