"""OpenGL.GLES2.NV.gpu_shader5 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import Int64Array, UInt64Array

from OpenGL.raw.GLES2._types import *

GL_FLOAT16_NV: int
GL_FLOAT16_VEC2_NV: int
GL_FLOAT16_VEC3_NV: int
GL_FLOAT16_VEC4_NV: int
GL_INT16_NV: int
GL_INT16_VEC2_NV: int
GL_INT16_VEC3_NV: int
GL_INT16_VEC4_NV: int
GL_INT64_NV: int
GL_INT64_VEC2_NV: int
GL_INT64_VEC3_NV: int
GL_INT64_VEC4_NV: int
GL_INT8_NV: int
GL_INT8_VEC2_NV: int
GL_INT8_VEC3_NV: int
GL_INT8_VEC4_NV: int
GL_PATCHES: int
GL_UNSIGNED_INT16_NV: int
GL_UNSIGNED_INT16_VEC2_NV: int
GL_UNSIGNED_INT16_VEC3_NV: int
GL_UNSIGNED_INT16_VEC4_NV: int
GL_UNSIGNED_INT64_NV: int
GL_UNSIGNED_INT64_VEC2_NV: int
GL_UNSIGNED_INT64_VEC3_NV: int
GL_UNSIGNED_INT64_VEC4_NV: int
GL_UNSIGNED_INT8_NV: int
GL_UNSIGNED_INT8_VEC2_NV: int
GL_UNSIGNED_INT8_VEC3_NV: int
GL_UNSIGNED_INT8_VEC4_NV: int

def glGetUniformi64vNV(program: int, location: int, params: Int64Array) -> None: ...
def glProgramUniform1i64NV(program: int, location: int, x: int) -> None: ...
def glProgramUniform1i64vNV(program: int, location: int, count: int, value: Int64Array) -> None: ...
def glProgramUniform1ui64NV(program: int, location: int, x: int) -> None: ...
def glProgramUniform1ui64vNV(program: int, location: int, count: int, value: UInt64Array) -> None: ...
def glProgramUniform2i64NV(program: int, location: int, x: int, y: int) -> None: ...
def glProgramUniform2i64vNV(program: int, location: int, count: int, value: Int64Array) -> None: ...
def glProgramUniform2ui64NV(program: int, location: int, x: int, y: int) -> None: ...
def glProgramUniform2ui64vNV(program: int, location: int, count: int, value: UInt64Array) -> None: ...
def glProgramUniform3i64NV(program: int, location: int, x: int, y: int, z: int) -> None: ...
def glProgramUniform3i64vNV(program: int, location: int, count: int, value: Int64Array) -> None: ...
def glProgramUniform3ui64NV(program: int, location: int, x: int, y: int, z: int) -> None: ...
def glProgramUniform3ui64vNV(program: int, location: int, count: int, value: UInt64Array) -> None: ...
def glProgramUniform4i64NV(program: int, location: int, x: int, y: int, z: int, w: int) -> None: ...
def glProgramUniform4i64vNV(program: int, location: int, count: int, value: Int64Array) -> None: ...
def glProgramUniform4ui64NV(program: int, location: int, x: int, y: int, z: int, w: int) -> None: ...
def glProgramUniform4ui64vNV(program: int, location: int, count: int, value: UInt64Array) -> None: ...
def glUniform1i64NV(location: int, x: int) -> None: ...
def glUniform1i64vNV(location: int, count: int, value: Int64Array) -> None: ...
def glUniform1ui64NV(location: int, x: int) -> None: ...
def glUniform1ui64vNV(location: int, count: int, value: UInt64Array) -> None: ...
def glUniform2i64NV(location: int, x: int, y: int) -> None: ...
def glUniform2i64vNV(location: int, count: int, value: Int64Array) -> None: ...
def glUniform2ui64NV(location: int, x: int, y: int) -> None: ...
def glUniform2ui64vNV(location: int, count: int, value: UInt64Array) -> None: ...
def glUniform3i64NV(location: int, x: int, y: int, z: int) -> None: ...
def glUniform3i64vNV(location: int, count: int, value: Int64Array) -> None: ...
def glUniform3ui64NV(location: int, x: int, y: int, z: int) -> None: ...
def glUniform3ui64vNV(location: int, count: int, value: UInt64Array) -> None: ...
def glUniform4i64NV(location: int, x: int, y: int, z: int, w: int) -> None: ...
def glUniform4i64vNV(location: int, count: int, value: Int64Array) -> None: ...
def glUniform4ui64NV(location: int, x: int, y: int, z: int, w: int) -> None: ...
def glUniform4ui64vNV(location: int, count: int, value: UInt64Array) -> None: ...

def glInitGpuShader5NV() -> bool: ...

def __getattr__(name: str) -> Any: ...
