"""OpenGL.GLES2.NV.mesh_shader -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GLES2._types import *

GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_MESH_SHADER_NV: int
GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TASK_SHADER_NV: int
GL_MAX_COMBINED_MESH_UNIFORM_COMPONENTS_NV: int
GL_MAX_COMBINED_TASK_UNIFORM_COMPONENTS_NV: int
GL_MAX_DRAW_MESH_TASKS_COUNT_NV: int
GL_MAX_MESH_ATOMIC_COUNTERS_NV: int
GL_MAX_MESH_ATOMIC_COUNTER_BUFFERS_NV: int
GL_MAX_MESH_IMAGE_UNIFORMS_NV: int
GL_MAX_MESH_OUTPUT_PRIMITIVES_NV: int
GL_MAX_MESH_OUTPUT_VERTICES_NV: int
GL_MAX_MESH_SHADER_STORAGE_BLOCKS_NV: int
GL_MAX_MESH_TEXTURE_IMAGE_UNITS_NV: int
GL_MAX_MESH_TOTAL_MEMORY_SIZE_NV: int
GL_MAX_MESH_UNIFORM_BLOCKS_NV: int
GL_MAX_MESH_UNIFORM_COMPONENTS_NV: int
GL_MAX_MESH_VIEWS_NV: int
GL_MAX_MESH_WORK_GROUP_INVOCATIONS_NV: int
GL_MAX_MESH_WORK_GROUP_SIZE_NV: int
GL_MAX_TASK_ATOMIC_COUNTERS_NV: int
GL_MAX_TASK_ATOMIC_COUNTER_BUFFERS_NV: int
GL_MAX_TASK_IMAGE_UNIFORMS_NV: int
GL_MAX_TASK_OUTPUT_COUNT_NV: int
GL_MAX_TASK_SHADER_STORAGE_BLOCKS_NV: int
GL_MAX_TASK_TEXTURE_IMAGE_UNITS_NV: int
GL_MAX_TASK_TOTAL_MEMORY_SIZE_NV: int
GL_MAX_TASK_UNIFORM_BLOCKS_NV: int
GL_MAX_TASK_UNIFORM_COMPONENTS_NV: int
GL_MAX_TASK_WORK_GROUP_INVOCATIONS_NV: int
GL_MAX_TASK_WORK_GROUP_SIZE_NV: int
GL_MESH_OUTPUT_PER_PRIMITIVE_GRANULARITY_NV: int
GL_MESH_OUTPUT_PER_VERTEX_GRANULARITY_NV: int
GL_MESH_OUTPUT_TYPE_NV: int
GL_MESH_PRIMITIVES_OUT_NV: int
GL_MESH_SHADER_BIT_NV: int
GL_MESH_SHADER_NV: int
GL_MESH_SUBROUTINE_NV: int
GL_MESH_SUBROUTINE_UNIFORM_NV: int
GL_MESH_VERTICES_OUT_NV: int
GL_MESH_WORK_GROUP_SIZE_NV: int
GL_REFERENCED_BY_MESH_SHADER_NV: int
GL_REFERENCED_BY_TASK_SHADER_NV: int
GL_TASK_SHADER_BIT_NV: int
GL_TASK_SHADER_NV: int
GL_TASK_SUBROUTINE_NV: int
GL_TASK_SUBROUTINE_UNIFORM_NV: int
GL_TASK_WORK_GROUP_SIZE_NV: int
GL_UNIFORM_BLOCK_REFERENCED_BY_MESH_SHADER_NV: int
GL_UNIFORM_BLOCK_REFERENCED_BY_TASK_SHADER_NV: int

def glDrawMeshTasksIndirectNV(indirect: int) -> None: ...
def glDrawMeshTasksNV(first: int, count: int) -> None: ...
def glMultiDrawMeshTasksIndirectCountNV(indirect: int, drawcount: int, maxdrawcount: int, stride: int) -> None: ...
def glMultiDrawMeshTasksIndirectNV(indirect: int, drawcount: int, stride: int) -> None: ...

def glInitMeshShaderNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
