"""OpenGL.GLES2.NV.non_square_matrices -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray

from OpenGL.raw.GLES2._types import *

GL_FLOAT_MAT2x3_NV: int
GL_FLOAT_MAT2x4_NV: int
GL_FLOAT_MAT3x2_NV: int
GL_FLOAT_MAT3x4_NV: int
GL_FLOAT_MAT4x2_NV: int
GL_FLOAT_MAT4x3_NV: int

def glUniformMatrix2x3fvNV(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUniformMatrix2x4fvNV(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUniformMatrix3x2fvNV(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUniformMatrix3x4fvNV(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUniformMatrix4x2fvNV(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...
def glUniformMatrix4x3fvNV(location: int, count: int, transpose: bool, value: FloatArray) -> None: ...

def glInitNonSquareMatricesNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
