"""OpenGL.GLES2.NV.path_rendering -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, DoubleArray, FloatArray, FloatArrayResult, IntArray, IntArrayResult, UByteArray, UByteArrayResult, UIntArray

from OpenGL.raw.GLES2._types import *

GL_2_BYTES_NV: int
GL_3_BYTES_NV: int
GL_4_BYTES_NV: int
GL_ACCUM_ADJACENT_PAIRS_NV: int
GL_ADJACENT_PAIRS_NV: int
GL_AFFINE_2D_NV: int
GL_AFFINE_3D_NV: int
GL_ARC_TO_NV: int
GL_BEVEL_NV: int
GL_BOLD_BIT_NV: int
GL_BOUNDING_BOX_NV: int
GL_BOUNDING_BOX_OF_BOUNDING_BOXES_NV: int
GL_CIRCULAR_CCW_ARC_TO_NV: int
GL_CIRCULAR_CW_ARC_TO_NV: int
GL_CIRCULAR_TANGENT_ARC_TO_NV: int
GL_CLOSE_PATH_NV: int
GL_CONIC_CURVE_TO_NV: int
GL_CONSTANT_NV: int
GL_CONVEX_HULL_NV: int
GL_COUNT_DOWN_NV: int
GL_COUNT_UP_NV: int
GL_CUBIC_CURVE_TO_NV: int
GL_DUP_FIRST_CUBIC_CURVE_TO_NV: int
GL_DUP_LAST_CUBIC_CURVE_TO_NV: int
GL_EYE_LINEAR_NV: int
GL_FILE_NAME_NV: int
GL_FIRST_TO_REST_NV: int
GL_FONT_ASCENDER_BIT_NV: int
GL_FONT_DESCENDER_BIT_NV: int
GL_FONT_GLYPHS_AVAILABLE_NV: int
GL_FONT_HAS_KERNING_BIT_NV: int
GL_FONT_HEIGHT_BIT_NV: int
GL_FONT_MAX_ADVANCE_HEIGHT_BIT_NV: int
GL_FONT_MAX_ADVANCE_WIDTH_BIT_NV: int
GL_FONT_NUM_GLYPH_INDICES_BIT_NV: int
GL_FONT_TARGET_UNAVAILABLE_NV: int
GL_FONT_UNAVAILABLE_NV: int
GL_FONT_UNDERLINE_POSITION_BIT_NV: int
GL_FONT_UNDERLINE_THICKNESS_BIT_NV: int
GL_FONT_UNINTELLIGIBLE_NV: int
GL_FONT_UNITS_PER_EM_BIT_NV: int
GL_FONT_X_MAX_BOUNDS_BIT_NV: int
GL_FONT_X_MIN_BOUNDS_BIT_NV: int
GL_FONT_Y_MAX_BOUNDS_BIT_NV: int
GL_FONT_Y_MIN_BOUNDS_BIT_NV: int
GL_FRAGMENT_INPUT_NV: int
GL_GLYPH_HAS_KERNING_BIT_NV: int
GL_GLYPH_HEIGHT_BIT_NV: int
GL_GLYPH_HORIZONTAL_BEARING_ADVANCE_BIT_NV: int
GL_GLYPH_HORIZONTAL_BEARING_X_BIT_NV: int
GL_GLYPH_HORIZONTAL_BEARING_Y_BIT_NV: int
GL_GLYPH_VERTICAL_BEARING_ADVANCE_BIT_NV: int
GL_GLYPH_VERTICAL_BEARING_X_BIT_NV: int
GL_GLYPH_VERTICAL_BEARING_Y_BIT_NV: int
GL_GLYPH_WIDTH_BIT_NV: int
GL_HORIZONTAL_LINE_TO_NV: int
GL_ITALIC_BIT_NV: int
GL_LARGE_CCW_ARC_TO_NV: int
GL_LARGE_CW_ARC_TO_NV: int
GL_LINE_TO_NV: int
GL_MITER_REVERT_NV: int
GL_MITER_TRUNCATE_NV: int
GL_MOVE_TO_CONTINUES_NV: int
GL_MOVE_TO_NV: int
GL_MOVE_TO_RESETS_NV: int
GL_OBJECT_LINEAR_NV: int
GL_PATH_CLIENT_LENGTH_NV: int
GL_PATH_COMMAND_COUNT_NV: int
GL_PATH_COMPUTED_LENGTH_NV: int
GL_PATH_COORD_COUNT_NV: int
GL_PATH_COVER_DEPTH_FUNC_NV: int
GL_PATH_DASH_ARRAY_COUNT_NV: int
GL_PATH_DASH_CAPS_NV: int
GL_PATH_DASH_OFFSET_NV: int
GL_PATH_DASH_OFFSET_RESET_NV: int
GL_PATH_END_CAPS_NV: int
GL_PATH_ERROR_POSITION_NV: int
GL_PATH_FILL_BOUNDING_BOX_NV: int
GL_PATH_FILL_COVER_MODE_NV: int
GL_PATH_FILL_MASK_NV: int
GL_PATH_FILL_MODE_NV: int
GL_PATH_FOG_GEN_MODE_NV: int
GL_PATH_FORMAT_PS_NV: int
GL_PATH_FORMAT_SVG_NV: int
GL_PATH_GEN_COEFF_NV: int
GL_PATH_GEN_COLOR_FORMAT_NV: int
GL_PATH_GEN_COMPONENTS_NV: int
GL_PATH_GEN_MODE_NV: int
GL_PATH_INITIAL_DASH_CAP_NV: int
GL_PATH_INITIAL_END_CAP_NV: int
GL_PATH_JOIN_STYLE_NV: int
GL_PATH_MAX_MODELVIEW_STACK_DEPTH_NV: int
GL_PATH_MAX_PROJECTION_STACK_DEPTH_NV: int
GL_PATH_MITER_LIMIT_NV: int
GL_PATH_MODELVIEW_MATRIX_NV: int
GL_PATH_MODELVIEW_NV: int
GL_PATH_MODELVIEW_STACK_DEPTH_NV: int
GL_PATH_OBJECT_BOUNDING_BOX_NV: int
GL_PATH_PROJECTION_MATRIX_NV: int
GL_PATH_PROJECTION_NV: int
GL_PATH_PROJECTION_STACK_DEPTH_NV: int
GL_PATH_STENCIL_DEPTH_OFFSET_FACTOR_NV: int
GL_PATH_STENCIL_DEPTH_OFFSET_UNITS_NV: int
GL_PATH_STENCIL_FUNC_NV: int
GL_PATH_STENCIL_REF_NV: int
GL_PATH_STENCIL_VALUE_MASK_NV: int
GL_PATH_STROKE_BOUNDING_BOX_NV: int
GL_PATH_STROKE_COVER_MODE_NV: int
GL_PATH_STROKE_MASK_NV: int
GL_PATH_STROKE_WIDTH_NV: int
GL_PATH_TERMINAL_DASH_CAP_NV: int
GL_PATH_TERMINAL_END_CAP_NV: int
GL_PATH_TRANSPOSE_MODELVIEW_MATRIX_NV: int
GL_PATH_TRANSPOSE_PROJECTION_MATRIX_NV: int
GL_PRIMARY_COLOR: int
GL_PRIMARY_COLOR_NV: int
GL_QUADRATIC_CURVE_TO_NV: int
GL_RECT_NV: int
GL_RELATIVE_ARC_TO_NV: int
GL_RELATIVE_CONIC_CURVE_TO_NV: int
GL_RELATIVE_CUBIC_CURVE_TO_NV: int
GL_RELATIVE_HORIZONTAL_LINE_TO_NV: int
GL_RELATIVE_LARGE_CCW_ARC_TO_NV: int
GL_RELATIVE_LARGE_CW_ARC_TO_NV: int
GL_RELATIVE_LINE_TO_NV: int
GL_RELATIVE_MOVE_TO_NV: int
GL_RELATIVE_QUADRATIC_CURVE_TO_NV: int
GL_RELATIVE_RECT_NV: int
GL_RELATIVE_ROUNDED_RECT2_NV: int
GL_RELATIVE_ROUNDED_RECT4_NV: int
GL_RELATIVE_ROUNDED_RECT8_NV: int
GL_RELATIVE_ROUNDED_RECT_NV: int
GL_RELATIVE_SMALL_CCW_ARC_TO_NV: int
GL_RELATIVE_SMALL_CW_ARC_TO_NV: int
GL_RELATIVE_SMOOTH_CUBIC_CURVE_TO_NV: int
GL_RELATIVE_SMOOTH_QUADRATIC_CURVE_TO_NV: int
GL_RELATIVE_VERTICAL_LINE_TO_NV: int
GL_RESTART_PATH_NV: int
GL_ROUNDED_RECT2_NV: int
GL_ROUNDED_RECT4_NV: int
GL_ROUNDED_RECT8_NV: int
GL_ROUNDED_RECT_NV: int
GL_ROUND_NV: int
GL_SECONDARY_COLOR_NV: int
GL_SKIP_MISSING_GLYPH_NV: int
GL_SMALL_CCW_ARC_TO_NV: int
GL_SMALL_CW_ARC_TO_NV: int
GL_SMOOTH_CUBIC_CURVE_TO_NV: int
GL_SMOOTH_QUADRATIC_CURVE_TO_NV: int
GL_SQUARE_NV: int
GL_STANDARD_FONT_FORMAT_NV: int
GL_STANDARD_FONT_NAME_NV: int
GL_SYSTEM_FONT_NAME_NV: int
GL_TRANSLATE_2D_NV: int
GL_TRANSLATE_3D_NV: int
GL_TRANSLATE_X_NV: int
GL_TRANSLATE_Y_NV: int
GL_TRANSPOSE_AFFINE_2D_NV: int
GL_TRANSPOSE_AFFINE_3D_NV: int
GL_TRIANGULAR_NV: int
GL_USE_MISSING_GLYPH_NV: int
GL_UTF16_NV: int
GL_UTF8_NV: int
GL_VERTICAL_LINE_TO_NV: int

def glCopyPathNV(resultPath: int, srcPath: int) -> None: ...
def glCoverFillPathInstancedNV(numPaths: int, pathNameType: int, paths: AnyArray, pathBase: int, coverMode: int, transformType: int, transformValues: FloatArray) -> None: ...
def glCoverFillPathNV(path: int, coverMode: int) -> None: ...
def glCoverStrokePathInstancedNV(numPaths: int, pathNameType: int, paths: AnyArray, pathBase: int, coverMode: int, transformType: int, transformValues: FloatArray) -> None: ...
def glCoverStrokePathNV(path: int, coverMode: int) -> None: ...
def glDeletePathsNV(path: int, range: int) -> None: ...
def glGenPathsNV(range: int) -> int: ...
def glGetPathColorGenfvNV(color: int, pname: int, value: FloatArray | None = None) -> FloatArrayResult: ...
def glGetPathColorGenivNV(color: int, pname: int, value: IntArray | None = None) -> IntArrayResult: ...
def glGetPathCommandsNV(path: int, commands: UByteArray | None = None) -> UByteArrayResult: ...
def glGetPathCoordsNV(path: int, coords: FloatArray | None = None) -> FloatArrayResult: ...
def glGetPathDashArrayNV(path: int, dashArray: FloatArray | None = None) -> FloatArrayResult: ...
def glGetPathLengthNV(path: int, startSegment: int, numSegments: int) -> float: ...
def glGetPathMetricRangeNV(metricQueryMask: int, firstPathName: int, numPaths: int, stride: int, metrics: FloatArray) -> None: ...
def glGetPathMetricsNV(metricQueryMask: int, numPaths: int, pathNameType: int, paths: AnyArray, pathBase: int, stride: int, metrics: FloatArray) -> None: ...
def glGetPathParameterfvNV(path: int, pname: int, value: FloatArray | None = None) -> FloatArrayResult: ...
def glGetPathParameterivNV(path: int, pname: int, value: IntArray | None = None) -> IntArrayResult: ...
def glGetPathSpacingNV(pathListMode: int, numPaths: int, pathNameType: int, paths: AnyArray, pathBase: int, advanceScale: float, kerningScale: float, transformType: int, returnedSpacing: FloatArray) -> None: ...
def glGetPathTexGenfvNV(texCoordSet: int, pname: int, value: FloatArray | None = None) -> FloatArrayResult: ...
def glGetPathTexGenivNV(texCoordSet: int, pname: int, value: IntArray | None = None) -> IntArrayResult: ...
def glGetProgramResourcefvNV(program: int, programInterface: int, index: int, propCount: int, props: UIntArray, count: int, length: IntArray, params: FloatArray) -> None: ...
def glInterpolatePathsNV(resultPath: int, pathA: int, pathB: int, weight: float) -> None: ...
def glIsPathNV(path: int) -> int: ...
def glIsPointInFillPathNV(path: int, mask: int, x: float, y: float) -> int: ...
def glIsPointInStrokePathNV(path: int, x: float, y: float) -> int: ...
def glMatrixFrustumEXT(mode: int, left: float, right: float, bottom: float, top: float, zNear: float, zFar: float) -> None: ...
def glMatrixLoad3x2fNV(matrixMode: int, m: FloatArray) -> None: ...
def glMatrixLoad3x3fNV(matrixMode: int, m: FloatArray) -> None: ...
def glMatrixLoadIdentityEXT(mode: int) -> None: ...
def glMatrixLoadTranspose3x3fNV(matrixMode: int, m: FloatArray) -> None: ...
def glMatrixLoadTransposedEXT(mode: int, m: DoubleArray) -> None: ...
def glMatrixLoadTransposefEXT(mode: int, m: FloatArray) -> None: ...
def glMatrixLoaddEXT(mode: int, m: DoubleArray) -> None: ...
def glMatrixLoadfEXT(mode: int, m: FloatArray) -> None: ...
def glMatrixMult3x2fNV(matrixMode: int, m: FloatArray) -> None: ...
def glMatrixMult3x3fNV(matrixMode: int, m: FloatArray) -> None: ...
def glMatrixMultTranspose3x3fNV(matrixMode: int, m: FloatArray) -> None: ...
def glMatrixMultTransposedEXT(mode: int, m: DoubleArray) -> None: ...
def glMatrixMultTransposefEXT(mode: int, m: FloatArray) -> None: ...
def glMatrixMultdEXT(mode: int, m: DoubleArray) -> None: ...
def glMatrixMultfEXT(mode: int, m: FloatArray) -> None: ...
def glMatrixOrthoEXT(mode: int, left: float, right: float, bottom: float, top: float, zNear: float, zFar: float) -> None: ...
def glMatrixPopEXT(mode: int) -> None: ...
def glMatrixPushEXT(mode: int) -> None: ...
def glMatrixRotatedEXT(mode: int, angle: float, x: float, y: float, z: float) -> None: ...
def glMatrixRotatefEXT(mode: int, angle: float, x: float, y: float, z: float) -> None: ...
def glMatrixScaledEXT(mode: int, x: float, y: float, z: float) -> None: ...
def glMatrixScalefEXT(mode: int, x: float, y: float, z: float) -> None: ...
def glMatrixTranslatedEXT(mode: int, x: float, y: float, z: float) -> None: ...
def glMatrixTranslatefEXT(mode: int, x: float, y: float, z: float) -> None: ...
def glPathColorGenNV(color: int, genMode: int, colorFormat: int, coeffs: FloatArray) -> None: ...
def glPathCommandsNV(path: int, numCommands: int, commands: UByteArray, numCoords: int, coordType: int, coords: AnyArray) -> None: ...
def glPathCoordsNV(path: int, numCoords: int, coordType: int, coords: AnyArray) -> None: ...
def glPathCoverDepthFuncNV(func: int) -> None: ...
def glPathDashArrayNV(path: int, dashCount: int, dashArray: FloatArray) -> None: ...
def glPathFogGenNV(genMode: int) -> None: ...
def glPathGlyphIndexArrayNV(firstPathName: int, fontTarget: int, fontName: AnyArray, fontStyle: int, firstGlyphIndex: int, numGlyphs: int, pathParameterTemplate: int, emScale: float) -> int: ...
def glPathGlyphIndexRangeNV(fontTarget: int, fontName: AnyArray, fontStyle: int, pathParameterTemplate: int, emScale: float, baseAndCount: UIntArray) -> int: ...
def glPathGlyphRangeNV(firstPathName: int, fontTarget: int, fontName: AnyArray, fontStyle: int, firstGlyph: int, numGlyphs: int, handleMissingGlyphs: int, pathParameterTemplate: int, emScale: float) -> None: ...
def glPathGlyphsNV(firstPathName: int, fontTarget: int, fontName: AnyArray, fontStyle: int, numGlyphs: int, type: int, charcodes: AnyArray, handleMissingGlyphs: int, pathParameterTemplate: int, emScale: float) -> None: ...
def glPathMemoryGlyphIndexArrayNV(firstPathName: int, fontTarget: int, fontSize: int, fontData: AnyArray, faceIndex: int, firstGlyphIndex: int, numGlyphs: int, pathParameterTemplate: int, emScale: float) -> int: ...
def glPathParameterfNV(path: int, pname: int, value: float) -> None: ...
def glPathParameterfvNV(path: int, pname: int, value: FloatArray) -> None: ...
def glPathParameteriNV(path: int, pname: int, value: int) -> None: ...
def glPathParameterivNV(path: int, pname: int, value: IntArray) -> None: ...
def glPathStencilDepthOffsetNV(factor: float, units: float) -> None: ...
def glPathStencilFuncNV(func: int, ref: int, mask: int) -> None: ...
def glPathStringNV(path: int, format: int, length: int, pathString: AnyArray) -> None: ...
def glPathSubCommandsNV(path: int, commandStart: int, commandsToDelete: int, numCommands: int, commands: UByteArray, numCoords: int, coordType: int, coords: AnyArray) -> None: ...
def glPathSubCoordsNV(path: int, coordStart: int, numCoords: int, coordType: int, coords: AnyArray) -> None: ...
def glPathTexGenNV(texCoordSet: int, genMode: int, components: int, coeffs: FloatArray) -> None: ...
def glPointAlongPathNV(path: int, startSegment: int, numSegments: int, distance: float, x: FloatArray | None = None, y: FloatArray | None = None, tangentX: FloatArray | None = None, tangentY: FloatArray | None = None) -> tuple[FloatArrayResult, FloatArrayResult, FloatArrayResult, FloatArrayResult]: ...
def glProgramPathFragmentInputGenNV(program: int, location: int, genMode: int, components: int, coeffs: FloatArray) -> None: ...
def glStencilFillPathInstancedNV(numPaths: int, pathNameType: int, paths: AnyArray, pathBase: int, fillMode: int, mask: int, transformType: int, transformValues: FloatArray) -> None: ...
def glStencilFillPathNV(path: int, fillMode: int, mask: int) -> None: ...
def glStencilStrokePathInstancedNV(numPaths: int, pathNameType: int, paths: AnyArray, pathBase: int, reference: int, mask: int, transformType: int, transformValues: FloatArray) -> None: ...
def glStencilStrokePathNV(path: int, reference: int, mask: int) -> None: ...
def glStencilThenCoverFillPathInstancedNV(numPaths: int, pathNameType: int, paths: AnyArray, pathBase: int, fillMode: int, mask: int, coverMode: int, transformType: int, transformValues: FloatArray) -> None: ...
def glStencilThenCoverFillPathNV(path: int, fillMode: int, mask: int, coverMode: int) -> None: ...
def glStencilThenCoverStrokePathInstancedNV(numPaths: int, pathNameType: int, paths: AnyArray, pathBase: int, reference: int, mask: int, coverMode: int, transformType: int, transformValues: FloatArray) -> None: ...
def glStencilThenCoverStrokePathNV(path: int, reference: int, mask: int, coverMode: int) -> None: ...
def glTransformPathNV(resultPath: int, srcPath: int, transformType: int, transformValues: FloatArray) -> None: ...
def glWeightPathsNV(resultPath: int, numPaths: int, paths: UIntArray, weights: FloatArray) -> None: ...

def glInitPathRenderingNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
