"""OpenGL.GLES2.NV.viewport_array -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray, IntArray

from OpenGL.raw.GLES2._types import *

GL_DEPTH_RANGE: int
GL_MAX_VIEWPORTS_NV: int
GL_SCISSOR_BOX: int
GL_SCISSOR_TEST: int
GL_VIEWPORT: int
GL_VIEWPORT_BOUNDS_RANGE_NV: int
GL_VIEWPORT_INDEX_PROVOKING_VERTEX_NV: int
GL_VIEWPORT_SUBPIXEL_BITS_NV: int

def glDepthRangeArrayfvNV(first: int, count: int, v: FloatArray) -> None: ...
def glDepthRangeIndexedfNV(index: int, n: float, f: float) -> None: ...
def glDisableiNV(target: int, index: int) -> None: ...
def glEnableiNV(target: int, index: int) -> None: ...
def glGetFloati_vNV(target: int, index: int, data: FloatArray) -> None: ...
def glIsEnablediNV(target: int, index: int) -> int: ...
def glScissorArrayvNV(first: int, count: int, v: IntArray) -> None: ...
def glScissorIndexedNV(index: int, left: int, bottom: int, width: int, height: int) -> None: ...
def glScissorIndexedvNV(index: int, v: IntArray) -> None: ...
def glViewportArrayvNV(first: int, count: int, v: FloatArray) -> None: ...
def glViewportIndexedfNV(index: int, x: float, y: float, w: float, h: float) -> None: ...
def glViewportIndexedfvNV(index: int, v: FloatArray) -> None: ...

def glInitViewportArrayNV() -> bool: ...

def __getattr__(name: str) -> Any: ...
