# mypy: ignore-errors
# The names in this module arrive from the declaration tables at import
# time, so a checker reading this file sees calls to things it cannot
# find.  The typed surface is the .pyi stub beside the package.
'''Autogenerated by xml_generate script, do not edit!'''
from OpenGL import platform as _p, arrays
# Code generation uses this
from OpenGL.raw.GL import _types as _cs
# End users want this...
from OpenGL.raw.GL._types import *
from OpenGL.raw.GL import _errors
from OpenGL.constant import Constant as _C

import ctypes
_EXTENSION_NAME = 'GL_SGIS_texture_lod'
def _f( function ):
    return _p.createFunction( function,_p.PLATFORM.GL,'GL_SGIS_texture_lod',error_checker=_errors._error_checker)
GL_TEXTURE_BASE_LEVEL_SGIS=_C('GL_TEXTURE_BASE_LEVEL_SGIS',0x813C)
GL_TEXTURE_MAX_LEVEL_SGIS=_C('GL_TEXTURE_MAX_LEVEL_SGIS',0x813D)
GL_TEXTURE_MAX_LOD_SGIS=_C('GL_TEXTURE_MAX_LOD_SGIS',0x813B)
GL_TEXTURE_MIN_LOD_SGIS=_C('GL_TEXTURE_MIN_LOD_SGIS',0x813A)

