"""OpenGL.WGL.AMD.gpu_association -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray

from OpenGL.raw.WGL._types import *

WGL_GPU_CLOCK_AMD: int
WGL_GPU_FASTEST_TARGET_GPUS_AMD: int
WGL_GPU_NUM_PIPES_AMD: int
WGL_GPU_NUM_RB_AMD: int
WGL_GPU_NUM_SIMD_AMD: int
WGL_GPU_NUM_SPI_AMD: int
WGL_GPU_OPENGL_VERSION_STRING_AMD: int
WGL_GPU_RAM_AMD: int
WGL_GPU_RENDERER_STRING_AMD: int
WGL_GPU_VENDOR_AMD: int

def wglBlitContextFramebufferAMD(dstCtx: Any, srcX0: int, srcY0: int, srcX1: int, srcY1: int, dstX0: int, dstY0: int, dstX1: int, dstY1: int, mask: int, filter: int) -> Any: ...
def wglCreateAssociatedContextAMD(id: int) -> Any: ...
def wglCreateAssociatedContextAttribsAMD(id: int, hShareContext: Any, attribList: IntArray) -> Any: ...
def wglDeleteAssociatedContextAMD(hglrc: Any) -> int: ...
def wglGetContextGPUIDAMD(hglrc: Any) -> int: ...
def wglGetCurrentAssociatedContextAMD() -> Any: ...
def wglGetGPUIDsAMD(maxCount: int, ids: AnyArray) -> int: ...
def wglGetGPUInfoAMD(id: int, property: int, dataType: int, size: int, data: AnyArray) -> int: ...
def wglMakeAssociatedContextCurrentAMD(hglrc: Any) -> int: ...

def glInitGpuAssociationAMD() -> bool: ...

def __getattr__(name: str) -> Any: ...
