"""OpenGL.GL.AMD.draw_buffers_blend -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GL._types import *

def glBlendEquationIndexedAMD(buf: int, mode: int) -> None: ...
def glBlendEquationSeparateIndexedAMD(buf: int, modeRGB: int, modeAlpha: int) -> None: ...
def glBlendFuncIndexedAMD(buf: int, src: int, dst: int) -> None: ...
def glBlendFuncSeparateIndexedAMD(buf: int, srcRGB: int, dstRGB: int, srcAlpha: int, dstAlpha: int) -> None: ...

def glInitDrawBuffersBlendAMD() -> bool: ...

def __getattr__(name: str) -> Any: ...
