"""Determine links to gl, glu, glut and gle documentation
"""
from OpenGL import GL, GLU, GLUT, GLE
import os, string, sys, glob, operator


def findGLName( name ):
	return _findName( name, GL_SPECIALCASES, "gl", 2 )
def findGLUName( name ):
	return _findName( name, GLU_SPECIALCASES, "glu", 3 )
def findGLUTName( name ):
	return _findName( name, GLUT_SPECIALCASES, "glut", 0 )
def findGLEName( name ):
	return _findName( name, GLE_SPECIALCASES, "gle", 0 )

def findName( name ):
	for op in (findGLName, findGLUName, findGLUTName, findGLEName):
		result = op( name)
		if result:
			return result
	return None
def _findName( name, specialCases, folder=GL, frontTrim=2 ):
	name = specialCases.get( name, name )
##	baseName = string.lower( name[frontTrim:] )
	baseName = name
	result = exists( baseName, folder)
	if result:
		return result
	else:
		while baseName and baseName[-1] in 'dfiuvbs4321':
			baseName = baseName[:-1]
			result = exists( baseName, folder)
			if result and baseName in ('glut', 'glu', 'gl', 'gle'):
				if name != baseName:
					return None
				else:
					return result
			elif result:
				return result
	return None



GL_SPECIALCASES = {
	'glDisable':"glEnable",
	'glDisableClientState':"glEnableClientState",
	'glEnd':"glBegin",
	'glEndList':"glNewList",
	'glGetBoolean':"glGet",
	'glGetBooleanv':"glGet",
	'glGetDouble':"glGet",
	'glGetDoublev':"glGet",
	'glGetFloatv':"glGet",
	'glGetFloat':"glGet",
	'glGetInteger':"glGet",
	'glGetIntegerv':"glGet",
	'glPopAttrib':"glPushAttrib",
	'glPopClientAttrib':"glPushClientAttrib",
	'glPopMatrix':"glPushMatrix",
	'glPopName':"glPushName",
}
GLU_SPECIALCASES = {
		'gluEndCurve':"gluBeginCurve",
		'gluEndPolygon':"gluBeginPolygon",
		'gluEndSurface':"gluBeginSurface",
		'gluEndTrim':"gluBeginTrim",
		'gluTessEndContour':"gluTessBeginContour",
}
GLUT_SPECIALCASES = {
		'glutBitmapLength':"glutBitmapWidth",
		'glutDetachMenu':"glutAttachMenu",
		'glutGetMenu':"glutSetMenu",
		'glutGetWindow':"glutSetWindow",
		'glutHideOverlay':"glutShowOverlay",
		'glutHideWindow':"glutShowWindow",
		'glutIconifyWindow':"glutShowWindow",
		'glutInitWindowSize':"glutInitWindowPosition",
		'glutLeaveGameMode':"glutEnterGameMode",
		'glutMenuStateFunc':"glutMenuStatusFunc",
		'glutPassiveMotionFunc':"glutMotionFunc",
		'glutPostWindowOverlayRedisplay':"glutPostOverlayRedisplay",
		'glutPostWindowRedisplay':"glutPostRedisplay",
		'glutPushWindow':"glutPopWindow",
		'glutSetIconTitle':"glutSetWindowTitle",
		'glutStrokeLength':"glutStrokeWidth",
		'glutStrokeLengthf':"glutStrokeWidth",
		'glutWireCone':"glutSolidCone",
		'glutWireCube':"glutSolidCube",
		'glutWireDodecahedron':"glutSolidDodecahedron",
		'glutWireIcosahedron':"glutSolidIcosahedron",
		'glutWireOctahedron':"glutSolidOctahedron",
		'glutWireSphere':"glutSolidSphere",
		'glutWireTeapot':"glutSolidTeapot",
		'glutWireTetrahedron':"glutSolidTetrahedron",
		'glutWireTorus':"glutSolidTorus",
		"glutRemoveLayer": "glutRemoveOverlay",

		# not there!
		"glutSpaceballMotion":"glutSpaceballMotionFunc",
		"glutRemoveItem":"glutRemoveMenuItem",
}
GLE_SPECIALCASES = {
		'gleGetJoinStyle':"gleSetJoinStyle",
		# not there!
		'gleGetNumSides':"",
		'gleSetNumSides':"",    
}

def exists( baseName, folder ):
	return FILE_MAPPING.get( baseName )

FILE_MAPPING = {
	'glViewport':"http://pyopengl.sourceforge.net/documentation/manual/glViewport.3G.html",
	'glVertexPointer':"http://pyopengl.sourceforge.net/documentation/manual/glVertexPointer.3G.html",
	'glVertex':"http://pyopengl.sourceforge.net/documentation/manual/glVertex.3G.html",
	'gluUnProject4':"http://pyopengl.sourceforge.net/documentation/manual/gluUnProject4.3G.html",
	'gluUnProject':"http://pyopengl.sourceforge.net/documentation/manual/gluUnProject.3G.html",
	'glutWindowStatusFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutWindowStatusFunc.3GLUT.html",
	'glutWarpPointer':"http://pyopengl.sourceforge.net/documentation/manual/glutWarpPointer.3GLUT.html",
	'glutVisibilityFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutVisibilityFunc.3GLUT.html",
	'glutVideoResizeGet':"http://pyopengl.sourceforge.net/documentation/manual/glutVideoResizeGet.3GLUT.html",
	'glutUseLayer':"http://pyopengl.sourceforge.net/documentation/manual/glutUseLayer.3GLUT.html",
	'glutTimerFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutTimerFunc.3GLUT.html",
	'glutTabletMotionFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutTabletMotionFunc.3GLUT.html",
	'glutTabletButtonFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutTabletButtonFunc.3GLUT.html",
	'glutSwapBuffers':"http://pyopengl.sourceforge.net/documentation/manual/glutSwapBuffers.3GLUT.html",
	'glutStrokeWidth':"http://pyopengl.sourceforge.net/documentation/manual/glutStrokeWidth.3GLUT.html",
	'glutStrokeCharacter':"http://pyopengl.sourceforge.net/documentation/manual/glutStrokeCharacter.3GLUT.html",
	'glutSpecialUpFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutSpecialUpFunc.3GLUT.html",
	'glutSpecialFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutSpecialFunc.3GLUT.html",
	'glutSpaceballRotateFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutSpaceballRotateFunc.3GLUT.html",
	'glutSpaceballMotionFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutSpaceballMotionFunc.3GLUT.html",
	'glutSpaceballButtonFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutSpaceballButtonFunc.3GLUT.html",
	'glutSolidTorus':"http://pyopengl.sourceforge.net/documentation/manual/glutSolidTorus.3GLUT.html",
	'glutSolidTetrahedron':"http://pyopengl.sourceforge.net/documentation/manual/glutSolidTetrahedron.3GLUT.html",
	'glutSolidTeapot':"http://pyopengl.sourceforge.net/documentation/manual/glutSolidTeapot.3GLUT.html",
	'glutSolidSphere':"http://pyopengl.sourceforge.net/documentation/manual/glutSolidSphere.3GLUT.html",
	'glutSolidOctahedron':"http://pyopengl.sourceforge.net/documentation/manual/glutSolidOctahedron.3GLUT.html",
	'glutSolidIcosahedron':"http://pyopengl.sourceforge.net/documentation/manual/glutSolidIcosahedron.3GLUT.html",
	'glutSolidDodecahedron':"http://pyopengl.sourceforge.net/documentation/manual/glutSolidDodecahedron.3GLUT.html",
	'glutSolidCube':"http://pyopengl.sourceforge.net/documentation/manual/glutSolidCube.3GLUT.html",
	'glutSolidCone':"http://pyopengl.sourceforge.net/documentation/manual/glutSolidCone.3GLUT.html",
	'glutShowWindow':"http://pyopengl.sourceforge.net/documentation/manual/glutShowWindow.3GLUT.html",
	'glutShowOverlay':"http://pyopengl.sourceforge.net/documentation/manual/glutShowOverlay.3GLUT.html",
	'glutSetWindowTitle':"http://pyopengl.sourceforge.net/documentation/manual/glutSetWindowTitle.3GLUT.html",
	'glutSetWindow':"http://pyopengl.sourceforge.net/documentation/manual/glutSetWindow.3GLUT.html",
	'glutSetMenu':"http://pyopengl.sourceforge.net/documentation/manual/glutSetMenu.3GLUT.html",
	'glutSetKeyRepeat':"http://pyopengl.sourceforge.net/documentation/manual/glutSetKeyRepeat.3GLUT.html",
	'glutSetCursor':"http://pyopengl.sourceforge.net/documentation/manual/glutSetCursor.3GLUT.html",
	'glutSetColor':"http://pyopengl.sourceforge.net/documentation/manual/glutSetColor.3GLUT.html",
	'glutReshapeWindow':"http://pyopengl.sourceforge.net/documentation/manual/glutReshapeWindow.3GLUT.html",
	'glutReshapeFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutReshapeFunc.3GLUT.html",
	'glutReportErrors':"http://pyopengl.sourceforge.net/documentation/manual/glutReportErrors.3GLUT.html",
	'glutRemoveMenuItem':"http://pyopengl.sourceforge.net/documentation/manual/glutRemoveMenuItem.3GLUT.html",
	'glutRemoveLayer':"http://pyopengl.sourceforge.net/documentation/manual/glutRemoveLayer.3GLUT.html",
	'glutPostRedisplay':"http://pyopengl.sourceforge.net/documentation/manual/glutPostRedisplay.3GLUT.html",
	'glutPostOverlayRedisplay':"http://pyopengl.sourceforge.net/documentation/manual/glutPostOverlayRedisplay.3GLUT.html",
	'glutPositionWindow':"http://pyopengl.sourceforge.net/documentation/manual/glutPositionWindow.3GLUT.html",
	'glutPopWindow':"http://pyopengl.sourceforge.net/documentation/manual/glutPopWindow.3GLUT.html",
	'glutOverlayDisplayFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutOverlayDisplayFunc.3GLUT.html",
	'glutMouseFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutMouseFunc.3GLUT.html",
	'glutMotionFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutMotionFunc.3GLUT.html",
	'glutMenuStatusFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutMenuStatusFunc.3GLUT.html",
	'glutMainLoop':"http://pyopengl.sourceforge.net/documentation/manual/glutMainLoop.3GLUT.html",
	'glutLayerGet':"http://pyopengl.sourceforge.net/documentation/manual/glutLayerGet.3GLUT.html",
	'glutKeyboardUpFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutKeyboardUpFunc.3GLUT.html",
	'glutKeyboardFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutKeyboardFunc.3GLUT.html",
	'glutJoystickFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutJoystickFunc.3GLUT.html",
	'glutInitWindowPosition':"http://pyopengl.sourceforge.net/documentation/manual/glutInitWindowPosition.3GLUT.html",
	'glutInitDisplayString':"http://pyopengl.sourceforge.net/documentation/manual/glutInitDisplayString.3GLUT.html",
	'glutInitDisplayMode':"http://pyopengl.sourceforge.net/documentation/manual/glutInitDisplayMode.3GLUT.html",
	'glutInit':"http://pyopengl.sourceforge.net/documentation/manual/glutInit.3GLUT.html",
	'glutIgnoreKeyRepeat':"http://pyopengl.sourceforge.net/documentation/manual/glutIgnoreKeyRepeat.3GLUT.html",
	'glutIdleFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutIdleFunc.3GLUT.html",
	'glutGetModifiers':"http://pyopengl.sourceforge.net/documentation/manual/glutGetModifiers.3GLUT.html",
	'glutGetColor':"http://pyopengl.sourceforge.net/documentation/manual/glutGetColor.3GLUT.html",
	'glutGet':"http://pyopengl.sourceforge.net/documentation/manual/glutGet.3GLUT.html",
	'glutGameModeString':"http://pyopengl.sourceforge.net/documentation/manual/glutGameModeString.3GLUT.html",
	'glutGameModeGet':"http://pyopengl.sourceforge.net/documentation/manual/glutGameModeGet.3GLUT.html",
	'glutFullScreen':"http://pyopengl.sourceforge.net/documentation/manual/glutFullScreen.3GLUT.html",
	'glutForceJoystickFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutForceJoystickFunc.3GLUT.html",
	'glutExtensionSupported':"http://pyopengl.sourceforge.net/documentation/manual/glutExtensionSupported.3GLUT.html",
	'glutEstablishOverlay':"http://pyopengl.sourceforge.net/documentation/manual/glutEstablishOverlay.3GLUT.html",
	'gluTessVertex':"http://pyopengl.sourceforge.net/documentation/manual/gluTessVertex.3G.html",
	'gluTessProperty':"http://pyopengl.sourceforge.net/documentation/manual/gluTessProperty.3G.html",
	'gluTessNormal':"http://pyopengl.sourceforge.net/documentation/manual/gluTessNormal.3G.html",
	'gluTessEndPolygon':"http://pyopengl.sourceforge.net/documentation/manual/gluTessEndPolygon.3G.html",
	'gluTessCallback':"http://pyopengl.sourceforge.net/documentation/manual/gluTessCallback.3G.html",
	'gluTessBeginPolygon':"http://pyopengl.sourceforge.net/documentation/manual/gluTessBeginPolygon.3G.html",
	'gluTessBeginContour':"http://pyopengl.sourceforge.net/documentation/manual/gluTessBeginContour.3G.html",
	'glutEntryFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutEntryFunc.3GLUT.html",
	'glutEnterGameMode':"http://pyopengl.sourceforge.net/documentation/manual/glutEnterGameMode.3GLUT.html",
	'glutDisplayFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutDisplayFunc.3GLUT.html",
	'glutDialsFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutDialsFunc.3GLUT.html",
	'glutDeviceGet':"http://pyopengl.sourceforge.net/documentation/manual/glutDeviceGet.3GLUT.html",
	'glutDestroyWindow':"http://pyopengl.sourceforge.net/documentation/manual/glutDestroyWindow.3GLUT.html",
	'glutDestroyMenu':"http://pyopengl.sourceforge.net/documentation/manual/glutDestroyMenu.3GLUT.html",
	'glutCreateWindow':"http://pyopengl.sourceforge.net/documentation/manual/glutCreateWindow.3GLUT.html",
	'glutCreateSubWindow':"http://pyopengl.sourceforge.net/documentation/manual/glutCreateSubWindow.3GLUT.html",
	'glutCreateMenu':"http://pyopengl.sourceforge.net/documentation/manual/glutCreateMenu.3GLUT.html",
	'glutCopyColormap':"http://pyopengl.sourceforge.net/documentation/manual/glutCopyColormap.3GLUT.html",
	'glutChangeToSubMenu':"http://pyopengl.sourceforge.net/documentation/manual/glutChangeToSubMenu.3GLUT.html",
	'glutChangeToMenuEntry':"http://pyopengl.sourceforge.net/documentation/manual/glutChangeToMenuEntry.3GLUT.html",
	'glutButtonBoxFunc':"http://pyopengl.sourceforge.net/documentation/manual/glutButtonBoxFunc.3GLUT.html",
	'glutBitmapWidth':"http://pyopengl.sourceforge.net/documentation/manual/glutBitmapWidth.3GLUT.html",
	'glutBitmapCharacter':"http://pyopengl.sourceforge.net/documentation/manual/glutBitmapCharacter.3GLUT.html",
	'glutAttachMenu':"http://pyopengl.sourceforge.net/documentation/manual/glutAttachMenu.3GLUT.html",
	'glutAddSubMenu':"http://pyopengl.sourceforge.net/documentation/manual/glutAddSubMenu.3GLUT.html",
	'glutAddMenuEntry':"http://pyopengl.sourceforge.net/documentation/manual/glutAddMenuEntry.3GLUT.html",
	'glut':"http://pyopengl.sourceforge.net/documentation/manual/glut.3GLUT.html",
	'gluSphere':"http://pyopengl.sourceforge.net/documentation/manual/gluSphere.3G.html",
	'gluScaleImage':"http://pyopengl.sourceforge.net/documentation/manual/gluScaleImage.3G.html",
	'gluQuadricTexture':"http://pyopengl.sourceforge.net/documentation/manual/gluQuadricTexture.3G.html",
	'gluQuadricOrientation':"http://pyopengl.sourceforge.net/documentation/manual/gluQuadricOrientation.3G.html",
	'gluQuadricNormals':"http://pyopengl.sourceforge.net/documentation/manual/gluQuadricNormals.3G.html",
	'gluQuadricDrawStyle':"http://pyopengl.sourceforge.net/documentation/manual/gluQuadricDrawStyle.3G.html",
	'gluQuadricCallback':"http://pyopengl.sourceforge.net/documentation/manual/gluQuadricCallback.3G.html",
	'gluPwlCurve':"http://pyopengl.sourceforge.net/documentation/manual/gluPwlCurve.3G.html",
	'gluProject':"http://pyopengl.sourceforge.net/documentation/manual/gluProject.3G.html",
	'gluPickMatrix':"http://pyopengl.sourceforge.net/documentation/manual/gluPickMatrix.3G.html",
	'gluPerspective':"http://pyopengl.sourceforge.net/documentation/manual/gluPerspective.3G.html",
	'gluPartialDisk':"http://pyopengl.sourceforge.net/documentation/manual/gluPartialDisk.3G.html",
	'gluOrtho2D':"http://pyopengl.sourceforge.net/documentation/manual/gluOrtho2D.3G.html",
	'gluNurbsSurface':"http://pyopengl.sourceforge.net/documentation/manual/gluNurbsSurface.3G.html",
	'gluNurbsProperty':"http://pyopengl.sourceforge.net/documentation/manual/gluNurbsProperty.3G.html",
	'gluNurbsCurve':"http://pyopengl.sourceforge.net/documentation/manual/gluNurbsCurve.3G.html",
	'gluNurbsCallbackDataEXT':"http://pyopengl.sourceforge.net/documentation/manual/gluNurbsCallbackDataEXT.3G.html",
	'gluNurbsCallbackData':"http://pyopengl.sourceforge.net/documentation/manual/gluNurbsCallbackData.3G.html",
	'gluNurbsCallback':"http://pyopengl.sourceforge.net/documentation/manual/gluNurbsCallback.3G.html",
	'gluNextContour':"http://pyopengl.sourceforge.net/documentation/manual/gluNextContour.3G.html",
	'gluNewTess':"http://pyopengl.sourceforge.net/documentation/manual/gluNewTess.3G.html",
	'gluNewQuadric':"http://pyopengl.sourceforge.net/documentation/manual/gluNewQuadric.3G.html",
	'gluNewNurbsRenderer':"http://pyopengl.sourceforge.net/documentation/manual/gluNewNurbsRenderer.3G.html",
	'gluLookAt':"http://pyopengl.sourceforge.net/documentation/manual/gluLookAt.3G.html",
	'gluLoadSamplingMatrices':"http://pyopengl.sourceforge.net/documentation/manual/gluLoadSamplingMatrices.3G.html",
	'gluGetTessProperty':"http://pyopengl.sourceforge.net/documentation/manual/gluGetTessProperty.3G.html",
	'gluGetString':"http://pyopengl.sourceforge.net/documentation/manual/gluGetString.3G.html",
	'gluGetNurbsProperty':"http://pyopengl.sourceforge.net/documentation/manual/gluGetNurbsProperty.3G.html",
	'gluErrorString':"http://pyopengl.sourceforge.net/documentation/manual/gluErrorString.3G.html",
	'gluDisk':"http://pyopengl.sourceforge.net/documentation/manual/gluDisk.3G.html",
	'gluDeleteTess':"http://pyopengl.sourceforge.net/documentation/manual/gluDeleteTess.3G.html",
	'gluDeleteQuadric':"http://pyopengl.sourceforge.net/documentation/manual/gluDeleteQuadric.3G.html",
	'gluDeleteNurbsRenderer':"http://pyopengl.sourceforge.net/documentation/manual/gluDeleteNurbsRenderer.3G.html",
	'gluCylinder':"http://pyopengl.sourceforge.net/documentation/manual/gluCylinder.3G.html",
	'gluCheckExtension':"http://pyopengl.sourceforge.net/documentation/manual/gluCheckExtension.3G.html",
	'gluBuild3DMipmaps':"http://pyopengl.sourceforge.net/documentation/manual/gluBuild3DMipmaps.3G.html",
	'gluBuild3DMipmapLevels':"http://pyopengl.sourceforge.net/documentation/manual/gluBuild3DMipmapLevels.3G.html",
	'gluBuild2DMipmaps':"http://pyopengl.sourceforge.net/documentation/manual/gluBuild2DMipmaps.3G.html",
	'gluBuild2DMipmapLevels':"http://pyopengl.sourceforge.net/documentation/manual/gluBuild2DMipmapLevels.3G.html",
	'gluBuild1DMipmaps':"http://pyopengl.sourceforge.net/documentation/manual/gluBuild1DMipmaps.3G.html",
	'gluBuild1DMipmapLevels':"http://pyopengl.sourceforge.net/documentation/manual/gluBuild1DMipmapLevels.3G.html",
	'gluBeginTrim':"http://pyopengl.sourceforge.net/documentation/manual/gluBeginTrim.3G.html",
	'gluBeginSurface':"http://pyopengl.sourceforge.net/documentation/manual/gluBeginSurface.3G.html",
	'gluBeginPolygon':"http://pyopengl.sourceforge.net/documentation/manual/gluBeginPolygon.3G.html",
	'gluBeginCurve':"http://pyopengl.sourceforge.net/documentation/manual/gluBeginCurve.3G.html",
	'glTranslate':"http://pyopengl.sourceforge.net/documentation/manual/glTranslate.3G.html",
	'glTexSubImage3D':"http://pyopengl.sourceforge.net/documentation/manual/glTexSubImage3D.3G.html",
	'glTexSubImage2D':"http://pyopengl.sourceforge.net/documentation/manual/glTexSubImage2D.3G.html",
	'glTexSubImage1D':"http://pyopengl.sourceforge.net/documentation/manual/glTexSubImage1D.3G.html",
	'glTexParameter':"http://pyopengl.sourceforge.net/documentation/manual/glTexParameter.3G.html",
	'glTexImage3D':"http://pyopengl.sourceforge.net/documentation/manual/glTexImage3D.3G.html",
	'glTexImage2D':"http://pyopengl.sourceforge.net/documentation/manual/glTexImage2D.3G.html",
	'glTexImage1D':"http://pyopengl.sourceforge.net/documentation/manual/glTexImage1D.3G.html",
	'glTexGen':"http://pyopengl.sourceforge.net/documentation/manual/glTexGen.3G.html",
	'glTexEnv':"http://pyopengl.sourceforge.net/documentation/manual/glTexEnv.3G.html",
	'glTexCoordPointer':"http://pyopengl.sourceforge.net/documentation/manual/glTexCoordPointer.3G.html",
	'glTexCoord':"http://pyopengl.sourceforge.net/documentation/manual/glTexCoord.3G.html",
	'glStencilOp':"http://pyopengl.sourceforge.net/documentation/manual/glStencilOp.3G.html",
	'glStencilMask':"http://pyopengl.sourceforge.net/documentation/manual/glStencilMask.3G.html",
	'glStencilFunc':"http://pyopengl.sourceforge.net/documentation/manual/glStencilFunc.3G.html",
	'glShadeModel':"http://pyopengl.sourceforge.net/documentation/manual/glShadeModel.3G.html",
	'glSeparableFilter2D':"http://pyopengl.sourceforge.net/documentation/manual/glSeparableFilter2D.3G.html",
	'glSelectBuffer':"http://pyopengl.sourceforge.net/documentation/manual/glSelectBuffer.3G.html",
	'glScissor':"http://pyopengl.sourceforge.net/documentation/manual/glScissor.3G.html",
	'glScale':"http://pyopengl.sourceforge.net/documentation/manual/glScale.3G.html",
	'glRotate':"http://pyopengl.sourceforge.net/documentation/manual/glRotate.3G.html",
	'glResetMinmax':"http://pyopengl.sourceforge.net/documentation/manual/glResetMinmax.3G.html",
	'glResetHistogram':"http://pyopengl.sourceforge.net/documentation/manual/glResetHistogram.3G.html",
	'glRenderMode':"http://pyopengl.sourceforge.net/documentation/manual/glRenderMode.3G.html",
	'glRect':"http://pyopengl.sourceforge.net/documentation/manual/glRect.3G.html",
	'glReadPixels':"http://pyopengl.sourceforge.net/documentation/manual/glReadPixels.3G.html",
	'glReadBuffer':"http://pyopengl.sourceforge.net/documentation/manual/glReadBuffer.3G.html",
	'glRasterPos':"http://pyopengl.sourceforge.net/documentation/manual/glRasterPos.3G.html",
	'glPushName':"http://pyopengl.sourceforge.net/documentation/manual/glPushName.3G.html",
	'glPushMatrix':"http://pyopengl.sourceforge.net/documentation/manual/glPushMatrix.3G.html",
	'glPushClientAttrib':"http://pyopengl.sourceforge.net/documentation/manual/glPushClientAttrib.3G.html",
	'glPushAttrib':"http://pyopengl.sourceforge.net/documentation/manual/glPushAttrib.3G.html",
	'glPrioritizeTextures':"http://pyopengl.sourceforge.net/documentation/manual/glPrioritizeTextures.3G.html",
	'glPolygonStipple':"http://pyopengl.sourceforge.net/documentation/manual/glPolygonStipple.3G.html",
	'glPolygonOffset':"http://pyopengl.sourceforge.net/documentation/manual/glPolygonOffset.3G.html",
	'glPolygonMode':"http://pyopengl.sourceforge.net/documentation/manual/glPolygonMode.3G.html",
	'glPointSize':"http://pyopengl.sourceforge.net/documentation/manual/glPointSize.3G.html",
	'glPixelZoom':"http://pyopengl.sourceforge.net/documentation/manual/glPixelZoom.3G.html",
	'glPixelTransfer':"http://pyopengl.sourceforge.net/documentation/manual/glPixelTransfer.3G.html",
	'glPixelStore':"http://pyopengl.sourceforge.net/documentation/manual/glPixelStore.3G.html",
	'glPixelMap':"http://pyopengl.sourceforge.net/documentation/manual/glPixelMap.3G.html",
	'glPassThrough':"http://pyopengl.sourceforge.net/documentation/manual/glPassThrough.3G.html",
	'glOrtho':"http://pyopengl.sourceforge.net/documentation/manual/glOrtho.3G.html",
	'glNormalPointer':"http://pyopengl.sourceforge.net/documentation/manual/glNormalPointer.3G.html",
	'glNormal':"http://pyopengl.sourceforge.net/documentation/manual/glNormal.3G.html",
	'glNewList':"http://pyopengl.sourceforge.net/documentation/manual/glNewList.3G.html",
	'glMultMatrix':"http://pyopengl.sourceforge.net/documentation/manual/glMultMatrix.3G.html",
	'glMultiTexCoordARB':"http://pyopengl.sourceforge.net/documentation/manual/glMultiTexCoordARB.3G.html",
	'glMinmax':"http://pyopengl.sourceforge.net/documentation/manual/glMinmax.3G.html",
	'glMatrixMode':"http://pyopengl.sourceforge.net/documentation/manual/glMatrixMode.3G.html",
	'glMaterial':"http://pyopengl.sourceforge.net/documentation/manual/glMaterial.3G.html",
	'glMapGrid':"http://pyopengl.sourceforge.net/documentation/manual/glMapGrid.3G.html",
	'glMap2':"http://pyopengl.sourceforge.net/documentation/manual/glMap2.3G.html",
	'glMap1':"http://pyopengl.sourceforge.net/documentation/manual/glMap1.3G.html",
	'glLogicOp':"http://pyopengl.sourceforge.net/documentation/manual/glLogicOp.3G.html",
	'glLoadName':"http://pyopengl.sourceforge.net/documentation/manual/glLoadName.3G.html",
	'glLoadMatrix':"http://pyopengl.sourceforge.net/documentation/manual/glLoadMatrix.3G.html",
	'glLoadIdentity':"http://pyopengl.sourceforge.net/documentation/manual/glLoadIdentity.3G.html",
	'glListBase':"http://pyopengl.sourceforge.net/documentation/manual/glListBase.3G.html",
	'glLineWidth':"http://pyopengl.sourceforge.net/documentation/manual/glLineWidth.3G.html",
	'glLineStipple':"http://pyopengl.sourceforge.net/documentation/manual/glLineStipple.3G.html",
	'glLightModel':"http://pyopengl.sourceforge.net/documentation/manual/glLightModel.3G.html",
	'glLight':"http://pyopengl.sourceforge.net/documentation/manual/glLight.3G.html",
	'glIsTexture':"http://pyopengl.sourceforge.net/documentation/manual/glIsTexture.3G.html",
	'glIsList':"http://pyopengl.sourceforge.net/documentation/manual/glIsList.3G.html",
	'glIsEnabled':"http://pyopengl.sourceforge.net/documentation/manual/glIsEnabled.3G.html",
	'glInterleavedArrays':"http://pyopengl.sourceforge.net/documentation/manual/glInterleavedArrays.3G.html",
	'glInitNames':"http://pyopengl.sourceforge.net/documentation/manual/glInitNames.3G.html",
	'glIndexPointer':"http://pyopengl.sourceforge.net/documentation/manual/glIndexPointer.3G.html",
	'glIndexMask':"http://pyopengl.sourceforge.net/documentation/manual/glIndexMask.3G.html",
	'glIndex':"http://pyopengl.sourceforge.net/documentation/manual/glIndex.3G.html",
	'glHistogram':"http://pyopengl.sourceforge.net/documentation/manual/glHistogram.3G.html",
	'glHint':"http://pyopengl.sourceforge.net/documentation/manual/glHint.3G.html",
	'glGetTexParameter':"http://pyopengl.sourceforge.net/documentation/manual/glGetTexParameter.3G.html",
	'glGetTexLevelParameter':"http://pyopengl.sourceforge.net/documentation/manual/glGetTexLevelParameter.3G.html",
	'glGetTexImage':"http://pyopengl.sourceforge.net/documentation/manual/glGetTexImage.3G.html",
	'glGetTexGen':"http://pyopengl.sourceforge.net/documentation/manual/glGetTexGen.3G.html",
	'glGetTexEnv':"http://pyopengl.sourceforge.net/documentation/manual/glGetTexEnv.3G.html",
	'glGetString':"http://pyopengl.sourceforge.net/documentation/manual/glGetString.3G.html",
	'glGetSeparableFilter':"http://pyopengl.sourceforge.net/documentation/manual/glGetSeparableFilter.3G.html",
	'glGetPolygonStipple':"http://pyopengl.sourceforge.net/documentation/manual/glGetPolygonStipple.3G.html",
	'glGetPointerv':"http://pyopengl.sourceforge.net/documentation/manual/glGetPointerv.3G.html",
	'glGetPixelMap':"http://pyopengl.sourceforge.net/documentation/manual/glGetPixelMap.3G.html",
	'glGetMinmaxParameter':"http://pyopengl.sourceforge.net/documentation/manual/glGetMinmaxParameter.3G.html",
	'glGetMinmax':"http://pyopengl.sourceforge.net/documentation/manual/glGetMinmax.3G.html",
	'glGetMaterial':"http://pyopengl.sourceforge.net/documentation/manual/glGetMaterial.3G.html",
	'glGetMap':"http://pyopengl.sourceforge.net/documentation/manual/glGetMap.3G.html",
	'glGetLight':"http://pyopengl.sourceforge.net/documentation/manual/glGetLight.3G.html",
	'glGetHistogramParameter':"http://pyopengl.sourceforge.net/documentation/manual/glGetHistogramParameter.3G.html",
	'glGetHistogram':"http://pyopengl.sourceforge.net/documentation/manual/glGetHistogram.3G.html",
	'glGetError':"http://pyopengl.sourceforge.net/documentation/manual/glGetError.3G.html",
	'glGetConvolutionParameter':"http://pyopengl.sourceforge.net/documentation/manual/glGetConvolutionParameter.3G.html",
	'glGetConvolutionFilter':"http://pyopengl.sourceforge.net/documentation/manual/glGetConvolutionFilter.3G.html",
	'glGetColorTableParameter':"http://pyopengl.sourceforge.net/documentation/manual/glGetColorTableParameter.3G.html",
	'glGetColorTable':"http://pyopengl.sourceforge.net/documentation/manual/glGetColorTable.3G.html",
	'glGetClipPlane':"http://pyopengl.sourceforge.net/documentation/manual/glGetClipPlane.3G.html",
	'glGet':"http://pyopengl.sourceforge.net/documentation/manual/glGet.3G.html",
	'glGenTextures':"http://pyopengl.sourceforge.net/documentation/manual/glGenTextures.3G.html",
	'glGenLists':"http://pyopengl.sourceforge.net/documentation/manual/glGenLists.3G.html",
	'glFrustum':"http://pyopengl.sourceforge.net/documentation/manual/glFrustum.3G.html",
	'glFrontFace':"http://pyopengl.sourceforge.net/documentation/manual/glFrontFace.3G.html",
	'glFog':"http://pyopengl.sourceforge.net/documentation/manual/glFog.3G.html",
	'glFlush':"http://pyopengl.sourceforge.net/documentation/manual/glFlush.3G.html",
	'glFinish':"http://pyopengl.sourceforge.net/documentation/manual/glFinish.3G.html",
	'glFeedbackBuffer':"http://pyopengl.sourceforge.net/documentation/manual/glFeedbackBuffer.3G.html",
	'glEvalPoint':"http://pyopengl.sourceforge.net/documentation/manual/glEvalPoint.3G.html",
	'glEvalMesh':"http://pyopengl.sourceforge.net/documentation/manual/glEvalMesh.3G.html",
	'glEvalCoord':"http://pyopengl.sourceforge.net/documentation/manual/glEvalCoord.3G.html",
	'gleTwistExtrusion':"http://pyopengl.sourceforge.net/documentation/manual/gleTwistExtrusion.3GLE.html",
	'gleToroid':"http://pyopengl.sourceforge.net/documentation/manual/gleToroid.3GLE.html",
	'gleTextureMode':"http://pyopengl.sourceforge.net/documentation/manual/gleTextureMode.3GLE.html",
	'gleSuperExtrusion':"http://pyopengl.sourceforge.net/documentation/manual/gleSuperExtrusion.3GLE.html",
	'gleSpiral':"http://pyopengl.sourceforge.net/documentation/manual/gleSpiral.3GLE.html",
	'gleSetNumSides':"http://pyopengl.sourceforge.net/documentation/manual/gleSetNumSides.3GLE.html",
	'gleSetJoinStyle':"http://pyopengl.sourceforge.net/documentation/manual/gleSetJoinStyle.3GLE.html",
	'gleScrew':"http://pyopengl.sourceforge.net/documentation/manual/gleScrew.3GLE.html",
	'glePolyCylinder':"http://pyopengl.sourceforge.net/documentation/manual/glePolyCylinder.3GLE.html",
	'glePolyCone':"http://pyopengl.sourceforge.net/documentation/manual/glePolyCone.3GLE.html",
	'glEnableClientState':"http://pyopengl.sourceforge.net/documentation/manual/glEnableClientState.3G.html",
	'glEnable':"http://pyopengl.sourceforge.net/documentation/manual/glEnable.3G.html",
	'gleLathe':"http://pyopengl.sourceforge.net/documentation/manual/gleLathe.3GLE.html",
	'gleHelicoid':"http://pyopengl.sourceforge.net/documentation/manual/gleHelicoid.3GLE.html",
	'gleExtrusion':"http://pyopengl.sourceforge.net/documentation/manual/gleExtrusion.3GLE.html",
	'glEdgeFlagPointer':"http://pyopengl.sourceforge.net/documentation/manual/glEdgeFlagPointer.3G.html",
	'glEdgeFlag':"http://pyopengl.sourceforge.net/documentation/manual/glEdgeFlag.3G.html",
	'gle':"http://pyopengl.sourceforge.net/documentation/manual/gle.3GLE.html",
	'glDrawRangeElements':"http://pyopengl.sourceforge.net/documentation/manual/glDrawRangeElements.3G.html",
	'glDrawPixels':"http://pyopengl.sourceforge.net/documentation/manual/glDrawPixels.3G.html",
	'glDrawElements':"http://pyopengl.sourceforge.net/documentation/manual/glDrawElements.3G.html",
	'glDrawBuffer':"http://pyopengl.sourceforge.net/documentation/manual/glDrawBuffer.3G.html",
	'glDrawArrays':"http://pyopengl.sourceforge.net/documentation/manual/glDrawArrays.3G.html",
	'glDepthRange':"http://pyopengl.sourceforge.net/documentation/manual/glDepthRange.3G.html",
	'glDepthMask':"http://pyopengl.sourceforge.net/documentation/manual/glDepthMask.3G.html",
	'glDepthFunc':"http://pyopengl.sourceforge.net/documentation/manual/glDepthFunc.3G.html",
	'glDeleteTextures':"http://pyopengl.sourceforge.net/documentation/manual/glDeleteTextures.3G.html",
	'glDeleteLists':"http://pyopengl.sourceforge.net/documentation/manual/glDeleteLists.3G.html",
	'glCullFace':"http://pyopengl.sourceforge.net/documentation/manual/glCullFace.3G.html",
	'glCopyTexSubImage3D':"http://pyopengl.sourceforge.net/documentation/manual/glCopyTexSubImage3D.3G.html",
	'glCopyTexSubImage2D':"http://pyopengl.sourceforge.net/documentation/manual/glCopyTexSubImage2D.3G.html",
	'glCopyTexSubImage1D':"http://pyopengl.sourceforge.net/documentation/manual/glCopyTexSubImage1D.3G.html",
	'glCopyTexImage2D':"http://pyopengl.sourceforge.net/documentation/manual/glCopyTexImage2D.3G.html",
	'glCopyTexImage1D':"http://pyopengl.sourceforge.net/documentation/manual/glCopyTexImage1D.3G.html",
	'glCopyPixels':"http://pyopengl.sourceforge.net/documentation/manual/glCopyPixels.3G.html",
	'glCopyConvolutionFilter2D':"http://pyopengl.sourceforge.net/documentation/manual/glCopyConvolutionFilter2D.3G.html",
	'glCopyConvolutionFilter1D':"http://pyopengl.sourceforge.net/documentation/manual/glCopyConvolutionFilter1D.3G.html",
	'glCopyColorTable':"http://pyopengl.sourceforge.net/documentation/manual/glCopyColorTable.3G.html",
	'glCopyColorSubTable':"http://pyopengl.sourceforge.net/documentation/manual/glCopyColorSubTable.3G.html",
	'glConvolutionParameter':"http://pyopengl.sourceforge.net/documentation/manual/glConvolutionParameter.3G.html",
	'glConvolutionFilter2D':"http://pyopengl.sourceforge.net/documentation/manual/glConvolutionFilter2D.3G.html",
	'glConvolutionFilter1D':"http://pyopengl.sourceforge.net/documentation/manual/glConvolutionFilter1D.3G.html",
	'glColorTableParameter':"http://pyopengl.sourceforge.net/documentation/manual/glColorTableParameter.3G.html",
	'glColorTable':"http://pyopengl.sourceforge.net/documentation/manual/glColorTable.3G.html",
	'glColorSubTable':"http://pyopengl.sourceforge.net/documentation/manual/glColorSubTable.3G.html",
	'glColorPointer':"http://pyopengl.sourceforge.net/documentation/manual/glColorPointer.3G.html",
	'glColorMaterial':"http://pyopengl.sourceforge.net/documentation/manual/glColorMaterial.3G.html",
	'glColorMask':"http://pyopengl.sourceforge.net/documentation/manual/glColorMask.3G.html",
	'glColor':"http://pyopengl.sourceforge.net/documentation/manual/glColor.3G.html",
	'glClipPlane':"http://pyopengl.sourceforge.net/documentation/manual/glClipPlane.3G.html",
	'glClientActiveTextureARB':"http://pyopengl.sourceforge.net/documentation/manual/glClientActiveTextureARB.3G.html",
	'glClearStencil':"http://pyopengl.sourceforge.net/documentation/manual/glClearStencil.3G.html",
	'glClearIndex':"http://pyopengl.sourceforge.net/documentation/manual/glClearIndex.3G.html",
	'glClearDepth':"http://pyopengl.sourceforge.net/documentation/manual/glClearDepth.3G.html",
	'glClearColor':"http://pyopengl.sourceforge.net/documentation/manual/glClearColor.3G.html",
	'glClearAccum':"http://pyopengl.sourceforge.net/documentation/manual/glClearAccum.3G.html",
	'glClear':"http://pyopengl.sourceforge.net/documentation/manual/glClear.3G.html",
	'glCallLists':"http://pyopengl.sourceforge.net/documentation/manual/glCallLists.3G.html",
	'glCallList':"http://pyopengl.sourceforge.net/documentation/manual/glCallList.3G.html",
	'glBlendFunc':"http://pyopengl.sourceforge.net/documentation/manual/glBlendFunc.3G.html",
	'glBlendEquation':"http://pyopengl.sourceforge.net/documentation/manual/glBlendEquation.3G.html",
	'glBlendColor':"http://pyopengl.sourceforge.net/documentation/manual/glBlendColor.3G.html",
	'glBitmap':"http://pyopengl.sourceforge.net/documentation/manual/glBitmap.3G.html",
	'glBindTexture':"http://pyopengl.sourceforge.net/documentation/manual/glBindTexture.3G.html",
	'glBegin':"http://pyopengl.sourceforge.net/documentation/manual/glBegin.3G.html",
	'glArrayElement':"http://pyopengl.sourceforge.net/documentation/manual/glArrayElement.3G.html",
	'glAreTexturesResident':"http://pyopengl.sourceforge.net/documentation/manual/glAreTexturesResident.3G.html",
	'glAlphaFunc':"http://pyopengl.sourceforge.net/documentation/manual/glAlphaFunc.3G.html",
	'glActiveTextureARB':"http://pyopengl.sourceforge.net/documentation/manual/glActiveTextureARB.3G.html",
	'glAccum':"http://pyopengl.sourceforge.net/documentation/manual/glAccum.3G.html",
}


if __name__ == "__main__":
	print 'search gl'
	for name in dir(GL):
		if name[:2] == 'gl' and not findGLName( name):
			print '\t%s:"",'%( repr(name), )

	print 'search glu'
	for name in dir(GLU):
		if name[:2] == 'gl' and not findGLUName( name):
			print '\t%s:"",'%( repr(name), )

	print 'search glut'
	for name in dir(GLUT):
		if name[:2] == 'gl' and not findGLUTName( name):
			print '\t%s:"",'%( repr(name), )

	print 'search gle'
	for name in dir(GLE):
		if name[:2] == 'gl' and not findGLEName( name):
			print '\t%s:"",'%( repr(name), )
	