"""OpenGL.GL.SGIX.async_ -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UIntArray, UIntArrayResult

from OpenGL.raw.GL._types import *

GL_ASYNC_MARKER_SGIX: int

def glAsyncMarkerSGIX(marker: int) -> None: ...
def glDeleteAsyncMarkersSGIX(marker: int, range: int) -> None: ...
def glFinishAsyncSGIX(markerp: UIntArray | None = None) -> UIntArrayResult: ...
def glGenAsyncMarkersSGIX(range: int) -> int: ...
def glIsAsyncMarkerSGIX(marker: int) -> int: ...
def glPollAsyncSGIX(markerp: UIntArray | None = None) -> UIntArrayResult: ...

def glInitAsyncSGIX() -> bool: ...

def __getattr__(name: str) -> Any: ...
