"""OpenGL.GL.SGIX.fragment_lighting -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray, FloatArrayResult, IntArray, IntArrayResult

from OpenGL.raw.GL._types import *

GL_CURRENT_RASTER_NORMAL_SGIX: int
GL_FRAGMENT_COLOR_MATERIAL_FACE_SGIX: int
GL_FRAGMENT_COLOR_MATERIAL_PARAMETER_SGIX: int
GL_FRAGMENT_COLOR_MATERIAL_SGIX: int
GL_FRAGMENT_LIGHT0_SGIX: int
GL_FRAGMENT_LIGHT1_SGIX: int
GL_FRAGMENT_LIGHT2_SGIX: int
GL_FRAGMENT_LIGHT3_SGIX: int
GL_FRAGMENT_LIGHT4_SGIX: int
GL_FRAGMENT_LIGHT5_SGIX: int
GL_FRAGMENT_LIGHT6_SGIX: int
GL_FRAGMENT_LIGHT7_SGIX: int
GL_FRAGMENT_LIGHTING_SGIX: int
GL_FRAGMENT_LIGHT_MODEL_AMBIENT_SGIX: int
GL_FRAGMENT_LIGHT_MODEL_LOCAL_VIEWER_SGIX: int
GL_FRAGMENT_LIGHT_MODEL_NORMAL_INTERPOLATION_SGIX: int
GL_FRAGMENT_LIGHT_MODEL_TWO_SIDE_SGIX: int
GL_LIGHT_ENV_MODE_SGIX: int
GL_MAX_ACTIVE_LIGHTS_SGIX: int
GL_MAX_FRAGMENT_LIGHTS_SGIX: int

def glFragmentColorMaterialSGIX(face: int, mode: int) -> None: ...
def glFragmentLightModelfSGIX(pname: int, param: float) -> None: ...
def glFragmentLightModelfvSGIX(pname: int, params: FloatArray) -> None: ...
def glFragmentLightModeliSGIX(pname: int, param: int) -> None: ...
def glFragmentLightModelivSGIX(pname: int, params: IntArray) -> None: ...
def glFragmentLightfSGIX(light: int, pname: int, param: float) -> None: ...
def glFragmentLightfvSGIX(light: int, pname: int, params: FloatArray) -> None: ...
def glFragmentLightiSGIX(light: int, pname: int, param: int) -> None: ...
def glFragmentLightivSGIX(light: int, pname: int, params: IntArray) -> None: ...
def glFragmentMaterialfSGIX(face: int, pname: int, param: float) -> None: ...
def glFragmentMaterialfvSGIX(face: int, pname: int, params: FloatArray) -> None: ...
def glFragmentMaterialiSGIX(face: int, pname: int, param: int) -> None: ...
def glFragmentMaterialivSGIX(face: int, pname: int, params: IntArray) -> None: ...
def glGetFragmentLightfvSGIX(light: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetFragmentLightivSGIX(light: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glGetFragmentMaterialfvSGIX(face: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetFragmentMaterialivSGIX(face: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glLightEnviSGIX(pname: int, param: int) -> None: ...

def glInitFragmentLightingSGIX() -> bool: ...

def __getattr__(name: str) -> Any: ...
