"""OpenGL.GL.SGIX.instruments -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray, IntArrayResult

from OpenGL.raw.GL._types import *

GL_INSTRUMENT_BUFFER_POINTER_SGIX: int
GL_INSTRUMENT_MEASUREMENTS_SGIX: int

def glGetInstrumentsSGIX() -> int: ...
def glInstrumentsBufferSGIX(size: int, buffer: IntArray | None = None) -> IntArrayResult: ...
def glPollInstrumentsSGIX(marker_p: IntArray | None = None) -> IntArrayResult: ...
def glReadInstrumentsSGIX(marker: int) -> None: ...
def glStartInstrumentsSGIX() -> None: ...
def glStopInstrumentsSGIX(marker: int) -> None: ...

def glInitInstrumentsSGIX() -> bool: ...

def __getattr__(name: str) -> Any: ...
