"""OpenGL.GL.SGIX.list_priority -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray, FloatArrayResult, IntArray, IntArrayResult

from OpenGL.raw.GL._types import *

GL_LIST_PRIORITY_SGIX: int

def glGetListParameterfvSGIX(list: int, pname: int, params: FloatArray | None = None) -> FloatArrayResult: ...
def glGetListParameterivSGIX(list: int, pname: int, params: IntArray | None = None) -> IntArrayResult: ...
def glListParameterfSGIX(list: int, pname: int, param: float) -> None: ...
def glListParameterfvSGIX(list: int, pname: int, params: FloatArray) -> None: ...
def glListParameteriSGIX(list: int, pname: int, param: int) -> None: ...
def glListParameterivSGIX(list: int, pname: int, params: IntArray) -> None: ...

def glInitListPrioritySGIX() -> bool: ...

def __getattr__(name: str) -> Any: ...
