"""OpenGL.GLES2.OES.EGL_image -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GLES2._types import *

def glEGLImageTargetRenderbufferStorageOES(target: int, image: Any) -> None: ...
def glEGLImageTargetTexture2DOES(target: int, image: Any) -> None: ...

def glInitEglImageOES() -> bool: ...

def __getattr__(name: str) -> Any: ...
