"""OpenGL.GLES2.OES.geometry_shader -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GLES2._types import *

GL_FIRST_VERTEX_CONVENTION_OES: int
GL_FRAMEBUFFER_ATTACHMENT_LAYERED_OES: int
GL_FRAMEBUFFER_DEFAULT_LAYERS_OES: int
GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_OES: int
GL_GEOMETRY_LINKED_INPUT_TYPE_OES: int
GL_GEOMETRY_LINKED_OUTPUT_TYPE_OES: int
GL_GEOMETRY_LINKED_VERTICES_OUT_OES: int
GL_GEOMETRY_SHADER_BIT_OES: int
GL_GEOMETRY_SHADER_INVOCATIONS_OES: int
GL_GEOMETRY_SHADER_OES: int
GL_LAST_VERTEX_CONVENTION_OES: int
GL_LAYER_PROVOKING_VERTEX_OES: int
GL_LINES_ADJACENCY_OES: int
GL_LINE_STRIP_ADJACENCY_OES: int
GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS_OES: int
GL_MAX_FRAMEBUFFER_LAYERS_OES: int
GL_MAX_GEOMETRY_ATOMIC_COUNTERS_OES: int
GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS_OES: int
GL_MAX_GEOMETRY_IMAGE_UNIFORMS_OES: int
GL_MAX_GEOMETRY_INPUT_COMPONENTS_OES: int
GL_MAX_GEOMETRY_OUTPUT_COMPONENTS_OES: int
GL_MAX_GEOMETRY_OUTPUT_VERTICES_OES: int
GL_MAX_GEOMETRY_SHADER_INVOCATIONS_OES: int
GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS_OES: int
GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_OES: int
GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_OES: int
GL_MAX_GEOMETRY_UNIFORM_BLOCKS_OES: int
GL_MAX_GEOMETRY_UNIFORM_COMPONENTS_OES: int
GL_PRIMITIVES_GENERATED_OES: int
GL_REFERENCED_BY_GEOMETRY_SHADER_OES: int
GL_TRIANGLES_ADJACENCY_OES: int
GL_TRIANGLE_STRIP_ADJACENCY_OES: int
GL_UNDEFINED_VERTEX_OES: int

def glFramebufferTextureOES(target: int, attachment: int, texture: int, level: int) -> None: ...

def glInitGeometryShaderOES() -> bool: ...

def __getattr__(name: str) -> Any: ...
