"""OpenGL.GLES2.OES.tessellation_shader -- generated; regenerate with src/regenerate_c.py."""

from typing import Any

from OpenGL.raw.GLES2._types import *

GL_CCW: int
GL_CW: int
GL_EQUAL: int
GL_FRACTIONAL_EVEN_OES: int
GL_FRACTIONAL_ODD_OES: int
GL_ISOLINES_OES: int
GL_IS_PER_PATCH_OES: int
GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS_OES: int
GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS_OES: int
GL_MAX_PATCH_VERTICES_OES: int
GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS_OES: int
GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS_OES: int
GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS_OES: int
GL_MAX_TESS_CONTROL_INPUT_COMPONENTS_OES: int
GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS_OES: int
GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS_OES: int
GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS_OES: int
GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS_OES: int
GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS_OES: int
GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS_OES: int
GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS_OES: int
GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS_OES: int
GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS_OES: int
GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS_OES: int
GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS_OES: int
GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS_OES: int
GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS_OES: int
GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS_OES: int
GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS_OES: int
GL_MAX_TESS_GEN_LEVEL_OES: int
GL_MAX_TESS_PATCH_COMPONENTS_OES: int
GL_PATCHES_OES: int
GL_PATCH_VERTICES_OES: int
GL_PRIMITIVE_RESTART_FOR_PATCHES_SUPPORTED_OES: int
GL_QUADS_OES: int
GL_REFERENCED_BY_TESS_CONTROL_SHADER_OES: int
GL_REFERENCED_BY_TESS_EVALUATION_SHADER_OES: int
GL_TESS_CONTROL_OUTPUT_VERTICES_OES: int
GL_TESS_CONTROL_SHADER_BIT_OES: int
GL_TESS_CONTROL_SHADER_OES: int
GL_TESS_EVALUATION_SHADER_BIT_OES: int
GL_TESS_EVALUATION_SHADER_OES: int
GL_TESS_GEN_MODE_OES: int
GL_TESS_GEN_POINT_MODE_OES: int
GL_TESS_GEN_SPACING_OES: int
GL_TESS_GEN_VERTEX_ORDER_OES: int
GL_TRIANGLES: int

def glPatchParameteriOES(pname: int, value: int) -> None: ...

def glInitTessellationShaderOES() -> bool: ...

def __getattr__(name: str) -> Any: ...
