"""OpenGL.GLES2.OES.texture_border_clamp -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import IntArray, UIntArray

from OpenGL.raw.GLES2._types import *

GL_CLAMP_TO_BORDER_OES: int
GL_TEXTURE_BORDER_COLOR_OES: int

def glGetSamplerParameterIivOES(sampler: int, pname: int, params: IntArray) -> None: ...
def glGetSamplerParameterIuivOES(sampler: int, pname: int, params: UIntArray) -> None: ...
def glGetTexParameterIivOES(target: int, pname: int, params: IntArray) -> None: ...
def glGetTexParameterIuivOES(target: int, pname: int, params: UIntArray) -> None: ...
def glSamplerParameterIivOES(sampler: int, pname: int, param: IntArray) -> None: ...
def glSamplerParameterIuivOES(sampler: int, pname: int, param: UIntArray) -> None: ...
def glTexParameterIivOES(target: int, pname: int, params: IntArray) -> None: ...
def glTexParameterIuivOES(target: int, pname: int, params: UIntArray) -> None: ...

def glInitTextureBorderClampOES() -> bool: ...

def __getattr__(name: str) -> Any: ...
