"""OpenGL.GLES2.OES.texture_3D -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray

from OpenGL.raw.GLES2._types import *

GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_3D_ZOFFSET_OES: int
GL_MAX_3D_TEXTURE_SIZE_OES: int
GL_SAMPLER_3D_OES: int
GL_TEXTURE_3D_OES: int
GL_TEXTURE_BINDING_3D_OES: int
GL_TEXTURE_WRAP_R_OES: int

def glCompressedTexImage3DOES(target: int, level: int, internalformat: int, width: int, height: int, depth: int, border: int, imageSize: int, data: AnyArray) -> None: ...
def glCompressedTexSubImage3DOES(target: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, imageSize: int, data: AnyArray) -> None: ...
def glCopyTexSubImage3DOES(target: int, level: int, xoffset: int, yoffset: int, zoffset: int, x: int, y: int, width: int, height: int) -> None: ...
def glFramebufferTexture3DOES(target: int, attachment: int, textarget: int, texture: int, level: int, zoffset: int) -> None: ...
def glTexImage3DOES(target: int, level: int, internalformat: int, width: int, height: int, depth: int, border: int, format: int, type: int, pixels: AnyArray) -> None: ...
def glTexSubImage3DOES(target: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, type: int, pixels: AnyArray) -> None: ...

def glInitTexture3DOES() -> bool: ...

def __getattr__(name: str) -> Any: ...
