"""OpenGL.GLES2.OES.vertex_array_object -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import UIntArray

from OpenGL.raw.GLES2._types import *

GL_VERTEX_ARRAY_BINDING_OES: int

def glBindVertexArrayOES(array: int) -> None: ...
def glDeleteVertexArraysOES(n: int, arrays: UIntArray) -> None: ...
def glGenVertexArraysOES(n: int, arrays: UIntArray) -> None: ...
def glIsVertexArrayOES(array: int) -> int: ...

def glInitVertexArrayObjectOES() -> bool: ...

def __getattr__(name: str) -> Any: ...
