"""OpenGL.GLES2.OES.viewport_array -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import FloatArray, IntArray

from OpenGL.raw.GLES2._types import *

GL_DEPTH_RANGE: int
GL_MAX_VIEWPORTS_OES: int
GL_SCISSOR_BOX: int
GL_SCISSOR_TEST: int
GL_VIEWPORT: int
GL_VIEWPORT_BOUNDS_RANGE_OES: int
GL_VIEWPORT_INDEX_PROVOKING_VERTEX_OES: int
GL_VIEWPORT_SUBPIXEL_BITS_OES: int

def glDepthRangeArrayfvOES(first: int, count: int, v: FloatArray) -> None: ...
def glDepthRangeIndexedfOES(index: int, n: float, f: float) -> None: ...
def glDisableiOES(target: int, index: int) -> None: ...
def glEnableiOES(target: int, index: int) -> None: ...
def glGetFloati_vOES(target: int, index: int, data: FloatArray) -> None: ...
def glIsEnablediOES(target: int, index: int) -> int: ...
def glScissorArrayvOES(first: int, count: int, v: IntArray) -> None: ...
def glScissorIndexedOES(index: int, left: int, bottom: int, width: int, height: int) -> None: ...
def glScissorIndexedvOES(index: int, v: IntArray) -> None: ...
def glViewportArrayvOES(first: int, count: int, v: FloatArray) -> None: ...
def glViewportIndexedfOES(index: int, x: float, y: float, w: float, h: float) -> None: ...
def glViewportIndexedfvOES(index: int, v: FloatArray) -> None: ...

def glInitViewportArrayOES() -> bool: ...

def __getattr__(name: str) -> Any: ...
