"""OpenGL.GLX.VERSION.GLX_1_0 -- generated; regenerate with src/regenerate_c.py."""

from typing import Any
from OpenGL._typing import AnyArray, IntArray

from OpenGL.raw.GLX._types import *

GLX_ACCUM_ALPHA_SIZE: int
GLX_ACCUM_BLUE_SIZE: int
GLX_ACCUM_GREEN_SIZE: int
GLX_ACCUM_RED_SIZE: int
GLX_ALPHA_SIZE: int
GLX_AUX_BUFFERS: int
GLX_BAD_ATTRIBUTE: int
GLX_BAD_CONTEXT: int
GLX_BAD_ENUM: int
GLX_BAD_SCREEN: int
GLX_BAD_VALUE: int
GLX_BAD_VISUAL: int
GLX_BLUE_SIZE: int
GLX_BUFFER_SIZE: int
GLX_BufferSwapComplete: int
GLX_DEPTH_SIZE: int
GLX_DOUBLEBUFFER: int
GLX_GREEN_SIZE: int
GLX_LEVEL: int
GLX_NO_EXTENSION: int
GLX_PbufferClobber: int
GLX_RED_SIZE: int
GLX_RGBA: int
GLX_STENCIL_SIZE: int
GLX_STEREO: int
GLX_USE_GL: int
__GLX_NUMBER_EVENTS: int

def glXChooseVisual(dpy: AnyArray, screen: int, attribList: IntArray) -> bytes: ...
def glXCopyContext(dpy: AnyArray, src: Any, dst: Any, mask: int) -> None: ...
def glXCreateContext(dpy: AnyArray, vis: AnyArray, shareList: Any, direct: int) -> Any: ...
def glXCreateGLXPixmap(dpy: AnyArray, visual: AnyArray, pixmap: Any) -> Any: ...
def glXDestroyContext(dpy: AnyArray, ctx: Any) -> None: ...
def glXDestroyGLXPixmap(dpy: AnyArray, pixmap: Any) -> None: ...
def glXGetConfig(dpy: AnyArray, visual: AnyArray, attrib: int, value: IntArray) -> int: ...
def glXGetCurrentContext() -> Any: ...
def glXGetCurrentDrawable() -> Any: ...
def glXIsDirect(dpy: AnyArray, ctx: Any) -> int: ...
def glXMakeCurrent(dpy: AnyArray, drawable: Any, ctx: Any) -> int: ...
def glXQueryExtension(dpy: AnyArray, errorb: IntArray, event: IntArray) -> int: ...
def glXQueryVersion(dpy: AnyArray, maj: IntArray, min: IntArray) -> int: ...
def glXSwapBuffers(dpy: AnyArray, drawable: Any) -> None: ...
def glXUseXFont(font: Any, first: int, count: int, list: int) -> None: ...
def glXWaitGL() -> None: ...
def glXWaitX() -> None: ...

def glInitGlx10VERSION() -> bool: ...

def __getattr__(name: str) -> Any: ...
