'''OpenGL extension OES.read_format

Automatically generated by the get_gl_extensions script, do not edit!
'''
from OpenGL import platform as _p
EXTENSION_NAME = 'GL_OES_read_format'
_p.unpack_constants( """GL_IMPLEMENTATION_COLOR_READ_TYPE_OES 0x8B9A
GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES 0x8B9B""", globals())


def glInitReadFormatOES():
    '''Return boolean indicating whether this extension is available'''
    from OpenGL import extensions
    return extensions.hasGLExtension( EXTENSION_NAME )
